apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-frontend
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Sn8JNqSFhnhjtLG5Ig2hGqj0kqaYUH/gr9Q=,iv:rtX0ELapLtOnk9opanWr5rASh24ce100DVboePnFkWY=,tag:5N3rwtlGvQW3VCTpDkJIBA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xnQuL4DCFaId5+l8R33Q+Zqg8gjIZqCqRuBDUiTjmq7wwWoXQxsHN295By3A9rAFShjsZvISELenm4Ox4YneoA==,iv:Fchbd8yW4OPLhEnxILaGywxptIJ37K0yz/QO+mg9D8k=,tag:LqbDfHN7FWyg2qOEDEKFfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ2s1MWxqak5oVWhUTkVL
            RHR4Mm9memx2WDJrVFlqcW9hUTMxNmRxNG00Cm5zUGpwSHFnMHBsS0hCczdPZDRM
            eklDajRPRStEVWxVdWY2eFQyVFRnNEUKLS0tIEM2WGlMWGZLYXpOTlJHMEp5anVz
            YWxYaTk1eitoK1A1b3RMU2pCaFZtY1UK+r6MKdy80nC75kDqI5jmmRi5uyGqfRo5
            vjawzPTWVgwcG8JkbRvyIAgdFsSj5XstX0ZYSKlqJgLSk7qEm9SNRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQy9xZGJpdm9oOEtWcSty
            R2UvWWcvRHVpMVE1ZWc4ZHZLVXMvREZTY1ZZCmFFTWN6Tmo1MktxbFg5dmt5d3V3
            bW1KSnF2R3VJT2Q3Uk4wNUttR21CUW8KLS0tIHdYWFZXYmo1SWJjK2xaU01objJZ
            YWFYbDJtbnplOGNqZmNrb2dJSVRUTmcKa2BGMJpGxqdAZbitrHq/sOufSXOueZTk
            eku/lGRrAnscET38uF7AfN/PBbkkzZAFzEQUaBuTGzrW/lvwpwfe4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneE1LdEtsa290NzRLS1pn
            WHdvNk5hdDFSRkFGbVhhVnJjc1ZpWXBKWnpFCmxseDI1WStTUjJwVVN4VzVqbnY5
            UnQ3Y3Z0THpkRld2TmM4U2NqYWRXUlkKLS0tIEUyMmtkSENhMEU3UTNteGNkWGQv
            eTB1TnEyVGp4MmlVL2pRVjBlb2R4alkKfpIC16KF/qPodZWaAqQFm8t8Et4zaU9y
            R0Iqs3lpqMdQCszN761PeJjMZPFqEUBfTPfQDrAWSlEcKgy8pxaarw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:QsJqTHCZVwslW4dTkSiYcnvrpklBQUKMbKGYkSflP1g1E+7JvlVi6mTs0TqvyzenY5qUEgJapJWKYdwzVUoLNUksEGxUKN91Tck9cWayTb21L/RuV3/Pfa/I9EhJmS0inArdvQFaqVhSJBVjV7yRSvyo6OYn004bg3m+EclKebc=,iv:8sD7iSwtC6GyqH5dm5Z/UDWx7VbpHEfdjY6xntmsV7g=,tag:SruyHnWRKxaW/3E73qo1Cg==,type:str]
    version: 3.13.3
