apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-frontend
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FERW0wCF1/9FudE869oUWOD266OsEY0ms6Y=,iv:rtX0ELapLtOnk9opanWr5rASh24ce100DVboePnFkWY=,tag:4dmFDfxzx6qobVUigq5UTg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mDtnmD1ZR7uUo+j9sKTEwxdVKX00QLV2c/lEzEPXLeT6j4gPiqSR7137/OalE256x6REAwrE84VdyI/FAgl1Pw==,iv:Fchbd8yW4OPLhEnxILaGywxptIJ37K0yz/QO+mg9D8k=,tag:otL1qkVICzV9/BlDdkCldA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTFREVUxtTTFVQXE0UGoz
            cGswWHNqNHAxUVpwK083U3piUndFYWJhUlNRCnhXK3JZT1VkSWdURTZhWHdWOEdu
            NVVmZ2cwU3F6VEV3b0RFajBNWTVtZ2sKLS0tIER3bGxTaFB2UWxUdVd6RzhVMTR5
            VW9IZEJqenA0SXRBc3FwMnR5WXBKVDAKaAUYf3RBciqy3qMs6XIfBks8JvJgCloQ
            tD6j15fmQxu4xQusq+n+Y4mZ9uedVyuVfn9351xUh4LRr5M1/9xT+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aGp6TlBlcnNrWU9HbE5Z
            bmVYQitQRlpEblM3RGdDYXVhcXFtbzVtTkQ0CjMzVXcwSTVCblBvTFVMMlNTSnk2
            R21FOVdBanlKRDdnWHJGcXhLSzFxZXMKLS0tIFZISStTL09Vd0hyV00vRjJEdFhu
            c2dkTi9vRUw2b3hOeE1vQUh2RWZqd2MKjOoqgt5is40unTbQ5cLZy83AsheAL5LR
            Yjt6bb1l/ZEoxrehpmtPc30amSHdHCwBi5KfRLZF9bZlwMOKUe9HUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL2Z0QlBqUzM0eTU2UUFH
            SmdqUUpFNHVpaEF4NEM1REkzKzJKWWJZeWdFCkpXWmRIRUVJcit1UFlmWVFONmRG
            V25WTWNJUS9aMml6K2gvTHlvUk0xd3cKLS0tIENzOW1wM1RyQkl6U2Y5aCszZEdK
            dmcrc1B6a1A4WUlkTzBnRFl2Q21ybEkKO2EB5vAon+lbO6VnsUHAJRBadXE96WFJ
            1XHYOQAze0gAxaHw3G9nP/CqECJet5rqJvAkx150TVeN3pTbOzkiUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:z9277P3Rr4mCtFxpK4PeD028e5LhK34fKXrS/mYT3zYrhGD5E5/1B5yC6UojZmrgH0Qdxk+D49/91ynTUHCY6CngnSFtlY1NgW1hsE8D0p2I7/JXjSE0JfkhTppzTrMT8seqvCWLq++NPFvCP8ZNj2jhesYAvft4JSj5a73dm38=,iv:wTmvKOVTYWIQK7gzM/TFOscEM4WXKcwcJ7H+41TGwoQ=,tag:lASc1TyUc54xf/Jc8hxnpw==,type:str]
    version: 3.13.3
