apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-frontend
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:pf4fQPXZ0A==,iv:f/56G2ipJRNewfDEOEn1uSsz39VaxbnFvCI98ullfXU=,tag:HtK7bvkXKXZPMtI/vns/nw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:PQZQ4ZZmDqIo,iv:X0Ii5xo7uDg9zrBhimK0znSUjXrNXdDYDFCFJmrgOEU=,tag:i7nviL4Y/g8aQ2BNLHPzZg==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:BUbg+HVoEIa366y3yuPTe9huMOLqeWCpRedbM29hSIFEM1NiEd19CR4G5Kjz/HrapMjisGihTnA8NbmUdiBERH4WLgydbRW7aVsXCP1o49FyAMR/Xn/g5LdlaZBE1XTDU9+LZw7qRFTWrTiQfu3EHb9PX9TkymHzjPgw58P3lkspV7k3vGuT5uAHddNyZHqFmlqM6smIBISp8CaGL5VaDpzFygs9GKh+IYfvKz3yKoqag+49qMtOv19uAhsI0q4amzODIzdXHhCECcTkq0UD/h3Nc+RTAH8t1Rz/xSKpFVD0XdNpB3MlrwpvWmOAJ/TN7ORWcFRbRigW+sUzCCXTgXcgpzYljmJoeYi/2S/SdteVLat+OZ6NFlHdy7hcFa0nrzA6cBkhIORPTVBAsnmlYFyOhieL0vJzVygyv9yyUJCyxoQ8G+6fzqVWRI/sWvJj+YMkAfUmL1dKOm1vuo/lqa9K9mSlRhiDP0Uv/f5w25N1GDo86/QQbDRb0Is47oGN8y49A3Z99miB+oalNeBCQVNDH+Gw9YTvzyo3RPqy4S4e7MMl/nRLcBZZPJKoSNYHitW7R6j3QsHFTOh4wluS35mldjZzkh8GBikkQT5mCtqQm+y3t9J4oyyW74M76ofRTW3SPJ3Xb6YKs4VnX9zocuwmg6bMlg7mj964SHJjPeQF3JnPHX8UPODB4GkzhjyAYFAJkt5rtlpX2y7+TS1KNzFiXdptWihZgY0VZWmmd0Bi6qd47H0oa80d+Rrkw3bp1lEH9/dNyslj8yAuHrYkwLdAuYxhjNQ9ckjUjvUlihEev7tq0EI+U/xVYGyKTlnBOX4URMULu3VIFPUylD8cgRBBuCKVyQZgOE6dDGyEW0yxqupB2rus4krVgkP+63DZ2EazpYMsNZG90StsrD0lI8ZAMAurZRJkXEsSP0Vxd5jcKnKYZ/Sg4hhqlcDFmCXf8qDTP53LeFj0ZKwdv9ImlzQvrvN2Ljlp2hk8okUYOz93iZnjmPr/1qOQVFfgMh8btuQu59Fjqk2cblHTqhZEPZSgBp0Nqntjl/rDZWv9z0IX3Ht3yItXKB29uq77gcU+p9ZyMIIUbuxtuJYNj3Y3p58I26WZ9cfekG+fzw1PTWtQ2XfpTUdO5IDfuEUE1gkFumt+NLfJYMnJzua8A9UNIROyCotsAPq0Eww03+oXPIkPvc0lIW+eEKVHzz3OpKL6Kozdw4phmmV8z2/NRJLnkjFt9OhufxlZ4q89FHCtSMJpuAYUI64HHOl+hKATIqfG+Wn1DtNJ1BSnhVMbKsdOhi21+SmgpTGJqb1O7+eb4hkIWeON8jC55sDzIvQhQJykBHWtDP/8kkmr30w2TuVHEPKsej+xVgZYWEyOmHJ1m8TutpE1I7kdjULuZJF1KxcAS1mhnX0hpqZstOJi3cMgR0tErSubRVfA6FSGMzGl0rFepGxIwTbS40RiRaYbR0cL5iTSKhAnEn0bhNJlfxOyzmk9FECC+qM7k7zUgRDQ9iqURZxwWBBNGmUoyG1FUmwqEKeA/nm/kuzl9wwfXRgE0oYg158X8BD82y2oNADA8izVM5lBAB6+vSUQOUNkwdQq3vWMdXfP+GwsgVaYr1KfqaMu6LxjoPzBX0wfuvBN6bliuT3OhG5JVZ3peIK+/U3xfQ4KRqLvDuR7Un8ug2AGQPGPFH42xwp6g83Wtq45D27UFQZajv97gqkAYhG5TwLczd3vo4H5z1NPL6vrp7T9Xpcd3WqozawXQlHGw8c5exANzjS/Yjmd8gjCVPoiBeyClyRSJwGFyauxawaze2o9O+u8XIyK5BbwckeDXF73H2O+PAOiUN63fZYMzsPewSzMYIGsaffUaJB02CBqLahKTD+PBG4NsHjxGMyGTv7+CnedvD9abUdvkzarM/VrBlyNjNjj7jkk7I+C1i5famUEyEdM36Y40PlhJqsRX0bL/DoGdS/tNMdhdUzKn1QhcWH+H7ypzAFiY0G/SnPlPg8VOkwWovbbpWtIMhHTthNdIvoKWPRy2f8Gyc68dhk/LY4PgW50HOE6PpUlY1MG/WPYOEbw/rSfwPrAUdITaFCGQanTlSONC+10OrlieelDnJ2vt86ozKYJPPGFFjlQDdLaxDOySNtOi46yqzOr2G67bFci167lI7PbaZPhbAxtx5FuqUow95X4jO6aiNphSsiz6IpowtnfuRHrgE5gjghjudaEx940X6qQ66LSENY+8g==,iv:i3OwNtCpECMjUqXYGYTx0qvgWHlf6zImlk5OpYD+wos=,tag:TWN3vAYSpMlvDXiE1rBs6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd3NHSFVmbGRRSzl6dkkr
            UXlNakQxSkUrbWNnZVNFZzN5aWhaT1BtRm1BCjR2OENUODdqYTQ3WmZndHVXTHh2
            M01nbUsxNjY0UjdsWnI0cWJ6UVZPcTQKLS0tIHNNeG9vWTlnT29vc2hHUE4wYTJ6
            ZHpScGFCeVRsSUpEdmVaMGl2OVVXVEEKGJOyFtjZUjT3zkn7dtK0dy5IltKCAF6Q
            qBBey7KPHXtlXNXWyqCfPnbxIyr5E3VdSnaYt3YlLvnIvIuO9qumrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNXdYODYwQWZkenFsWW9J
            eGg2K0lzT0RNQ1ZBZmxkTzkxT2RUcGcrR2pvCjlYUGNJMElZNTZXQ1BoZkpiMmJp
            cHQ5dWtYWDJYUldMZGhSMzBMY3U3L2MKLS0tIE12dnBTUytPakh0Mm9NZGFtSzN3
            WXBzOGtRb0djMVk1Zjl1YlJPNXp3Q00KiXMIj7Z7+l0GY2fzo8l1200WCsVB7jNe
            VZBjYA/f7JB7VyjwyK1OebEvnNXZx7x4kiIR4t25xmJs+3fuXrRuVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNWVWTnUrZ1QxRG82RWJu
            c0hxRmN3Y1U0U3lSNmxjdHFBSXIxLzd1dkVjCm1ZQm1DS284MXJETlZNR3JMeWFS
            VWZqWkw1SWR0ZE9uVktoWFJuSXNDODQKLS0tIEZhWWNmOUg3ZGdCSHdmcktKSTZK
            SkFJT3hQWWFSa3pBd2hUVktSaDVON2MKPFadjRY4LvgmkcgV+yl6c2oQWZNGJA5I
            47wdrgIr42jCvViWQknOY3EBCozSMoXdtz8IOojiXsEEd9nMz3r0VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:peoaomCyGReNOruEjfG6uzYYRBiZ4KTGgJz/Br7wZZppYym6CbEeVa3b6v8cOqcUHIwO1+09l4PPOtG1yW3k51dJW450p/1EZnYThzu0fQcNvMu9YRiX55Uf8S2XkkoCGKIANyFc7guu/AV+zCwLgZS7f9uutuZXrq701fk56dw=,iv:DBCwZO6vNLxUKjNz/urGutUL7TPvwjgZxZ1vu7osD94=,tag:ttMJUJtgcvdgJfDWNN8KjQ==,type:str]
    version: 3.13.3
