apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-frontend
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:KPQYxN2XUg==,iv:f/56G2ipJRNewfDEOEn1uSsz39VaxbnFvCI98ullfXU=,tag:5m7H4xibH1ZmwdhiDp9TMA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:r+h3FbULkWSq,iv:X0Ii5xo7uDg9zrBhimK0znSUjXrNXdDYDFCFJmrgOEU=,tag:d6Ey36ECqhjWVrLI/ZbW7A==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:2Mhaaxeez+CPpbHNnD7PgywZBL1H/bKhp2bsLpbel1eCn9U0yxjVoD69Er4RZoDQKaZgyGNnkFa4g3fi/We8qJRoBUDoTEsZdCup6LytRDdL6bkw80Q59FWdT7+MPWTqZW6kAW9wUZkOFG1L6CVlUmu03pDKiRefO3T74cSIZxzzLY6ftTRbmvO9pxQyx91MtPwL1jprQfV86jIKVEV5RWaEwKKIAe4guiKXUM4+3SgoNoLc3BSMcLjJtN9a2Wpe2U0cxw+srj9f7TeArOSjCsQd8LHtftKR/Tvrw+969k5Pgo5AFFzulqWev5U1a0nI+Ksl0pRnACBJg1ekETKpQ8yE7PNbb/SwypPBdSQuyIfV4zFEvnoqAYshm3lnKqRX313HSI1JtJjgOS+DkboOc/TiwzA13X7bs73e8d2yLAPndglwTGPQL0kpCDS9vjxjxnKTZ1K505wZkq4U103lbFz8pTeV5UyIAWqk9VxHG1zlG7lhhHPrU3wa1uSFdF0JZxJ5REiG2IBRVMA00XurO4yrA6Uly5Ay5ZFZpwSY8cdoc4RRI+NehwceJmsCYxeFkeJVVH40WbdWquT070g6QhuxzCJmSC2WfC2Dg9kQnjWvFJ4aniaOwrVt2s67nKL9FMwbFSu/kGRuXj7kZQTXSSyungKuo5s6toPdcEG0sfpbBV0INXGAete4grfsShQIvjE0Q7wT50Mecb+yTQymFISVZb5I6QHZ6WDM+YB6rUUL9kORZ+LvzdmmRljWSbbykvk4mFX5Rlxi+nnWFiUav2Q0rCv1D1Z+8bKDyFUcZdTBYkFyzqQvDPNf2N/xeKWgSO+0WBQPxEscEjofEl+SkocTIm8Lp/mNBI5+rUd5RbVWJIdbpyUadCAIc6UrAcXHWv72S2kIv8Yv0L7hivWQAsFY2EmSGZvbAomMTVBusGDuzuuWH5g+6Z3FSU8bWdrVetW7QZ9n9OpzWXsDvKZcVWTsf8e0sQqL+sF9OvMfRPHZdwB8Gzv6ED4dPPE1gklP3QSTu1t6pXct768QygrBiiOtoKOjxBVj0h4RtYJv3UBFhUREKqtaHhPPirm6SjLJIWrL/nLTUdOqLtXIXowRgxdFMc+cHqeH1PBMU2lzI9nXCfaj4Jcuou1QCXJtX4IcZXMaJlVpE1yUUSaMdOKSZTsH+YSn6BmgCLYDHq23MPsas3xt6Cw2ekWjI4+ug86oHwHzTxg3FqzG3cE8lcXN9WYE6dHTakOx1lLaJvlrod+3iP/eI5v2KAZIlcDdhDsJIuTYVWygkrDJ7ZSSioB1bH2R82c5SZY+3zpdSkp9e0equ5ZMq/PanNVAYLDRoGeWRxlqgckVq0rADxwo0uuSEIl14Wf9ZsdcNbsIcUcsAi5UbE5Kz0rJVpvYbZ0TW2GyFtMTTF2W8Cs56hPQHxKufzTM1Ox39N7vdl77pNNEmAMO/4VJYtVeBdl3lUJf/Etj5fti2QKcR/TYvOKsdxuMPAPbSYuejGwst60wfaS/mnrVWqhbF/7rj8t4f+N/+bCX8lmAtyAnZccNKTYW61mb9V/Sv6N0Xu1douw4mtz/hLug106itqOVJt/05l/JAuuLIb4beiBaJQ6wo28WDpE391dSRTKZWmjwMMDl1Yg3NLTD4YsEZ/M37gxP0Hc9XPmA6fNAubF2vtTGiAq+MSEDPkL7Lp1rExT9yAiPh4wTySZXf8sC5OkILluIC2w7A2XRgr4ISqw3LxCy+PV3U3LvF52Yl1wzbRJyc2A/E2RdNuuILK18x3um9XXnbvBum9Qeyh63HqWz2Sb9nsWPYfLc4wn08la0jDOR0OgWNEAKVg7AklrQ+KVwjVpeq8D/11sA2kpU9QSLgAlP/uZHpJrCTk+qFhToRZIFsqXhmKzvJSoeul5pRc/xNTuMTWSi8zkAt+Jnopntrubp1r4Wxb6+dUFjP5Gx/11xNv85z9/FuX/bOR634XzwKkBgnvHZjuz0e/awvBaKSgi6zM9f9sNeQ5j1ESLKG5+KTWpc9XhwtVafUSNqu2854OjE38/2wzdBaNCvriQDR1cyo2OLcPxvln5K7IGgTtO0Od5p4KThRKd5kRgsXokc++k8SRHdjCcBiVqwRTSqef36USDAwlGxsHogRdCD+tsynXfAymBVnUmO/fGvyziw4crfTRglswRNwq6oYX9U7HNDFCWQiek+ZupsCXentOY9/0M+86RQikpYdLWQYYle34lpzLN7+w==,iv:i3OwNtCpECMjUqXYGYTx0qvgWHlf6zImlk5OpYD+wos=,tag:iAGG084VHlTKPXe8wVE36w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ1ZMVHBMU1BqUzlLdUsr
            RXNlOEc0cTZQV1M4c0NxNnloYVU3aXRnamlFCksyVVBPUzk3ZmpnWWVkTUNTQUpY
            V2dkM1RRZ1JXb0tSVnZJWnNzNGtvSTQKLS0tIHN6RkVNcG5xeUNidFZsOGNUSUxK
            bWpUSDRtWEZ3aklJZFhnMzU4L2M0L2cK4f2HB+lB+D8jwApOz74Ghtla2zWLB1EE
            8fh2fLJGEzHUrXvJVr2P5BxKQiqVdBnCWJsS8IQokwF3buqAy6XmCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla25yZDNmZUQ1Zk5KYnoz
            bFRkVUYxYlUvZnJrTk54cENDdXE0UkVnOUVBCnJPQXAxTEpoMFlRblI2VDJuZTQx
            dG80eVRzQ3VyZWFEMnBrdGZFYndSem8KLS0tICtnUE94cjRveG5ZcU5CZXdqN01n
            dmhXcGlXRG1sT29qMjBsNTNnZG9LYkkK0W+hPNZE/fMTBy5pCGQle1XSouq8U19n
            DQxv+DonNvaO9RUE72ptaBq/Iibg6mMWlGtdQNhIaQ9rCEBo5ZKzxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRkMyc1VIVlY5ZkxPNDBS
            VUVvWk4rY0lYcnBhekxMamFsQ3huS1lvMUJzCks1eW16Q3RWTTBGcVZzdWtjVHRN
            S2FDb0RGa3hBN0ppWlZOWkRueW9DNk0KLS0tIEFFbmx1bFV2aGVkbnlTWGFYcUxs
            Skh1aDJKVlpDYmpjVmk1bmtXaHZZOEEKTPE7UIgZbziYQrFnFwdFIlwsGzFoaojB
            YE4hWyDYxLPSZSeWmOgRiT608TNaZClHN9w3ncdnpseeMY9BW4KaMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:32Z"
    mac: ENC[AES256_GCM,data:reXTGgXH6LpeBlRZfkH+izBcUzYVuG+URrltIl/hTLivAPhSVAWCLvsRLhHer+SGS6Dmlk+9g4a8qsOy0hELQShdIv5538G0r4aINA4hFNX4FurghZOylPAsdfKG+6ieBCO2HlNxUkmnO6hbOmrsu8GaOeiO+u6S1PTVwjxDEJo=,iv:cg1f5Qj/WgVvKWjfzCYSiTwD6ZOJFbxYQAze0sapmzY=,tag:6HzTQN5FsYMzx2HgQO77RQ==,type:str]
    version: 3.13.3
