verify:
    gatus-token: ENC[AES256_GCM,data:R3zdVhxaowd+SwoQKC8XD6c9Rj1ssV43LgzGruW2U9q4vDlW3Ratt2GBpBSlz96TK4755/6dSdpPVUIG6BGIeQ==,iv:MQdKUUCMYA85nHbmM9jZcwnnSAQZAownOQkmg5N+Gfk=,tag:rjQa/HtzFspeyWhxDrezAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bGpBVW1nVUVkb09ObEhR
            bmdFZU8rVEZHSi85V2U5YlVkYzU1Y1d4QVRrClQvMXdoRmo1dUM1SEttMzNiLzBa
            Z25HVktBUGM0UEVEdjR2NzRmTGxJZXcKLS0tIHN2WW9tOWNFa3k1M0lnbE5YdGJt
            Um81eGhHL0lZNlh3eHJldXNoZ24wSzgK9jR8NUJ1diL4PwzaUiG2MY17hiNTa8jB
            30qpuuO/0H+M5CMXDcHU/N3d6Eg3SqncYxgH40QK+dTwhZLjjwwD9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaDdMOFJoMkJiWWtWK0hV
            TkRITFNOMzFkZjA4dzBLR0tzSmpzUXo1L0hFCnQ3YlRIRWlWaTFEZ0xRWjNWZ2xU
            QzZKaVNiMm43OXpWcHZQS3lxWkpMOFEKLS0tIHpsNE9xbmcrb0lWdHJUTkJ4UWZK
            RkxRYVMxam1rK3RqSVVjQVdxNzVqNGMK1kFf+iytgOtZZDn59lppHaIShie95/Xg
            4R34fjghglOJnENckRKhkbPEhfn6k8iam3Rg5ZHCFxNiFbTKVbZWNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    lastmodified: "2026-09-26T14:55:54Z"
    mac: ENC[AES256_GCM,data:aC+vRbjAUeApPOC3cMwtUPBzLJMJpy7CpdhW8dYJ7AlyJanjtzdzfS39StyblCZFzmfIdowiQ/ztgB8Js9D+Iu0UY2VjeggZnHpV3zj5WEk8xxQ7fvnJzpV/rIdjr15G4uckM81g7GehdbmHiO1kG/vydAzYB0f1u0/Qtg3zW1I=,iv:6qZ+Ol7YqzSGq53pyZe5xunFLOGgmoQhhn+vZSpUABM=,tag:wS4ftSuWvsShO2Lh4xyMtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
