# mkQuadlet — our own tiny Quadlet abstraction (ADR 004). No third-party flake:
# ordinary Quadlet unit text, generated by Nix, placed where podman's per-user
# generator reads it: /etc/containers/systemd/users/<uid>/<name>.container
# (podman >= 4.8; rootless, so cross-user traffic is loopback-only per ADR 005).
#
# CONTRACT (step-0 freeze; phase-1 stream B implements rendering, phase 2 uses it):
#
#   mkContainerUnit {
#     name = "llunde-backend";          # unit file basename
#     uid = 991;                        # service user's uid (users/<uid>/ path)
#     container = {                     # [Container] section, verbatim Quadlet keys
#       Image = "ghcr.io/fredrir/llunde-backend:latest";
#       Network = "llunde-backend.network";
#       PublishPort = [ "127.0.0.1:8080:8080" ];
#       Environment = [ "APP_ENV=prod" ];
#       AutoUpdate = "registry";
#     };
#     service = { Restart = "always"; };    # [Service] section
#     install = { WantedBy = [ "default.target" ]; };  # [Install] section
#   }
#   -> { "containers/systemd/users/991/llunde-backend.container".text = "..."; }
#      (an environment.etc attrset fragment; mkNetworkUnit analogous for .network)
#
# List values render as repeated keys (Quadlet semantics). The module wrapping
# these also owns: service user + subuid/subgid, linger, per-user
# podman-auto-update.timer, and the daemon-reload hook on nixos-rebuild switch.
{ lib }:
{
  mkContainerUnit =
    args:
    throw "mkQuadlet: rendering implemented by phase-1 stream B (${args.name or "unnamed"})";

  mkNetworkUnit =
    args:
    throw "mkQuadlet: rendering implemented by phase-1 stream B (${args.name or "unnamed"})";
}
