# mkQuadlet — our own tiny Quadlet abstraction (ADR 004). No third-party flake:
# ordinary Quadlet unit text, generated by Nix, placed where podman's per-user
# generator reads it: /etc/containers/systemd/users/<uid>/<name>.container
# (podman >= 4.8; rootless, so cross-user traffic is loopback-only per ADR 005).
#
# Rendering semantics:
#   - Sections emit in fixed Quadlet order; empty sections are omitted.
#     .container: [Unit] [Container] [Service] [Install]
#     .network:   [Unit] [Network] [Install]
#   - Keys within a section render in Nix attrset order (lexicographic) — stable.
#   - Lists render as repeated Key=value lines (Quadlet semantics).
#   - Booleans render as true/false; everything else via toString.
#   - Output is an environment.etc attrset fragment (text + world-readable mode).
#
# The module wrapping these also owns: service user + subuid/subgid, linger,
# per-user podman-auto-update.timer, and the daemon-reload hook on switch.
{ lib }:
let
  renderValue = v: if lib.isBool v then lib.boolToString v else toString v;

  renderEntry = key: value:
    if lib.isList value then
      map (item: "${key}=${renderValue item}") value
    else
      [ "${key}=${renderValue value}" ];

  renderSection =
    name: attrs:
    lib.optionals (attrs != { }) [
      ("[${name}]\n" + lib.concatStringsSep "\n" (lib.flatten (lib.mapAttrsToList renderEntry attrs)) + "\n")
    ];

  renderUnitFile =
    sections:
    lib.concatStringsSep "\n" (lib.flatten (map ({ name, attrs }: renderSection name attrs) sections));

  etcFragment = uid: fileName: text: {
    "containers/systemd/users/${toString uid}/${fileName}" = {
      inherit text;
      mode = "0644";
    };
  };
in
{
  mkContainerUnit =
    {
      name,
      uid,
      container,
      unit ? { },
      service ? { },
      install ? { },
    }:
    etcFragment uid "${name}.container" (renderUnitFile [
      { name = "Unit"; attrs = unit; }
      { name = "Container"; attrs = container; }
      { name = "Service"; attrs = service; }
      { name = "Install"; attrs = install; }
    ]);

  mkNetworkUnit =
    {
      name,
      uid,
      network ? { },
      unit ? { },
      install ? { },
    }:
    etcFragment uid "${name}.network" (renderUnitFile [
      { name = "Unit"; attrs = unit; }
      { name = "Network"; attrs = network; }
      { name = "Install"; attrs = install; }
    ]);
}
