# mkQuadlet — this repo's own tiny Quadlet abstraction (ADR 004). No third-party
# flake: ordinary Quadlet unit text, generated by Nix, placed where podman's
# per-user generator reads it — /etc/containers/systemd/users/<uid>/<name>.container
# (podman >= 4.8; rootless, so cross-user traffic is loopback-only per ADR 005).
# The wrapping module owns the service user + subuid/subgid, linger, the
# per-user podman-auto-update.timer, and the daemon-reload hook on switch.
#
# Rendering: sections emit in fixed Quadlet order, empty ones omitted
# (.container: [Unit] [Container] [Service] [Install]; .network: [Unit]
# [Network] [Install]). Keys follow Nix attrset order (lexicographic, stable);
# lists become repeated Key=value lines (Quadlet semantics); booleans render
# true/false, anything else via toString. Output is an environment.etc attrset
# fragment (text + world-readable mode).
{lib}: let
  renderValue = v:
    if lib.isBool v
    then lib.boolToString v
    else toString v;

  renderEntry = key: value:
    if lib.isList value
    then map (item: "${key}=${renderValue item}") value
    else ["${key}=${renderValue value}"];

  renderSection = name: attrs:
    lib.optionals (attrs != {}) [
      ("[${name}]\n" + lib.concatStringsSep "\n" (lib.flatten (lib.mapAttrsToList renderEntry attrs)) + "\n")
    ];

  renderUnitFile = sections:
    lib.concatStringsSep "\n" (lib.flatten (map ({
      name,
      attrs,
    }:
      renderSection name attrs)
    sections));

  etcFragment = uid: fileName: text: {
    "containers/systemd/users/${toString uid}/${fileName}" = {
      inherit text;
      mode = "0644";
    };
  };
in {
  mkContainerUnit = {
    name,
    uid,
    container,
    unit ? {},
    service ? {},
    install ? {},
  }:
    etcFragment uid "${name}.container" (renderUnitFile [
      {
        name = "Unit";
        attrs = unit;
      }
      {
        name = "Container";
        attrs = container;
      }
      {
        name = "Service";
        attrs = service;
      }
      {
        name = "Install";
        attrs = install;
      }
    ]);

  mkNetworkUnit = {
    name,
    uid,
    network ? {},
    unit ? {},
    install ? {},
  }:
    etcFragment uid "${name}.network" (renderUnitFile [
      {
        name = "Unit";
        attrs = unit;
      }
      {
        name = "Network";
        attrs = network;
      }
      {
        name = "Install";
        attrs = install;
      }
    ]);
}
