self-hosted-runner:
  labels:
    - infra-1328085692-amd64
    - infra-1328085692-arm64
paths:
  .github/workflows/project-ci.yml:
    ignore:
      - 'property "workflow_(sha|repository|ref)" is not defined in object type'
