apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-nsql
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:PiCiBaSy/g==,iv:Rz1DcQKgbjyAdXKzpKjLNF0tI8igvUIfrtWDaNPwD5E=,tag:8HIzIOs//TfdkRmUak5J6g==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:2E9D+qZI3S4H,iv:cXwcsGNWgoTetYhIrOuMbJOdqswAMa9PeFgsrHs2IlM=,tag:jYVr/huHbGEg4USzp0dd8g==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:mTQnU9n04NV1s531pH8TjufjNXod6u5Db0+8AoQ8icEr65XOSyP5TaAa5TgpC5t0Sc1K3mgM3b9eIF6RYB8CaEvOlz12Xb4o269IgpRbx/aPXhnUR7zXIVOLa3OrON695GAzfRxtsVveIRK5MdXSxqq11gq6PNsh2zdBcwzStv0F6AO/Ed1GJKFIG4Tu7Wvb+ckH0vmMi0aL0x5ChOcnjEZpOIs1Jndmuc3EdrvczZcAZv2riZNqsDiyHiY+bpjkRffEYPzxLDNGdXhU9uAnEaWLm85vWEwbx595PQJa7BBvWFNJvJPNqv3/jaHQAf0JvywVYeKTJ2hd0o5/rNdbDnjRhIKCAmvRJeiz1D3uZYC7IQpYYfvnP6/OaRlUcnIFTtB9KYWycVPBpZTe50bJ23szy3ny7Te7HQVYJr15cUQPfw26WFtCBuxtSbaUCHLjyXEhkmMqLjCpZBMfR4p2gjjX9Co4niFUc374613880x2roKWri/cEKVieQppxC/nKtNvZXFv1yvWO1I5DXZoxZQyQlJuh9Z8zYx+JY6kCAjGS25y67MleffVhpTEQezWSK85QBCXKTtyJbPjgNoNiEbuLYzJOqhuJ43aAafV5f2CUqygHS8189oAJ6MnqWjZ+OpGIU0HiOH8sDwjdoT1cSgwKaYPv1uonS5Bj8p3sb/6OPXA5gS3LFEc6I+rk2ndjT7V9J3Q6/2ZwXWUTichE5/0qFlf6ceQFziLklpEsk2RlubIo+SClL00lm3NJr2dYVZcZkpvSpRL+pzDttIBLNj0shIrO9FvZc1/9cUviYQolcYHmxmTms0PlqW3zSCx5OaaGBPU81oYzgNaz/vMkto6iuS2GzCHcZbQ1sbsxWeM0qg3Y3ZHtvTpYptGsKaTasOY0kGgDEl82L1vv9GBCWt4uFTF3p7BZ7iIHwG+zNv+u8mu6xe5H968vYQpHpY1V0ejMTU0awgWjWwclZcx3g+ojwSffs93K+BZ5RVMT/H1BFuow2omBuRbsh+lVTu11Zbx5izlMBvM7/TMvcaQMp42+s5TcdlFig48Lpn/YggLZJCPeOPcpDkBlSQx/LWFZ11m1/3I4O8z5HCE8eqsJ5DUlN+orlxaM27JZybFEOtF3iilvtnPYJyn5miXaWSJshcAMOsHGXrFicq3/SWR2L32zmyzy1wsZpzQlpXo8SHiD6sjvBjxcd1nxDzlpEfrM3iNPufSKCvQpQHtCFohuXZaJMdgx+GFcH8RMuXRuekxl6p5Rxc/faM+zxIXG123P8vlUmUNOBlGT2ZpU4RmZltvP/W1dHDuZMxynbPaJiv+J53KG9dUo68J71ispVuAoc03Z0Cps8OBqoFrr6AvBbMiLFYsV2uXczrK29MWbeWyUkDRlvC70kpAwoR2+zO17PY76xj4ed0rgjfpuNvGn9OEMy4hlHYaK7cBuYeVQ8CZ1SkR7d67Am6Z8DesDSU/l1jTACWz1elLcyqYMkW4nOq4p2ZaAK8NsPxBfLkVBQYP3DWXxDFNsnfqTvB8KwZdh449v/MjP/IisZXn1WMKinzRpzTkZVz6H8wrYiBPixiphG0FnlJs2mJVgX83NG2XvCMzQ6DZHj+gDfPX6xzQc4b1lwG6rpH0tLMkKtsV4CFHQDLZaaam6G9lZqRVRJPX8vVNOWrBQsLIRDS//ymdKo0sIbkvM7O4mXeTDU4xPbKMCAV5fS4FGjDKNfmmry6By+YJ0mgBXbruo6qjkRpscL+eoE384ZI5HBaV989rDZo+Z29PXkmM/KNmTqZNrRAl7ahywcGL4x/r1DDCDGbES6gdk+dsJ6wHmMQFvpIPUf2VMa+Jy4UO94+iWoJexBVRM0AuonfU/E2eiD6tVsoYOoMp2z5jc6tgiLqykz3jS4W8f1OzEbQ+WPUO9cd0s6f5K99U4F4jUxWs7+J2kTUYfVBzU15bnmlfPFDLbemzYIwsWIYRt41pDvtQYiqwf15a/N2XXBVqmvY7YiDNAkWNUlvVcuFeOT/gI7AoFv2M+Ser0Jr52CrS8IOU9WvlvoQvSa+fycyTqcAjTtMA19Tn1D3CVNxw2Jbk0yaZy+DvGNgw5OF8ZjyB3G2Ad7+X+gf/uN5X3pHSDOQ1LA8uDwIr59piSuFCYfq7LmJqttZJTWJn5k1hZPJKMv+9odHa5yFEp1rj7+n0vZaA07JGS1FAfdTIrNp/iBMWJGDowVNxNiy48ceEH8y3XtWFajRQOg==,iv:Hy7+lBeiLHTFn/9+xLJ/Q8NtCiJ+1guTI+xOPsfEH2M=,tag:S8SrOVtkoEVrA5nUq/3K9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUjB5QVFhNnV1WUVQT2No
            M1R0RXIybGNDQ05GbExxMFR3bEc0NDV5UGtBCmQyVURIcHFFK2Y5MlJBK1g5T0dI
            cTFudGM0eVdUQzQzakJ3UUtBd2JHWmsKLS0tIDJLNi9RRm9uZHdrQWZDMEhXenRR
            QnR4NWhSWFBMVGtaVkozd0NXWEt4Z2cK/7M+ZQZc1iJ/sBu+LzbW+XW5vTIRPyhc
            M827tZRnVI3OqlH7i9TuRDjY7dqXi/Iqikzf6PDlHNWQui+zCH+Log==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSElWL0V3QUgyQTNoOGNM
            RmN4dVJseDJSaVppZGVibWcxdU81ckpVeXpNClRYeGdqRzNYS1J6UXNBYy90eWZF
            QmhUUkNSaVVDTjVOVVNWTmk5SGdhRzQKLS0tIE41dmhER3NCYTBpdXViVHZ6VUdm
            cVQ3Mk5VS3FEclAvenlOdUp5UVdIMmMKajCNSPuNc3W8MO9TP/Oo9vqtcqY2UdSM
            xEK2jsQVdxoCl+9EqQBCMZnPNz68jrgBWB8S4UFQpXBJi+KlFFEw9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dHdmazhTa3dvVlJzOWZ1
            WmNrTHl4Z3QzanE3YXN5Zjh3NytKY2s5OG5jCmY5Rlo3RWVicUYrclRjUG9rZ3g5
            L2tjaTBBRlV1V2M2QXVTNmxtOWxyTWMKLS0tIHRMbmh5aVRMcUVZanJEWEs1Zzla
            blJrbUhGdEVxdW1TcjJ5VGJycStBQW8KCs0U3Bv2t174TUEI+BkvlPSmpgZzjnQ6
            bDmk3cdBL4uN6c824a7n8nn3xY1B3MYdOfSCj66XW+3oT1gnVJeP3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:A19o3W7CMnY8c6ylG6rMKxdYtqhiHXuR0lIu8llWtSh+02Il68Lp1VELLHf3n/oX9AGs4RE+8x9u9sVt3jig6S5rMUAZCkbmvayN++mgSTYAqZVO1amthdCEyUNP61IAIft4MWjbADyvS1KTmgMimytHNXDb6Eq3nA9+/TqPXMI=,iv:/V9Mi9QN8wpkqVTWkY6YTJByzfBcvuPdgYKzuQkOBJc=,tag:9VHjSV4s+g3MIMH22cqM0g==,type:str]
    version: 3.13.3
