apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-nsql
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:3QdWjSXNaw==,iv:Rz1DcQKgbjyAdXKzpKjLNF0tI8igvUIfrtWDaNPwD5E=,tag:H/OaTunL+R0fsFmp5Nd6Tw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:cAPmC26RzuiU,iv:cXwcsGNWgoTetYhIrOuMbJOdqswAMa9PeFgsrHs2IlM=,tag:3MolRtUpZWccykgwSXgCSQ==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:h0mhYZNbgj2gJUEX3KqFKEDBcLwDuohPDTDWbk3EIxk32LgmXLxfnBHEKR5q+zVt4VlYI9Bo9Ajj9NdVS0e2oQTLdh9e3AGeTqo5/GksBCwuCe3eS7ryz1UM6Te6nrpjkHr+dlMa20Bqy62xjpat/8MPVClGOFV2YSNVHXm1Xtj1ySoDO6HSvBZqhJaPMhXaejIE98SwLZNGIzRgWPJOnAYAB7xaWQpVdQTgMchIt+MY2agoWSs6tTP4Qvcs5PdejxC/yX+srr8G/mem/bMaiRpfBkapmByOLIQuYg3fpDsEMu+hKxzN2dD1ZaeryYIM3FK+ytnPih0AJK3wXL5k1drJrbcFPl2dmBdazndV9f3zdgKPB4/Mw2Iq2jFxlma+5KpOZoiL/CSqMB30ZqBn4bWitO3RLjPOwo9HzEr0AlAH9vPfaJkzNUBGhXfLWwT1RqZG2GPUpbPbhITKF7pDmrsp9PxCIzIWpEVpe6E6IX7OJnMLouNbsI5e13jK1PGlR7m0bgGQzIGUlH671caZqAmJiHhVPJ3zIqqHkAQLyLiCvvsiXEcvYTZEYSlJa6QORJTNVOZtXfEgPJU6p6Mn3XP1ZCgiXHP2c6atIiXh88p6Ne0SE8e7DHMT4tIu/cEOarxpV3UB+5tKcziFyCTo7aubBlojTFkAJeggYq1679WzrMelXIDAlO4FDYPxLdpUw95jGaSLGekczvXiFAU60/NfaNIddJymhs2PkJz7wZwxTiVOYZhCV2rt+lKdUaJ5xko634KUTK0k18qWic8jeWEO96Z9xJH1pUctzS3Djw1rbka2OHbgU8V4HPwgU4+qv1/Bb5Z95aHLR+ehHNFBDJSkG0jt2ls29G7+ZZ1SyWmESY2BHQSfWva+n+Nzyoxqwim/B7RAFLCGCGE6JxmCyeyzIZu2uOOv+oHpuN3qpmfwOioxhEe5s46nx/PtI48ZSnLrA10z/u7HpQFtq/JZ1UhMoAlpSuLbGoJefcV5AAggZkR6gw/bHxaKOaWAzNPw6Uut9bSfQ1ugRxjspyidxstoiGB6ET478hWeAKxK+PXdXty4yQAIXTuTPvnJ83bGcahQwV5cLiN9AvcRYDtg15R/LsYFPP6/YOS6fNiGXFR6k3aGaxb/ydutRnWkSYx4VibKxx+DrD6rHbqe983KugQRmLuBjLGZjUtqkpJIMwGEDd8MPnSMoOTO/H8Vss5RtREvHKedYeBW3l0lgv3nhYw+WV3IB34MmMSq9N2ScBWdaSz/cmsKOKrFgMAzy7dmp7MutCIEXffnBakR0D7n+8YHH6/Wvz5FCXuQkoWKkMX5BjAoaiXCf89rC9gS5Wo4KtiFTJiC5UI1FL/rR5ksCC1wpvyZsjZKETfS44c3KFI7olOkR0NQ8WwSpc7LhgvQ+ikWwntb1TD5J/d1Uf06uTSt/g654X/fK/byU8lS18U+p3sDYRaWkxBup2eKTiIkAcTjny2hOoGretqkNln2Jyx+exJ4o6B9UQhw7gMjac8D8yQ2+qpj28R7gNed0VFaYDlzWYoezFx7Gm71TEAi/93HlKSSYEM3WJoJwnTF8/WWTjONfN2YrVGOdhd7EfuKlO8WOniSUw8kfQeBjNtaPsfrsOAUklVu2S+mYHTJMkthdQpfD+P1nHqHiPI64pUljafWFEVn15dcIK/5fnOt9QAWGHH2zSfdyWEDOoebk7hGNk+mQdqSKnKf++pgUH6PCforYFHJz3SDoTvirJeQ/xMtYopDHQxodsH1CYd4YajiT43iolA0Bg0nQ2cuSld3IpY1sQuajS44pJLM9k/ESyXXOtnen2qhRzUSAUicfMdDan9K9IYGEtIx/J3B9/s1kbCeYYbOsPAiQJHXyD2U8j8+mnTyrufQVaTcT0tFrh/fR7cQY7aeo3ekCMme4oVo56VGLe61uBaS/MXrp2IUDANwKY+Gz1uVvJBUO3SgbIOhu9Ha7hnFzEV9eWoSVQnnOayONhaZwcCAz3X/z9KiSaoJSRGZBE6mlVlajLENOvKicwDN1NqLacB36Z55hPzG6lB4LIaMJBr/G+8W5mWm8P54iW3F5gnK9TjxvKSLmaxt84fKHbJnQYEZ5EuNv0GjnynoCcQWoJ2ex+eEWpir9ahqO4biUAG69PHsmsVv4ThPWkEpmJ8RK66cgGgApRwGrzJp6KFSQQLJbwf7RKX3OxFCiXY/ek5xVVRsgkwjmWFTKJH4Ty1XBZPpef3hfw==,iv:Hy7+lBeiLHTFn/9+xLJ/Q8NtCiJ+1guTI+xOPsfEH2M=,tag:eFShZOxAW3poTAUafidPGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ3JjZE45UjMvLzg0YW1I
            blBMOXljdTBBUlZVT05oMTB2Z3JSWG4rMkM4CmxMbUY5VnhkYTJyeUI5T0FyOUJk
            cHdGODJXcGdpVW1rM21SR2s0cWJ2YVEKLS0tIHdjWTc5M0hUOVpVV1pmMnZoRG5D
            Wi91R2sxRkNSNXlHK1RFSjkydURpT3MKBdQursCzy2JXxsNzMS6ElJTWJ/Ghg7vu
            7WYHSzGWQwB7rzkRFh2tFIbZIqJa30qsxlmjxxNzjAPNMRknVPVoOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TDlFMWR6RjdRVEh4NU81
            OTBkQS9rblg5LytyRWRBMXkrYUNrVkVXbUg4ClFJdjFKb0Jia0RKWHJsMGtBYW9h
            Tkp4bUZyZVlLeVZxTER0WHpNWlJBMmsKLS0tICtDb0JySHowWUxpcE83SkoydndG
            UEVCVERkRHhWT3ZYSkYyZWxGQUhlQkUKgEh9I3aUoj/vkrATielV/249Q5CMb71n
            My/gqayGSb0b9oZK/bdStMqC0A1+rv6yUBL2wN2YP2YgLXW/1IBBFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2emszV3U2ZC8yWEZ3TmlO
            eHhnRyt0YkpuM0QvSlp2bWdMQS84UXo0bzM4CmEyemkzWjV0STZYekNqR3RlV2dY
            QnQxZE9vL1MvQlJUZEZEclpIQTNSSkkKLS0tIHFLU0IraDUzRVpXenVUQVFlZE81
            M25qSE11RVBWTytUcGQ3WVlnZ2tWZFkK3zSnXjkeChtzx9kFxfUhy5MBkIcLsMZZ
            5f38nsBdxr6DhGm6PpQvmKEmnYsoNHT+edhKC50B31IOzwCsztuyXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:28:09Z"
    mac: ENC[AES256_GCM,data:fVrxSQFiM99s5bhsBvfTC+ndJPrAq+KBgbqJ17iO/7TmRsoPNfL0AB1YbJtf7sH7nRFXqS5VDEZy5AoGjwvi5eqR3a89nRDJ7ZY/4yZ9RChag41h5xDCHjfcPwPMSJXnVx0kgawr/6Afs0Czk5mdeLL0C3TAv6cfgjEu6HJKHNE=,iv:mRqIdDb+0Ym497WhQkjSU0ugUXdkjLFMTcjew1f1bZY=,tag:zgY7qITSqwoE/YUeuVW5XA==,type:str]
    version: 3.13.3
