apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-nsql
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:PiCiBaSy/g==,iv:Rz1DcQKgbjyAdXKzpKjLNF0tI8igvUIfrtWDaNPwD5E=,tag:8HIzIOs//TfdkRmUak5J6g==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:2E9D+qZI3S4H,iv:cXwcsGNWgoTetYhIrOuMbJOdqswAMa9PeFgsrHs2IlM=,tag:jYVr/huHbGEg4USzp0dd8g==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:pNf2weOgstjjLIJjV5XSp3o5prx7yFPlARC+3nB6wNOCs/VAIqNAPc+X/N39eNTFzspxqzR0IcDrgSZt1J/CJRXc4AwTa3j5angQxjT7BXsqtI933ueRRsPaMwpfVLm8NZ3TSboKF1dEiLh5WNSLftCFlOjcksJjysMagBtTSv+6xy0NgZmg5al/FgdWsuZOOjH4AnQOYkXw6O9a7FhuxQ4yBpfnFuSUYNi9Q4qBtVLUmCuhWoNbPNPiYKz6M2WEboW5BUN4ZgrPJFT9T9WrX/PqfPqFJeYl/4m43NdfQ5rk0kW7huI/55NiMZvoskT0QVSxmtmlZxOPNB5ZAtb/HG5zRKrSB93Bxk8eUxLGqBBb9DrxcRbPlfnF1YYGr5nxD8lRJYfjpY1cIF2fn4t3hCpdGksUoCkMTxzKCWzbrHHX+rGsVEcQhgT5KZWKRuT6uPoxsiqkmh8/Wlasz5S66cPIRZt1yboMQteJjt4+TOFzDBMli4DJdQpfyDaqnTw4pEfroR/H+Agk//H/fk54jk9RIZD8NiyEUf6OhqG3ueZoTy60EfZpO3akLHmAfY6jxxBxTascvP3ky+Vcfeqs2KgjSPDrgd8tuqEr8FeEEJu94bCX4enz+Leda0XVlCCnbBpixPx93tEO2ybnHIugB4eWSm5SKx4iFDExCXMfecGswnLm5628jUTlMfgHpl8J2u70EeitKjt4445m7LCvQlSamzszI7Nj8ij+ki9J94oekys5+cbC+eWmttYO/oGjXa3afPLwfYQGZW+uIX45d98iT78hcYIhMg6F8PrXNLFwZHfUC+38NHvWwKfcSdVUUlg2DaJLs6+G7RooxVu2J5ASi22ocdfjcx5uUkXRwaFhlkKMm/xp+73CzpV+M2BHtK60vTSdTHl+/eZdWzqwptjQ9B2xT4hKgHKrknUqvk0KtXN6CW+dEgGSX9Tr+uuuW2dQOTtjm7pEdc2ghzz7tV46iGofI+YmdMaQWO4cPMgfEisNr5NykZCBgcQqWd6w6LQjf2A9ZSedIq/qmXB/yNL4LzYPv4NKzRC/zOwV0aVZVvKAqcI2PbEKEzjx/MBud/ERf03zfxQCNrSlqR9xr8cBeSw7hU4HqCprRYQsBzCAwkA1w/ZYTWvEFbSdYZvLLxEe53Fkqq9pToeZGl62JJHgcUNkss7WntHrQvSAo63RwWZmmzFjGHut9/ysxoHRAAwWIkBWrGFdE/VsFYzZ9OXNDp69oMse291uqoAjOszQigWrQx/caKGUMmRNBofcdBzByc3naPmUO07rOJrAyUd+bE0DzJpinssuI4gczFo56SjSDfvNP4/voVT1GlV3qqQ/Ah4PwA7y1XNNlN5+fWFOq495tyi79DKjOlysB6jRxOBbxtMgUDYNbe2myuugSBcSB53gCrQMAXvtf2j1pXUvsSW5odlE/5AR8nY0xMw84vGnezhznJBY0VHcmgpqy05YZebUFsS1kWtmHkXcZdPsJkrbl4hfIWYfWnGES3NF1/BoEn5yUc5sDfs2ED3o9PuTwcf0BZqfRu17HQ7SRAiz0STTidXMbrPUBEuHSdZlXYZD3saMBx9Hgi9M0xoE6fNQ/ArpaQq9FDP3rm/QoFr0ev0PVAorcQe7m9a/1IBxtpUZp0QGKFjFehckA/MBgKGMA3nPPgE8wlN/t4/kTIFy7jTaE1vHh9oGxkXoDdVCaIBLmeXzdXQx3+jfZ2Npgx4zJWYY1OinVySu1CM8ouhG6Aqtx6TjEa21ilf82e1jKtfBeX2B7pZf84ArhXarV/VHSDFZG7z/tBLzT2umJAhZm8tvjYz9bSKQ61aH2hz6E1TFRXRVjkAAnvVETOQ8L66yE8P/EXbRJRWdU4U052jktc9d7VoVsplPB47rfSD8yjb4lge8HGUURXCfIGXxAwJehkGT1q5GhfuMfV1MFdzEqQSGsKcjrng/xS39Yz+t0s0tVJ5QmrBXSd7vrmuVXxbUEuqgCmq2/Ad1uzqkhYN27L98CdPNCynizwgfg0Gl4GUDsTuVy1LQRcmLiUXQIYNESH6rDIVkLjViiz0Ee5mvDUMZlr8FuE/4d35G8ENh7JiQZhoq/Q23ynWYhi3sckmB+d8pVcCNgGUvCr9MgQNm8aTaRwDA40k2bd7sPnFy1lcngKY3IrrM5pG/8BvE/qFLpKRC6TJv0nrWKH8WpNo6Tr9u0M32pq/mFRpkhHY88TkEeviKe7v7gG1e7A==,iv:fEICovFAguJCswQDGf/09IUhG0fqFfUwy6DLkPRk4b0=,tag:RXs/MyWhrPsKUXOQzQEHVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUjB5QVFhNnV1WUVQT2No
            M1R0RXIybGNDQ05GbExxMFR3bEc0NDV5UGtBCmQyVURIcHFFK2Y5MlJBK1g5T0dI
            cTFudGM0eVdUQzQzakJ3UUtBd2JHWmsKLS0tIDJLNi9RRm9uZHdrQWZDMEhXenRR
            QnR4NWhSWFBMVGtaVkozd0NXWEt4Z2cK/7M+ZQZc1iJ/sBu+LzbW+XW5vTIRPyhc
            M827tZRnVI3OqlH7i9TuRDjY7dqXi/Iqikzf6PDlHNWQui+zCH+Log==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSElWL0V3QUgyQTNoOGNM
            RmN4dVJseDJSaVppZGVibWcxdU81ckpVeXpNClRYeGdqRzNYS1J6UXNBYy90eWZF
            QmhUUkNSaVVDTjVOVVNWTmk5SGdhRzQKLS0tIE41dmhER3NCYTBpdXViVHZ6VUdm
            cVQ3Mk5VS3FEclAvenlOdUp5UVdIMmMKajCNSPuNc3W8MO9TP/Oo9vqtcqY2UdSM
            xEK2jsQVdxoCl+9EqQBCMZnPNz68jrgBWB8S4UFQpXBJi+KlFFEw9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dHdmazhTa3dvVlJzOWZ1
            WmNrTHl4Z3QzanE3YXN5Zjh3NytKY2s5OG5jCmY5Rlo3RWVicUYrclRjUG9rZ3g5
            L2tjaTBBRlV1V2M2QXVTNmxtOWxyTWMKLS0tIHRMbmh5aVRMcUVZanJEWEs1Zzla
            blJrbUhGdEVxdW1TcjJ5VGJycStBQW8KCs0U3Bv2t174TUEI+BkvlPSmpgZzjnQ6
            bDmk3cdBL4uN6c824a7n8nn3xY1B3MYdOfSCj66XW+3oT1gnVJeP3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T22:34:10Z"
    mac: ENC[AES256_GCM,data:8P/xhxCzslw/BESg2iqb+svNc6KXnJ9WcKz2LoWQ5wrWoBVfgv0w6s7T/t2LRT26c+OA1X/eDKAzlDNJL+7Os+gJos8RvYb6u5UqtIX/KJEI8rAwzXFRmzLxiUObMM5TGX0+PSZenby/Kh6kP4BAsdyesIxOSLk4s6m0by9hAqw=,iv:rF0lRxh3WuHaZYu5FDlAAUP0RctkogAmVseabhOuLXk=,tag:XkaHBjYJM7ywOhkrSg0sOw==,type:str]
    version: 3.13.3
