apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-nsql
resources:
- ../ci-namespace
- github-app.secret.sops.yaml
- sccache-ro.secret.sops.yaml
- sccache-rw.secret.sops.yaml
- sccache-release.secret.sops.yaml
components:
- ../rust
patches:
- target:
    kind: HelmRelease
  patch: "- op: replace\n  path: /spec/values/githubConfigUrl\n  value: https://github.com/fredrir/nsql\n"
