apiVersion: v1
kind: Secret
metadata:
    name: sccache-release
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:04H21Z4lkZ8tnLGnvFS+3b3h8wE=,iv:YY0LU6apYomZekxsgGRWPL9RbUqCbv/TOkJPRUIxUaU=,tag:DFt0wVhM3Xx8QW0Qgd206g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cSQfEqXULRa+bVB4fGjsERav+k39QU5V14J6/BJwu7BfRS/NxvpGHBDBYk6CG1A2IetWQHtJAB0vQYAhKWhbDw==,iv:lznCDOxKN1OOB07D9GfnmxXc+uBwwTMfZfOmFklkYYM=,tag:C43QapbGVU2bZT2NU/Uu4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTytNZlFmVkV0N2dLOWli
            UTNQK1YvVm50SWF6VGFvc09aL3prR0hUbGg0CjNrQWIxVnIxa1NNc25tcHR3eUVo
            dXpTeThZc3RPU0xsNFNhU2xLc2FlWFUKLS0tIGdQT3RRSVBmc0pka2JIVDlpZTFR
            bXhhTld0cXhWa2dyZk9FVHNBYkRsZGcKnZ+/i7dye+aFWIhhCwt/b9+SSZAbKBe4
            Jw4GP901C6QCyKkYwO3V29UqPRi5/msuEoxvJUIWjdhXMS0ufANoqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bUd0UDE5bUlUa3c2blpj
            UEdlMGl3amxNQ0sxVHA1Y2J1TUFndXhlQ3hBCnk5Wmg0RjFML0dLUmtVYkIxYlB2
            dVlWQlhiTExLM2xpU2NuRzZHRkUyc0EKLS0tIElTODA0SUliZm5yWWdyS0JOekVF
            OWI4VWF4RDhsWXVnOWU4QldiVnd3cGcKeFISRuT4Gy9Vz7BoBDKFfvxgYCeqQJfd
            OSNTZpwVdZidS88SmB/9d3BNCA/CsWe+Q0F5xZJz+DxLkWCR+ZPCAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Wkx5T0tlYVZuVElBMU00
            RkU0eVBEeVVicGpESVloUUxHYm1YSXpwMml3CnIwdjFmRTFjbjVxZGx1cHpiaGJj
            bE5taWZmTm9tRmRFdk1TbDNJMnRYMUkKLS0tIFk0bkIxYTR1aklDZWJlSlovKzl5
            VFBlKzQyRDdrdEZPajR1MXp4elVHL3MK7e+xVC9MGTwYZdyXtNYynM9KhBQnsohX
            DHLjRQdfSVRv4C7sZhrJOOFQH88VYB3WtIJUmu1FTEsU22o+pYOVzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:55Z"
    mac: ENC[AES256_GCM,data:kVtmmxbo9nz56oZ9eut8U2S/bvyIYSMV9XMSf9iyUIlHFxdOHAk1J9M8IpTbwe8y95AUOmxLqqWURakm7Ba1lwNA7dCfVDe8trZPxdQoYFa+JsjSH3Lfwsqw1OkmXbuUlRIssJIAmTr4e8vUcq3XLTRDEdYxvk3v8aMv9q5nDGo=,iv:8QLtsSAMuigykDLX7nTMr5Sn4h5o2xG8cNvz+UU1IxY=,tag:iJmw3EP6HCRvnxHh/Nv+DA==,type:str]
    version: 3.13.3
