apiVersion: v1
kind: Secret
metadata:
    name: sccache-release
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hocx2YirnCpRc8BtBspmHaPjrJLojTQDpFo=,iv:i4PIvF3mR9RVfZyfjaTXqeGYOfmpSQB6IS2/M9ZSGu4=,tag:t6E8X85dEJVz0dirjpnZ9A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RcRoMnfXr2tY1qU9djYJJuqIKdIsHqJq2bW7TaJVFRX9VwPbnMgwI/5u0PcBlzM5kVrWx+hCYGtqtK9QBUiQBQ==,iv:QBikHo5W6+20hFj6IxGIK3HuWi+xjAnoXtARYOP/RsE=,tag:7XxHOfc43nrFcsW/T5azsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITTI2YzRBMS9XYU9kNkJX
            SHRUeXZPbXlqYzl6RFoyNXFoT1pJcHIxNmdNCkQ3QU03ZW9EaGxDVFU2VmFCUHh1
            TzJ6NDRsN3MxWkFXV0ZGVERNN0pkRW8KLS0tIGtSTzBlL1VrdHRwTzlYYkJ5YnBz
            bnNJTjhaQkkzTXlpUUdrRWk5MEVoWG8KwtNzOycFWbs85i+wE4DKZySyBD6QUiKq
            WTtTJpNRAt/dFvbhzsOKAj4jwtPRBV4JQd/iGxl5qmanNGqiTorVig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdkJBellZK1pPRjluWWgy
            SDJmeEZpcHZ4Q3EwZFFzbU5RcWU4UVFYYnhrCng4ZGd4WXBVOG1RdVdmM2phYTRz
            TDdVQ3lvb0dKOVpLT0xWdzVkdkh2OTQKLS0tIGJzcE9jMDh6Y2xlWG9jZzBJT2FH
            ME9kYk9wNXBvTFUyQ0dKMGRpU1FBQXcKzt0R6b/gAy43vhr6Jy/oC7WHOdFz/M8m
            J0P7WRZj1HBoF8ZLZTTomkXwWjXv2ggYLHEDp9umKtKPmcmsDEG6uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdGJwUm9JUVgrSWRuTmJB
            WWxXdG5vQVo5ZzRBNDVDVlh3QVBndDUzeVNNCmpJVnhseDNHMWtzWGMybm5ndnAx
            anBqMFZJUVhUc3B0Z2oyaUFjZFpqVDAKLS0tIEU4YWUyck9TMWc5eEhwRVRWcUV4
            b1hlTUpKeUI5ZmU3cjlvYkxucDRtMWMKWPNf5BcyWyghcMFfoyGlVmaw0J7Pyo4S
            Gl//90wNcYSPg/1iZGgcN3cHrc3YnuGuCEo7XV6jLoaNXYPoW1ay7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:oYrOuu3phOA4+coxGsY8ElB1hBgQliV2ZgKbXdO625bD1Vdb6LR74z9TTWu/ePYnqBFn9xy/K/sowDxDhM6bhr31hYj9bsAL+PsAID07xXvT1nV76zNm7/LzhHMbTFHJCuxCyKj98atJDiPer7/MzWMPmncyqlxVlMpo+mMZDvk=,iv:2t+PG+XVwxtScvjzUI5qX85yDZ99DJxJP79e4VcR9ic=,tag:PkHZ9hqI+Le/AjU93bfURA==,type:str]
    version: 3.13.3
