apiVersion: v1
kind: Secret
metadata:
    name: sccache-rw
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MP3q3Kybj9pK60Xedvdt0UhaJ6UpeYzotDg=,iv:ma7UirtUfvMGRUYPYcL5B8nYh2AfZj8WgTx2glTUC18=,tag:uMSHIVAkZLdjEhkl590GnQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ROsgkT8aJxvVUm5r+RCUZjLPXbUYMT6t5HynmqcN0FaWfVl2fhdOpAaF/tj41/8v2aHTmGN1OdlZmSiiczCWtA==,iv:MhhJokFz1uOGlZKEVZoGrQL8tOzG5XcmzysKALgvjX4=,tag:LfVrbiVlIczdDVRmrYy+Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc2tsdHBkWHBGRitwaWZ5
            aGFRWlFQT0RXcEI2c1pkMjZHRytVdGJpcmhNCmdnV2UyUXFWRFR2UkdvbVZNWWlQ
            amUxVzZrZlRGa09rOTJQSXFzV0lKWkkKLS0tIHVINzVHSUEvdlNjQnJ6SmpKTnN6
            bVpOY0p6Q3pwbk1ucExDTzl1eFhXZWsK17TXHTETP/NTI+zDdfFR0z0xBzHRr8ib
            vVQXCa7LHFTGMYLL65KsFwxK+eLgUQA7JYFGZQ0k10KeWsb0+psdAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS3JSVVl0QTQvZVFjamlp
            dTI5MGU3MGJjTU9pSEhET2NnZDk5M1BSRUFvClExN1d2Q3MxbU9LUThNbStjY0pY
            L1dQR3BXMHVaVE9TcHBSTUhRM2Rxd0UKLS0tIFh4a283RHMwWTVNL1BvcENUWXUx
            bDgxVXA4ODRVejNsdFlSYmhmWGFGL3cK/mmq/IIgUChnlpzcGjf1dJlhyAjMpOBB
            nVdQqbngwgNh0PxfXkdAX3cCtu4To2M7KzhGF7fsZga9wyJHAQqvxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NVI2ZXVsU2RWbER5enBs
            K2FmcERMYngzWHUxbkRid2ozM2F4bHp4YXhRCnJqbmNBQ2pSWURYblV4QmdXWVNZ
            enJjY2hYb1dDY253cjlNbkcydEpKQXcKLS0tIENDc1EyODVzWTFiRjR0akpHZmtQ
            b3ZlL0VmbjVidWE3UFkwa2VwK25ZUVEK6bpnQObvVfl6l0bNQY8dpBAEztHethyc
            zGnJn9PEv1MNie7dSYSwvIk8Bagu1nblROZ4HEgxwNjt9xAoOLAAMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:28:09Z"
    mac: ENC[AES256_GCM,data:JJq3CpLn9JxXMOfTuIQaKwYrOI9U3jp4lcVs6xZ3dXukXcVBQz8LfF+6yJqn+0RBCZvQvtrGBVN+u23hBCCH3Uc0bVKiNMurnj5D+w9BDHB2Tc80wayGLiDyplntjJuhK8842kdAL/UveLCSybS5K8EiO5Q3P6hXjoArslSqbl4=,iv:0rd3gGe0U1Nr/5hsi5Ixj2hgUEAoNhjxWX/GiBuuhvM=,tag:urGGhJbtB5ARfBKa/J9Qcg==,type:str]
    version: 3.13.3
