apiVersion: v1
kind: Secret
metadata:
    name: sccache-ro
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Eg/OkELKU292RtKqI999F1PYQoY=,iv:ZCUfCYQdfR6hVUXzdR+Sc2ompa1TJ9CYHRJgj7QR5fk=,tag:PI10o+YH8qBMz516u6dAuA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fT9O2owgsPsWPlyiubx6EK1JNdkbUUbvqxMv5BNfEiD6crLBK8RtEmAwOrnXf4Ipt6M7MUFNlqvCTMvIfOdIWg==,iv:fR0fmOy6z3tjalIN7McE2NL2NHPo/aDldcNTWoAsgsw=,tag:VL4OKtzcdgkCD3G5fVLHGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vys5MUJzcVFjR0hneXI1
            MWljdVpOQmpJYi96U040WEU1SStabjQwVlRVCi95bTN6WEM2byt6b1dSMFltVW1U
            YXZLeldnWjl1bXBqdDkzbkkwdUs4SUUKLS0tIGlvUlhQLysvNlRmOWlPWHRPWk5Q
            L1JQK3RTTFlzWS9qdkRYSldHZk80bEEKTMOeYJe62OYW0Pjuk2dZDLX5Ht9v9M1f
            uwuJaQ74MfWwSl0137pp+SWeEFMQsnsb/7B0lUc0kQ7k+Bv58ThI2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ0txNE9LWjkvNlZGNHRG
            YXQyNjJDMHh0TzFTK2grbm5ya2FXQ25RMXlzCkY3d1B6SUhqVlp1ajJLVHlFRUJv
            alBDYnpNUmw4OCtkNkRoT21yR2NwTU0KLS0tIHFNc25YbU04aGtaaHVwRUJ3L1FI
            Y2FBSktLZTd0QnpNdGc2cmM4enlPeHMKMUnJsPEn0sZhnzpX61xKgCGArp1u2yxB
            6p51sEDxpy/RpSugBudTedv3dRF7jFWl/nTlFdGesf70YZtxPXphcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEanRXZTY0b2tXeDd6engx
            K3JOUnVFRkJHSVVMQXczRW1Ob2RhYmk0QjE4CmJ4elFjSW02bHc0TTR2VHBuM1Jh
            bjMrWVE2Ynl0aTBDRjlkdUFnYmRLVkUKLS0tIHRXZk9DVGR4S0hwa1pwV1VXN2gy
            SFBWenFEcFVuRVJ0VW5xb3lSMGIvSk0KV4cCFkfTCQWSEkVG3iGQMqNSI8OvdBeM
            8Q7se0XrzS6jBmD491dw7HGl/mVxUi4oqhGSQmi4jW+0+REhGnM/bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:55Z"
    mac: ENC[AES256_GCM,data:/Bh8r82N5S86fN228VqXxiSFnoNVzu1uvAfHLhtY41e/MgHLHy58aPod/wY6TVstBRWzss2rV0flUD7MLB/EYASHdJq1xgk8NSzvmpMto3lIIrzUopn8kjo1ANJbBJA55wihn1Jcp6rWIyAv1O0MFzhlXLQwTAEA+lkjq5/07Q8=,iv:7WhHO0OheS2l2GOFAl41oUm9dcj5C1bgAu8P38NgNgM=,tag:UgKcxzJV22/rXrScl9sFxw==,type:str]
    version: 3.13.3
