apiVersion: v1
kind: Secret
metadata:
    name: sccache-rw
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dcWOE5Nxfwo2QHtPFLj9l7cVUUU=,iv:KEqHIbmiOzhzi339Hn0wLYyT+E5d0mBnopS4BDB6iV4=,tag:bWbBLsU17XvSESrN0MnqsQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zD3LvKanQfVTQPr+zWQcBV8/OUcEIb55Qp16xfVEQPtJqfYSNe4g4C+1AnscYRU/H3RiUBGvSYAKPXy5tQgYgA==,iv:Xkbe3M+nhU/9H4BBb22hpiUuyrbHkLjsLsbbPJQWSEg=,tag:w7IjvYk2UJZTw5wj6OKGLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQnp4ZllZbnFMN0tCSkFT
            NHVva05VTUwxUERWaEZwZnFJZ1htL1E4T3dRCklkanc5QXpBTndac0FqOWJMNmRE
            NDRoV2Vkb3RNajhMQk1Ob2dJeE9Ic0EKLS0tIGxVS2V1SzllaEhPMjduTFhHK2xK
            UlphY0hlZm44VmppMFg0N3MxZG5pRWMKblRb3suT0CONNtwB0Rz85RU/KpLeo34M
            VMXEAgo07fC00xHx0z/I3WBRJRTyHluufIme1f2vwU1FLKoZqh6e3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWWRVdlRtdTlOWENxcFRw
            ZUs4K1R2ejJiQnZWeEhJM2RuVlhTdVNkTFZFCmk1aTI5UE80NStYajdUUzN2aEpk
            NnZzdWdmaEJ3WjJ6c3E0Z0JSNEtNNFkKLS0tIFVOdHpTcTlkSXlaL3QraG5RUUs5
            cmM5VkNldHorbzFxZTlsQkZDN21jcEkKfOkfYsm6macXt576CRC/mA/MMjfZbK8j
            hswPQyNxNvrWFQrMuymPoyx+ewzK4LC7V8TgBm/pUoAoCjTVNr6lEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaE1TQmNGUUJlbnNyV1I2
            QnZPQmUycjM1UTMxSE0vTzBwdmM2ancxSVc0ClVYVVJaa25xTFB4STZtRW1Eek9y
            Q256WGtRZ3FHY1lDbUNDWmRUemMxdTQKLS0tIEh5MDV3MURobTZzeWtYcUpVSVg3
            MHI5SUZkZVFXcFEvb1dqM2hFenpmM2cKy0FFAl6fYO5nKX2g16qpqRbNHmZ1pIIt
            Cd1dsLyulZuZH+m0F4swdbB6kl76Xtd9A5Gu32XDf7uvfKHJ3FpMmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:55Z"
    mac: ENC[AES256_GCM,data:7YeXkaV2LOVs8P2vhRO66S1bM/KK17MWPkAFaz+blHsVDcabjxn8ELpjahjbGlQ9ngSCRNoaHRTsg0GAqalBimb+VROF84FK8tjDiGhwe2iPLBtuLSvnjTzQDrF/Khlzg5dZflxotGrH/O543O9YiOcd5AhnIuz/UUcmBefKGbU=,iv:Wz8NAd7m5/spJFofFp4zZGszJraYncWyT14i5gVnIpc=,tag:vDwvYyMh2uMFGyM3qDJcyg==,type:str]
    version: 3.13.3
