apiVersion: v1
kind: Secret
metadata:
    name: sccache-rw
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yOzZ72tcu7FwIptklLUG7hgwlWLTl8NgNBI=,iv:ma7UirtUfvMGRUYPYcL5B8nYh2AfZj8WgTx2glTUC18=,tag:19z/PTal18/lBV0gp+3bbQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9sb6/9IpABwoecRGPwtO4EIgcI1oMJisSUgi3+zX8oPXmPjNWY3SSXPiXJsH7l+6cdJ09y+mB8HRaezwI5z6Mg==,iv:MhhJokFz1uOGlZKEVZoGrQL8tOzG5XcmzysKALgvjX4=,tag:+AYZF+xPnMXtn+IVVYWjfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN3V2dWJzbTJubFRkSWpZ
            Mk01aGxLbVk4RWFCU2gzd2JOSjhWL1F0blZZCnc0aTIyU0pNamtuenR1SFkxbkts
            cDlKTmR0MEg4WlBYYWJZcm42SVl4TDgKLS0tIE9aK3gwVlBmM05VMEVKYUZUQ0k3
            Mkc0M3JtUjVFY2NnVlBxdFlOSXlRUGMKEaScLBsNdzpGXMj9kfHFMyusnyphpEc2
            88LIzgt6LBy3B+MQ78uCOzWyf+a6VbWA5jS2k1MN4vV4iZ2xrLEKjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TFBHNTFzWEJ5NE9rcmZD
            MmNRWGxZSnltbDhqK1AveFNPS1VoL000eWwwCnhJYXpIZUZWeGZDclZVZzZWS2JX
            WjRyVHJqOTcyQ0JXYUVMT1ZFcGtyUkUKLS0tIHhrNGE4Q2QrZ1MvQ2drTHV4ekpo
            UDFUcEl4NHQyTC9HMWpuRnNORldyUjgKCqowjj+lodfcB+5O44Wk7vfLasNVqWBM
            A54y0oBZif49XhSX2niPEKL80NOb+cx5hgDn2YHvvvD3C8CrhPFXJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYUYxMXdERExSUjc2WEdV
            bTJQdzhOMWVWS0k3WnExWnBUZDFxdG9pM2o0CjZ1eGxRR2pvN2lhY1NPTWZjSk9u
            bDNrb1RIZ1VnZ29SMXBrdkxFZGdsRVUKLS0tIFpPWkRVc1BGME9ObVpxWXlzYjR6
            WUV3ckhpT0R6NThtZ0V5YXpSWHRHNXMK8wfmcy+lOM1n6s69bQPYm8H/SumytiHF
            cPwzhgK4tE9H6lGDUBT2KXtzBJv5WzICF0myetuCtw4NzdldmsZWZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:9EiCG1zFmC/q47hMBF0aRdm7I7oR1pCymqJWIVVsfvEta9AiLYMW7YkFlk7LZlRMNazViAj5yCRdyd0GxIVFs7NQXPuipJ+H+xSEMTypHHkus7iBv/io0ehfYm+8lwUTqPBAQPnMWgAkTiYxM+4/Jgn7GjkCAWjnDUNAbogZRoo=,iv:2LhROcL0+s5iKslTWZbYEyMbQbvShBMcnIYRSNviqoc=,tag:V/qR2s8TzKNisfLIo5P6uw==,type:str]
    version: 3.13.3
