apiVersion: v1
kind: Secret
metadata:
    name: sccache-ro
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s0oTMVtVLdBBuPFrjXDANMm56KZMuxwV8zs=,iv:ZLl6Va/DChLUkEFJTddjJgTkZ1nXeJG7bTSqzN+hh/0=,tag:DjNj1yS37nYk7k+VKamGgw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XfRgeU2cfesoRyBgywE4en1bE4iGJg0cjUmEmi9UOC65hJTFA1aE9cEW10qC4r27aM9CAbpvvBJj+EL/lbIn2w==,iv:aCaAEjT8C/d0QI8GxbfhwI79BpAL+LwsrvirGkpGK/8=,tag:sqQarfxsC+4ulMuKMZuLZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1UvZ3JzQ2NIZWd6SFFx
            OVBVS3g0a0V6SUh6MG55TTRlMENDZEpBQ1U0CmcxWjFqZDlKam1EUVNyL2ZNVE1a
            UGh6YjlqUWFlTFZsREdyY2E4WmsxMG8KLS0tIDNHejg5VDBYbVlKZTZhWEVPK0Np
            bUlFVGFNVWFWUGpZVU1QQXJ6K2t5azAKlIteIq7pI+wVaK3VmsxrRBEBw8qZrFl+
            udbxlH0iIMNAfzUYij+nez/7qD21mDjHfMknftAlvUBO6Ok9jjfIvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTE8vemlySGxvOSs2TlZy
            bHVVemZybE9WdXBCM1UwaE9nNktVNHlXd0hJClRQZUJ4ME84NlFwOXZCN3ZaZzBl
            SDRSemsxTDBvVnIwdlowelg0RHZQRjAKLS0tIGtiSlJpM04zSHZnczlmamJ2MWdQ
            QnJLd1M3elVNQVFVYm1SWk85M254amsKFZ/l80tErgscZ8WCfCJFkzahn4o5nyGv
            dcMlzBC+BDvLhk6XAx2VNCf9hy7c3XNjcTHD94BiatP1jhdl0a5kOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UVVrT25pbks4QVFIaFQ2
            Qm54N3VHaUVIczY0TksrN2N4T0UrUGJOTURjCmk2a2l1bWhyeWdzYklqK2IwT0FJ
            ejBBYTFRYzlrcmI1cFAyUmZUREx6VVkKLS0tIDhEdW5pMS9zT1lGMngyS1liRGJG
            TS9RSy9KYW5aOTNsaGwrZW8xRGgwQjgKZXnSFZjUzsheFkElmW7cEASPIJtSYvR1
            +FRu1CBmqUZEpBe9Mw0/iNf3/uytGEYcZZAXitvu69RUUqziUF+nDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:28:09Z"
    mac: ENC[AES256_GCM,data:GMmYRYSwJm/UZDOXnk1YRu9/x9vT1Rt9cpNqxT5Z5Y/zrqM+qqB09cxH2aG2+5VmParVDt2qc1LlCkFVx9LCDaAHTLb2TZDwuh9MTz5K/KKIG8Am+cZZ9j9vDiNPsYqZI5JDqRMwzDZoCz4ca9o5ktkWGr4uOHWuKIocPM3e9NU=,iv:MxjChGwVd5qe1MHWl/RpyezvzXTfglWWj/rEbPnKiIk=,tag:HWNSGQ85PjOP4vkag6V+Lw==,type:str]
    version: 3.13.3
