apiVersion: v1
kind: Secret
metadata:
    name: sccache-ro
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DiVebFH/f9ETo/63Xk0T/1i19jaYMSfbd4o=,iv:ZLl6Va/DChLUkEFJTddjJgTkZ1nXeJG7bTSqzN+hh/0=,tag:q8SAvfJQ4+CEq9k2NWceyg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pcjtc0RJ55wYHxYMRD79hIdfpskY9HyrBv2/0BYPAcwmPMIV/fGHwMNCs8tc4/ZDz2UQbYNPQuz/MeRrWsBNNQ==,iv:aCaAEjT8C/d0QI8GxbfhwI79BpAL+LwsrvirGkpGK/8=,tag:KB8YKXcEkBXStFKL+u6xxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY3p1M0V3K1hlSHNrOUNP
            Z0FYb0RZWjRwM2Vtd1lBTUowTEVKL0owQ1U4CkNJeXpuU0dKR0VmMHh0QXJUcnhR
            NG0zRm1ha2ExNnNINSt2bGY1M05nZm8KLS0tIDdrZFQ3S3BkRDhCZzQxZzBWMm9D
            VDd1a0JjQ2VNRGJkMldldGZacG9kQ1EKhm5BZwGXi4BNyo7gkxWjKzgaBmP0Zy7v
            /4uKlwxf+wvfLEPviRhJQ397c4ByNormp+mAaSKMZfyLsH4sITgqcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZDAxNUNlRzdqd0VOSHYz
            YTVSZzdLNFp3VEN5UFdBTG1uVVRQK2ljeEN3Cjd6OGwwQURDTUFXZUwxQ1BqMVl2
            UVlZcnBLUlltTFovQ3VaTzlQbHU2bVUKLS0tIDBvM0dacEV4T0lSOW1meXAxb1Vm
            ODBzRGEyUXFPSVdZQlJQcWE4eUNBY2sKcP4lSHsi+hkLiJCxtROM/D8wopmwgPZp
            ApXD9lchhR6b0NxMIROQslEWTb/igHFWjuOj1DEJKJ6qhBmkE1UZUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYlJGMi9mWE90QTN2dkRa
            TzVBN0pqK1UwcWgwOHVaYUhLdHV5UHBFQ2hrClkyMkRFMTR1OTFaMHZoKzRVVDVN
            R2lpKy9VMTcrcFZnb2FCZk5XNndMeWsKLS0tIGszV1N1QlMwSWFSMXZoVEFXZWZx
            WG5IckY5bWZpdGJyRnByek5TMlRwZm8K+XPSe2EmGu7qw4dp6QpHpknjWD8MN//D
            ferwjWaZeF0fKDPZ+ClTAWoMG3rwIHf84S3RDpVQNgBmbyBilA5Ung==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:ExMFMqXf49p0K9g732MvEKP/RZFFrFBi7fi5wWb4twgC7serO5VJrtiYNPpgRAk0BTcl6Pda60FKcxUNgrGjmMOQZJGXnnCc7h/Jd7/U0B9R2GtG0nblwS4aKFfu9HRhGWEQqktPF4IXROQfxRJcFfJSjXcyyOtZ2sEMeB0oM/8=,iv:5U71kGGmU9K0SWT1XDhwIVCZL9BwqxJWA4GBtiNVCGk=,tag:vBXJi3ZtwEuuoWWC0NTJNQ==,type:str]
    version: 3.13.3
