apiVersion: v1
kind: Secret
metadata:
    name: sccache-release
    namespace: ci-nsql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xXI2n1KQsF60VM6mlQfT7y4DVo7hlwzYW0c=,iv:i4PIvF3mR9RVfZyfjaTXqeGYOfmpSQB6IS2/M9ZSGu4=,tag:sPid22tLRdUQH9Zsu3mEYg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ykju48y6UvySGaX9qzETHXPfzPHbnuoQeCUwRtS5frbelKWzdz7ya9c0T1jbOUWHnFj6YbMTq9naCza9mOEqvQ==,iv:QBikHo5W6+20hFj6IxGIK3HuWi+xjAnoXtARYOP/RsE=,tag:sLZ0JRBxOphSKQZ4ACAQ4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOHFhcldWQ2tCZUhvc1pl
            ZytoL3Y3V1A3U2hOSTNrcDF0NEZEaXBaVEM4CjV2REQyb2xvaGthYUpMUlBFd2hv
            Rmp5dVJncEl5eUZ4SVNaRVZuZGp0eEUKLS0tIGpRdHBUUElMejFCL3RSQkVWckJn
            bUtwWDBNVGFrMVFSWHo2MmQzdzBaUDQK+rTZ7480dV1wNdblcfUSO0PRz17JNTAM
            ZQ9IgDVU5p5HfbeFZ8YsOTPH1k+4CWCmgMga1ZujnnI8ON8KP8SHHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYkl6SzFUVGF0K055YktR
            SGNwclFHRmJKWWhTKzBjanBvUW5YRElyczFBCkpYRFZJV0txK0I0TUtSRXhUTTRW
            R05MVXhpb21NRCtHZ1ZiUGMzeXFqVTgKLS0tIGxsNmFTSWJCZVF6R2tPT3FMTHZz
            dUFZSWdXeVJ3NndiSVE3eW56cmREN0kKbMcHGfICGIX4VkxN1PTzQTKQHMUtySxD
            9ikNY58fYNmjvVJfQTEeWaTIH3VXZPuuk8hMmJ5Ao5Bli2PQFM0G2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmMwcWV3NnNHVXVjVHRJ
            WXkrZllhQ2NHZ05oTHBKWkg2ZE54S0E1SXc0CmlzeWtxR0JqUXBWdlo4T2YvQnJR
            SGw4czArL0JmeXQraTM2VCtKeGVrTncKLS0tIDcwQTJjL1R1ajZNL2FEUTR6ZHJU
            aE5UMWk1ZG0wUERiMU1IUTBiTldYbk0K7By1qxqRaKpEIc6SKvRjU4Eem1sz9z1b
            R6eQij7a7vDJjjghqwXDII99zZPBDLbbdRirB0ru2LqrzahqhRgZ6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:28:10Z"
    mac: ENC[AES256_GCM,data:smW6AuXq267mZLZ6uYZztFFbAhZHXRsf+tMlyTM+668DNJ1G7dl8Xdt7Pd54QaEIs1kZw77GQFxXXZ1JSiRP818sdJ+cfo8IvXJyFdfgTOjJIPzq5w/FYDZdwRSbkrRT7aExjf7EmLnnXGPmPehYvnoT7XHQxOM+bvsI87f6qHw=,iv:wFxHaWGSFSIum+p7z7RLwbQT7Y3K0pOFDhe0I0VLdbY=,tag:EBQo4bRG3DLqIyUVLwU+jQ==,type:str]
    version: 3.13.3
