- name: Restart infra-dagger
  ansible.builtin.systemd_service:
    name: infra-dagger
    daemon_reload: true
    state: restarted

- name: Restart infra-bazel-cache
  ansible.builtin.systemd_service:
    name: infra-bazel-cache
    daemon_reload: true
    state: restarted
