apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: "y"
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:mFAqXgln3jOO2V3xIcGryQwwMDKq7BCYwtGJ8sQis1RBKWzBmXUUF1SV1vHrF6qSQXasPvI07omUvEJOROHdoEIc9NiqlZ+++dWyDidcw6iyJLVR0FLsNH/gtCxb/SvBiwqx4wMdsINZi7GfnKEtS2MaUMNhJF/Z,iv:TaYyRLHYfwYs1K/VylC45EhpyBmFs+AtC9NUgrKxX2s=,tag:oJ4SNtybw971rdpLFyjfGA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:f9hd++Bn8stEUxhFPki4QiSj8vsP506W5HccsXyYUZ4xtITGW0YhW7JjA5pJNkbjB1WVfriDUxUid3s9p3woegw/r1lWb5ZiRZXTQNQAQY5vXkr8Fao=,iv:+y0gIOOPjSPWRhFWtl0JnUSFQFizcLzGhjblh+Rjzk0=,tag:kYJl6Mh3A3Cm+VO8u+B0zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFVIMVZnMTF0VUZVcEh2
            VThQcWZia1pwbGxlc3JGNjQ5M0RPcnpvOVc4ClQ4cEUzY2dqdnQ3dHc0dyszY016
            cWg1cnJ5SEl1dlJqUW1TeDVrdVE3Zm8KLS0tIElna3lNYTZMekYzOVpNS1laNnJM
            MDZrNnR6UGJyaFp1bkpnejBacitiVm8K/zRp2J7117gW877JWlPaMlfSUmcPAZbB
            GwPxXoFaa9zkMJwW/TbfbsqrBxcB/R7dST3HhbN4mIMoDjB8jB5B5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmejVISWRnZ3gxZyt2VnZW
            MkpHNkVZT3Y3Y3NkRWg0RlZoMjl3S1ZGUzBRCmFGQ0Zqc0FxWnZpTGNmU3Y3ekFv
            Uzhib3BLMnN1ZzdURzNwODFXSkhESlEKLS0tIGp5NzRMU3JTY0lRMklFcnNEMWJx
            UlJmM0hzV0VnRzg0aVVQaGwwK25SVG8KI5vw7sFX3lgkyxDBEC89Cez+d0t9PMAn
            Sw678PnOL3GKj8TjymJ/puG4tPe3u/txhKXiSDk/w9tz8ks3nv+yWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a29KdmdXU3RMQUx1dDBM
            QTVCWG45dy90ZDdHMmVYYjV6Unp6ZXNlQ2hVCnZqaWVIWVE5UUJOMXhocUVCb2Zs
            ZlQ0U0tiYmk1dE5iTmF5dDhLcmFBM0EKLS0tIFJROU80RllaTDZDNWdzMFdNZ2ty
            U0lDWUEwRmNjYzJiSjN1S1RaMC9vd0kKOx5zBdbBIThgnXhvcCLoPrpDN7qUW6xZ
            //kYrbyTqbUJk5Ij070QadZI6jRuDYdlg6VVGTlkKDL0fhkbRZKlqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:18:51Z"
    mac: ENC[AES256_GCM,data:Zr+bWHyAwlkCdyXAT2efL6GdfE/MjX5ed8NJ5wKkjW/8N7woM3EQXWgMSI+1l5xCjgpkWPaP/4lwRmu3kfLaf+kzqXxI7S0uOkQvszRD7iPYrE7yQnEwJe5N/0L4R7FO0Bvv8wc5aUjK6cXZQO0cVNuYP0SDdfIYQJOZ/27yYqo=,iv:0KfhTiDvzAHA6cSiqCQI0HtyREA8rV0NWndsX3h74bA=,tag:x76H1qoBu+sRStHuBUZlvg==,type:str]
    version: 3.13.3
