apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: 'y'
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: 'y'
  ports:
  - name: http
    port: 3001
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: 'y'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: 'y'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/part-of: 'y'
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: fredrir-09
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: ghcr
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: api
        image: ghcr.io/fredrir/y-api@sha256:bb2ef1a0d37adf720551d97d2bc3c5ea693eb9ab9dae9a4fb49ace0508e95e3f
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - name: http
          containerPort: 3001
        lifecycle:
          preStop:
            sleep:
              seconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: '1'
            memory: 512Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: media
          mountPath: /var/www/html/uploads
        envFrom:
        - secretRef:
            name: application
        readinessProbe:
          httpGet: &id001
            path: /graphql?query=%7B__typename%7D
            port: http
            httpHeaders:
            - name: x-apollo-operation-name
              value: health
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet: *id001
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        imagePullPolicy: IfNotPresent
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 64Mi
      - name: media
        persistentVolumeClaim:
          claimName: media
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: 'y'
spec:
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: 'y'
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: 'y'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/part-of: 'y'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/part-of: 'y'
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: fredrir-09
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: ghcr
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: web
        image: ghcr.io/fredrir/y-web@sha256:52fa7dc00474a7b79b5d3b8d5ff937787ffa9bbe42d864159b2ca26a462564f1
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - name: http
          containerPort: 8080
        lifecycle:
          preStop:
            sleep:
              seconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: '1'
            memory: 256Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet: &id001
            path: /healthz
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet: *id001
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        imagePullPolicy: IfNotPresent
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 64Mi
      - name: config
        emptyDir:
          sizeLimit: 16Mi
      - name: data
        emptyDir:
          sizeLimit: 16Mi
