apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: "y"
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:xMiCjslfIocG2OigjcdivrNVeYs1eiqBEy53/VugOA8LhOM0Zb1aiCHHLzdePUb3fCAFceHdQmN6rv4c3Ri1HBH79+t0RfwGQaAebamgdyEmhXYJCZuiwfXTW1oikD44tlmrQy/cIfXnXJu2YDz2zDCwrjKg1xpr,iv:TaYyRLHYfwYs1K/VylC45EhpyBmFs+AtC9NUgrKxX2s=,tag:JcmNSZvGv+cfP9OobREmZw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Z4nRnPAtP5DMJ4FFLivnNdiFBtU5z0L1S1gs0mxpJC+GkS8g/BEhXAfK8LXVH/MbNwWhTaoxOcMhc+IjWtprXL9fKvwBt7+v7cMbYHsc1GFtmptfyco=,iv:+y0gIOOPjSPWRhFWtl0JnUSFQFizcLzGhjblh+Rjzk0=,tag:UL16OD3TdsrS+wVAoLcK0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYXhicWFHVGZEUVdzVDFX
            RVJEdDc0WmxMQXBheGRnb0NqbGFxS3RhY1VJClNxN2ZQNUt6N2ViQndueUxGaVM3
            MG1VL1E0YVo3cjRuMU5YaFlNaXY5ODQKLS0tIEtSL0hza0Nmdk9zVXpqbXhwSG1X
            MWd6Ny9XUzgrRzZDMXl1d1U0TkVZTzAKYJqHXQNQVU2OBtTb/coNt2qJ34cnZI32
            BCCLDXAoNVZ4dsAjIUFT3euFeyOMdBzsxShsRCTjeAZdAdFOlV5HWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NnpxNlN4QmIxcU9ESG1T
            b0F4ZGNkZUNaMmpBWk9JQXJ0RUxCTVpibEFFCkxlcVJ5bitwT3BBakJJZkV1bVZz
            allSZk5aeHo4R2lubVlUaDQrSlRyRnMKLS0tIHgyNE1QN0RHb1hUZEJ1TWs4WHFK
            VmpqWDFpNUNPSE42QU9DYWxxRXQyYTQK2JwWxn1Z3nQGVXjW062PwqvUWbfANOQ4
            o1Gyc1V97CEd7aVitE6/XHS9tWHcUZXVhw4R5dkxDv/s/04SnL55kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdHIrY2hiUmRNaGVVOFcy
            SVg1cU95aTVOTzdkT1lUeU55c1JzWVdRWHdnClVEbjc0RTJkSElLOXAyblJjR25h
            QUNjK2lMOHYxRDdtQ2lQVmhDU2NGNWMKLS0tIFNydGJJNUdKcG1CdjF1WVhnODNq
            bEhEdnNVSGZpbnpMcVpXSHlnYm9EMXMK+x8FdYmyHZya10UQLq/jbQZr68iFGdtv
            5Zm9tfH6NavG3DXccQUt3hzWy6174QewuDxGVGZdvwU2O0OEYeBcTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:UhDaFUjm7K1FIWRItxDTZuEEtZ3VrG70Z7+WOz04pd3gQYJphk7FZbpKYb81unK2M+JmIiRLI3x9RFCJmFSJjGunF6/7S3JuSQhVQ890ZGxUxApAN2v/uf6PIHS3iBMwTyYOpc2phvpA9Fzdhe1sSkTO+eSvZAc0BZknFRlGfgY=,iv:pBzugey0BALXRv/r8Isks+0kxrq3LgDGF5B5HAhkDaQ=,tag:0rEjqpoJH3SKD1pS0tzxkQ==,type:str]
    version: 3.13.3
