apiVersion: v1
kind: Secret
metadata:
    name: backup-primary-repository
    namespace: "y"
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:IzY4iF/nUK+uovchMPLbGscwK7ckDfqO1v+13NrCawYBtO7gdSif0K4yKoMvUs93MxPI1I7XGjjpSrVB91bggGHf61lviA==,iv:A6dwcayMRRiD3u3HFd/A4fEMnE9ASqDOLjpWkarEFfY=,tag:0t2cJUZlofZHxqyQAkMLaQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Gd4Pzj5vepAp/x7jzy2IBXzyS4bArhMp7fT6k0K+8/1uNm+SrPNamUvtSZw6tHHEO+63rhDsQh60/bB/+8YUIQ==,iv:V0aJuf3AT3VIA7XCKrfwbrMEuun3JVo1nPB4WS7JEFc=,tag:wcZAJZIZVKIWIGnbP69m+A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:b0/BbPK7VHMqO3QWnDja0+ivbhI=,iv:pwAT3ic+nYVSkF0qPI1RxGGuAptkZbisalHW74Idhtw=,tag:18eQEE78QtQ38LT6YOgFYg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tbDPnazRtaDhSyx+h2RUH/Flr4YsWmIUXqlKGqA7PPe9jtxLnWy1WNNhlX1ysIZFCEa0wn7Y148TyUTVBCtSgw==,iv:H+fdkluxbmFEY37Vu0NR841YtKvsalUqUFWQvNhXEXk=,tag:estdMgW+IkaFFPnSnvPYDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEt3U0Y2OU83TEtNM0xE
            eHNGR25uYTg5NldBTmRWdUlIQitQc1Zzdm1VClpTNmlLUTZJZWRhaFVoQVJ6STMz
            NWU0NVp0YlpXbi9MM3pES2JkREdOQVEKLS0tIDBmamlRSy90MXVEOEhWUHFrMStD
            MXFjajBZTGpxMkgreUVNQWd2Rlc2ZFEKK1AHBZCjm5rAilsoCTLayaYXnTrv5iBy
            7pQPJDBrseNe7Qmj5ecga3H2xH/KQwnOABI3qQvWW7y0yyI5thmR/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRTd0MnBEZHF3aU5Pa3Qv
            VXlmZGhFUC9pMTVSckhRZjFWV1dRNGlFSVVZClJTbGxzd0lzWjlqMnhKYnJrZmpp
            Z0VhbXdkMU1XY0M0eUNNVEYyTEFPcm8KLS0tIHVyaThMeEU3emVPajBtZ05QNkJj
            SzlwOERQb0lMaXhUMWoxNkZIeDdPazAKsMBwhw9SqrNrgvZ4zYfWCN0zSP5VVxbB
            C412Zdz4VZWHxbt/+tpEd402Q6jlDmxsdaj1Z+rY0EylDXPTxgPYyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YUw1R29oVVUvQzhNVUVF
            ZUxHMDdEYmd1WEVnOTFXMTV6cnRRZGhYNWxzCmlUUzU1TUJmUmtVU3dPQzFOTGNM
            ME4zN2ova2FyRzZ3OWszU2VLenlZbWMKLS0tIEg1eXArYTlxVlpQVmhyTng2SHJt
            U01sS05wcEZhSHAzWm1mY2VUKzU0WU0K3WUaf26EHQxboKnmfrXyXY2PteGGc8S6
            XR9IR5SDYE6N/4RDkOhQnMuZYfT6uJn1zYfmdCk94CLV0LrSbqkoJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:10:20Z"
    mac: ENC[AES256_GCM,data:WrRFNx8os+kA5Sz7k/mlI08vormLjJW467X6ybPFyjZAPZWZSkhKTFCT73bATo/B29X2ACuroXBEaxfxS2QQHPpMrEBDkIwlAcKE62LI6T2Ks9BiyH1ESSMji2XlIrvfTSrSiknDjiJqm98MffR9zXgn/ZiXESdXOT2ujcBaqGA=,iv:87Mm4ipcxm5hPc4238mJ6bBv9YKbs1TTLxKnYg4BLw8=,tag:hRteVEKukoWC0Bir8i3MEg==,type:str]
    version: 3.13.3
