apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: "y"
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:syAJG0UfwT/EI/qgqtwj3V/f2qgWLHkMTOM91cjgQHHQVXTlCNuN7RQLXd/3LZJp8KfRjgPDeg15zMAIrglQ,iv:TCWjDt2l9xFndYIv5lMxvXSuLl9diTYdU4fSoVWoYUg=,tag:20fmmkVVnCtkNS70Hq3leQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PFT5dNxkyuzKgIYOsJFHBO+XSpKokZnZVQFrA3DyH/xgcPyL1aIrpbPeD466GzUxMNs8PhEGTaXb2Kq8lRAnfg==,iv:XdMddZ1bOEd1MWc2dLGyeV3ZWQddOHh01/CNGLlAS44=,tag:uWtTjva/NWpTAgrbrfFHqg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B6poRN6pyDO312syPrsBiT2X3mo=,iv:Y0ZpRzG7w6B/w5gGmbrB4xVJaemiOyzMRL7FSfZ5y6Q=,tag:SPxw8vvVas3p04tJRoaXCQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cgU0fjuFSzmwfbZ9NlEYJIW4Brc8MHB4GGCuOY6O6Q8dE0iAxptejQ==,iv:G/kX50GOTQl8mKbuYckUW6CGUo9YJ/kx7HxRi6Vm7dc=,tag:XPzVOHo9870GAaA32XbKIw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:oTC8ZfwEnIJeUA==,iv:sgHMxKfvybfbi6yorSFNdxw6E6qS/7GDuyo7e1PHFh4=,tag:KjEN7jFnVIl+xSC1U8J1Ng==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:FJtabN2T2RiTexglZZ1dUarDiPhCVZ5wEYHUYYZdUxEs8O+csL8wgS2QcuVgNwnLRkWSZ23+7n+ZnLWm5lMj3w==,iv:7U20tywfUQ+bsHax+ggR+Ru+Ht1KxQmGFDiww/4kWFs=,tag:M1g5IbIxT6u8Tu2Q7nbNaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdjhEOUpVdnFwSzIvN0ps
            UTZYbEUzVENIaGNWKzNWZlpHZXpyRmlDS1NnClJKRm5EUlRRc2xFOWZQTllmQVN6
            WmxsTkV5RU9aTS9vcC9HSEpScVlta2MKLS0tIGY5UHBxbzdyNk12S252UXUzS1ky
            ZHJOb1NNVEY0Mkw1WlQvOGp6dDg4eFkKunNIk5GqygOwnQrEU6hvxHrQT0RoQKaY
            vFrxZBu2+mzxXsZbwDfJPYK57WlQ/3jLRrIE7PsgKCblUt2d9VPWow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrd3FDQWl1VXZ0em1WcXlr
            WmMzVE9GcTVBWUg3UC9vTEpmUG9JQ3JqZzFvCkwwR2lHRG0xZlArRWNrQ21ZelI5
            cVhPb3NTdkN1VGdGVGJmOHpRWFpRd1kKLS0tIDJDRDQ2T3hUbnRxcFJuWS9RaGZO
            VW1MUzAwSnIyVWFpaFk5VWJaRXY1ajAKFtvir2yovM1LPgiPcWr1XnSq53rgMrKk
            6RB5UXfKcthjOB7ObjwjaVaOVNpxeE6pVg8V7yiWtHM7ku0HGcUKXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0JJMEdFbWNub1pYb2U5
            Y05Bc1NrRHQ1UHVxWHFsenZTcG9XRWsrWHdBCnk5SHVKbFFiQXczOWwvOEUwcGph
            SUF2dEJIU0VEWUx1VW01cEhnYTFuMGMKLS0tIGI3dmdNaGI3dW9pNklEaE8wM2Y5
            TFVNNldGYVQvancydk03UjM3a2l2cWsK/B5ab0AsbewRSoGrpykT5kagK/yekVPD
            ARvltYuoxIocHjTeQaQynsp9r1grL7viUIJwQW0F1bbuHI+r11b8ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:14:04Z"
    mac: ENC[AES256_GCM,data:HPfLdvCLslSCyeOVAULp1keiy9g8Dn7S+7s9bvRkHcOzDTWhMTTBd+OvJs9u5BQ6VUCZPS3Cm7b9T0o+1Ct0JJ9qf0sDC027xZg9llyZXoUQnWjqUZLFDiSx0qGh1pePi0C4X/JJTXDOb1t+LYQhqK4K3P5PkbK8PAPDvaUmhHg=,iv:P9FMKqreCwxqYriEqHDVkK4zCTAcrdk+fGrNwOOtdDs=,tag:MS/vGqhZ+n8CRQWKMg/nNA==,type:str]
    version: 3.13.3
