apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: "y"
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2LY6Ly6Qf71IyQx4F4yxwkhJBsysD5+f2ZdEOS7dYB5T7/OFwQkwO9oWEOca31UQZqS8PwbYVdhjnTCQKkSAu6vve5uou9E=,iv:2euLhVhInSWZ4OFBzZ+bEpp8lA4EMpJBvPxlCwVR8x0=,tag:9i3pljy5RvsaoJU3IKH67g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:aVw3G/c8XCFEH9BPl/0Fkah2olq1bVpy2DRrpjE94Xh54zDUZhaaMez0LOi/ITPSXdn1Fw+NtKL+Put6igE55Q==,iv:lrcwvp8tOiBxG2N6aWrUKV61WKENKml5+DzC5w7jP2Y=,tag:xpdnhL2uwX3EwKyrSDJneA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:J9nAONVxV88L75R9SvaChDyT4QE=,iv:yVtfPiOmIyECEr/Cep1dkzGIWaP+Ivn1j6t/lEK9gV8=,tag:yK8MoCpqPHdo2vsXrsJo9w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fPOkvjpyNp21W3+XJyb70NZw01bGGS9A11oqJRrOS3kG1p5yr9zk+w==,iv:wnhNwBp2TgcDIBT6P2YKIjnoaMFnVS9WxKF0I8y+6kk=,tag:Fd/RJWtLLlvjCZNy0dmzww==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:UDvbYo1LIYgcYA==,iv:N2tqG8kH5oe7l4T98Bci94fiXqNz0bmGZE7/JDRyj0M=,tag:dP5R5rn5CFpip6VnqcUrSQ==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:+4EAJu1d9Gy+A3A3jkS1IHGXSBv1s31Lt3rUO2GtFAwAfrFi3dT5fejWNQ==,iv:sOKi9n7iiieUb0s8kD4I80HiafVYVI1dyqLKlfYGOPo=,tag:Lp5ti1qIApQwGuMfywiuHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMVp6SmRrbElsRVNVNmxi
            aDh3K2NJTWErNkxMTi9IZENMQXpUR2tKMWtvCnJKMnc2REtsMDVHbkcxVUc3YjQ3
            VHNqbHE4OVo0OC9MRVF5Z24vekdVWUEKLS0tICtBYVpqRU1pWHFIOHlqRTJCZWVw
            ZkJIdytoRHA1UTFlR0lKVDMzdkd5TEEK1+TeYQXIXK1Mz4jYjbxIcudOU4yD8RMm
            oXOLcZwzA5hcOc7u/S2ewegG+rYQw7IeOAsDVsymz+cN1WiP/pduWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON2daUmo4R0ZvVEZiMVNC
            SjRYbEpBZTBENjcxVWZyWWZ1bngvc3Z1K3pFCnhua0lTdzVmaDlQZjhFVlR0SFBj
            ZktXcFdkYjYzQklQL3dlK081akY4RU0KLS0tIHZFS3cyUXFQUGdBTkZHL244WWlH
            bDFQRzdlMG94MVQ3MWhyNVhUWDZvOVUKMLydcgKBCXKSEMGRVSW8xzRrp+Hq2YAX
            Y7vAaFxPmgNCCGiZe+BuFsEp32FW6I1PBu5WgBCKY7SyEupWJM8sSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMDBlMGpYVjhYVm1XK0xI
            N1RwV1ZHQ1lKM3oyOXgyOGRxSU1HTDQyMjNrCkxZSm9MM05EZklna3RYN2U0WHh5
            cG8wMlNMalN6R0hoOFUwWVFUMi9Fd0EKLS0tIDNGc1lCcUd6OExyd1NqYjVpYTBC
            ejB6NGU3YVRGalBwUENzNUJ3L2JzV1kKHynTa1NoA5q0KW+UBaMUopGS2d0CeXfz
            5G7UYQfvjPNsTB6KxM5NqYeZ6oOwjcdUjpvpjaCqlRWvomk4LM2geA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:10:37Z"
    mac: ENC[AES256_GCM,data:Mbil0OyGSUeWMXK3YiaVs53Q3NBFrKTkKz9EsKf1rRht6ocXrWAqmEEuddHxZJ1xlQUkDxSDWMyWxbOkD2/mECj7fGdj9e39qAbCdEv6RMwQHBV4NFcU+aboN0ZWnjddTfRPiyrIl40mQHWc9EmXXZU/0WXMjCDFAsgcnUVtnPQ=,iv:2SAiVPrgbmcVFO/XtY95kgbkL3c3NmI5hYDAqcKfYHg=,tag:uKW0ZcLUFoISp9+ftRvX3Q==,type:str]
    version: 3.13.3
