apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: "y"
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gpAJtYr6UXEOwD+ILUYCZwCZSsqb1UIRKF4Hu7fDoycahbXuHU0iicT2RfN8GkJrmXm7oOA04dFuOs+lyNnMJiC5r3NZuls=,iv:2euLhVhInSWZ4OFBzZ+bEpp8lA4EMpJBvPxlCwVR8x0=,tag:Mq1a2WFOoqSfjGQvZ9Rh8A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/JEecsy3Jqvkr+UGvHbuaPhbznTVKs3dv/E6DXS+kqzCw9WA0ASDscH6D3ayWdtUtrefw0MOx16+pTpiIxu33g==,iv:lrcwvp8tOiBxG2N6aWrUKV61WKENKml5+DzC5w7jP2Y=,tag:/WKmJjeFzFGcjszei0v+9Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UVN8QeJUen1bTyTAqdUYGKAWU6Y=,iv:yVtfPiOmIyECEr/Cep1dkzGIWaP+Ivn1j6t/lEK9gV8=,tag:7RlhyGS29eK0GsIO4ekPuw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DqM/W/4XjhaWra6jrBou4KvtwUFIo3c4lbaS1nw0nn3WhnGZWlp3ag==,iv:wnhNwBp2TgcDIBT6P2YKIjnoaMFnVS9WxKF0I8y+6kk=,tag:rz18Fi+ibNVBbaAMoLLr1Q==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:7RLj+upXmA1TeQ==,iv:N2tqG8kH5oe7l4T98Bci94fiXqNz0bmGZE7/JDRyj0M=,tag:7PuxJkGJJl1Dg8pnyIBk+Q==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:DMJ+Pyl03y4v0RX0EoydTS0PHl2OEPjlk9QriyHHtO43sbTPEcaySmHCxA==,iv:sOKi9n7iiieUb0s8kD4I80HiafVYVI1dyqLKlfYGOPo=,tag:CniVpJMyS4/iPxolBIUUlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OTJPbHkweDVjbGNJZEE5
            Sm9qMDY0cGNaQ3pFL3I3K05mNHFFZ0Fsb2dvCm5WZjRycUlOS28rNnI0amw0Y2o1
            UFF2anRMWlhFNDFJWFJVbit3WnpZTkUKLS0tIGFmOGxOT0sva3lneE5WdnVwenRP
            enExV0dDQUd3a01HdXJjS1Z1TE1uV28KMNlQFeaVe+gig3S6zHpy/Rs1NikhrCex
            OIg7fPchBu72zUIkIJnPgLgiAhGw8QFQ9sRyJ/V8am13qXDN33slkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM2phMEZqRFNHbTNyUzZy
            WEN1bmlrNHlWYzVuTUtSS3ZBMVF6LzFRUGpNCnZPWGxURCt5WmkwOXRHb0hmM1Rj
            WUFrc2VZN3VjU3dsOXA3TW9XMzJQOVkKLS0tIGhkZnd5L2paNjhxTGxqMnYvaHk0
            eDRsK2tEUHdqNisvVUpxK1hIZDFnbEUKxsRNdWwkWMhk/s0vLy/DwHkIasG0fK/I
            1qtGlGE85eVJyvaF5iNnPsPYerzaMCtJtk7UJv/DQl/jGctOQuVo1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRjdBUzAxdzh0WVJwRnN3
            cDRXbEpiNWJIY1hVUGRrQWJZSk1oaE1GVlQ4CkZWZFZ6S1k3NG5YYS9YdjBQVzhp
            aWRoYkw0OFhGR09VK0UyQ3lnT3BOVUUKLS0tIG5CRlQ4bE5HNnZrWFB3UVdiaUNj
            em5UZ2dLQ1F3Z1Y1aG4zY1RqalMveUkKIm7kry+hPhIOLMPZ1uS8lSXK4AnF7O74
            +HCiT5al0SgFk33M8eoDRwW2MFwCt1s4tTJJuTUtM6RECZ3F55HKow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:/VaoPMKd8PL7pAWTf46dTCJ6s/C1D7rZIbqO3FuUgH1lXVltJqYMKEnhOmjgqvYDAROTTmwantVIFLGm9uUkKLb5AgEltIuAw90lDk66LkhK7tZQw5WGEPqzbZNb2odHKUhj7npzxf7VmMZvOgt6Dl9Eps9g1J60eMc8KtZOaTY=,iv:9k1v8La8ElwqgMpDwW+HaW6N1FWQF8oCoEd5s2ZnYSw=,tag:P6BEM/S5XIkkP9pYFMivIw==,type:str]
    version: 3.13.3
