apiVersion: v1
kind: Secret
metadata:
    name: backup-primary-repository
    namespace: "y"
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XhtgA7ThF3bRuT9c/kDIow23B9cSdwwBya+OjFoaQbkwrvw9T/HFC3WiFllkXAmJwXoKvacfwDWDsIHLNl9+VmtPlCvzZw==,iv:YaGdGxjRhr7n2b4S0H+8GUQDD0GJZRZfLh/C2Md+Xs0=,tag:1k9Oxz80+2zDlg1ODq0mOg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:QIa7yRdYeig6NmoV3g4Wa0e1fLiMEVSh9EUbVEF+1F3YI/cW4A1yVQuOffZLrnirQ8hNR6lcvIW80c04aYxIsA==,iv:Og7CBryhPHQPk/1lSYvulN6pWc4aLHBoNx6bbLaA2X0=,tag:wpexyK0pTAqy6AK8nv+79w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vlg/RHGfRQBi91K8HQWWy1rHu8U=,iv:WDlaTofmuboTgVT0M1P9kPZycj1tOHv2BsbFhMTyMh0=,tag:Lqvn4czQ/SrTSfjqv9Z/rw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R3TnN4npUVhlAvGWc8TnbpjpRpK4186beH6pjuKf/YwuOJz+pVqQGttipMMJAQPN8IPViW4tW/y0SbiiWkFPOA==,iv:QYeiMdqjGhI7VoluO4cg76vDDp1nYMTs8tw0NVskPD8=,tag:QCHtny3Axn82UVic/opa4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aWlybklwQUwzMjN3R25B
            bzcrRHhlYlA2U0c3WllacXBQZ3U0bzl5WTJZClRZWUhnYzhsWGhJaFhZeG1mUmNL
            dlBnOXlMWTZXRnhrVjQ3a2xOd2Q5YVEKLS0tIDRZR3o2WVFsQ0NIeklzajkxS2ZS
            ZHEvbDdTbVhBdTZ4aUN2ZU1nNG1HYjgKeomffLnMakw5ok5OeClBMcnG5l4jSA70
            lPTjhgnPmwgnCHObqVALysrZP7bG5WM/uJqOPww76nVtJPgXuwbc+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaUo4WVBneS9OS1FSaGNq
            NytPOUxXcWJ4SVdzTi9sS3oxUWVCWTBQT1hZCjFSYjlvRnYwcldxbUd3RkxnTmk0
            L0ZJVXJYRGNldFVYcU41clQ2blRWVjgKLS0tIFNwMHcyV0VKMlhXcERTSWVSVDM5
            aTVVQ2Q4bEJYSE02NUJ5bVJ1eHZvZHcK4Dr7jHfbP92tT2keb8bW/kKbYbKvpxeo
            oYZF7DiO/K5iMK/LPZ1TsEyGKGe8fLJN3QbLqjvqqCOnwdNCqVyHYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodWRGcXhtRGtVSXc2TzBF
            NWJ2U0dFWHh3TzJxWmZseExoclVuTE9neUM4CjJaeHhmSngzNnJhVHV3M2pIYTZI
            TTFMaWRsVmdPQUE5RDdoTjFlaUZLM3MKLS0tIHF6SjJqallqUDIrUWRXZ3E4c1pH
            VW4zNldUVFpZSzNpNndrSlVKMWw3WDAK3qNAoNx/sZ5qG7Z9IGf8HjubN5rn6aBA
            zATDlYNCdqBNNmcFlLvlVcmvufqgKcWdoAWyd+E/3/3V1089/FSdcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T01:48:23Z"
    mac: ENC[AES256_GCM,data:Fhe/KQEVhJ7amXjZ0CbNOQcQFNU5CjMobXXtye6Of3gbYxJVIkx0vtiMTnmTTmhDsvSQZ+wrcadJom3mW0uK1AVQWje9T2dhmJYhcOX0q+gU6aAu++2RsMOq7rROZnNlQUBfTL14REqgMoSc9IrVR2q5uys41wuXdfcJOMEm4Ng=,iv:63m04vcvSp0LwIsYkmsZA5Nkw5unhCLVmCqtBa9iFKo=,tag:jBH4fuoyM2x2Z3cB6NG5aw==,type:str]
    version: 3.13.3
