apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: "y"
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:ME4U3ob/,iv:l3KfwQBvwWJAoB6JwNpZdxBBLbR/io2NB/GFs7OP5E0=,tag:O/Odvn0yi77hlI0Ua+k7wQ==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:6J+NIyS4kPYAUjHvbh24GcfuQdRC8gD1fCUyLS1N1Vq5grssOQNzsaIWjC75fz3NhCHtYDtnnQrQ59wuIB4hcg==,iv:+UNzircrchOe4nTsxHYbEWhu04Qnjo/8vtNwJ7UHEws=,tag:ZLC5Ar5Rw2FbuX9hl5Pjng==,type:str]
    MONGO_APP_USERNAME: ENC[AES256_GCM,data:Z85EoA==,iv:6k04oc/L8abWhx3M9uNaeAv+TRIYN/o2spiRJtl5MKY=,tag:jBhL6bwuzgGvmcFqitLr7Q==,type:str]
    MONGO_APP_PASSWORD: ENC[AES256_GCM,data:gGILHBC5Y69zTu3xPQSgNJdsAIge4V4cZol2cFmODc6CUOrUpJwgZt8Zmo1vAIHCeo6mKVaNXwvWAm48AmpbWQ==,iv:JMW+53EJJqU9X5+H11ZjYQ9cfkKfL6ykqsjQpyNFM2s=,tag:ZJqF5gMz+WmJ67xnoCtcnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVllmZC9nNUtiWFZod0hr
            Z2xOcEkwMHJCODhUN09IS25PVjlXRWdORFRzCjF6eU1rZ1BGc2NhanJmUU5sWU5Q
            NzcvRUNZN2FCc1dBejZza1JnQTdwZGsKLS0tIGNKUHc1bHNqcGpvaHNmRk9Zek1i
            UzNUeTJxYi9uVUQzVlhncWp0VVpPbncKAq9VPYPh7uwOIll1boZGEsQLAnWlYEn7
            U4suAWKHsL04jJv6jtcsCgETnNIW1TOdgeZxk4D1KB2/+D4xftts9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnJpMTdRbnNrd2RwTXRN
            MDlpLzRHNEc3MHE3WEIvRWJYVC9qY3BZZkE0CmJ1TXA5Z3VxQVU5dDQ4MExUeHVK
            dWl4dkVhSmhRUFFkSFhkUTlTL2ErMTAKLS0tIHE0cjdlbmVTUlY1MXg2ZkR0WkxF
            L3BjTVMyMWNWcWV4STNQOUVRbC9MOFUKCrmb4YryPtgH/LXGthqP5lxBRFx53H2R
            rwwTeOclFT8pvvkmlDPztnQOp6J/PaLSE/0U4EVoJIW49EISb2+Gaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd2dlTVFzVHpnZFYvOVI5
            RU1xQXJwMVA5VmhkNXRGU2J3cWNteHQ0VVZZCm56U0ZVbW9oZ1FQTGRuSkxwQjRS
            bFYvRjNGdUpzYUFoVEQ4ODdtQnV3RFUKLS0tIDE1dXZNK3pza00xUDJheWJUUGFy
            b1ZZcjR4RUgxOXk5WWY1NDdEc2JHejQKuoeLoi9KdUb0p3fGW0m93PE7/mcm7wls
            tZGqq5qGgyJnsCZ1H9JMdKJugJVVTVN0951D3EIYe3tt8OSN4tqDzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:u+awYQRMYbY5SMaqsBWTpJ1pV8N/KSolKlfLJixc6JpIvCFjLErkw4nK3WtGTIPGNAZVTUf/UUrjA3Iq8yxhszU28Iw9XqUsiwy6Yiyj1eNHQ6T4AbVk17pRJUF9n7IB3M5+89E1a+YESOIWsRu0VNLthd76+O7zbzoBd17wxos=,iv:FbM7ez2QrHnEKxkncSl0lHKTVvbWXw4j0rOSoeJKSyQ=,tag:bXIIBR/VHSEmGTotgBpjxg==,type:str]
    version: 3.13.3
