apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: "y"
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:Z3NGcCAv,iv:l3KfwQBvwWJAoB6JwNpZdxBBLbR/io2NB/GFs7OP5E0=,tag:5+BbAZ5a6AZo3/nVDvqitA==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:gdbQMzqfGsEssduFurKxUy77DUz67eRgr9IvTtpMp0nm2QA16unzlMjRVT3ac7sL10/zajsQt/E44dASyWHHog==,iv:+UNzircrchOe4nTsxHYbEWhu04Qnjo/8vtNwJ7UHEws=,tag:GDv3Ah+A58rrRraeHeBttQ==,type:str]
    MONGO_APP_USERNAME: ENC[AES256_GCM,data:2SmiWQ==,iv:6k04oc/L8abWhx3M9uNaeAv+TRIYN/o2spiRJtl5MKY=,tag:UoDeC11299UwoRPZi0KyaA==,type:str]
    MONGO_APP_PASSWORD: ENC[AES256_GCM,data:o/1WKR3fWcHjbkyDwIuDKdQqnVVIQY7X3nqWMsCaLfiiyktAqnPNK+Y3WOE2/FzjQncV70RRJJFL0TmWFER7PQ==,iv:JMW+53EJJqU9X5+H11ZjYQ9cfkKfL6ykqsjQpyNFM2s=,tag:Nn6vCaO8zHJYpehswP2qGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbldrTEQxK0Y3bnJiTGVE
            S2Nuc2E0RS9seEZOdXV2RlBQNFV3SFZlWmxrCkhyc1JOajlKOTJMb0M2T0hWVk1L
            U0p3aE1rUGc4UVA0VzMvaGZWN3EvTkEKLS0tIFVmMHVPQ3FDOW1wNURucmE2Ty9X
            b1lmN1AraDZyOUU1dmZkeTNLc0dINkEKLMzkKmbJE2ZRWVRCbyZPBZQQ9zr0J/ig
            RsAjweSOQfq/11KqqETUR0jIn3MbS8vsJViaau1avWsjceBMeSPMIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTkNERFFIQmtiZUFlNGRE
            ZWlzMTZDc1VIakNnOC9hWXVFY083MHpMK1N3ClNxT3RCQytubVVpdE56VjZFY0I5
            WVhDZFBpZDZadkhPb0pNVnFqRnBRNUEKLS0tIFh1QXlLbTZGME1yWC9IanhMSlVF
            MG1KQnpDcHpjbEFBS3dqeEJrVy82eDAKfX/t6tote53OFwUq0gE10OlqL/qW1drq
            GCeLYyj/bzydZgTD2Zx+pEbK0pKuShvXD7vpdCseb0+oXBm7riBjsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UURkRFdEOStlU211Vmcw
            dVdKOE1pbjRsOFYxRE5yaXhRek5VUzdoTkZJCldQeDBCWjFTa09OUSsrd1pXbGRR
            dEVudFZQdmRHVVNoclFDanV2WEQ5aFUKLS0tIFA1cjAyQ3VZNmtOelJac0RDcGF2
            QWNRMEhPbGVhZFdHQmQyaFZNTE42YlkKkoafTxT2p54rMIWl4voegJq/8oitFjDV
            PQy+ijoPrcWvp6d2MSGIYPH1dXkr1jnyFpK+F9QrsNkfJy6iI2TXFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:18:51Z"
    mac: ENC[AES256_GCM,data:gubDxZDeKJ8HMBMG/QOol2+ryD+Go8kwakMTTIj49e8et85BPa824A2a6t7ZCVmbgfkpTH+bdV+Zc9jhVI0vmtuZJKqHAnbaTBL6WMocVC0FOpHNc+fdoE88LM2vHNCyjBsx1AuuzNNn5tzBboOi665APqDBKPfqjAAOpZYa5FA=,iv:/0AA1D6sM3LT55WDi1yiGoRSQzeUajdEm9RvC607DlA=,tag:yU+3dFs6hOvYOiB3bHCHrg==,type:str]
    version: 3.13.3
