apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: "y"
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rjYK0Gkl0/R0RMl+eLg71zCR+t0OTfsHW4mKpumkhF7zYoZsIO2F/DBPzy+NJThfLK+fSZk55ox1ZjY/+JqqyLRE3CJx/0v8N/80PCJ8duaAuSwpVotwECeJlaTrhoQIrBl5vjM96CkFfUlhNKDvYp3PGu9J6dc1IhnhigFvDcBdcfiI,iv:3KiF9RdxjWg0nXjDUPxXSpHk9sMGwO8NYDRB80oavZM=,tag:eMgl0OYN3MkH2VsrYOb9Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERlBEU0dESDN5cm5McDhT
            OFQzejNZSmdMUFhxa2RpTFZpR1hIaHR5MkFvClBGaS8xSW5WYndhaGZYNVdUR2c2
            Uzh2VFQvblJycmlrNG42d3lCNEFIMVUKLS0tIEdDRXl4QmFHbXpCTUNHZnRUT1Nw
            bWUyNEk1WExOdmhUaVA2S0oxN2MwaTQKoekuCcLaHNTXNMCEOMOp4aSrIbD9DPDo
            U11e2PQ8xQiXIC/fXV2hIXJ3pOSE8jA6eqI8/whLvgWrJaWm738AjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDlhaEhlS3E3eWJGQVBY
            Y2c2Slo5K2NBUGZsRjdBelM4YllTeE4rK1JrCnIycHQ0aUNSUVZhbDJTY1VreEhh
            NzVmelBXM29OTldySEdKL0RmcnZrcGcKLS0tIEVNRW1nMDd4UVBEZVpIV0hROWdn
            RU11bHYvNStYcEhTQmFnSXR1RkE2S1kKQuLtmmbcnZqau+0eUlrcJ3jmF9VsTDxK
            NHfZipLD+HiFyAWO4sY1X2H2u6pp5X5M+oGwB479YGe1MDP2Ul0MqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1VBVFlZRnNDT3RneS9C
            UDZsTVJhTFE5a3gyTVNwWTJzazRRSTFJdHpNCk5ndnhiaFd4L21lSmEybkpGc3NT
            djl3UWFDMFg3WEYwV0kxMEprd2FQSEEKLS0tIE95dS9nZ1VzV1ZTd29sTDBXd3ll
            Ny9kQy9vMnBaanBIbkFqTGlKWG5XSWcKLnJyxGVcFMuV2pNBGVSkV8NaaNSOUcCz
            OOdVtIxk8k1xK9LY4cwlBLYRK2o5DGKfECqgnGJ7J9koirNQuzC6Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:8IewAE88hLgp37OIGqBqLnr18XBa4N8I90zgcEwxIdts2G4yFrmZ+0atJvm4RGWx6IKxPy/NJxBSQ9AeY/kU/CnwC4TKaFx6xYXVwWQhkpGAszuP6ldynAGeJeTTrtgdK4JImReT5CGofyVj7JMm5Rbw6mmJRcfEkefEOopROZE=,iv:oK7ADwUSar9/lpsW05TVyGzofV4O2TdbhHPIMxNhzLM=,tag:/YDtpKcYH1wb1ycV3L+a2A==,type:str]
    version: 3.13.3
