apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: "y"
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PupuGgfpjQ4+WGNYEHsNEDxoaqJopdMCNeCoP+vRZsbCR7YEWHROP+xf8k1H+lNm6bgt/RHRWHSgoV7R86ZUSYXEIzE1bctvnjyuGCZb9OO5HgnbxU8D+EbglaMV5yDiaIGyEj0BqRLRquO7fYnlRHeGkUtQiPCAdhfDasOURUhVjtlU,iv:3KiF9RdxjWg0nXjDUPxXSpHk9sMGwO8NYDRB80oavZM=,tag:e5zANxVmq8L2m6FynDlCvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb1ZDaE9VdUk1Q3dtaVBj
            UnRyNmJOYlRaeW1GVXh6dnplRHhIRkZWVUJZCmZZY2lERGRjZzdBc3dnY2g4eDRh
            QXVTTXIrNThzTUNsZHdCeEJQU2dGNFkKLS0tIElaS1psajJRcjV5K29tbzBaL3NL
            MzRReW1YMlh1TzJJMGdoeHZZUDZqSzAKADl5QvbK8XQ+KnIWOyO4V2DS4gFqlcjr
            KX/HfVlrZ/bL6h+2ay/32HtdwlF0i5ffq6K/OMgK4IgrxJ5TujnBnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbTlSWGxSUzB3QVFBbnQx
            bG9iQmg1Y3lycDBxUXlweG1Zand2RkxMWDFrCkJvZ0taRXZoSUQ0R205akYyWjlt
            Q2lHOUFNYjhxSzl2SEhxaDZGTlZUMjQKLS0tIGNHN1JDWENQZ3NobUpCWjF2RTlw
            SUhGRXNvY2g4ZG1YRllJeGpsRTdvK3cKD0+F4zCPk95gwe7ZMknV7euVtpvAMJIp
            NHNQaJ3U8lNXGe6x+85VuBX1669gFeC2+iirJ4GoHX7EfTxlOBBCiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU0RnczB1YldFMmZxdS9U
            bGVxYzVNRVdTZXl4YU5HMDhSVC9wdFo3bEVJClhaRHlrbnNXWWg3T2g0Q3N2ak4z
            ZlRJY2ljakFJUSttei9xTGJqZ3lMbkEKLS0tIGFIbFBnQWZKVWlZdm1HTW81T0RX
            RDZKOEtLQmlEMnhZeWROT0RobncvNTgKuSjLOJg40wT5YaR279tG87b1XBKLpneX
            heRnMJ2eZ68XqmvljCQeFwhXy1WN49DXPcHppG+lvcRRNBli+UJcqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:18:51Z"
    mac: ENC[AES256_GCM,data:Kbfosb3hhXFoxf3S1E0CNyJd+fv3q3fxPC94xJKevc5ntpoDEvwWo4bprHYbGdGTPz85LMezbB3NP7bTLeIMcX/JWIior2Sqf3+sPrcznsiCUftgd2VZBm1WxBEbkqAOing72XrAAxtextA8Xy5nL3IsdeSdzFyosTEC/544YzE=,iv:U7uCjpo6rLP6ve8Mag/Izx71cG9QtJzHYHTrPgG/W5A=,tag:qjMW+Qk77VIS9RnS4EFiFQ==,type:str]
    version: 3.13.3
