apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "y"
resources:
- namespace.yaml
- storage.yaml
- database.yaml
- application.yaml
- network.yaml
- database.secret.sops.yaml
- application.secret.sops.yaml
- ghcr.secret.sops.yaml
- tunnel.yaml
- tunnel.secret.sops.yaml
- backup.yaml
- backup.secret.sops.yaml
components:
- ../../components/backup-job
images:
- digest: sha256:020a189dbe15435757ece00639bf374e152d21e69f814f3dcb30afd2ff2c6a2e
  name: ghcr.io/fredrir/y-api
  newName: ghcr.io/fredrir/y-api
- digest: sha256:594d0c080edd24e3f295b8bc38c4db429fa2b4a2523eae56fb5c7f77c3a5fdf5
  name: ghcr.io/fredrir/y-web
  newName: ghcr.io/fredrir/y-web
