apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "y"
resources:
    - namespace.yaml
    - storage.yaml
    - database.yaml
    - application.yaml
    - network.yaml
    - database.secret.sops.yaml
    - application.secret.sops.yaml
    - ghcr.secret.sops.yaml
    - tunnel.yaml
    - tunnel.secret.sops.yaml
    - backup.yaml
    - backup.secret.sops.yaml
    - backup-primary.secret.sops.yaml
components:
    - ../../components/backup-job
    - ../../components/backup-primary
    - ../../components/netpol-gate/egress
images:
    - digest: sha256:397f91a650f193c89b21a47d84403fb0f6e059583f8a7602d26e1dcc42706402
      name: ghcr.io/fredrir/y-api
      newName: ghcr.io/fredrir/y-api
    - digest: sha256:b9d15aec4565237f2d341c447c52d3ec1525483ada2ea499d04ab45fca2e302f
      name: ghcr.io/fredrir/y-web
      newName: ghcr.io/fredrir/y-web
