apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "y"
resources:
- namespace.yaml
- storage.yaml
- database.yaml
- application.yaml
- network.yaml
- database.secret.sops.yaml
- application.secret.sops.yaml
- ghcr.secret.sops.yaml
- tunnel.yaml
- tunnel.secret.sops.yaml
- backup.yaml
- backup.secret.sops.yaml
components:
- ../../components/backup-job
images:
- digest: sha256:7d4f58b2e4ac561e932835f01c35a614cee87d1c59db2322b9a146e4f8e482f9
  name: ghcr.io/fredrir/y-web
  newName: ghcr.io/fredrir/y-web
