apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: 'y'
spec:
  storageClassName: local-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
