apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: "y"
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:veuAiJ2FCnwe2+3CUxtTuFLCc02lyX9RwEoKzQLBnX7cGX2zcp7iQl3n5Uw36oWdPmIrIN9wylhG01uEDYzsipRSn8Wj1hgAhUhvZ5sfo71E96iDoLl/DDt7ttNW3MEX0w1sEIjNMjx9UjXa99RFWKdgGxhNkSidhgWdRD29YQ+JqZHAeHr/8DCPp43EqEGIvdQ5zCnuhd4yCIyxdntyQ1ui2bwQRlZ76u3et1jV3ImoXjTUOs4AcC3k/gS+rV6kZp0BOJ8piNM0F+CMfTpW43st36SeRE3GbuRC0K8jtES4Yjtvp4mPwCMPf4Ctqmt6,iv:m8obJIsqN37spbByMtWA2OcH4ya5SugLISlkZdkUUPY=,tag:oxP2rMI0ltxC4xfkvVAeow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNm55aEFMYXUvZy9VNHUx
            eS9FMStnRkdMVHNHSWdLNTBYMGdZUC9vdEhRClp6ekVERjhHNXBHYVppb3NzNEZ6
            cWRpQU5sTy9acGVLd2VMcjFWRlMwZk0KLS0tIEIvREFrS2lqLzBYU3J0ZzBPM2Jq
            eHo3djdWclZhT1dVTCtZQ3U4T3VJU2MKi7FAtLNRtfm4mAiXcelGf/iZ1u3FDB30
            a4OTR/4sK2uPWRscOYyND9GHyCFhhyLd8QvNoYM/MSl28LIaNchlnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweE5LdU9PdEllMTQzUWxq
            Q1pUWXNqS0I2WjFFQXhSSmVKSjlqcFJhd2x3CjdFTGw3Z1FQbFRGaFI4U0tyR0ZK
            Yk5vZkxWci9EdlhBR0Z5bjc2TTBBcUUKLS0tIElYdmR6VDFHeHh6MzdMOXZYMHla
            VlQxQkZFazN6M1NDVFRISis0QjNnV3cKw5TqQvoHzM4K9JckXCfNcAD0TEoS562E
            oQUvJhgIFnjfYImqE9Ztp1PgxESe1CdSWPJOsqJhMgydHBlETw2cJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmelhhTjJaczJlNlpsOFhm
            dDd0b0krWmg3bEo3a3ltUHZ0ZlF6REIyZ0djCldCQUNQcWRtMjh0M1lWN29Nb3o1
            Mzg4UlZUQTNCZ2dvUzRXQjdzdjFuU3MKLS0tIHBqOHpLc2laV2dQdzVUY0xHdXBX
            eDlGaXlLMlZxbXRsaEd3d0xNV0owNjQKCnjmmgeVpWc/5svMGthFIFzdS1DQyI5C
            ZOvmKEkQ4DqNd3KO7cMh5Uzz7MR7nzzbobEsEeTN1pMEH8Ge6WjyMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:51:30Z"
    mac: ENC[AES256_GCM,data:ObK9Be7fyPsuOgvKhNDtKVY2m9Qs52dqWlS+ffysi06RSgzWuCo3A6BKXGds0aivGK9XWwwJt4Eihb8tTqGmF7GXdoDC2wMwClvz36UenLuKA1CQwqrrwK70IixiSHeEqv2aJIr8TKhgyeHXQlxTeuI+a9dJAuG//2hu+LyZ5TA=,iv:aT3wdJSlSBCluUc6nVDMQWyFWy7fpWlYvZajx02iZwk=,tag:xIUkarSMDr5SzDj9Vgqv/g==,type:str]
    version: 3.13.3
