apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: "y"
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:m7h5uMSo5T/7n45zhsd8BhWK3san4blE/YGI4zAnexpbNUvsaSyN2nkKn4wpzKuOcDIV4aj/bpGpOg7MgRUbP/rH22n4gveltm3IaajcTSdER8IhxpgUd5ZSDpPIIcT1LbFuN+d+qYXeM+ocVlmTa8bApGLAYEqEgcGqmiIhbbXdtP+9ZjOuNgJeXi47eVpwwdckb45tqiVIThccCqeNQD2sAmM8G7H+Ybykb4A8+D3Oy5M0QanAFvwiC4lBP9/D2/IeTttMriJFZdqE56AphmlyzgWJ34LUw5+ObK8JBMAwJedHI6bIZK1P8w078G2f,iv:m8obJIsqN37spbByMtWA2OcH4ya5SugLISlkZdkUUPY=,tag:mHUI6Ajb4ToQsKdjBmup4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q2g0YlZCeC8zb1IwdWpM
            YUcrK0lxMlBocmZOVmg1elFIeStrRk9xaTE0CnlJZlZiVEE0N0o3S0lMVXZaR3dK
            eVF6Nm1kbHdZWlFUazZyTUlyNVhzKzAKLS0tIEZtUllqNVlCai9xR2JNSVB3UVV3
            cnlTWkNtNGRvZ0ZOU1NuTjBLVlgrb00KeHMl/h/wZ3s85KLR9/sZWwrbP93EjW81
            2jpl3oDLHzTZMLB2FNxvK/nlPpM3nMkcoPoDSpX3D7EmGv7HAvi1VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidy9iWVVaSmRKL1ZpMGlL
            OUkvNjNCbko2ZjJlQ01oWTN0U3NuQnVRNTFVCmUzNE9RWlMwSTZQeWRBeS9xMlBh
            WXpXck1oMUZLdDYwUWxUa2tUN2NxRVUKLS0tIHRtVm1jY2RyclZwby9PM3lRdHFP
            c2k1NFEwYVZ0QzVoQmIzbUJoNUx2TXcKgVFHOhgmyWUi8TUtkVHfROwhmNJdsGo/
            bvApo+Qre9EMwJ5tmYWRy+PoATvYeDuqq+uFDI0O0tycGpPwGo5Niw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSWlxL05JV25qWTYwQU1U
            aTVQckc4QitWajN4cmVQT1krU0FrMVlYSVJJCmpTQXNEcHVlVkpVSXNkbDd5bHkr
            REkvdnZvODRwenljd1k0bTRMU2dic0UKLS0tIDdYVGphN2IybEVRNzlYenAvS1lS
            UWFQc1Z4cCt6NnRxTWpDVmc4VWxzUDQKLvw5YbLUP72YdeqihgHZF2vRCafbfaEj
            QPEB/jh2AiYYTrtTTL5HYsyErIhXs6lRzcJ+gNiidUGc76AOJn4WJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:GL4QPWzslubq/9sS8jJHNoPLFoxwMGqkgSz86546Yg/BuRKhJrjQo5rjUXclczak6xQOmot8fqNw3W5qyppB+ujphOBAEcW0D993vevI0evoR0sF//4gWM8IQFPR+nviaxjk2GcTaEpPYfhZ40MwawjTKsikBXFZb9dt6z64IJI=,iv:fLs/iASZEiAo02GHqinujpfPYxKJk86H52bmjJaWzBU=,tag:Ag15Xw9rbF5NvD5MLzDA6w==,type:str]
    version: 3.13.3
