apiVersion: v1
kind: Secret
metadata:
    name: api
    namespace: portfolio
type: Opaque
stringData:
    SSL_CERT_FILE: ENC[AES256_GCM,data:TiNjDZAo6qwnlzM1IJGwokhr0Kc/UE1HbUcBwe7YvcwIxQ==,iv:4NK4tzQtIy/GO0s52nPXre0Oz/4wTi2o5/l19MGMPZo=,tag:Kpfcpyj0tuWZsyrv4T2yUw==,type:str]
    API_ADDR: ENC[AES256_GCM,data:Z2frbCa/HDqHrqrf,iv:vxrIYl97gCOBItGH8jKVYQFBNiW96evr9Of4ScrxTrE=,tag:H4RB3kDzbFF2pxrtfpaj3A==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:e5EBMlLP2lexibY7RF7blV3Yy2vDFcDINt3N3qqcPiBs5SZGECn+ob6oD0IqMG2I,iv:XUSL3aTkSH+8ulC1x46QDwjbhQcry6DfBmNDXzc193s=,tag:GcrmEGFZ568WyigRAs61mw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XsUXKv1u7B7D1FgoI/BwsPW9Fj6PaJT1anEhmWCekevYTvZe542CgA==,iv:GEwhIhzSV2pRQTrYiHD2gVEyS2i8Fxsmla/t9943Ao8=,tag:7ZKYKjpXcOTzuGgPWFGlRw==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:CLWT3mps4CwtHXsy8bP3KnIdKmVSkN0PP6l6b8gEYf4=,iv:hqH/A9BFpJGkjlCmFMTaOD6A0AIsejKRLP+rnPzT5uo=,tag:fy2sYO9ilili7lgOk4awwg==,type:str]
    GITHUB_USERNAME: ENC[AES256_GCM,data:p9t5wbBRCg==,iv:SpHl4m/IjLQfOFS+MQF2kn5dpwb3Ts0aQuBBUJLYeHk=,tag:yHldXciUsNAYZ/WaI4YrCA==,type:str]
    RECAPTCHA_SECRET_KEY: ENC[AES256_GCM,data:3teD+F82n6xdOmZkrnp4UaX0xyJH1db1ScItmUR34ryD1GgHAveZ1w==,iv:HrMUGtzvSz0ckpnixZ6CAov75JsmMbAB/I0zjQ+wGTs=,tag:YPKUQRnw3QhyIIMUzpdQsQ==,type:str]
    POSTHOG_API_KEY: ENC[AES256_GCM,data:hDSOQBxOM1qKJFkxmko5zyHwh68yqx/a29R0E3BgCIvKFDW21ypnGM7oihfLFJqh9CStSA==,iv:xlB+BP3zif+62r3/XciI/SO/dtPYdVjeAbEDsO/vDfE=,tag:euoWHpivwmDSz7FbzeFIoQ==,type:str]
    GIT_SHA: ENC[AES256_GCM,data:Is3MtDrGGmXkomlpfE4iJGfpDhqGHh0beN1axgO9fp9TaCWL4VQvdQ==,iv:TI8wa34cuEwMSMA5MYXdRA6x64FcrZbkYr+YHGKccCM=,tag:2+Edwh9w1AIBoTwpfLzP6w==,type:str]
    AUDIT_HMAC_KEY: ENC[AES256_GCM,data:EraNDxm5Arj3qOTHX8PLtknI76dZU3HufOKBFYtGJ4CpLW/2pEupM/7/VN6D79aB95RVsESWeqvtwCWxskBRUA==,iv:ysHCyvbYHYIMIfF7KLoFVEbw7EFnd4YcVmhokSpFLHc=,tag:lMyMYgVGVqBBqUCNIjopiQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:XibMboJuP6C7zA==,iv:moYYfK4oScKPiWLztoB3dDNkuxUezZL7U3Q2YGyRj7w=,tag:DnlBRei5wyRl8pJIjeLtWQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ZW4p8Ni3YyQTi3AWfBhnJu8+SxRltLtodIyGlYlgLSdIE1u8/jmtycd8hs4LCFu+VoOqjUB+ZyUD8IlCHbVbYYtm/xefAps0mRt0lGdgqLFcd6jjgJdP/Ololp+D,iv:3DPDfOSDTsbCtX+TclMZeC+3w9mg1LZWpLwx5tEMV1A=,tag:2Jt7s5j2P6AraBIun1GR8A==,type:str]
    MEDIA_BUCKET: ENC[AES256_GCM,data:mRTwfHr5ctubOTbK0i2L264xuE0b2iN4Proqd/o=,iv:m2tYLCIgjMZApLJvMAkZU44HVyPxima2X7EgnDqT9xo=,tag:TVuV2PZrKzykVqHy85/Eww==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:4txesqc7fZxhoDSWuqhKqz/WcmX7RH/s8fD4jZLbVJU=,iv:Rni8vfPZzcpARajVfloFDGYtKfdHD0KmHTDUYJt5Ruc=,tag:PElWdFNMqqOp36qRcXVh5A==,type:str]
    POSTHOG_PROJECT_ID: ENC[AES256_GCM,data:xDu0weFo,iv:Vfpa2A7cKx7YGes6X9yt68YJ9gwM+qCnMPOwC01xGmM=,tag:yqQu3kAJIs8jatx/xDXgVQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bJQH9M9tEHScSzBkI1zz2KldaE0=,iv:HyCiPtu3MGWM24ToPNcCJdt4pvQPAkapoSw/ABHj8MQ=,tag:AXw5GtW0pvUel7V5x5vZwA==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:6B+4bkwP,iv:551ksZFnzkqFnIbN5zO1JBQbzYxgjjn1XpxhszG1G2E=,tag:0/uVEkyjngfgJilOBtNy+w==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:k592fJ6q6d9q7A+8dbi7je2cex/oBrJNVxG887+opQn+DzkxvtMSGiE78RWfQxPb0f6D+6aFPUsZ7JnzoEpamZ/50gZXsPW/7xoqpI4NyuS9JRpYM9O+CfGlHjHeB9UrEj+YHNxNu2xRmqDJIwH/22Qej8wT0eVpS5tXbF1i3lZvp0g=,iv:9aeUntEOaeGztWhcECZVIXKPEho6nUiaAg3p+e/pa8Y=,tag:RlAH66ssPRb9XuKtVqtY6w==,type:str]
    RUST_LOG: ENC[AES256_GCM,data:diYrXw==,iv:ncDGPGXsYnmS8urQ0xdIkp2Pg5qia55RRHsPzrr5moc=,tag:eWKOGX6JVZxyNPKhn0vBtA==,type:str]
    MEDIA_PUBLIC_BASE_URL: ENC[AES256_GCM,data:Qyw+4NIsahKANGl8ASZY+esYhr5t5tIVLDc=,iv:hriyE33c44bmENLhjzW1fGzxUrOi4HLKTrAxhLAnPgQ=,tag:NVr1xmYnnCz1XvhYJ4sLEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc25heXZ6eVFWNVFCTktS
            V1Uxb1k3VERIclJrV3d2ZnJ4eGtOL2R6QUZZCkZTMWNZbnU1aHEwaGhmYXprSnlw
            QWZhQU43Njc2VzU1TXhBV0dzWG5xTHcKLS0tIHo5cENoTjZCWU1iYmJZcEdLcXVa
            QThLeHZkbDUzSnpnamFjancwZGk0MUUKOoez62YbJDggxu2RXabwQVqY04RPY/1L
            KFB6kcq9hbl6x4lD6FO/9IdR05Q/eyKvDWpNQmiUs1LBVaxv+M7khQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MHBkOFh5M2lvdmJBUnpo
            Y281QVFGOGNEb2IvVmV1NDJvaytncDNrWmtzCjVhOWJoTzdHQkNaZVYvT2hKWFFw
            UHB2RThpLzVZNE1NZ04wRWduVkxkMGcKLS0tIFh0dDlMKzIyaHpGZW1DRzloc1kx
            Z09LTzhXTktoQ1pUSFRTQTVvYklieVEKGFCvV4MM2J1T04uvmYh0bN6jyJaD8R6r
            pglLPsw5m4wKU813KeFjtrMnZKpkHpRaGedfP2l/RrRjwdzwnsGYAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cGNsbUtRM2hSS2FXWGFy
            OVdpUGVRaXdCc3RqMjhRdTduMU9EYmZhNzJrCmhwdGtWTkVsSFh6RlFoU282WGYw
            ejlPcCt4UWp3UUU3T0NwVmpMbS9ZNEEKLS0tIDlXbld1dVcxbW9wNFFoUVMwakZF
            SUw3RHBOZHBBckcxVGtMOHBZMUF1d3cK5fSTTgojy9O7BNb3CFy3YdU+JRT/O0x7
            Nd7NsPUiaNsmc1nYsAkGipbfekoJQvb+mkdKjfiu6newiaPQqalyGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:oqyudyDYXFqjFB6+sKDw8tuBrAOVF3HNWMMdnuEmY7a0z/VwZJ1q0PZ5MqSGVL6SYvgYwISWL6GMZope1n3w2/04GaNDvv5K8395l4PJ6+J8OYvpE5PNE7Klcj1f8NIDJhPsio+Zik2nZ7isH+uVmdGaYkQSr58vPkNCEv1480s=,iv:mZhMvIZwsrs/hzSd7mVqAgY3bVpd+5JIK7dtHwHo++0=,tag:h0yAo5qcN1bbU6Bd3qkDyg==,type:str]
    version: 3.13.3
