apiVersion: v1
kind: Secret
metadata:
    name: api
    namespace: portfolio
type: Opaque
stringData:
    SSL_CERT_FILE: ENC[AES256_GCM,data:fJ7OzBZiPeh0gboAetTRSe5ljf/+EN3Ob2l0eN5ur7hE0A==,iv:4NK4tzQtIy/GO0s52nPXre0Oz/4wTi2o5/l19MGMPZo=,tag:acrxub3ZbFCNt5PPIhTH5g==,type:str]
    API_ADDR: ENC[AES256_GCM,data:QPPGGkyUjrTJZcV/,iv:vxrIYl97gCOBItGH8jKVYQFBNiW96evr9Of4ScrxTrE=,tag:AcVZePzDLdbmu6Z8RVvjPg==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:RbjmrJTCUE7yuaxoRsRc8v7TXQru4WC8rwATI8oSKKS//cdJ/aZyjIaFlspHlE57,iv:XUSL3aTkSH+8ulC1x46QDwjbhQcry6DfBmNDXzc193s=,tag:TovoyuwYkRCpFHIpzSVTHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:W5wnwCWl4Hz96bPVI044s076wrdBhd4e9fhJiABMMsnmXJHSH0Q1IA==,iv:GEwhIhzSV2pRQTrYiHD2gVEyS2i8Fxsmla/t9943Ao8=,tag:dqsNZspYez24iC1rBgpnBA==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:waKGH7P+47ddEgDou+fk8rTrH4aoD3fm2t8ThPQd9sE=,iv:hqH/A9BFpJGkjlCmFMTaOD6A0AIsejKRLP+rnPzT5uo=,tag:onWvrxsBt3mE+1r1zFP+sw==,type:str]
    GITHUB_USERNAME: ENC[AES256_GCM,data:em/+qwb0uQ==,iv:SpHl4m/IjLQfOFS+MQF2kn5dpwb3Ts0aQuBBUJLYeHk=,tag:55bvaQRsGa9rgbooiXrr6g==,type:str]
    RECAPTCHA_SECRET_KEY: ENC[AES256_GCM,data:Gb7Hz2S1bTzZw7TqqDY4JeciNzzfTXc+MSahjUCdfeyhZH3nQ50trQ==,iv:HrMUGtzvSz0ckpnixZ6CAov75JsmMbAB/I0zjQ+wGTs=,tag:R+q2YmaendpGqrSxsyy0bQ==,type:str]
    POSTHOG_API_KEY: ENC[AES256_GCM,data:cqSw3IsctbbraBYBJ5BOe1mtRatoiU4VY6xySiXzYVxBkBnSyO949gnLSU15yt5HQ9YI8A==,iv:xlB+BP3zif+62r3/XciI/SO/dtPYdVjeAbEDsO/vDfE=,tag:SJQR8kDtL9ZaC46yRnAuIg==,type:str]
    GIT_SHA: ENC[AES256_GCM,data:JgMgfJ+JQFQ4/eGk+hfnzbByvElEfTsrRbI7fUil2M9KhxBVG9qmqg==,iv:TI8wa34cuEwMSMA5MYXdRA6x64FcrZbkYr+YHGKccCM=,tag:SGfcHX5Be75ZT0ocDY/4rA==,type:str]
    AUDIT_HMAC_KEY: ENC[AES256_GCM,data:6kJRId7D3keF+jGl+SpOnouR+UYKp1z2e6OPfe4uWA+vNMgTGwz73nUgxXD5WYl3AGeW3vaRnHja/o24CjIFcw==,iv:ysHCyvbYHYIMIfF7KLoFVEbw7EFnd4YcVmhokSpFLHc=,tag:eg+RgD/ukLsd0clt9HBabQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:yItlEZ9NpWMm+g==,iv:moYYfK4oScKPiWLztoB3dDNkuxUezZL7U3Q2YGyRj7w=,tag:l+Ll1utLmwJDUkrMdP2t2w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:pfsTLCTikWhkcRGv7izSs0AVg0nI0QWmXfmAz42pujOjXrk+1FQHNafLbpzqZcNkN/UVhbQdnA4hMsrDs2YW25CVuDpQr85xufEo7+bshmu4nHtMAxhwBaMnrZJ8,iv:3DPDfOSDTsbCtX+TclMZeC+3w9mg1LZWpLwx5tEMV1A=,tag:GmupsN7hPn1d4UQ78OQ/Rg==,type:str]
    MEDIA_BUCKET: ENC[AES256_GCM,data:OJrerIijJHqQszofzJyUgXBzTmnD/Hlme/sVgsI=,iv:m2tYLCIgjMZApLJvMAkZU44HVyPxima2X7EgnDqT9xo=,tag:K12TzzFRAxMQws7AekTBXg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:4yaxhVIuFFI2edyfx5BW9hbCmZcdQaOJcq0MH//wI/0=,iv:Rni8vfPZzcpARajVfloFDGYtKfdHD0KmHTDUYJt5Ruc=,tag:de2aQZxJX9mQahhmZ8D8oQ==,type:str]
    POSTHOG_PROJECT_ID: ENC[AES256_GCM,data:1yLKuHLA,iv:Vfpa2A7cKx7YGes6X9yt68YJ9gwM+qCnMPOwC01xGmM=,tag:rw0QmFqa1zuusXRpgZ/Yhg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:54GR4jDjcRA8iSHrxEOxGLnTXYs=,iv:HyCiPtu3MGWM24ToPNcCJdt4pvQPAkapoSw/ABHj8MQ=,tag:b8/1ehN2Hlu6VQywFPxFVw==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:E5u3welt,iv:551ksZFnzkqFnIbN5zO1JBQbzYxgjjn1XpxhszG1G2E=,tag:gztNTrz3FH7dHnhsPkadkA==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:8UyZOGDdhvLKkz0kJy9zc+yzNLQNNdqNF6HyLW0E9HQQTMeVg6HxyClR0Dy/qV853N9YhEh5//+eZGq8f2fzoT+DLZnb8iSoGfwKd8nkAzOb/aEAWqB0wfWxpMIfKJ3vhoIOoE/+9IlWZ/QZxoaTFR9SBHNKS7j0VQqoSrZUHTxttA0=,iv:9aeUntEOaeGztWhcECZVIXKPEho6nUiaAg3p+e/pa8Y=,tag:Mx8psj7i6ML7/1NSvxBr9A==,type:str]
    RUST_LOG: ENC[AES256_GCM,data:dv11dA==,iv:ncDGPGXsYnmS8urQ0xdIkp2Pg5qia55RRHsPzrr5moc=,tag:9PVnaYuovHjTTuazM7IEPg==,type:str]
    MEDIA_PUBLIC_BASE_URL: ENC[AES256_GCM,data:Mg1illTzUTFyY+eDzNDoRW4IT8HbIWM/DwY=,iv:hriyE33c44bmENLhjzW1fGzxUrOi4HLKTrAxhLAnPgQ=,tag:y1ntHyYN+XrWo12rmJd0Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcHpvQXplNmdVTFlXTDBN
            Nnl4NU54RW5USHBYMitUQld4Q0RlSHhYTVVZCmNDQ3ZLRkZweGlXRTFtd3Q1WmxU
            cXkreURLdDlRMWxQd1VaTHl3QVdYQU0KLS0tIEZvKzNMa1FTQVFFMkx1bkJIMnVY
            aE8xRkVBWmlycjZoQ2VKK3FSZ3JqSm8KBi+8MNlTRv9iGHWrmaQxem/HxGKv60m3
            yXvFYAY54SLmQQZFlI6CbYfK3Nasxn7PbaI8ilfK2O2U8zYTPxpYZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUkRYRjlDSE5QRDl1U3Q5
            UTVTZ3VCbUlXRzE2RmFldmtXZXY3NnMyQVQwCkhHenh2RW9wZExhd0RSQlV5b1Q1
            Z0hyaWlicGphQ2tOTGNVMEs1ZEtxdEEKLS0tIDczRDE1bnYrcklObmJ4K0h6R0Nx
            bHhCUWl2ZmVQQUNPUHVyaFZyL0FVLzgK/9JopwnbxnP9wn1RU/BLZIuJEf3t5LHw
            0uEUvL2D50wFVqZaD6TJNBgU5mf+5G7sbva0NrtsocSasS5sxzvkog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNDIvY0ZKTm1VcnZEcU5w
            TmVqaG5ENkdGOVdEVVpYNGxOMVBMa3Z0QjA0CnZ2dkY0MnFVOGhsenRWeXFDTkhJ
            YXBaSzEyQmd5T1doejN2V3cyT3NMWXMKLS0tIEtPUnpuUDhXRXpUaENHTzBHRks3
            b21KMGdZaWd5aEorY2d1RmF3b1AxOU0Km/hUlq+dz/XmfUSd1gFbd/hv++mtOs7o
            vZ2VbwMABB6Km76HjV+Y+G7L5SO7EZIfGjWhcbcgjsN1cL7jRHB+vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:JvmN25khS3LX15jhIrn+7tHMhNl7Zmf7XGTbPLTXGRSsP8LOA/adu/cQ4kSXmQHLxHzMM/vKHxD8JU0wIvx+mh1dvn2fd7+Hq2m8SG57/zx89vuqk1c+NznU/B5JenIK7kxVVeI7PXma66eNtFsfI5N997wsxp24w+n2AzwJous=,iv:pDbSTrvBCu8xoLFNdmcC5NY/WtGUvrZk3Xqa+CrDtMU=,tag:5+IflFuP1lobFXrDiwU4Xg==,type:str]
    version: 3.13.3
