apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: portfolio
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ap6F+0FtfnGzFgXjxq3hDHNn+Duc7MyuXGEmuwJGKkvELqOyCTX7hHUlkAiz4vpEFoZZYw9s0qnMjR+nIp2A1SDjy0SmHEc=,iv:Jug8RnHkHXJlDzAhel/JgSJYQvSDWP0OyHx47FIWuE4=,tag:FraP63i0UALQX8mYyVp1Cg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qC9byhRKNKn8niMs7WLcHKV2EBhJU9tV4butL7UYZmXs6TQ+EuDpL7Uw2+HK1HA1ksnNeN2lcoLNPNJUyqdJCg==,iv:fxNu6GTSgmSvPnqwOIgnPFQQxV9pI/kkT/EanMVparc=,tag:0Xi+Z72OYZ0DxhM/lCfvgw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:umtlKYHIbC5R3tIVPBC2i851QHE=,iv:tbtnvR2/jyMQBVncUqmYRLWcQmHY+c5udYJzb7Z+0FI=,tag:CxM2OCTULF/HvOvxUuc1jw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TAtOMVtl4oPmyJmV+H9JWWe8Bucj+idR9Znvq2VnCW2kYxFs0k2rwg==,iv:A7W7do5tY5K3+cvn2FXU6GwCMrjowfGghg0VhfKYq3s=,tag:H2kDSNbUYBBvghALXvkosQ==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:VcdxJnibbsMC1A==,iv:aDbBPT7Eq4SRl2xu/1xYkenpylXo48ZDnVsrmAXxAOQ=,tag:jeEL3L3IO6W8C1ma3i3Wow==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:u4DFjteBu5GxTrhExu5RZ+yQxE6TziduQJQxpcgF5ZF0EHZC3qEOapQCbslhLNSYxsojAhPPI9unUFJxripu9A==,iv:440OUldks9gp0OymSn3Hz2G3Tgbv0KGtWTKFuAcde7E=,tag:BFjlEqodIVIo0PLYFPyVSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteVJBYWxvWnNoWWlvNmpx
            TlNkWVlJNU8xSS9LTGY3TTVUcndDYWJBOHowCm5LWmZDMk9QK1lPR1YwcUM5Rzc3
            QWpDc0Q0ZC9iKy9QOFd5RXNXaklFRFEKLS0tIHhPYzBtekdCc25ldW13ZnhrcStp
            ZlBUVi9Xd013QzJ0OWVRbGIxSVhsY2sKxMnOdf1agzsImRUyh3zUMg02S54r1ImV
            RGkTk/XExJmVG9tIKXASJ5SvpX0LIWdTdz2fgOPvk3eTFLTUN/Rfxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T2svWTVONEJWUW1pY2Er
            TnhDbmZXTkI4M2dad0dleFpFL2QySFQ4N1FjCmVYSjRQays3SjZLUFo3OXR4d1ps
            YUtLT3djczFtZkZXemtBT0JIclF2NFkKLS0tIFZCM21iRFdIZW9DVzNDS1I1andD
            Uk9PVjhOdm1Ea3lyVEhDa0NlK0lZYjQKQw5/J6xgxmsqs15RKH0UbHcHZhBgqB3W
            JFqnluRZ9IeK+EC2ivphmsniz71+xyzXhpFuSeVds23kD7DkXBkrDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNFVKd3VIbE54aVBTYldH
            S3Q0NkhtWGpLcGljRE5GK0ZGZ0kyRjNWeVJzCmduMm94ZHd2YUhpa3Z0VFE3eFpD
            c3BFWHdvYzRQWWt0a0M3Y0V0ZzRheGcKLS0tIDFJN2FTR1pMbXlsT2RIWXNBbkZt
            anhYN0ZHbGFzVU5ZWW5iN3lhaSttWm8KzheDiUl6CsL+mw1OWPlFr6Ga28qalMBz
            4aEX9FcOxJCiZnxcdulrB7eco0UIJFGzPjKzDxz939vc+9Ub8+XwLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:14:04Z"
    mac: ENC[AES256_GCM,data:RgprNZRWReu2clRw5RWw9aUTlunaiv1b0GgJonV8CXImV1RWc6GYWH+EjuiBjU2dytw0+5gqHKd3MYAwrXRIamRrKDbTCELw3Qid9wJSdDtdKoabr2SyGHM0g50yWarjdPOGUppTXp59hDIZKUbsmovboZX2xT4NXvifYy0V8+w=,iv:8/B73jPrXhwsUic7ICOv96eiHS0VmdwWwJ/+FeOa/2Y=,tag:MpdjVfLRD+0syTo0sV1sZA==,type:str]
    version: 3.13.3
