apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: portfolio
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Jnhi73DSKrKGmrjkPLFjCMu6C2lnQyxbYDs006z6MRarT6PZ8cG/cRV/JSZo/bnm9B6P8WYbGoNpa+/GKNFSAcvu5hcj8xXkAr7vQT6I3A==,iv:ZW7Jh2enSswudnmVRLHaCrGFqf+/40PnssloK509U5k=,tag:qtm37n/3n/vhoNxYUjzMuA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:7lQd4I0++paHCMGkqPYHn4bngeDL/c4rSyyOM+2/ZQBz1iYNIY7j3X3+SQspcaDWo5BTjJ/4NNk/t0cVTINNog==,iv:v3M8F8ihau2P6d2tMfk5UeMKV2ja06j80JSo+F2+UAs=,tag:4yoGemlxjyWnTI3NHvfaKg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eb7PxB3vJexgYqmJAxDwZsk1yZU=,iv:SmBqv5qvqtFfUk/cfD1tbvPFCReTjAzJuejxlW4zHzw=,tag:TblSlAFKJvOpaOwv57ft4A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:b9fpcM2I4ekMpbl9yILnPpJxK0uJ5Ka7SsDcEo8kgIxMzDMbbhw3AA==,iv:2KTYuBJK0GgF1Q2eH0HFtaU2vF6Fzw2++bUzKV8Fs8A=,tag:jeOYz6XCuPzASprow3WFoA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:DyztiIatfx+g6Q==,iv:QC6hKR5X6Z4itsC+47iLU/U+7s3a6wxL+x6Iu3XwMMI=,tag:LfaEVxM++/O/O1BFOZWf7A==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:DLbHvYV/t4AxyMrHwrEUQx8ummaBjgJnswJ8IsQbi0IBWkht3YNpmUyzIQ==,iv:34QMGRw6f9kUBsoxWa0k4+684EptOcmLujAH2aBkde4=,tag:OdqqkiZuEkJeagDXk0QUgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRWZqM01tYWM1SkRqaEd2
            VXpIbmdEZEpwM2htQzA1NDlsNGNrd1lSU3g0CkNCQUdJOW5RRjZqa1lQbmNMalox
            eTlDWlVTQ1dEVHU2VUxMeTJud3VtR3cKLS0tIEpJdnVlNnU0R1dYdDJ2clRBS0ht
            MU1nNWJpOHdDQmk0TkRnRjFZUk5GRkkKEmcataHJUDSgkifKtnDXJcZsYxFeSXBt
            gM8uZvIxWjrs3xNLXs3Cjy1uyZsvOkFtRFiHEXimqkQ0lZFhfJH2MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSnZUaXpGQnN6SW1TanFk
            bnFEM0l3aU84bDcwZEtkR2FXVEpSZUxHakd3Cm1NVTlRWXhKdnozUkZ0SGM2Vmhx
            Q1VPMFhKNkY1YndrbUJFZkszWUR6R0EKLS0tIDl3ei9ROEtDYzZzQUJQdVY3dllm
            VlJ0UEVweUZBc01YdVpFUm1UeFMxM2sKuZCH0Ylpg+sO0Rw82rXrk1OPH6avFY/R
            Y8wwfL4zHobQgWdD8q/6zkpepyNVvWwLK835co/0zTi/uWrpQGxi6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdmdTNXB2dmZRL0JJMW16
            ck95M3FqeXorYWFXVHFqNDMwZVduYlladDJnCmhGYjgvMGpLZFpZRlRsTVJmRXB4
            eGpCWnhqVzQzcS9HV0hGODNnd2s1bzgKLS0tIGpJekxpV1MrYlBXMTFYRk11SjlI
            MnBTdWRQNW83N21oODl4YzBtRDhkc1UKywQLxm/yyPVahSglx2tTUfrKR0LpgROF
            lhSY5BilbgS1vre/AOWV4KFQLVKMn5GUA4mYRR9IK7/zQfayymtRqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:10:37Z"
    mac: ENC[AES256_GCM,data:JREgVCfXdDPmeHibTyZqXvDI6sRsLcUL7Ehg8jHPoLZnENkkO/YU6PTCUnUdAsk/1EK0/ChHvcurbK9XjqVBlKF7dYJLqiDkf8bxMOggkVtWjl/no81/s+sfHGrP+D+5curaUaappW7sy1/OX9OGoBqtGZm7sH0+ecJZGtQZ7Ek=,iv:nOyiLI8Z+Z5JHAiJsWlGjNvH6fkh8udwdUmbINyg7pk=,tag:WBoN+4U88ViyrwTLZIkr1Q==,type:str]
    version: 3.13.3
