apiVersion: v1
kind: Secret
metadata:
    name: backup-primary-repository
    namespace: portfolio
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:GKFtLX2Hby9oNnwpmtuKqS1wybhCykBNTlULK07SX4OpvVw+GIoQ4FDdKh+8G89e9f+fOarxjrEO/YcEPPxVQI0OxBEp4FNPBN7BJAmV,iv:z04CtkOeSFIcqJH44WY1TWomRAyon1gBB+bze+zODQk=,tag:hTvjWoK/+btY6+hLXLuZrw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:UMerq3//ym3wLJI0FowlXIQDFHq3bKtF+sv7+kmmAZdm0EeQwZ09DvASp26RypgA2XHHS5wWs71tUteDE7K4SA==,iv:1w76zE5GwJjznKWnSdkUr5yatY0iIQVar6F+bGYBlCw=,tag:LHgiDqanvrJU0FpsXP2wvg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:klITtpebYP/DjY7138KfezV5BYk=,iv:Ov7T4lQwA1ItrPVInOKxlfUKunay80+p7T0t/Qp/cog=,tag:acZ/PXv+nYyUouDJcdQmag==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kIt8fnSOMy0juX8yUNDnk1/nk5nXqmZnoCJx0MHEf68bTYfzoVI2qJ4rWx6rEUJ8pKsPo2txJ/RIhLummOZHhQ==,iv:dUZtN3Tq1UqNjNBRawc6yyKup18AwoiT6T2FjC/kpk0=,tag:shSBVIxhy/Bu+EWH//ePkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHF2OW9GVUlXbUtNTWRV
            eGdGU2hXTzYwMm5uQktxZTZiemhxNTBZd0J3CjZtMWo0TmVRd01EVEJERUpyZ1lO
            TnQwK2g2MUVmcjlFY0p2b2hoTVMyRzAKLS0tIFBDYThvNnlZeC9GQjFYV0VBdEI5
            aE93Y2dFQVExdWsrVFZnajEzV0R1OFkKVVSIHUkcDRFIlCkgtz5BsyKrWGomWfmP
            u0aNemfHu+pGU7UwfktSGXP+6szchFayHhQp9mgsRaMBLiCoZXhXog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcXgrSzN6bXRqa3piQXp1
            R21FNUU4Z1RRUFY3UWxvTFppNWdOUWVjL0FrCjlyUlhwR0RLaTUyZDZ4S3hiMmh2
            MnRYNkJHcnBUK3VmdjU0OXh1Wk8xbmsKLS0tIGNUanRacGlvZUZSZDNLdDRudjFo
            SlVUY1ZRK2NaQVJKbFR6eFkzdnhPcTgKDcaI/VOpEkZzxj8YzeUAWBzo9AJKnj8t
            wPltEImw9J04N3tm5+oDSXZiaXtXpAWg3SEjQ4uDIil6fYZbzV9MZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS2ZTUGpOU0pZT3ZxN3BN
            dDJPaDRYbDdBUjBkSGk2Sm5Hd0pZSjM5VXlnCkJhR3VVS1FubnJQRVdXV1ZRK3dH
            TmlNbk5MelFlb0I2NmowVVlPV3ZzT0EKLS0tIE1aeWthdWUzN2VJbFVVQUI4YW1U
            OEFSaWtTTE9mVGFpZ0NpdXgva0hhZkUK4m0IgPw9bEYLp5n+FaAnutNqo+Y2Ted2
            p0r0+kK2OplxUDG6eKM4TFeVP/fY7pO9SpvWz+SFxKU+KkVSAd7F0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:10:20Z"
    mac: ENC[AES256_GCM,data:99SDcHcA0bBmIvd5QPmreIXN4MVFNKC0HcF7b2hUNidgXXTeoLaLN8V9ScoxNl2wpem2RnVsFk/pDILSmevuvKi5j6G6m/jBUugmjIGIa1KEaRUNmHcL1QOZbL//RPVHTu5BuaUtdiRoLAQPZF+Mcgy57G+aPhVzo0R6+RioVyY=,iv:vwIsvjrY9UvYV8W5nzmwyirxv31nN/sjXd3+dgid7H4=,tag:sJGvgWLQVn5rgJM+jdkEQA==,type:str]
    version: 3.13.3
