apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: portfolio
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:/gBflsnTrGDxhIiirZg5BJwZUNImFw9ad7OdSulSWnEOBpbEtvw91j7VxEjD9bU0Ny3jmgm3aQqywzMONyOVg/D3Y6XBQjIyAIbkbeuUnQ==,iv:ZW7Jh2enSswudnmVRLHaCrGFqf+/40PnssloK509U5k=,tag:5Hp3Q3drs68XRX1sbUUIHw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4WNnPiyUV4f6MjTQ9ts/a1U22s6WS8/7SEnWBE9FLZF5BhF4Nne3xvB+P+qH7fGYnnWPKE/J0VCRn24CRMpiVg==,iv:v3M8F8ihau2P6d2tMfk5UeMKV2ja06j80JSo+F2+UAs=,tag:ovZTONLmtbM+qcbonhH2Vg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kIAuX+184+He7aWGQMtNtLwB1Y8=,iv:SmBqv5qvqtFfUk/cfD1tbvPFCReTjAzJuejxlW4zHzw=,tag:c3SBK5lLpQybQtHypHEpCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:w7u3xZiLLtXoZnU6LHuWBucC+DLaOObGZ04ep6t17yajDnl+AI1WGA==,iv:2KTYuBJK0GgF1Q2eH0HFtaU2vF6Fzw2++bUzKV8Fs8A=,tag:zt+jWTMQxHAX1WdJIY/rzA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:JfGGT/FF+9qszQ==,iv:QC6hKR5X6Z4itsC+47iLU/U+7s3a6wxL+x6Iu3XwMMI=,tag:L8Fh2pX5K1miV3HsnEZGrw==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:FN4FN8PedhP885kjJ8Oypxo/66MvQ72otDWduG/I7l76n//l1ySuSRsV1g==,iv:34QMGRw6f9kUBsoxWa0k4+684EptOcmLujAH2aBkde4=,tag:NCJdWD4mH0EFw1YqTcJhjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSUdtNFBhS1dRZHhZU1hw
            WmV1NEQ0aWd4WGVYajRrbmVGbUxTSUJobWlNCm9ybXRKRGZXbmwzQk54bjVYLzVE
            VUhDM0gyQnJQRzRoM0pOTDJyMmFZdGcKLS0tIFFBcWtxRzVwNG9NS3JiMmFPaStS
            emZJaWNNMTFzYkFvSlo3YzVWQkk3WncKEEAf+V/69Tc1nVOP4PoBuUR5rC96C/bD
            w56EVXhUP9cxe3f9u5GAvofbBNaCFWymOxOuxwHshwgtcxZV3HMo2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa2ptN3JaSWd3N2owQW1s
            ZVpNdlFyalJ6cmtHYmFmRkJRbzBleUpiZVNnCnlnck5US01DcVg2azgzMUVYYktw
            SDRhTmZ4eEh4MWVRTGxZTE1PU0dGdVkKLS0tIFE3YzVZK2lmTlBoeXNlaDRxdktk
            OXlhRU5yb1pLZjY1UTNyV0tuT1ZDcVUKraVVVLBpR6c8j6+NfJqrTOB/kA8u5Io+
            IfU/XMcUTEQ4xk7FPMMi9s0JmiwG0ovonDJQF2bnbuRK/ytzbWfykw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWEk5SGd1RDZjQ054aWY0
            VGZMVmJRaU41anJ2bjRQTmdSeEc2NDFsUENFCkdLZTNpSW54N3h3cVdOMkw5a2FE
            WWtzWUNwZmVZWTlqU0d2T3AxWUVFU3cKLS0tIFJFZWhiTnVkUU0xYVFONzFseTEz
            VlcrUEF3K28vTEk3OFRhMThpQUlPd2MKr5XwOWA/lYa0MyD1VwgTNTPLGSoICbS/
            UAPUcSGEGYJ3YW+UK9hzkVhgmKdtl+w9+5K4D52GYjfXEE/yclJreA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:twrpJPw9XGGyQJ1FMKEP+0DkJ9LJQKiQrTqGW1bHMu/c0HdeSNtiUK6TH5lvujvxXY2t3rhgfY9cR/jsuGJARTPZUXndCBrn7DUv6ucojz7aiNsBX9ltpWTi5c+f8vmd33lXQZV4uzFCkqihdkUqRCdEtz+BHdGlQs8FkQWnm9Y=,iv:jhv5YHuN2iy0QsnmuRLj0DstIEUAV2p3nN9AhqC7z9c=,tag:7YXcZd4QOMJUIP3StvAzWQ==,type:str]
    version: 3.13.3
