apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: portfolio
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:PHJ99kpHCd+n,iv:OH9SpVxMNvYUosgcEY6Kv8KIsbal3lPrTuyqJik71KE=,tag:V4gRof2P25EwiS8OeyN6ow==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ClvgQMj6HyLp,iv:I2D43hwiQZ95DCShM/WegwhPB9U2tvJqjUoso2LX9KQ=,tag:63XsRC1o7Jsn5mx7KXA2Rg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VK1+zx11c5ug0V661vVSf+E1OiVK+2j/mZB85yr1z/dUwu9x57NXT8F3kezDXBj8,iv:yiNvZqKK3S04DWsNnotSVpo8Gl0N1pjDd4xV++ZRzyI=,tag:GCQiqoyHP/NSKwVhMoeWHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSE1VZCt3T0ZCZStBeDds
            UHNPZXMya1hzNHJwK3Q1QUNLenRSZCtQRmpVClNmSjg4TjJ5bW1sQjJpTks5WmZE
            K09nZ0E2L2d6c0s2SkFkZkJQeGJlcHcKLS0tIDBwcDNvM29rWVFMbDAxbnQrMUsz
            YkhWbTZPeUloNm1UbzdCT2FxVXZSRncK58rOZZyqn7FS4OG8QaZqSCo0NVaat1Iu
            qOLg5mKx6LNKOUWcskJYh8YQ72N6ZLIv6l4nRG8ZpZ9OKcCoQlBnTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRmQvekp1VFJjQkZGM1hS
            amxWN2o2Q1dXa3Q2MTg4bGUyTWcwQnlyaXcwCjgxc2hveTJlUktrZHA4S25QbEdQ
            WGNSckhnU3M4c3hqUktzUjZHc2ZqbHMKLS0tIExldFg4R2NINHpvUlV4NlRvWk0x
            QXBsYzFSYU1WYmJGc1FqcDZsdE15akkKVH8E7f/lqjaoaOgppQRDHMaYOfL/vhYp
            Jso7E1Z05tUFN6qfhF2OUiPsVLfjkonlIMAmvu/ffEZEEz4ZDiZhew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZXpuQWJ4WGdjcWpyVGE1
            RTMyV3ZuM09hRlQ4U04vOUFJa0t0aUdwMHdZCjM2alJIRkZ6bTlGVmdXZzlYZmxO
            d2ZLT3g0ZmhmSHhsdHV0RTJBZ2NDR0kKLS0tIFd2dkpqK3N3cmlpVFQ5eVRia1Nu
            cGp1cmxENzY5dUNyWXp2SXh4TUU1cTAK1tx7OffiZT/vB2e4ZINdpHg9QKPkEG27
            13RF8bnHcpg3UnCTV3Bo9UTWtIYJW/eRQv+7uu6zFZaF+D3FCB3jzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:hpTv2wcMACGRKYH12D/4QA809Cwy5QnWM+uv0yKy7fOwxHxFPGVEVf5Wv0BiglcBPMJ85blaHk8MvDkKKYHDRHyg2jiMWYJbGgxMY1rnXeAtySwPDbo+e1KtDzsMK2AwJu5Hfp4j4AyCv26gezIardm3ASouNgZxOIeiXDzlI88=,iv:Bxrk0pwaFAtG/D6hk5HQD3qoC2F3ZJJVhx1EVqEuS8o=,tag:KzOgdCsNNTspj0nfqoWWDA==,type:str]
    version: 3.13.3
