apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: portfolio
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:EN1roFr+nSwy,iv:OH9SpVxMNvYUosgcEY6Kv8KIsbal3lPrTuyqJik71KE=,tag:p0VXxWZY9K1qgRITRlVoMw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:4UYgn8BbEQxl,iv:I2D43hwiQZ95DCShM/WegwhPB9U2tvJqjUoso2LX9KQ=,tag:6HX7U0/z87PJSAMeY5uvow==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6OznM/vMf6p2pqODFbSrD8//GcBmuoQta/tSD+zBA5305DqFqToKMHzzafudKuv8,iv:yiNvZqKK3S04DWsNnotSVpo8Gl0N1pjDd4xV++ZRzyI=,tag:m+4S4JMtTBiQKF1S3a8Wng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRDY5NkJrbmk5d3o2dVk5
            WlZML2FCeU5ZM1lCMEJoRzVOdTg4a21RaldzCm84U1VvWjd1dG45NHh3ZVVSYzRU
            OWFtU3Noai96cU9wWjZkSHFDeDVUbDAKLS0tIHVKSjlLVGZJK2RxS1VDdkd5R0Y4
            S0Npa0ZxR0x4SWUzQ3hPTE9vUXpsb2cKdk4HNNPzeBcMn91NB7yPszFiegfs6k6b
            c1bBEcL235jtH+X9U8tP336ukpZXiay9oi+0CPQLbXs0Tbob6rpUGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeUJmL0E1Szh0ekhIQitT
            UzZXNVBIWEN6cDIwRGRpRVFWWW9HamtGbEJrCmR0bjRJUmdrSENqM2N5a0JHRlZu
            dHpERkgzbVM2bHNYNFhjRGhpdHRtaWcKLS0tIGlaYXJtb2g1WjlFTmxrZEtGZmlG
            UTBEakZsd1UyWjE4UjJzRkIyajRKRDgKqFxWshW3ap3MK8fSSWSENyzAiegl4e+k
            6Mii5Ta63Cn2T4KZh/AgDMe9we5Suacb0P8bOZE5sCZXMVFs7s/cbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNkw0WFdzNm9KWUsvSTlT
            YTNoN1ZQZmR2WU8xdW5Vdk9FS3BVL3liRjFvCnFMLzR0bk05eld3dUVxUXFrSEVY
            U0pzNmlac3BxS2R0alNMZDhCSUtxRFkKLS0tIGN4SGFUNEJneGtBT2F0aEVpWnlY
            OWJ0RTg1UWI0ZXU4UXVtTU0yMTR0d1kKdhGvhCoVsVHMtuiIz6m0iv2JSsy5nZRg
            jiQ2hKmbDeUrUch137+r7PZ9WgsV2vR8ZGFMFldI2eycG960+sOCxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:u0qqctAZp8RHURBM6LGjDAfqsF06UpQoSvu6mtaLJElNtbxQwPfp4fTTmNOtTZV0lws/eEIAQraf174m7b9ZWo1kirPvKSvGUJWa5RyxPFpvkczJx0N1HfaRR/aeOVgp2l0hGTaT4C6+ANsi/UKd6dNBkHDFcy1cVnetpldcUHE=,iv:w6MdjqnfVCLYF1LABdBjb9eBG6gig7ohUTCS4F77+aU=,tag:BcTXNQ5R+jj57804umAaug==,type:str]
    version: 3.13.3
