apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6F3x1KtOeVyJrBlM7KqNcVVeukIK+Mz4/pNUumxE/PWW6+yV6V4dCqopzgQZMOECp0wC3ZuOytjTB78RFuzKauYTxkMxYNaN7e+NJk8TeTpojk1GUdhklK3iZl0TaBja23s=,iv:mgok8QP6pluSLcc+fC4pu6TJzhVWTnmjxGHoTa3ovKo=,tag:Jhmn9xH+qV3jtSYmJ8U9ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYVEvNmw2MHM2dnJLRHRr
            SStZMmV6WTFQYkNUNk1pZWR5MzRFZU9qUkNBCmxPc2pwOFdtNE5aVTVHcTJRWGV6
            T094azI1eEdqMUVLTzBzZ005QmdJcDQKLS0tIDBrVFY5UDFYclMvOUVZbFlNZlVj
            YjZiRDI4UWlkL1U1bnljZFZvaWJ0VmMKOKrxQuo9qlCm52XtqkXwl/22jWQVqWEb
            kgnaecBH10pCL2tp42rVUVaUD8bTR9bc2xO0H2BGAOrfL6ruFo1f0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNmdTbFRSZ3ZyVUpoNFRB
            dFV4eHZyRUg5RTRpa3pxeC9SbC81ak94cGxRCm1jVlZKUTI1Q3RXaUxqbFROTWxs
            RzJxVUpnUUYyRVRUemFucHhEQ0tHZ1EKLS0tIEVYcHArdHJ4SkRXTTkvVzBlWktq
            VE96NklDUWVoS2VpR0xlVjNSOTVNV3cKGriiVAO9+7scnA5dqVI87r174gpqtyof
            HgPrBWOnV0X+jD1Y9HQyzRMnQIwr2b4wf/BOhXsxfRbeWA5OFOXp6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZG1Bc283YnYzZW9hU01s
            YWI4WnFpci9PZ2FpY3BrQ3NQRnhlajRyeVhrCmRkbXJlOG9EOG94aXY2S1l3aUhz
            RnFXUW0yRGZXVHVDMG5qWEJjaktjT0kKLS0tIE5Cd3NPeFAzOGp6cktCSFNoTWl3
            YUdQM3JTV0ZWcDF4L2RPUTN6cElXL1UK6cjUWwejvk5lgLwbE/iXbW6SWBOHpeBm
            Vrw+d0Wu0R5ocgR9x3M3V159sWhbVOE7KHib555KZYGhajJrx0py3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:Jk48waQIiBiH8pmkgf3jhl2XHW/g+0IOemnLN/ICfi5YxH5ijjwOQyXaQWxrFAHcR9yXjY1OTFMkZWV3gsEcuCVJeMrz1vuHAgShuv4cItJymc1sW+1d8xXIB8rCv9yNmbH3oGys8RxbYYjbKSN2IED4oVTe3cDd4NGzNPwOI8w=,iv:rxgNjf0nL6KpNgmi1U9Ll9EMbwwsKE+4TybpHPL7wxY=,tag:NtX2ChVQ8YeswoIG9QUT6g==,type:str]
    version: 3.13.3
