apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zKUNDcPdi2lg6gm7LMGVMHBNtb+pTXLg7TO1sBUKA4iB7faAOqPz4H+hmqUONkR6314y8SAMhcStlah3EeuNsYFsCoCXJAJIxA71/DQF2Wv4NZlmkckXdAyJGYYUVrDJ0nc=,iv:mgok8QP6pluSLcc+fC4pu6TJzhVWTnmjxGHoTa3ovKo=,tag:9zEK/R2H499yb0OhcaFsZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUzFudzZXSkRTVjNrTVp2
            TlFCUXFPK2hpUXhvR0hvR2ZCMWJ0NldDTVE0CjZhZWZMMXMwSUxQNStObVFiNEFM
            S1NNN0s0MDRFV2IvQ3NFODNBYmRjeGMKLS0tIGlrNWRLMFRtMkhvVWtvUW84cExh
            QUJPSzhlaEszTVdMUXNRODRBa3VZZkkKYfL6epvZirblG2pcwPG3wx/dA/pYkMZ0
            QXpEjM/MEscdc6O009ry1vN4SITErvM3+q8eZrXEHz/EGAuyTeNI0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETVB5ejVjVFlGcGZsSGZw
            Z1VNMDZrRDV5ck95aStDaGdib0J6Z09OLzNRCmJRWHlqKzZQblZBdjJhWFMyeCsy
            LzdyeHNaV1RDd1RqVkZpL3p5d3ZnTDgKLS0tIGdxeWFVbnNqVWNoekZaSmRZR25G
            RFVqNzlHTGtuOUJkRmM2MHhUbjF1UVUK1HaBVgcjN90htRNnjEXBVlkqJsgUJmk1
            QFxqsicmJ/ThC2jnqCeW5uy/w9FBS2gYMfTHNKRzrss3yerk3R8Z0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSFRSdXVmRFVodjdrbWEz
            RDJQZHVTTmY2M1pQa21uQkNUWi82TThjaWswCjF3YWhNN0hlZCt0dFFsNGhxM1Bh
            dG42UDg2MU9WQzFjd2twU2hSTDFHd0UKLS0tIFJWbzNqOWVleE9Wb1VOczFFcXBC
            TFFnbk1XWEwxMUdXcDRaZCtVVjFRMmcKY5QDlZ0wM8PLxoIuz2UFVNvmzrzBu37c
            XzcyoPJPKXyW3tYQbjFn7w161wRJSlrpCU0ode5QITHOUuCNQmsASQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:NwgfMlffvlm3ULy48qtvrZkR3xJrF/WG3+edG/V6NqoqOjPiocqFqkiIITqLwBI6q4VF8/15vsvEWc1gbAEiJmqyKQTZrQACRy53HOcc08OdFwEdIoTHcwWusUP/YRi0/6m/lFuHJqzrByMBRiSqj5qetcqGIhbUZqNOMUoRauc=,iv:WnI1csp6W9IGdA8Q7zBQbPHSYEn/lVxXbVIfp+QCAV0=,tag:JXLRlm49np02IuB2e59nrg==,type:str]
    version: 3.13.3
