apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
    - namespace.yaml
    - database.yaml
    - application.yaml
    - ingress.yaml
    - network.yaml
    - database.secret.sops.yaml
    - api.secret.sops.yaml
    - web.secret.sops.yaml
    - worker.secret.sops.yaml
    - tunnel.secret.sops.yaml
    - ghcr.secret.sops.yaml
    - backup.yaml
    - backup.secret.sops.yaml
components:
    - ../../components/backup-job
images:
    - digest: sha256:ca45aec5f74d2902dee1cc0276bf6c7731a0d937057bc9399c26ef654e9194a2
      name: ghcr.io/fredrir/portfolio-api
      newName: ghcr.io/fredrir/portfolio-api
    - digest: sha256:46e02e43ad85da625c83e401476736c42536d4c98a2b87c52d269267679d8513
      name: ghcr.io/fredrir/portfolio-web
      newName: ghcr.io/fredrir/portfolio-web
    - digest: sha256:6910de04d0709140437236bc467043f3cf44764adee97d4786641efcbd5332e6
      name: ghcr.io/fredrir/portfolio-worker
      newName: ghcr.io/fredrir/portfolio-worker
