apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
    - namespace.yaml
    - database.yaml
    - application.yaml
    - ingress.yaml
    - network.yaml
    - database.secret.sops.yaml
    - api.secret.sops.yaml
    - web.secret.sops.yaml
    - worker.secret.sops.yaml
    - tunnel.secret.sops.yaml
    - ghcr.secret.sops.yaml
    - backup.yaml
    - backup.secret.sops.yaml
components:
    - ../../components/backup-job
images:
    - digest: sha256:cd271ffe5bced1c0b1dde91c195b313905791e445701a7b4ce3c7f5f147e71f9
      name: ghcr.io/fredrir/portfolio-api
      newName: ghcr.io/fredrir/portfolio-api
    - digest: sha256:46e02e43ad85da625c83e401476736c42536d4c98a2b87c52d269267679d8513
      name: ghcr.io/fredrir/portfolio-web
      newName: ghcr.io/fredrir/portfolio-web
    - digest: sha256:a470e5f5ae0fb87071b6b8750cc4e4951b8c4de3c0d67d1ebe3c360ee521a1c4
      name: ghcr.io/fredrir/portfolio-worker
      newName: ghcr.io/fredrir/portfolio-worker
