apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: portfolio
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:CYH05kTeVNVf8vtZfduM0/6jC5RRKJpVhuWOBJcDkRWrR2lWPr/7XaVxcH22I0E42Ve+Sq5/7Bvyq/n50BpB1GMkjf4wBTSTMCSSB9j9OtNSsL3C/a7BSOSbNQTcqqhhEGTzvEVUe7ApizyJEbAJD6LLFL+echDvdpTMPygK460eeaVGHPQWVd78DBOOnrM6d/ApuVZnjjlI8S3dI13kAyfock5ZczWzNK/Q0GILNNTqQipSEHCZeL6mxjzsDF5PjuK2H6PTSJJXkJQJZ02LR7YtSOBu7PsI6YfYuZIGglVJG34OQzMQtqDOJtP6vQtA,iv:gAz5FVL+Bp0VOvTyd8ZNuzraxKFB0JOYo8PWGnY4WE0=,tag:p4sz1IFkitKAJRitsI+3FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDVKcklKd1l4TXI4emkv
            clQ2TFpnRkQxWk4yYjdtd2VaY0FTS3FUYkJFCit5cGFHUkJjQk9oZys1L1RZbzM4
            Qmx0UGFYQXdEYWpxRXRYZzFkd1lwdlEKLS0tIEYvM0Rwc0ZXQlp1aHFla0UyTE1r
            cUFUYW9jZmt6U3VTeXZRNk5yUDUvd28KcvC/HZGL6YeelOOwW7PkJn96K9qbYvT3
            BVjzOSlDdC938bArjbz0ZiYLviAviV3JlUcR5G2ABwSuFnA3pXk/Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUlvS1NqT2c2eThKbWp3
            cXBqbktQWG9DSVJvNUw0QXVPUThoTjE4U2xVCkVOaFV0S0FUWGZvaTN0ZjlJTEZL
            L1ZKbm54VjVNeDZFUzczQ3dPRnN3aTQKLS0tIHhMSlZEMGF6ajRUTW5rL1I2ZjZE
            TXpOOEFlNWpmM0lqcCtPNEpVNXNIK1EKztSIvkq2ywIY+Jaj7ix9gnZwF/yi0Sbu
            aXhHkKcKQ/BcViVEvN3pk9VEPj8Jtxnb2KMPwanP9c/6dBs3zaJqew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkFvTU9LV0VFVmxkQnRD
            cXJDZXFFWDQ1K1RDTEJBclFaREM5L3d4R1M0Cnd4cjE2Vzd6OEZiejNKWUI4dlRR
            eDlmNlpldFBQbkc0am9xeithUVkvV2MKLS0tIHhieDM0SE9zYkZwand2clF0QXJP
            Qi9RUXdiQUtRbXRkQ25ScWhqR2FmUWMKj3gdQK3/g7OEiOEmQnr4ffEqiyH0FF9s
            uB+9OEYoj4WoGD/pWog0vGVJt9ykz3lbK7WzkzpEkwZLghjxSjsUPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:kbI3o/IYxwphIsQbvOuzdOVwBP/9ix27dspgSTu/voaQrdF4/BanUeLL42H8ZBnIjoh2U5cM+e8PKtXIJOEhU4pKgQV9+QP4WHC76XDbvTqFbhckg2ra3iuH0vcp+IAEiMRHzqNiurnwYMznppeu4U7kq8E0ylxSxHIQAbhMJwA=,iv:p985sy9eOnvDSf3+5SEJGBVhLcKohc/vWMEexWEKoas=,tag:dAEuFvUZGT0/axoM9KZRTQ==,type:str]
    version: 3.13.3
