apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: portfolio
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:0qDfkKeCmOeLJrs/kMwIHmXfp1PmYFKs4dyYUzIFoyFt14sbjHvJ5wb8hWPaIlvbeWHYios7idnSYFC+UWRVGFnj1M460dD1mHko2LE0DGIVe9ydHQRVGNCYVv1o8yB3ZHkjt8fY//pfmYXDau12FBEmpWxqjQ7LANpMRC6A6IoK/uR5fh0PoLRzFtuRyG3OGJhqEFW7Ucjwo7TfKBZJMEw+fNCfe+I+HIn0J7s+DKcKLAGjWYVvGAi34mUxTscs8oORw+cHltEeTI1EM9NzUpcQomz8/3I4Or6h5MavCv6UKNko4YQTTxXatpuf6cL3,iv:gAz5FVL+Bp0VOvTyd8ZNuzraxKFB0JOYo8PWGnY4WE0=,tag:C/7ILd8cofPkabPujFwQTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OHFMN2lENlpxd1ZwY0J6
            bDJsZS9iUFp6eDZMeVgzZ0NEeWVJVnBJandBClZ2aEo3RDQyTnlwNTNjaXJSMTJj
            L05lbEJiS2ZDVXNyN2FtL0ZPaGR5UFUKLS0tIGhta2tmRTVBQ2dYTmdjT1A3ZDA2
            V3ZjTW1YVnpITjViUlhYUjRSTzlSY3MKhmcqboYtRIKXlcnzlGwFAjpzf4RP9HlM
            vYCld9ENsvw/FEj5z8+PTaXUzdZMf2hb6FGghN7EChOtWW+5ZJly6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ak1LVUtZT0hZd3pMVko5
            eGx3bE5ER3dIQ1A3RUYwUVplMWQvdlNPWTM0Cks0c1JGZ1VrVTZlcTVHUFlMcUsr
            QTRVU2lEMjNGelc0bzRXKytjM3ZpelEKLS0tIGNKWHhnZlpuMmZOWXRkTzlxSzVK
            N0tWRDFhOUNOSHVYd3VORksxR09NVlkKxUzkRCjohjWpagAvCzeBKWoBMo36NtgA
            MFi65GjwNe50sJTHlwrFENVb4jDLOjPJJw8LxhmYaWIFKztHjJ0N5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcXRqM3lKNkdiTW5GUGg3
            MVlueGgzSzJCWEVnYUhWd3F2bnFiYU9ibDJRCmozVk5pdUJ6bTFXak1QaHZOc2VQ
            QkFhMmFpQnd5WFVSajNIcDEwc1Z5M28KLS0tIHBhZFdKcktCN3JveWlsSGoyMDBl
            VnI0REJhbEcyUzlPZitKUCt4Tk43MHcKiylxRXTRjNvMX52Hf8UqOyGJxyu1Fshd
            irs+hY+teg6GBQKPaVNJJbYvUVWGNMEG33RaxLiWfFkx88huq4QuEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:hte2b+0BTzl67dh9er6el+7+dOC0Zd1rzU5e26Y7DK1xf87aDS23tNtN5ARnRflF53ZHMR5SskkJQI6oqV6RyeHfeVCHn15t8RswkdV5utchjjZ3rLFkxSmx4uot0p13BnBB+NtiexbGm+TFgtd95Oo23S/4ebGnNJ5m/w4QE30=,iv:PvlwAD8DQIXi7qVbzhr4pfi6n7qs1Uzyvyb9upWBDOE=,tag:51iUa92kbBmf8GtN8KutGQ==,type:str]
    version: 3.13.3
