apiVersion: v1
kind: Secret
metadata:
    name: web
    namespace: portfolio
type: Opaque
stringData:
    HOST: ENC[AES256_GCM,data:8rfNtnd5Fw==,iv:jl9/eLvB8OWHUA0HYzb/Xxh4fKLdKV5xSjdH+K9yLj0=,tag:oO59hzg6xaWGbwzwQXacnQ==,type:str]
    PORT: ENC[AES256_GCM,data:Zjf9fg==,iv:j4BlWaaXz0DNUZc8oNVaCGdO0ft2B8O9+IjmfFnFy2c=,tag:+oub6pv9v/uFLFtdQ1v7gw==,type:str]
    API_URL: ENC[AES256_GCM,data:PWJ7Vn3lhhwZMwNYF2bi,iv:3tk3MudvaP/w9fo9rNOtPxnctoOnVEPMwBWlxP8Ux/E=,tag:6CwLsfinKSWPCUJ2v+4lDw==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:KLxIehqicJtGztOIw/O1bW2GNR/R8eWMfBdZaqWpQVCtYpsLOqdmLNfEZ0zwCMlp,iv:4LWB9dJeQzswB9WK9HyZoD/1UkVEOicXk4q7djTVzj0=,tag:lrX8emluOxUCY/rTU2DnuQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:yq/31kLjBsM+ig==,iv:nkRoMVlJlPVK+l4NuuaHjeDXdVo4zJzwoqTqTD4E3ns=,tag:q7Un3CKYa3gmVCVAXchvxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaXJuSHNpZWRnQ1BUb0NU
            Q2JQWmdYVkdzcUFXYXgxeWhDYVc1WGtydkFzCmc1S2poTlRnd0trWCtRVWFHNCsz
            V2NrS3hud2ZJaGJ3K2gydmRBbitKNGcKLS0tIFh6bzJldGYrc2Y3NmhrYVFTTkl0
            QmswQllTSUdpTmpqRmtYMUpaM2tiamMKdAf1CDFx8VTNgNDDhIv5sGPyiCdjWq3B
            rjEprNQ1vXoWc45zP3mW3U7RU5VwPvFk2QBrLymMIKha+TGgqx27kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VXVXbVdiQ0QyT0VqWWxa
            d3ByclB1amFLejlUc3l6V0NxR2d6YTZMcHc0CjNhYlVmTVdBYWt2SmJUZXRCaFZM
            eXRQbitOd0RYdjBscDhubkJBZkgyUVUKLS0tIHMrL2hwazNQdC85d2RkTUhiRFpD
            elJaTzRQSXRtWm8wSzl6eTE0MzNNaDAKriII6wm7tRLqqC8+cflNvvFvqR4gFuyR
            X3HpLUQbNOwmW+nUn4a9c15s+SxJjP0TCdUHidhUdJtopwiGTlALeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLK2pwcG9nRjlnWERvNHI1
            REtsSUJibUNFOFFlZENBWHhvaWZBZWlPQXhVCjZ4RkQ4cm1Hb2hYYlRSb0lVdmZY
            SzN4c3NjWGdnQUVvQmEyMVpVc055TEUKLS0tIHlTRFF5OXNzVSszZGRlUUpUWitI
            R3MyQ040RFdTcGdBZnU3ekVmWEMxQTAK/YL+R2mSHX8hG/hcv0d5Xe9fwUarUma6
            gEEnQW9h1fQ7ShUzfbQkDLNyoWw74beTFrJmdtF6DzxYXM21hVoJqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:3DpmgqxGCGYaqfBgNA5f1uBZHBK2yiFPcT7ZqYvvL60plLV1pP6goKSgLFCL1v2kx6RrR2FWmqcbUn0tIIVZvtS8z+4j7dI+tsu+cfaLvI3CMJI0qQhMxhXmC7ld7H8RfiMzCeJS2BEADqQHgQy/UiVr2iwa+TLpnk8Mm00KR+A=,iv:2PNxxjYMynqOTdlz71Qe69dbO9i37yC/sVNNTn8EcBs=,tag:xS2xC8wPWVfWQH4xAQu4ww==,type:str]
    version: 3.13.3
