apiVersion: v1
kind: Secret
metadata:
    name: web
    namespace: portfolio
type: Opaque
stringData:
    HOST: ENC[AES256_GCM,data:GFx6tHYUxA==,iv:jl9/eLvB8OWHUA0HYzb/Xxh4fKLdKV5xSjdH+K9yLj0=,tag:rDMcMLbTVAvmqIDAB7+xAg==,type:str]
    PORT: ENC[AES256_GCM,data:IqC/Qg==,iv:j4BlWaaXz0DNUZc8oNVaCGdO0ft2B8O9+IjmfFnFy2c=,tag:aSgd18B9p7f+Y/IfjgGMZQ==,type:str]
    API_URL: ENC[AES256_GCM,data:OL5WI4Zfoewc5PnVydbG,iv:3tk3MudvaP/w9fo9rNOtPxnctoOnVEPMwBWlxP8Ux/E=,tag:veI0oMWQKkHLzqDzRjLysw==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:wtIm4szFWBbQ4Y1etjDXuiMk5JW6d7O0zua2DQfoC/N+HzcgbODNbZbf16NLWaHh,iv:4LWB9dJeQzswB9WK9HyZoD/1UkVEOicXk4q7djTVzj0=,tag:w5lg2X/gaFh8lmaaOgtueQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:1+wbL1BQoN9SqA==,iv:nkRoMVlJlPVK+l4NuuaHjeDXdVo4zJzwoqTqTD4E3ns=,tag:dmiuKvpncu3q77Zxg/phCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYlRZbUR4dkxwTkIxVHBG
            dXJIVEgzOG9FcHc2UTkyRUROZ0FaQ3ROZmdvCmViaWs3V001Y3VlMmc4cUpyMkNz
            bytUdE53OGZaeUNHMXpsUFlKcFlkakkKLS0tIDhwTEozR0lPVDJLR3I4N3lsSDVN
            clFnZHBDeGhseDYyQVFoZUJBMysyeEkKjsJsRE7yi3TGpLjN/GToweKzRkV3pOxA
            2QysjLy7IK/3ZsEVA75UhbfGYgYFjbHpgBZeRIqeBE+7BGcvxZDqTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU3lBV3lsUjErMTZySlhQ
            YVcvbXgzZ0JJKzdwYm15b0lJdEFUMW05M1E0Ck5YelAzY1RBOWFGMlhuS3kxT0FD
            a1ExOHFkWEZ4SFplMFhoZjYxamlZZlUKLS0tIFo3YlBRRG5aTDMzczZYQUxkbDVz
            ajZlRmFWTFJnN1hNSjhiZTdHcWhJT2MK4Dader+8ZUzQ9cWaBa+R/T14kmdUSmT8
            67ZqqUKW4i7OmrGvXEFGW+GGGu62ZKJZl8+lbuUwyOW3W8U5G2ElFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UWFWc3VNZnU5T2lEUHJK
            TEpQMnhwRTN4a21OWWErZk04cTd4eEMxUGg0CkpESm9mSEo4dG9nYWpGbk5yclpx
            M2JFUXZIRkxSWjdOYW5uY0txMDRkYVUKLS0tIFVoNXRNR21tWHpiVytiQWdhK1dv
            R0RmT1g4Q1RycDFuYWN1L1pOVm9IbTgKSsRLrVN8N183VoPwsvWiDeGtYe1oRC84
            4ofP2tD/jyOiO6lmyU4OBQWAr1mb6l5zc0V2tLK0Tx//QbRW3f8aLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:xHnvqEwmSp+Z5Q19upySybGdz21m4n6rx0iA5YmWtu0muyB07Y0Fs4YMhDH+6fd4Ywhm7e6qBAMYrtZeNkJFEysxIWzIqpEbtQmojLDvg60tfSIN6G83vgA4UJyZK89TzugPbzXws80gKGiS80cvOsAsyifrsERK6PYeXY3Cslw=,iv:QIXNdt37qmIMFL6wiLBAqpx22toop4CzU0Yn2ukCm1g=,tag:HZyPZvjv0SmU1bMRFAyLkA==,type:str]
    version: 3.13.3
