apiVersion: v1
kind: Secret
metadata:
    name: worker
    namespace: portfolio
type: Opaque
stringData:
    MEDIA_QUEUE_URL: ENC[AES256_GCM,data:qa+NRrR3Ml6DVVvFaqwxwHGgCtZGY3d35TXzkcrdRhE7GqzcTpKdum4gYNo1d8UTn+jLyDvOtBDZ72eoHVXbmH8jlzr6jT25QPWGeMMP4TZNs6wOkW0m37qe,iv:8IBQR1I17omkK1lgT+Wl5ZR2OHXFlo51zV5iEog/bu4=,tag:w3MBw8Sn9d6vVmUjg/Y+Bw==,type:str]
    RUST_LOG: ENC[AES256_GCM,data:bwnfGA==,iv:+dw5lbH8juttkfUofKP+/knEU4OaPvTyr/4twDOnrGY=,tag:T8kGwDE8cvoteuygsKUl6g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rSD+veRbUSOJXyAJ57N0qVSPwn3USuJm8SFFle9xmlXOPhuvYwpHHsbb3zH/Dt71SpPwmCoiNS9ot8pEkrlZOIUfqU8FhMRhjZNXsTIB/klqowXxU2nvJHvkHUme,iv:JT7+MVLt4X9YvT0xjLccJYko7cJwDetr4n3PjbDZIWs=,tag:OXSGnLQYIg/y/YUl1JXYkg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:shoAHPntdz5CVQ==,iv:sBJmnbJoqGOFI9fAZ7HMFUo9cqXqGg6b2XEzH78vTaw=,tag:ORtZcam5CyT9rPFlOEaTBg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:J6EeLqKCEytx7O1LfUsQVj3bQQg=,iv:L5Yo3MpQKBaR/glGbnpKfT15jI5HOKfQFIOOTe7yr1g=,tag:ma8tKG1meuLZhkapFhPUNQ==,type:str]
    MEDIA_BUCKET: ENC[AES256_GCM,data:9e7YAP2GbISKk/npgVbGNCynitx/d7aGFaP0S08=,iv:2QG5TfdPZGR2zUrM87YNh6ijqBxm0vYhoW8mPWU5Zb8=,tag:kfBV6+OmUc8QfYQoHzrCRg==,type:str]
    SSL_CERT_FILE: ENC[AES256_GCM,data:63+6WeblyWlczoqhwvb1yEhiEnSz03RCXaq80IXbjE9tQg==,iv:AATNEMFFEx9BX4FIs3Od3utu+S7euvr47SfDU8kS8FI=,tag:qgcGESAuLTq29ksTJzvdUA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iHdUIDht3pKFizTJXZlLY7RTJqAh9pD/EpH53gjr1UuJY02zuPnn2w==,iv:vm37PXl8Y9QxnyVZDd/iWWnD2KkyscejwDe/P9eXKK4=,tag:Z9vaoTr3n84ucrBZ7S9DhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQis1SmM2N2FhMlhjT1pp
            UGZqVTFLbWJXZ2ZYWWtaK3plRUZKZWZlNW1jCnVVTVhyZEFaenV3VUFqNEVuT0Ur
            V0Rla2Frajd4VmZrT0J1cEt5THVRZG8KLS0tIEF1UG5ja2liU3B6WmFwOGIzOFpZ
            ZlAxaXRXSzB3RTRpMGZ6L1BjM1VGck0KCRnnxcoEsZgdoDnFYkenL9VofrRqQn3a
            UQh08GmlycaTubhwDtwRIo7kZRCpE5QOsJWtwSj6N0aB1mA4L4YDJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRWRLS0NxeEI3Y2xPMFhs
            Vko3TldUakdUSTUzQ3JlbXZsWVY5RlZCd2lVCkVISDF4NXpIWW9ON3VuMjlPZ2V2
            aTc0OTR3S1ZXNk1ySnRIVytuaDMyRlUKLS0tIDNwWVltQUh2VFAyUmUycHBFenVE
            aGd1MVdFTFQ4bytOdnJIRHhkNnI4ZUkK0QZYthO1BU5eMT/j2+AyCKP4YR1eTsI1
            ydmlhqjqrs2bw6P/Y8+uGxrfZjf1j5fNxUQSPz1pND5HOnfG+awv9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UzYwQ3BxYWRlRlBiUEp1
            eldzbEdvSmNkUFpFSlk2S0gyZWc1VnJsVndVCmZERmRZVnJxc2tvdElaYnNHSGFE
            OHFzdkVLbFJQKzE0ZjhhTjhOeWp1QlUKLS0tIDdlS0NvbVdWMHp2NzQwd2RZTWpJ
            YlJoZ3kwQVV0QU9XTHRaY1B6UUFPaXcKVlwh9wZxxjAHRMDRT1gkHQB5xuzSw/5o
            AlVmIjojULlf+MV1AlF//IkLojZUa12BT/XMdxtb4Wu5rHjfDXmTtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:MwGtiXg4VZoWd4e/rTKw2K9pbpkGy/BCR956PCRaZujqSAoEbOy2UC0I5OZKawPH0ZSqyFNKArxhEsiJUvkbrRdjVWOitXp9hGWmnAAWeCnXFnJt8yz4Srg72vHy/KWZr6evun8VbYB0/SVcjqitWeJ+SasvDXlZxXM4yW02rbo=,iv:/VkOGeuDvB/7NEY97sPdOlxS4ale61HNSWKCbuEM4CE=,tag:z5dfcDDash7hXW5oVhdNNw==,type:str]
    version: 3.13.3
