apiVersion: v1
kind: Secret
metadata:
    name: worker
    namespace: portfolio
type: Opaque
stringData:
    MEDIA_QUEUE_URL: ENC[AES256_GCM,data:85srfj64m5PcsfR69Ne4neVW852oQ8XH4AdEqyCCzdhmJ5goZGFgolnTbYw6lCd0YwUQ1b6SOAo3aVA4Fud/BHxOzVqzl0hVT63EGswWt4TCq/qUal6Fj7un,iv:8IBQR1I17omkK1lgT+Wl5ZR2OHXFlo51zV5iEog/bu4=,tag:jheRNyMBh9UtpviDwnJRMA==,type:str]
    RUST_LOG: ENC[AES256_GCM,data:Yx95tA==,iv:+dw5lbH8juttkfUofKP+/knEU4OaPvTyr/4twDOnrGY=,tag:5BrXUpIraY726hK150fiNw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:aF1Od9ReEMLhDMwK+8d1OjmGNCVelzmOQ1bWLnJy1JJBORijCUbI/OT1WWmFGaIy9ealALE3yN24Wktalp09yrGsKY9Kl2pmrSRhiZ3i+Y2dgQiuPOQg2UbT1gW9,iv:JT7+MVLt4X9YvT0xjLccJYko7cJwDetr4n3PjbDZIWs=,tag:KvfMgufoi3M0KmKyf5wGgA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:6iwwicb8p/O8rA==,iv:sBJmnbJoqGOFI9fAZ7HMFUo9cqXqGg6b2XEzH78vTaw=,tag:ERWYtjIq5i/RO7oFx4tr8g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CX1Am8Ir6CreDqaux6OUtionfmQ=,iv:L5Yo3MpQKBaR/glGbnpKfT15jI5HOKfQFIOOTe7yr1g=,tag:GPPIXSTOjOSoC/8zLWLnlA==,type:str]
    MEDIA_BUCKET: ENC[AES256_GCM,data:a4Vg/UsVymBbQXX1F+CSsVsEbMZo9SQP8g6lEdM=,iv:2QG5TfdPZGR2zUrM87YNh6ijqBxm0vYhoW8mPWU5Zb8=,tag:OlsuV5eA27qGWYk4xq3M4w==,type:str]
    SSL_CERT_FILE: ENC[AES256_GCM,data:+YzFTJVyium0Th0Tp+4KmpePwjnjMXRPT1njb9651uuPuA==,iv:AATNEMFFEx9BX4FIs3Od3utu+S7euvr47SfDU8kS8FI=,tag:US02HICEecGcPJEBo3sheg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:e+kRE9q151BEGJEY8rw+3OE8+n8HAd8WrqSY+3SU1r6SWu0jSGRF9A==,iv:vm37PXl8Y9QxnyVZDd/iWWnD2KkyscejwDe/P9eXKK4=,tag:kHRTxUJjTeS0qOAeiLK4fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b2ppc1NPRHcvcFdMZy8z
            b2dtQVNUcHBsZjd5bEhIaHg0K1hZNkt0djB3Cks0dTRXcFFONDY3UW9iMkdETXcr
            eFRFTjN3VWZrazN6cEk3UmV6NUI2eGMKLS0tIFJSWEdlMmgrTmZVbkk1VGRJVWNn
            OEJWWE1DOGhQSmkvcFh6S1ZjMkpyVVUKOxXc23bcB6sdMB4GkD1DD1lJ91uGh7pX
            OugXqvCt6vix5piyknwEQwak8fUh7i5IubOSqXKhoCz9RNqcor8DYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZGhpdTNCUk9CK0VqZFNP
            Sjd2NmI5eVk3b1ZybmxpYWQ0SkZqcVFkV1JzCmd4YmxXMG1wd00wMHBnMDZVR2sx
            WG10cUV5QTE5NHBSeGZhMVZtUkpjVjgKLS0tIDlYVXc3ZnhBR1Q4R1FTckNOK3dE
            bm0rKzV1blI1ZE5Pa3NNaWc1bnlhT0EKAjg5VuxoRYwn25iQbrYQWp7rodW/cbkz
            wJobtnokFjkRNQeD962TSmsvL3DuIuh9Akc8Glhuo6dPuSLR2SvRnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaamRoNXFJbHBLM0hFWUNW
            T0J1UXFMUFlDSW5aR2VZaWR5ZGNmVzRBUlFzClhiNUcrMU5QQkFBSzgyVmVLYmZP
            aFVBL1FNeDdiZFNDaE5YWUNzdCtMaHMKLS0tIFBBSXZKMDU4dkorNmZLUE1vVDZv
            b1Z1Q1VVNVEzYjdDTTIvYThDbkNrMFEKeXb9otXq1nA/TYIUN8cwOTRCZ0Lu/HoL
            xf0qglqc80IqGwPiLbCKVEvhY0AZ0rwGZ8iNmOqGCjLtq6qNZARGNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:12:59Z"
    mac: ENC[AES256_GCM,data:H9d87Yb3vN/HibIcETsfs+u5aJ7GQGrvhFhkIarhX63IcvRJCi/rfrutPlbZJ1PsyoEwuPtaKAMU308qsRc8qYlXnOUH9HazLziaUZ8MPdI/TFyS+DWH6mieXtSofGBK+OD/YkYgLG7jOpqxrdOCvkd1qFvzsIR0/Ss8bY55H4M=,iv:KFhO5JfEUm0RcYUnWtEKpsTlC+G8AdJ44f2XXBbe/rA=,tag:CF5ooLTve6Werkf5k3IwnQ==,type:str]
    version: 3.13.3
