build_runner_repositories: [infra]
build_runner_owner: fredrir
build_runner_version: 2.337.0
build_runner_sha256: 70920811a4f8ad4328818682bca5c6469c1c942fab52448868071d0063816613
build_runner_labels: [dagger-amd64, infra-trusted]
build_runner_memory: 2G
build_runner_cpus_percent: 200
