RESTIC_PASSWORD: ENC[AES256_GCM,data:EqdOmMJTzi/rUbYID/5e8xzpZkxepaxO7psWCbG27SP2jgfiSbMRRQkraiKelz8nTF6fNern9+1l5NRJ7f2Y6Q==,iv:d3T5Ku8OZ/p7XylJbdVnVbdWToK72ruOFpHluOZJxOg=,tag:ie9fHH2x2qwt50hffl0wIA==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hzDrKZUVV6jeqfUQXE8XZ+kESiM=,iv:GQYPDyetdxY5/p+CpbZoKrYC3BCOa1yMFCRHLmCJt9w=,tag:kt6RUzaW+qhxf7BKLJZTlQ==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qtmnkswKNK9bU5DEDD79G7U6SzITfSnfNaHynRQDYd/IZ62VmAFi9A==,iv:aXoXELSgPoREp6sklxiA1teYSvxUxEcYcVUa/yWdTDE=,tag:F4DDQFDZu8mECYG7beVILA==,type:str]
BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:zX/chv6D5cqjaNCHbOORvvPcvLRvRIF0RZnTMkSd+6WUaxEXhm0V9E3ae+9zVQCIEDBCWTZ8qGlD1ze9Re7hBw==,iv:lNvK9b+ohW1MfZd0Ex7oUn1nkXknFoWg7Aj6oEVT4lo=,tag:r3D7GRlYz9o+iMUMPTE+6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK1R3ZjRhUXZuVXNDdzVM
            L0d4TS94MHFRbU5lRFFydm1SR3hmMXAyclF3Cm81OWdLZ29hUTVDL0RjQktsUzBB
            MDc5SjYvQ0hqVUJySU9wenNsYm1mNkUKLS0tIFJ6MWJISUlCcE1QSVlsRW5hMzNM
            OE9ycHc0bXZxU011WFNlcVNVRjFJTUkK6sf0KdnHV3wrSXJ1tynTECGh5nsxaEbE
            TfCTEbMPPt0+nkWh1L/qARiew7qXcToprKdFpHARxpWfUlbisz++gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a1NpTWtxR2dYRXBvTTRV
            M1ZQeHB5b1NCOGxDak5McitZd2RtMjRjL3k0CmlkRnVDbWtVNHhZTzlWaUhZNEFL
            d25lZ2VCbnZDb3kzSDN4Vlh0RFZmdWMKLS0tIHA1NkNXT1ptVW52S3FBVmloc0FU
            OEhyZGZsdHQvNXptZ0tkMGxKdnRzUDAKzh0fGdHr6u9+HPpVgZOQSwg24L3zwpEL
            6wrjim+4kmmusx8niMM/vbV9LTeoGDOqSiO6wIiyvtxb8bI50M06uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenUyYVQzK3FDZElRMzlB
            MEtQY1VacXNlNXZYcWZ4NmpiK0ZEaHE0M3lzClVUSDlQaUtTRGw2RTNzTGI5WjM4
            RnEyaGRBbEtxSTBYaVVXbWMrQkVGS1EKLS0tIEZXanhjd1Q5dUlrOVRBV28ydjZY
            c0lsdndXemQySDk1aitNU2tDRlBOTlkK8lTMzGHo2DpcIJqRhbIW2qL/7uInF65c
            aHw3fiSqO9hrM0jCmXW7lUp4TSHCZcOGTXfchjcihANS5BFoCafFcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aw6w4ttxk62pxjgcgv27nqetekjxmrw538j8cqmmql4wa0577ynqxvs52d
    lastmodified: "2026-09-26T07:10:30Z"
    mac: ENC[AES256_GCM,data:ucjqBHar/7w6CadmyKqPktz/sao5B7mrXYEAbJbpq8rVKiTgZ5LiJnYSXixqdZfakRPq9geu7yK4st9+FBUoN8BRum5W0/8yMqNgl4PXJdwFZfjg+HxeEpl8mhfc2Jp51wqMoLE415ZAbsHCuQAD4faY9kOcRzWBotz4ewbQGDU=,iv:+EKUj8d2aSJVbyetyU1ppaSzHfOxXyaVCTWmj3Vy8eI=,tag:m4tz+yMn6rn2sz6NlHY4fA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
