[hypervisor]
[hypervisor.qemu]
path = "/opt/kata/bin/qemu-system-x86_64"
kernel = "/opt/kata/share/kata-containers/vmlinux-6.18.51-202"
image = ""
machine_type = "q35"
rootfs_type = "ext4"
vm_rootfs_driver = "virtio-pmem"
rootless = false
enable_annotations = []
valid_hypervisor_paths = ["/opt/kata/bin/qemu-system-x86_64"]
kernel_params = "cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 systemd.log_target=console"
firmware = ""
machine_accelerators = ""
seccomp_sandbox = "on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny"
cpu_features = "pmu=off"
default_vcpus = 1
overhead_vcpus = 0.2
default_maxvcpus = 0
default_bridges = 1
reclaim_guest_freed_memory = false
default_memory = 4096
overhead_memory = 256
memory_slots = 10
default_maxmemory = 5120
memory_offset = 0
enable_virtio_mem = false
disable_block_device_use = false
shared_fs = "virtio-fs"
virtio_fs_daemon = "/opt/kata/libexec/virtiofsd"
valid_virtio_fs_daemon_paths = ["/opt/kata/libexec/virtiofsd"]
virtio_fs_cache_size = 0
virtio_fs_queue_size = 1024
virtio_fs_extra_args = ["--thread-pool-size=1", "-o", "announce_submounts"]
virtio_fs_cache = "auto"
block_device_driver = "virtio-scsi"
block_device_aio = "io_uring"
block_device_cache_set = false
block_device_cache_direct = false
block_device_cache_noflush = false
block_device_logical_sector_size = 0
block_device_physical_sector_size = 0
enable_iothreads = false
indep_iothreads = 0
queue_size = 128
num_queues = 1
enable_mem_prealloc = false
enable_hugepages = false
enable_vhost_user_store = false
vhost_user_store_path = "/var/run/kata-containers/vhost-user"
enable_iommu = false
enable_iommu_platform = false
valid_vhost_user_store_paths = ["/var/run/kata-containers/vhost-user"]
pflashes = []
enable_debug = false
extra_monitor_socket = ""
disable_nesting_checks = false
disable_image_nvdimm = false
cold_plug_vfio = "no-port"
pcie_root_port = 0
pcie_switch_port = 0
disable_vhost_net = true
entropy_source = "/dev/urandom"
valid_entropy_sources = ["/dev/urandom", "/dev/random", ""]
guest_hook_path = ""
tdx_quote_generation_service_socket_port = 0
rx_rate_limiter_max_rate = 0
tx_rate_limiter_max_rate = 0
network_queues = 1
guest_memory_dump_path = ""
guest_memory_dump_paging = false
disable_selinux = false
disable_guest_selinux = true
initrd = "/opt/kata/share/kata-containers/guest.initrd"
[hypervisor.qemu.factory]
enable_template = false
template_path = "/run/vc/vm/template"
[agent]
[agent.kata]
enable_debug = false
enable_tracing = false
kernel_modules = []
debug_console_enabled = false
dial_timeout_ms = 10
reconnect_timeout_ms = 60000
create_container_timeout = 30
[agent.kata.mem_agent]
mem_agent_enable = false
memcg_disable = false
memcg_swap = false
memcg_swappiness_max = 50
memcg_period_secs = 600
memcg_period_psi_percent_limit = 1
memcg_eviction_psi_percent_limit = 1
memcg_eviction_run_aging_count_min = 3
compact_disable = false
compact_period_secs = 600
compact_period_psi_percent_limit = 1
compact_psi_percent_limit = 5
compact_sec_max = 300
compact_order = 9
compact_threshold = 1024
compact_force_times = 9223372036854775807
[runtime]
enable_debug = false
internetworking_model = "tcfilter"
name = "virt_container"
hypervisor_name = "qemu"
agent_name = "kata"
disable_guest_seccomp = false
enable_vcpus_pinning = false
enable_tracing = false
jaeger_endpoint = ""
jaeger_user = ""
jaeger_password = ""
disable_new_netns = false
sandbox_cgroup_only = true
static_sandbox_resource_mgmt = true
sandbox_bind_mounts = []
vfio_mode = "guest-kernel"
emptydir_mode = "shared-fs"
experimental = []
enable_pprof = false
dan_conf = "/run/kata-containers/dans"
