apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-packages
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:vDVuPLUgkg==,iv:spUKtHJ2ajm6KCjslbAgU9Xb8uuZjyH9AcvBAWX57Ro=,tag:wuFEDogh9fvQz35jsGQPqw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:S87C9kcMEAKn,iv:+0xh49r/ib068lt9Y1TWyzjLLrJeHLWED+zIJCjdnyY=,tag:39y9snTyCqGKZX6qYaHcLA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:suGBhXg55S1uXLw6jvt15tMGF12fg5Im18nr20hy4k6M0pVTp/E/7Epr4UR56h51MhMIKI9B+ESGiZ0njJvYNY46lFjOklZ7FgDhQ7B1HMF8AGJj2/dtads8KFCydYPlLS4Oo7poI/DutrlVyeaa58jYHFCPwZl+U6QP7HXEioWFzUNFTi5EaWe0v8A8UX3uNz4nKbA9ums7Aj2Jz9xiJBGFp5upEnGKXlQkHc8cV3FaayfdoGb38DYN2XmIL6ap68QxT4Zu2I+hYfp+EshBAEuiV+ja2pQMXJOq2jdMhxV8WL/rHqSesAmHzGs0wgH3tAplHEBOLnFKNn/mpLcAWucyGxMunWNK323sFSG+/CR8XSQSXjy0EDrnb1QhgVAdjfKRvziqr2jB2f0T4q95SmhGrX7S9VxTwadg814mlDW1C9/Pm6YAY+i1t+/mWDz/Nf3im0aa9lNG/hkNmrOQikjHL5JBxIIFLNZBd67jkLwVZ313UeEp7Q2tDeTzboKiQiTo10BMA1MKalpP21eSUhbQFGcG/aH9K1Ut7+sRVtJPq34+3TjlQlg9j3GsTALMtkATMDb6nRwanjMRyQi78/Ws6M3ieziNuJjUKvSK2JpRCkGXQstoonf4lUrwh1DkbvY1nFDVvCGQAAcQ8lJRysB8eQOMjtT0Yyt1CMvCLgux6PxhpYDJZd8q20OvQrmlmDw8C0ksduwXfyee7vCMBvAyyuIHJq/ZDXlvR8UsPEgByVt2UcVacQs38lPIqdct8+ZGpYQQYON/N47AgMHpwpzOceNPKEsO1CfKnrUcjX/6UVR0U1DsKPs+r1r9j77jHAzxO8vnuAC0m1MLfqnzaOlSgfNQqkhLx+Aki89r+Birf8KbqHI5qw8mteyDEa8eBYwJnJXluNcz1kUnJJVO9nedGKx0aAkX8GsR0FmhCqzCQJ23TNY2kTcI0mCV6r1sUv2x1L0Auw4q3c/X2rCNepK3GbK96ho9GhA1LKH1bNhNud5O4J1O1UID+80KkcWJUxIKm3FHaRCMQPWPufF9WuKXwOhyLv50qv2vls4jksxSXmhhFPtevP73IbOI0SqPwm6Isdr+teCE4eX1BHHLnPGMHFTn1oz5KSRMd68gArpp93eKDvy8u1nFuhKHPBxPPlJdyJL/JGs9vYlW7pIIAHR+0J3aAVac9HPyTRszD/1BDY+F1gTAQtQ+SGJ3r+X7YTykTlZYnIohzU3u6yM5KKtxNBrUqonOmWg1WiREE3rnF9dLf8ppzNmAfQXZ713EfLKDX0TMbbO2afo12oEVs9MZXq5YJwXjSMZzCCCQGl9dl8TLiG/HqOZpuxLkBKaD8ubk8Z0qmDLrgYIytTHDHQybNLeF7gX++XATvrD8LF7khP5S/boGnu+EESEQQXXwpDFR19fJnnTeqmfoj0J+ADkCNbRPrQFxFn+RXQqM4nV7rDeGpr7lqEN4PXnXmyWWxJJF1Pycnx3wIcfp17hZyFyF3BdrzkLIAWETylGI0AGySH5917TqIpGsIvHsSwQdiYg2y9ryB6KVNVm/oaSiuZH6MecrGvW37O5hAspZP8MwJxwK0/jmVZlEM4FUDyngM9zNrweJ7A0K6bBWby2g7gnLGe8WK7aGwV6oecu8DN5pzyFbhB/nJTXho8B5MaO8PVCxPDdDIooC+zrUJXrdduDkh0J2U+j17hkv17Zpf7cMC6LOegP55wzz+2GImccqUaTbrgAukRQl85Vl9veT6ds+UkQtM0Wkk/EDzG6RXf//ZeaCC2FfnUP3HdLERDZ4DUtImK1vfIiY/ezoPXOwWsjdg4uCNc+eDHe5VfNFj5KPWjQzz8AmZHNoOK5INa1cCUyIQuDNyTH6ivFptlNtdbISFHdHJmNTgVAugcvlyGCh2nqiKM+yOM6gKpOlG05jppsAAI03c+DSJ0H71onZ/VQAGx6NCT9VdO9qKdOtQrUO0imoGYMmYUY6OOurZcrqxDVEx9jYYCXUUq0uzxrTd+s4RuUSGPi+KHZ864FjhxpEukvX4vGzmdxQhYVOtjyr/EsHaU7QBoAI+8yzdygyY8TeS7tsRukDfOKmja5x6FBrhwqluiQvwc2ublp5ei6SMC3ZRZYHCKCFCZKdsoWjxXU1xu1A807Qep9SOPTotSWGls+ByJl7cblcGDd43ilXbPFjY+4JweVNMnHlc0QPuhSfZUcBJZ4g42BoiiQf6AIUOUF/8pwa1T33sFZ/jA==,iv:Z6V7irUKskmwVAC0I9u3fLrRJ4oooVLiAMWgjKOIXTY=,tag:4Rc/DR0GczmymGQC9XCiUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWVZWaUlHUEc5a1R4NHFO
            TWU4eEcvUnNQYzc5cFdXNUhWRWFlY0lucVU4CjlockxPL3lPY1c0RDVJQVJldmlS
            OUNYUENXNnFvZjVvbEgrdU1rcEU2YjQKLS0tIHYyMzdXbGp5bmh2N0h6a05TMmRK
            YlFLTnB1NlN4R2NZRWxFOFdXZTBHb3cKKCJrcvZx4yEio58sQuIWdRP8r/6h55Im
            V4sQzh+uoiRlAOrvoVC5/2tog7yuf9acCf4QOUxNTJ4/82nfaMI/WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY0c1ZTAzQk0vdGlVTWhR
            dXRKQ055NnZrblhkeGt0SmdpdTdjL3ptd1dRClBZaGs0b2RwUnpGc2lFWFZ2U3NH
            bURqcXBCR3JLNjFyc1RVS1FlNlFBcFEKLS0tIFd5ZHY3Sms4ZkZGRzd0ZHVkWTBK
            eFJ0T1lzS2x5MU5QbDVhU2ZNV2t5SkkKeCjmNNWbs+rXz0ewg3NZv8SCRhgzxqqO
            wGq3XS0hzJ36tHFZEiDtynrjRbGuATUK98VuqxaAiol12K+itHxU6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRVg4MU9qWU9KZnduNmp5
            VkdlL3ZzakJCazVlam01OUoyNHpNcjRvVml3Ck5LV2xsaTR1bW9FdXdZK1E4Y2RU
            dGdNT0hlN0UwMFBYMk5kQjNsTUdiWFUKLS0tIHJJUlk2aiszaG80a1pOWGlGd0Zx
            OHlaYUwvazE4MzV0UVZPRHd6M2wzUVkKeXrVGuc14BP1Hg6ZUdyuHjNpvscMNRKG
            g42//j6vNDWP3KX0eu9Z9KUyMlxr1F+e+720BiGyPi4fzxMIx7EIwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:nyVYhM6UQe7q8E1pgt2Ng2fEACBDj7OZ8KxN4Z3PXkMgVnGrCsJTREtO/l0STRy788PEDj00CZE2+fJyq5QCNkv0Z68+iJFEIQxClMgcBrHg1xC/aXrKQ+bfA43/pB6w4Fr/83PneFnzhTlZwxl4IcyuWs/0DSMtTPSqTcenoqE=,iv:a8uSnE4f4lNnsq4lmGuQ492mvy2LVBmuBox3r8ZwFI8=,tag:/xeUSeNLZ4K8pyUeO60hoQ==,type:str]
    version: 3.13.3
