apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-packages
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:rTNl8xA45g==,iv:spUKtHJ2ajm6KCjslbAgU9Xb8uuZjyH9AcvBAWX57Ro=,tag:KmB+NawZBLWbG0BBfvynTg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:1QArr/zm5NAU,iv:+0xh49r/ib068lt9Y1TWyzjLLrJeHLWED+zIJCjdnyY=,tag:EaNmcDrsTkkj/ciozicUdg==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:gyiluzdc2iSqMOlKuRNu9aCx07GZmqgHFhF9W8aDKTDHbHjXUbxfA9LO3Pn8xc4UvugRQD4feT+5dyg5uDm3Ek81e5PGQlsgBfwfCvTY3Q0exzbCJwABnswLaxVYJQH5WOm7ysOz+WI4jdc+jepDke7dqsOeeiKSlnbFfgSHcR7uJrU09eEy22yK74rm4iTGuSI/K3mgfYqi4isT77mxHUAkkruy1k9oPN4AA9uN2zbKwz1hmmgOGQq8casThwBHyZKF21s76KMdhNZHRJBpZ+F8R01czR2eDs1qEe6Qb0AOVQ3ENNugnqAx6c9OuXMAsJ7lCSxNDsJQsYeaLyiFBdkMTGi4RQJKVVNSGwVp6QqHDRUx1wnXmIM0gtULW6pvPFM+0fSK43uWbDRtBVLBMBtFrKxJeUtkVaC+vNK7dxDSvBcXyKpgomWZG069UYVQCVaHfDLQ/XeNGJ0QH7JcLMXiVne1Y4VjolAlqMGwqFoXnJ2jIKfWi++7HKYDJCKCE0tTaJhHghsC/3US0vZG3e7WCcE21E9o/yyDsqf/Osl1xCKPwgf4NoMOIK1vBQ3MfeiB98avxDdsxFIoFHEPvq5cKEhFaVZBvdaCSt+/2jUNCipmKob7cqKuhZqgNifKbUTbxi/irg/cEfhP/ZS85gMrxslQO6GtlHWVxpRqMdpj99ZRaa9zhQtOUF3aez7Aw1y4NSLYsa80w6TjHM0rd3Sj+XvNXy/+xFNgDz8iFttk27nlGbgwx0w/zfJWQgVAn/tPloCIdj9O/BjZgQmI3KRFBNFo0pcrY8IbeDHCA7ptpUMXiFBwzItGA/f3jFFvXPRJ2rF2XWDISeQoTvn08EPtmkwO7stH3JMSLBtu+GS50CEwN6yUcJCJ7GWR98mrJJwqXPppOXjMdvuFr0iL6XdRwqtCLWIIpqpVibuCvhus3DJBANe1fE3GBbFYwYKWC3a0oKc4a8aIWhRU7nAO821LGU3SE2eIzGTZzmtl2h8h9YBHEZCKUWpDLQYDkDnHTj7uURe9KaLypv3BMd5QeHLJ/NBJoMpBk+7QDB5CEIOkMjJhxvEvSw0WzSi1GLBygQ8FQDiVHC1ferGm3dQFV3V5csE7eDLD8SQwRa1MDtoTmGxpNbUyOpoVXzZpbbDLykM2iwM7AofklJnr3an8DTvvHUbTSTCx9qiXDsmIkoSIxtqIIVLNjN+bd5tb3UZCuHHpxC3/9edlcAjM/v/xA+NW4uYTE/9iGbmvAVivulBw0rEinf/OR9xP40VXHocMYx5+d+PCNVpl9YGWdVMeC6bSuPbPRIAEwmumBO8GTEn0FtRUiUHBvRKkb4jtqliaNVPDCVx8ut53Tn+caE4d1TQ9jicayGWQnBrLD7FPJeI9MKZFIVJgdJXJKdZUDt+zGKmAa22ExPsPq/YQj0EqSHEfaLhgQeIazKg1MSrS4p1Z3+8nWXG7dRu/ZJoqTWMDh34xyTvbutKBkYRHRVvXDb7VHuaKfl8B1rwVNMCrvzeWoUQVwtanBF9by4jURgdhCCqJsRl6I/K6p+4SHYfIuu7xpcTXQgTDEA1KmHydcg5gZYRyzbneYTFHAvzZHc25S0oBxpu1HlaDdgCxaD+568+TnPaAQVMhtBKf9m6T3c2Bb1U6S9BvdEi3SiTwANGXw3957DjCMU+DPmGWYSMU8xRddVkpUh/qMyWEJ7VuRmqegnJmOKJHRZtuMk1INyVpfGIzBzw+uQAc1DJe7lXWP0sjId5Ep9VwAlUafG5bhk5r9pDZM6xBQqGFPaMR3iPDiwm9AZVcJKqg6i+E+Ocob9xZ1fBhLV/72nP6QUaVgx+YKnz1v81h7CzQDL8NG/JcBS23R+12th09mS/EzgswGXHAop1/YeLUOX/XJ+ozlguT/Y1qQa+5nAk3XCFmWM0BTo6iKkZuXfyJkJre5N+8t63/cQuzrmqz24ZVUVj2TE1NP3LpqWlr5zrZI0no+Q6azr2NHBE8IBgm42dkjp2hHR84+VOPe8+LH19D76sX9Lcbh7d1rA3fTosXax/aVBGgMT7O5U/5sudiSacY206NhHbaIMyBj+unDJ1gaU+wUBfIOJA4ZqT/fY0QGs2YC5Dzm/UZNoLDkkUBa/LYr/ww+rVkfMtOb83NyyPiSGawn92y0CaR/fDWWQHj+etPJXUzqBNj2HYla8tuLRdBMIz4Is+2IgSZMnwQ4htEJu/e4LtHh9554TKpKdazZBa0BA==,iv:Z6V7irUKskmwVAC0I9u3fLrRJ4oooVLiAMWgjKOIXTY=,tag:O7tTcEzJ+15zcAcVpwIAsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM0h1WGR4TkpIODhpTmhX
            UmhOSDdwVTA4WmlDc3FDN1N4RnByci96elJNCnVTdGxxbnloaG5KblFzYWJaeEhF
            d1Q5TmFmYi8xUEhWVkowUFpuSERLc00KLS0tIHlHVFpiYzFjWS9UbUd2V3VIdXA5
            V1RuckJpbkZqOEs2V25SVU5aMWE1dWsKpZa1TBl1NR68rVsyYrZtZFMjI2SpGxyz
            XNmO5fldLDrjRQZrX0PxBNTcco225i0S8+E3yszbxRrSp8xYUaG/6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dW1JUjM5WXRuSWtieDNi
            S05LZmhOVm8vNnQ4dE1KaGg0S01aaktTd3g4CmZmZzA3UzB6THpuZ3BJU1lOT3JO
            dDZxMkY2NWpwc01pZ3JFOEhUa1RWRkEKLS0tIGE2N3psSG9BK2Fpa2wybzF2U0NN
            K0IrdjNlTWNuS2h3S3ZHYnd5NVNQczgKbvFdP0aL2oFyCipwUjxMHF1TGdy8L+St
            PWcU7fyX7ODPJTdlGC9kNWzYMFTqOhjND/Tzo3+mzU/ahWiJf7i8CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSXNTejE3aVBUZm9hWmhS
            dDFCRjduVXFycDVFZGMzSTVyT2pRRTN4K0ZjCkJOb3dmSy9kRTFJclZKRkVlc1Bs
            bnA1S3NoZXplR2dvUXdUTmpTdzZwQWsKLS0tIFJsT1BPdUVNNWU2dHZPUERjR1lL
            RG5UdkRqTW1lY2JueTdTWU1NU1pNQkEKAMbboFZQr9d5d5sEUKRhWImitbCN4C6Y
            WF8glt5pjeZE625fdn3BXjXqh4pss2enjTlVmWwZmM/M7FmDfHEpgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:47:29Z"
    mac: ENC[AES256_GCM,data:TkqfCr0sUeXXK3nh5+51RYH58NVlzcoNwKIIQXKKpuJSvLgCyCcG3wkU+xC/0c50hjUWxJ8y7Kunr+S13Zw3mUMcXvJ5ir07+/K3hDPV4uA0krqr/Gcj4ORNRaOQ4TADk8Tzi9WQybA9tCpt8qpjzdZIV/rAA6YFtdV2iHk2rfk=,iv:GhmRIpIDobre66oIE/F9hOnasyw5Bx+CC1XEFPtMpow=,tag:8Sc/qeTzCzr1zwi/ODWT0Q==,type:str]
    version: 3.13.3
