apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-packages
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:vDVuPLUgkg==,iv:spUKtHJ2ajm6KCjslbAgU9Xb8uuZjyH9AcvBAWX57Ro=,tag:wuFEDogh9fvQz35jsGQPqw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:S87C9kcMEAKn,iv:+0xh49r/ib068lt9Y1TWyzjLLrJeHLWED+zIJCjdnyY=,tag:39y9snTyCqGKZX6qYaHcLA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:180Lo+9PpaqjTnrtsr/5oyJFA4CqCszVY13tnG0yzPmj1HWN+wg0huMZ80PyuAyR99bdGRXk9IeL12Mt5rONTbU1xvJrX1rY42g0ZxGeHJMNphf1Ajh+4iPcQwIeTRK2eZH6eDKBGJ4MYqi09UsucCbVzLmlQiwX4sc7wsFZXj2V0qj1h8/f8vq7JdeL9U0xS1SfmGqdgQ1h+CS09EL7bi4kx5VvQo4W+PuyRCtiJdTwsRY5cftSSMTVdQZJvCUbGuO6mvAWAhhcOp+I2irJaZh1Zf2z5WRxDlT4IFFThgynrtxTP48JtsIXj+bfeI8QTWWM0OFr0qor6MGv883WMZdJiq/ru7hqEAU5E7tZlSmKdHCV2Ai4FABmfc8sGH8QQ+ijxOBsZ4aihH7bVd1zjbCd6wacQxkDo1gD9YVW5J5RXBRxp/aGuz5bct08/gGYVgvm+Rg602xQe0ACJmpolzDVtIeiy9QW0RUwM0R5eGE6J5JRrOszU46a46wJ6t4bLaICKsf5P3afERTIvUnsH/OGUaFSHIt1cJt2r/A6WYtgMGk8gNopJWAWnDsldOtv2KXgp0pq9NT73FjXvPxIjIiLyT/hEdnT+cjMQz/XJzoTJFbcN0SOeAJQj9/BoDAyLEz9Nyd/PE37kIwiO+xRK02aT8BIttyiXXleQLq+1CBI1j9UCJOIcvR8zvCOoUXQ7kxp5MtXkxwLklY/gTjtRO4kyZgAUK41pGpaLjD7n0ht1Tq7f7TdXlz1vwA5zn7a1otfAnfLdtk25s1I7HRHsQhiDrIWpf5JZ2eyRuBaqLNhpvEe9ecAmMJxv1k8GyNd65gvG8kLrCjUYFfHReGrX8rYSS14nXmviUWxqzuwhnkP1tZ7XYWspmR4KccbU01Uz9z6B800/dr73Sx27q948pDdRT43cuN4ho5FFJA94mO/3za4Q8eQv7TY90UJIZw+eSJiDR+CkUhWRUdJxcFW9zz3MUUGRRPQLIRp8MAk+0g5jxHuPgi0pis4LBB8DWjt2m4HIGPb2l7ygiUQvpciGEHaxJkM6a2Sn5+mzQHR2L1G4eSPhgNq5jgWYNtomwUYYm1tpSre3zqN7B8g1yPiIOKcvrxHxQlcSBdnl7nBQYiOlibFQWEt7amIJwHNQ3VEpUIaD2h8L1YiGO4ks5IDWYF21d4iGTxW7nBDnVtZqMyp+e1uWj7udplRD8VU4rIglvlgEkkhPMIrGmjgGkEFY3bEvVSsa8Ed6Gw03IBEsLYzG63pjOJDVRIEbSOtl5HWq0VCSNmW4d3IQWHlOYrTNXdo4aT5tYp38giDAp0V58W7hZ1ykTpVptLb6ysufCNt0vNQjrDUq8mqWTo7hrknvW5iU+K+xKplkm2nE5nXSYu1EVEcjvQrWv7hddzdb2JIDjOf7tsoeCbi2SIjmtt9JAyX57jN/u1Tvbz7vF9KWX+67Ql6iPzczAWRkp2i6q4Me04yavOTRt/HOKCU3G1hDFMnk91dHHx/9apCATk2N2p5oKVoBacuPMG3RJCjxpaQP+OQP1Vvh64ofRQA4hRLZjDeS3rIJ5JYaAWLPlZw4CwE0m8SUFjofWSWgrFzUeWY94Gr+lDsO1ayqmLKHF0GKjLaxatkCGKd7q09YYTquE8VNY3KDUSt4pcxXOQyAFIoob7RAG4IayGzQ2jI+Qrdos6gL5EucFvJImslG6QchswVLwRiAJ8k+iXOwP2ZBh2IXmSFzk2in02mX9HQxJHhZeBP5BPp7HhL2p7brgbCR3k2RDpzEWMoifs9dQNyVfH46YCyrqVaAvb+4+ZrFB0vEeb9UQJOhrjxZ1icghvNe3Shz/0JNk5WvYpiSjWtPw1NJ4ZGVIL9fiacHjij8kxrS/mlcp5Qstimbt3S+Qb5n8+0RTU7mm081JB9GqrrHeeHMb9sAYniij31atOm5fxhdt/rg99Pr2CPxF1raogE7Nmi1dbe4oLDwEe8K8C1lq1dXusolFaS4FWiItFSV8CwOvLOlYxVEzUgTcRiu/9EvK0KF99BMty4yTeTWhQd4C3DmQ0JCXm18PIjC6jcQnF8r41fRuA26YGPQPwSTHQMO1sfkUwjSx6NXavEFEtCP8OKynK1tmOymZdL7pv7sMzepqHnRPJCY+1nflJESbWq/8y0edtZq+FPNtb5HbKrwHYi1A1ZH7uxXDpQXBAbKI6vJtxWjp6eQucQonGfSgC/E8UMiuVOuJ25qU6hNg22gw==,iv:LOp4oAHbyQY9v2/fB/TYWV5XjFPFrV6K75Ef1paLalg=,tag:jE9KNmOjdzDUU3PUBMCiCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWVZWaUlHUEc5a1R4NHFO
            TWU4eEcvUnNQYzc5cFdXNUhWRWFlY0lucVU4CjlockxPL3lPY1c0RDVJQVJldmlS
            OUNYUENXNnFvZjVvbEgrdU1rcEU2YjQKLS0tIHYyMzdXbGp5bmh2N0h6a05TMmRK
            YlFLTnB1NlN4R2NZRWxFOFdXZTBHb3cKKCJrcvZx4yEio58sQuIWdRP8r/6h55Im
            V4sQzh+uoiRlAOrvoVC5/2tog7yuf9acCf4QOUxNTJ4/82nfaMI/WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY0c1ZTAzQk0vdGlVTWhR
            dXRKQ055NnZrblhkeGt0SmdpdTdjL3ptd1dRClBZaGs0b2RwUnpGc2lFWFZ2U3NH
            bURqcXBCR3JLNjFyc1RVS1FlNlFBcFEKLS0tIFd5ZHY3Sms4ZkZGRzd0ZHVkWTBK
            eFJ0T1lzS2x5MU5QbDVhU2ZNV2t5SkkKeCjmNNWbs+rXz0ewg3NZv8SCRhgzxqqO
            wGq3XS0hzJ36tHFZEiDtynrjRbGuATUK98VuqxaAiol12K+itHxU6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRVg4MU9qWU9KZnduNmp5
            VkdlL3ZzakJCazVlam01OUoyNHpNcjRvVml3Ck5LV2xsaTR1bW9FdXdZK1E4Y2RU
            dGdNT0hlN0UwMFBYMk5kQjNsTUdiWFUKLS0tIHJJUlk2aiszaG80a1pOWGlGd0Zx
            OHlaYUwvazE4MzV0UVZPRHd6M2wzUVkKeXrVGuc14BP1Hg6ZUdyuHjNpvscMNRKG
            g42//j6vNDWP3KX0eu9Z9KUyMlxr1F+e+720BiGyPi4fzxMIx7EIwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T22:34:10Z"
    mac: ENC[AES256_GCM,data:QLjvaERqbbq2UyFJffFtaO1qGEkzHSOWBWLa/kpDVk2ksAPuk5tGYl24zfaJJNG5ylMMJR4IhSYxFi5iLT53L2A1CMN+hkPGkmtp2uHLABvBoklxNz1cUYRUDkb6qlt98aMDV9sH93Vzokl6r3Bz1DdpH8p1Im3thIYPh0FSamc=,iv:qPE/CJfbbwalnaj+l5DWH+ooAhayfDVv4naAfy8WadM=,tag:KEIc8CSik/EH42F76owTNw==,type:str]
    version: 3.13.3
