data_volume_device: null
data_volume_partition: "{{ data_volume_device }}-part1"
data_volume_filesystem: ext4
data_volume_label: infra-data
data_volume_mount: /srv/data
data_volume_binds: []
data_volume_consumers: []
data_volume_packages: [parted, e2fsprogs]
data_volume_table_signatures: [gpt, PMBR]
data_volume_mount_unit: >-
  {{ data_volume_mount[1:] | replace('-', '\x2d') | replace('/', '-') }}.mount
data_volume_bind_units: >-
  {{ data_volume_binds | map('regex_replace', '^/', '') | map('replace', '-', '\x2d')
  | map('replace', '/', '-') | map('regex_replace', '$', '.mount') | list }}
