web:
    address: 100.86.241.75
    port: 8080
concurrency: 2
storage:
    type: sqlite
    path: /var/lib/gatus/gatus.db
    maximum-number-of-results: 100
    maximum-number-of-events: 50
alerting:
    email:
        from: alerts@fredrir.com
        host: email-smtp.eu-north-1.amazonaws.com
        password: ENC[AES256_GCM,data:3TSEnrCOtUB+YjZAXOYhjzqYCvYWsbNM0QMMYfaDmzv1qdWEfWaw/ne4Z6g=,iv:m1k7Hsh5bCOVl2C8m+MNbFZhhBB4wUFVqpsSZD44z2s=,tag:zTsgMbPwzV9MbDqvtvKgug==,type:str]
        port: 587
        to: fhansteen@gmail.com
        username: ENC[AES256_GCM,data:bDk9IcyL1MUNOSQ/1Cj/o0BBGuI=,iv:f3H+Ok2FrazHMqIspC0Nfx8eKsgHnIHfDCCyq84A9Ck=,tag:ZZUhayUX0giPTDznM8KzEA==,type:str]
        client:
            insecure: false
        default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
endpoints:
    - name: llunde
      group: applications
      url: https://llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: llunde-api-auth
      group: applications
      url: https://api.llunde.no/health
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 403'
      alerts:
        - type: email
    - name: parser-access
      group: applications
      url: https://parser.llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 302'
      alerts:
        - type: email
    - name: parser-external
      group: applications
      url: https://external.llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 404'
      alerts:
        - type: email
    - name: portfolio
      group: applications
      url: https://hansteen.dev/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: false
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: portfolio-origin-auth
      group: applications
      url: https://origin.hansteen.dev/readyz
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 403'
      alerts:
        - type: email
    - name: "y"
      group: applications
      url: https://yeeter.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: y-health
      group: applications
      url: https://yeeter.no/healthz
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: y-api
      group: applications
      url: https://yeeter.no/graphql?query=%7B__typename%7D
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
        - '[BODY].data.__typename == Query'
      alerts:
        - type: email
      headers:
        x-apollo-operation-name: health
    - name: grafana-login
      group: applications
      url: https://grafana.fredrir.com/login
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: grafana-auth
      group: applications
      url: https://grafana.fredrir.com/api/user
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 401'
      alerts:
        - type: email
    - name: logs-redirect
      group: applications
      url: https://fredrir.com/logs
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 302'
      alerts:
        - type: email
external-endpoints:
    - name: parser
      group: backups
      token: ENC[AES256_GCM,data:hyO4ESwI/4hm9TsmOC6BeujcpwmcxJHLHN5jKOiwkYPGw5DICk1SGzYQhw==,iv:jrcHiAwY0SS6JYv93bLs0JcWZl3bwIFtGmFQ35nHuR8=,tag:viyrAaaWH6uLV4SQcTttzA==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: "y"
      group: backups
      token: ENC[AES256_GCM,data:iUta+MY7MzBP64HA6W2Q1wPJEIWg11sMPw6yE+0Rns+ToPI9dCe2ESghuA==,iv:TY+mIBQIp1heJt++gr197cXEHVP6prR6UmovtvdlbM8=,tag:1cDOltGFyo1Q1tC4IInSMQ==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: portfolio
      group: backups
      token: ENC[AES256_GCM,data:76VtjPpuUd6CWoltiWbXk7JXLL+8WYovrErrzD/hSJY0MR6dUhVrLICFEg==,iv:Y4/jtASmAUk9Xtx+w/3KCAlp/t1qf8qX3ylF6CHNhUQ=,tag:N9aKvfBrVA04JHG2hWIoyg==,type:str]
      heartbeat:
        interval: 2h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: attic
      group: backups
      token: ENC[AES256_GCM,data:czXH1PEbwZKYaPwINwGHVdrOMeB8tGI+rUPgcQKGySjY4WALXiSEHqn1GA==,iv:RL5N90eyL+sC9JCJlOZpdpe4/YHvoicErNHcml1m8vs=,tag:HIwCXm1aL5hCXyEdmQcQqA==,type:str]
      heartbeat:
        interval: 2h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: control
      group: backups
      token: ENC[AES256_GCM,data:sUXSMiwUNdOXD+hsjJ207yvXy69ZvEy4u/nbQhDEnMDp5Fr8cRsJxwDBGA==,iv:3o2h3te7WJ10DcR3nUGm7DiP/C+aRU23caH/S4Dax9g=,tag:HeTlo3R1bJri7x6jECUwSA==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcjhHS0xaNGtQNVpNV1dQ
            ejdMUEt3UC9HS0c2aXpKcXVIZDRKUmtQQ2tRClZYMjBuNE5sNWF5SExqVEJ4aEF4
            NW15cWNnL2FpdGpkNXNDcURaMWI1cm8KLS0tIFl4TEFuZHFQdlFSY0dFMWtVRVp6
            Sjh0dlhLK3JQVlBsc2JOZGZubm10RHMKyoKcfjvcnzwYsLy/9dRvPx+xMXHeQ1a7
            P6FZxH0SxGkku60VfXFNWfOut+PTCTrwtVlSQo+4KmjVnmDh4TPmjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGkvQnJpNjFXNm1JOVdy
            VGtoc2FmVmpxZU90MUNIQTNJSGQwaFNza2tnCllaUHlzdEl1Tk0zUk9rcjkzbXlM
            TFBaVGFrUDJTaXI2dUtZSXhJbE5LWWcKLS0tIEN4aXhSVFpxK2dVdW1PRTczS3Bn
            Y08rK0FGQ0M4SkZwT2NYTjBzU3MyU1kKRU7h52cFyWREI2O8Xr0kpAp62obFmqGu
            FDFU4lVfClXydNePqaH1XV5e856W7W9coUw4AsoxyE8c+Okl3P6+9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZGk2MDgyaFJzR3YzZ0J5
            UGk4N25vbGNuMVZTWTMyU3dnZWlOaTR6SFRjClN4NUR1Y01KdnprM1oyelZkeWRy
            QWFtRHdxN0x3a2JOQXhsUURWd0tCUGMKLS0tIE5WRXNSRSsrYURZVk13WXp1KzNO
            d3JCT1hoRXEvTE56TUc4aFM5MTluZG8K/+pkEkTmUcZiPk6/gTAMmKQ4ZMUAh4ay
            BPd2tnMBlAmKhpQzjOaciM6umRrU7Wdg13akmBEEQjG42FXoVar1Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(username|password|token)$
    lastmodified: "2026-09-20T17:02:25Z"
    mac: ENC[AES256_GCM,data:T0gCVI7O0+lEYFsdcR6k4brwn1oEgrnmu/cxjXlfRTishGUft95HQT3ojFZ7k76NfynSY1RNeA/WHjG5uUAWzTGO42ZDjYIlD6iHIusGeG/06WsMR0aoa/0ukOXmIsJ9UL+zRShJ32mRRCDb2FvB7tiEczUeLegmOyvYsqy27oU=,iv:NRwytd22m8SorgHU4UT87OYZbbfalk86PTyXiyoQGh4=,tag:twWqT7f572gyjrnNiDHhEw==,type:str]
    version: 3.13.3
