web:
    address: 100.86.241.75
    port: 8080
concurrency: 2
storage:
    type: sqlite
    path: /var/lib/gatus/gatus.db
    maximum-number-of-results: 100
    maximum-number-of-events: 50
alerting:
    email:
        from: alerts@fredrir.com
        host: email-smtp.eu-north-1.amazonaws.com
        password: ENC[AES256_GCM,data:ZObBuuiN7lH54gqQ/ia+d9QFu3aEVrZX/FvKlooehhTR7SxMF5l6BTxinZw=,iv:m1k7Hsh5bCOVl2C8m+MNbFZhhBB4wUFVqpsSZD44z2s=,tag:epOCVI536fXhRk+orJv5cg==,type:str]
        port: 587
        to: fhansteen@gmail.com
        username: ENC[AES256_GCM,data:cShMGn11Mi0+PuHJo2bFbAxLHCI=,iv:f3H+Ok2FrazHMqIspC0Nfx8eKsgHnIHfDCCyq84A9Ck=,tag:ByofOzE3IyGmq6HIzKcQLw==,type:str]
        client:
            insecure: false
        default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
endpoints:
    - name: llunde
      group: applications
      url: https://llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: llunde-api-auth
      group: applications
      url: https://api.llunde.no/health
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 403'
      alerts:
        - type: email
    - name: parser-access
      group: applications
      url: https://parser.llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 302'
      alerts:
        - type: email
    - name: parser-external
      group: applications
      url: https://external.llunde.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 404'
      alerts:
        - type: email
    - name: portfolio
      group: applications
      url: https://hansteen.dev/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: false
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: portfolio-origin-auth
      group: applications
      url: https://origin.hansteen.dev/readyz
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 403'
      alerts:
        - type: email
    - name: "y"
      group: applications
      url: https://yeeter.no/
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: y-health
      group: applications
      url: https://yeeter.no/healthz
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: y-api
      group: applications
      url: https://yeeter.no/graphql?query=%7B__typename%7D
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
        - '[BODY].data.__typename == Query'
      alerts:
        - type: email
      headers:
        x-apollo-operation-name: health
    - name: grafana-login
      group: applications
      url: https://grafana.fredrir.com/login
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 200'
      alerts:
        - type: email
    - name: grafana-auth
      group: applications
      url: https://grafana.fredrir.com/api/user
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 401'
      alerts:
        - type: email
    - name: logs-redirect
      group: applications
      url: https://fredrir.com/logs
      interval: 1m
      client:
        timeout: 10s
        ignore-redirect: true
      conditions:
        - '[STATUS] == 302'
      alerts:
        - type: email
external-endpoints:
    - name: parser
      group: backups
      token: ENC[AES256_GCM,data:p2OYXVstpSTB/nSD4HlC+0P2MvaeC/+m20N6wWk5S9U7s0k3RulSiSDljQ==,iv:jrcHiAwY0SS6JYv93bLs0JcWZl3bwIFtGmFQ35nHuR8=,tag:9Le0GiBQDCaefqRnh75sNw==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: "y"
      group: backups
      token: ENC[AES256_GCM,data:UoraUZ5kKX0RlExRfTkdNeQG28ceLwIM1ILX3cmwwUAblbYqL729RB8z/g==,iv:TY+mIBQIp1heJt++gr197cXEHVP6prR6UmovtvdlbM8=,tag:LNDLQ+N1s+2K7eJk7LfEZw==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: portfolio
      group: backups
      token: ENC[AES256_GCM,data:PaLClMbzZJJcLAii2yslnuSQ8G/B8EmrYOJ+yegoqJ4ZVdvZCIvI4o/qHg==,iv:Y4/jtASmAUk9Xtx+w/3KCAlp/t1qf8qX3ylF6CHNhUQ=,tag:K6JacWaof4zOYTxRuEIPcA==,type:str]
      heartbeat:
        interval: 2h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: attic
      group: backups
      token: ENC[AES256_GCM,data:EoL6BX9CK2f3wnmWtnwE23gHJS1asjfy/i/6m3cM0DL5zWXctPuVbUN1Uw==,iv:RL5N90eyL+sC9JCJlOZpdpe4/YHvoicErNHcml1m8vs=,tag:wxZndi0/RDoKaDhkO5yakA==,type:str]
      heartbeat:
        interval: 2h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
    - name: control
      group: backups
      token: ENC[AES256_GCM,data:WiOrhiFJuwifp/4dXMiL6gmyaZcuuIDkKiXxeb77a1XhOb7iFASatQKGIA==,iv:3o2h3te7WJ10DcR3nUGm7DiP/C+aRU23caH/S4Dax9g=,tag:tWU05ZyKa7ZHwjLxha8k8g==,type:str]
      heartbeat:
        interval: 8h
      alerts:
        - type: email
          failure-threshold: 1
          success-threshold: 1
          send-on-resolved: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTUVzL2JsS1MvZXhQbkg5
            aFBXMmo0YkcwN2d6d3hJUXpkLzdaN2FyR21vCjZibUFNajNQS1hOYTUvUlNqT0V4
            L3Q2Vkt3Vlp2RHh2SlJMVVhjeERGZFEKLS0tIDQ4RjVZMkZQd1JuWEJXS0tldW5B
            L0lVbUhhdlB6ODJnTmNweVQ3R2kvc0kKzBLMHf7qX31krAecM3FTVDUepBbZ0UIM
            6OCz/mpKnkQVpbjNXXVg1FlnEHFCAJEHHh2uBPG6Z9HJh7T7iAAoGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNUxuM1ZlK2dpT0ZXZWVD
            SnpNMG5YSnRMa3BsQjlzbU8zS2dSeHgrbVRRCkZLa08xY0xwNk9xWXlqVStLZndq
            QmRVazBNOEVlcmlJamEwY0xpUWFCTDQKLS0tIHhzcTRkS0ltRW5mV1I0ekhGLzVt
            dVdGYk1Ocm51aUFhelRIZlNubzR1ZFUK9HyQqZwzLZjEXyoeJa62bQypdXLH0z8Z
            Kvw2tq8IcTFGBYEqOhSfd5xSQQhb8zcuRftugsj3DcjTYzW3/I8gSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZmFjdUp6WHNnUDgzc0JZ
            Uk0veHRDUTF1WTQxcFVxdWVtQzZTTWdQQ2p3CkxITzJCZnJ5bDZUUFNRVTNJUENp
            bndvVGw1enVYY0tSdVdramNKdU94aTgKLS0tIFhWcDRmalhDWHpzLzJBVDhTeE1i
            enFYRnpQaVExcGRZNVdsT0VCU3I2MnMKMtVYSzvoEKyxStWNz+EmgEwOfHPtL7FU
            kVDIknQTRXWiaQ8rz3tOgGhbLk4jjrUX4W1rxvt0xt3y2k41GKfsmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYkp0MjVXZzJZQ2htMHNF
            MUcwbGVQSkhqZlZHckk1Wm0veDdnWS9wSnlZCk5ydnVnazh6UXJuc3M3RkxEV1pw
            YVhmWWgvcjQvWU5YbDB5clNlN2czOUEKLS0tIGtYL0VoY01NTWdrc1BxK2pHWmJj
            KzE1bXliTFFmT2Nud3hnMFJYTlZaMzAKVyhIsJKhB+yCSyNr/xWnjFa2E4rKNuas
            Ntfz6KK1o+DVnUpVLBA9mD496GaBOJ6AtWPQjd1VmS7fZ1W0+AvWQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jm6xj8qlmfjlhw0vdseaaqkpt3mqj3yl0upx3smwutsaghcq6pesvrka2t
    encrypted_regex: ^(username|password|token)$
    lastmodified: "2026-09-20T23:22:33Z"
    mac: ENC[AES256_GCM,data:6dfdDfOBID/SorB48E1kULWA0AqqiMLG82DOXqeH8/hb7zrEQJe/5qId9lW0Jqo5S4BXYu+i7V1U0wFNDECOn+OZho+bgLKzlRCcstayENUHeikYB8fTTmsWrlFn+wd0TnjACN9uEC0MairMAtF68NGsJXxSIK64/707vq+kYPU=,iv:/KHsYk0Ezr7AFYl+nEtZYEpzNoyuyPMirlM6QJRegUw=,tag:beClImFE+hOhvB1sxmhOQg==,type:str]
    version: 3.13.3
