GATUS_SMTP_USERNAME: ENC[AES256_GCM,data:r92RIolf1XHwq+QDhPwtSMEe3Gk=,iv:h0hiWMkdefENHzS99FAbupunBFY8nEBPUgeROgZzixk=,tag:3aoFEN744D7sC9VQjyArVw==,type:str]
GATUS_SMTP_PASSWORD: ENC[AES256_GCM,data:B2ExWLryENMrT4/wr+0qEUhEDuSLge0NBsz8yO6hvcd56JY6dz1PsUy0+2w=,iv:vLH/jIubwOdp7gERPFZWQ1H5C/HjT+UvKIyQR3STK/Y=,tag:UQNZAqW1FXqJG4zde31jZQ==,type:str]
GATUS_TOKEN_BACKUPS_PARSER: ENC[AES256_GCM,data:OU/bvR2QbX9WFtjhOZquIp7rLHEc/gMGV/wpL5uCIbjl7J+8oA4vnqanga+6TP7XE7uqqmexHojciX6HrplSHw==,iv:GU4uJ2KBZ49vzTpzfT26VC3cU4nJJVIgw46Wp3VZbx8=,tag:gdE26M7ZkYycgZjof+2kgw==,type:str]
GATUS_TOKEN_BACKUPS_Y: ENC[AES256_GCM,data:Vav0zrgHBVg6BrQ3FmyI3iAut3voXcGzrUSX6QYWrma3S/5xQwcXHiVxG9Xh00VWteAnHon+8LoAcr1vYJ2m4A==,iv:IIFeFqiMwNy94uHqNAfC3FTzfu1+jDV+YfbRGJyHig4=,tag:XKvwmO1t6ooDiIb0XfJBJA==,type:str]
GATUS_TOKEN_BACKUPS_PORTFOLIO: ENC[AES256_GCM,data:D0gCc6hJ6JnzU3WIqTSZ2diBmY4qx6dEPJoPtk3lWiT45UmzMIdfk/BomZcTSLUdyQKg7p9/omwRhw5ToJxggg==,iv:QQQeGccH8Z0YTFfL8jlvs3rxdDuer2mIgQ/0cnG6c/o=,tag:bT25kv8h1TXj9IcIO34YPw==,type:str]
GATUS_TOKEN_BACKUPS_ATTIC: ENC[AES256_GCM,data:lBYWi7cGuQt3GA0uESGpTXXpulgCDnZvD5sLIP6X4g95BXE0AptOf6qQoAEhhTODf8ELUS42YxuMcSpdxt8+rQ==,iv:+VrYnbB48FsXHhcsKk+hTWFUOMTelb9DTKonxUlCwPQ=,tag:S1P3Z24ClPIozsQIm0mXeA==,type:str]
GATUS_TOKEN_BACKUPS_CONTROL: ENC[AES256_GCM,data:B6ujoffk7DE8jNXmdo9vf0J3QAGkfnr8JnK4q4MfJQ2JzKshv8xIttO1jg==,iv:8H5H+SI7wkNhACIsyvtiLjrO7TzteNgJ0wYDUXDvq+I=,tag:2Hpp54qvqkfnXeVMCR2kOw==,type:str]
GATUS_TOKEN_RECONCILIATION_VERIFICATION: ENC[AES256_GCM,data:ZkIh8RZWZsLRLgBTljS9TGQdGtjBZVqC/PJGcOeY78tafCTWuwjwzZmYPw==,iv:ZmEC2y6jfloFM/U4/sYp3lXbeUdOjQ7iVVZaZhfFL7c=,tag:Icy+qzTyUjf6L2peQvTySQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdkZQWW1JMUhVSDBKRHgw
            TUloUXdFWmtpNlZiNlRhWG0zYThRS0cxQlRNCndWUFlxUjJJbnVnOTJFaWpDcjJD
            QitLeVJ3OCtXVFJ0U0FGZUZqZkhqUWMKLS0tIFlHbXc2U2NWM1poYTdQS2lpQ3d3
            NHliN2c0bDhUTDFVWUZod21QVjBVczgKnYqPhUdv54g9il8GMSN9u0LWcqxV7F4I
            H2ldP8HJyMgFgUXSprHLXrzVZ9Ku4RY600DI2hCWEswjwuQaH7D+LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ekVmTjJsazQwTUJRNzVn
            bmtRUUFOWTJGODFCTElnZDBlWCtqY1VGWHpBCnZDaDRYeGs2YTJESlhiTmh2ZHgx
            TVlndDNuQ1kwRUpuY0pLdStqYUJWWW8KLS0tIHZFdXd5RGpFNnVqbEJTNHQ4a1pE
            b2NBUi8zTWdSekpGTE5IaEZsb2xpakkK+Vey2nDp1jr1MoFmHykfqyTGyRyTVXxg
            quV3sw7wLEUPkdDxajp3a45XmrEQvIV461dO9XnpAalMFo3sok22ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UFI1TlM0azhkaSt1QUtG
            dzhZNTJjY1gvbnpMUkt3UXJINDZKT3U5alh3Cm91VlVqSURUNVlhaXVDc2o3bi9X
            cXh6QXRieEZqc0FqWURsZFZWZzlPZFUKLS0tIE9tMm51dTVMN0JDYzh2UG4xYTRR
            MFVRVmFnRWhPbDJRbzlvZ2RSVlYvc2cKgf+JDgWRt32Z+CqpAVavHa4yBYQQ3TRs
            AOvms/uOUICUX1U1/85YDl0OUfBn+g0raCxac1d3xJNApNoTcR9Ehw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xru5rv42fzmnm4uhv9rwz5gf5ynf7v7qr2e68epcjsq9l33zdulqq53v9j
    lastmodified: "2026-09-26T03:06:53Z"
    mac: ENC[AES256_GCM,data:pREyjp1k48o/CVHwQQz7qCg3OHlvLFGpSGkyT+oZMJbHJftzB8PH2hGDyZ2zO6z9TUdOqJWsl7MId+K6aH3UaI1F4SEwadSEKzr034KqJcA3ouuqSMuD3HM/ecdPPvs2sfBrqlaWoUB9Dn/3p8sDrIefFNOQXPHazaVuiBuUlHI=,iv:1wLagKgvSRrHOxO6eqBdSJSqx1VXyi0HPNzkztYcRjU=,tag:feipX/AtAbikYrK/Drq7Zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
