build_engine_dedicated: false
build_engine_qualified: false
build_engine_cpus: 2
build_engine_memory: 4g
build_engine_pids: 256
build_engine_cache_gib: 20
build_engine_cache_port: 9092
build_engine_dagger_name: infra-dagger
build_engine_bazel_image: buchgr/bazel-remote-cache:v2.6.2@sha256:8109f1f39eb17d898cf51e08b41e4eabaaaeb1f584c2f22c1be45b7568fcc512
