apiVersion: v1
kind: Secret
metadata:
    name: build-cache-backend
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: backend
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:goL4BV+rtxlUoOpFEmRIlVq4wMSf0vfae68=,iv:sZlzS6s8Goc2jsOAuy76hJf16FqvLymuaZQnK6CKHq4=,tag:1M9yW4u1j8u/fqF2VWCpTw==,type:str]
    ro_secret: ENC[AES256_GCM,data:0GqXM6XUOhDBbgn2DoaXkHC6LTZq6g+qvA7ATEeoel/YlBb5AbMlMVRU3y47BnNp5dUDM+jdTLedBrp67ASO6Q==,iv:xnDibXvzr4LfFon1C5vQ0M8bxQ1X6HqDebzCJyX2iR8=,tag:iVFLO4kfhsB0U4o8JgqSwA==,type:str]
    rw_id: ENC[AES256_GCM,data:99uRV0IIZKKbwDslGZ6+jzop17DIvrupTmI=,iv:MpL+NlwjnGy5obn30m9KO0C3Ujn+kgJBHqmfBK6O6s0=,tag:OEVmINUKr3NUHZ//Bp7cxQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:aNXDo7LnRzIgXYYwndRqhKgfsBoHtHYfVipxi6vMFM5LU7OJQpgDw7YZUFWd6W20U58MjWf5kB1FJJHWbg+6ww==,iv:ZemIRBtmNFz5QE557KLEdANr3cum/JEYnbqtLE53N5Y=,tag:zTvhyCc0OVo/ham26PvdwA==,type:str]
    release_id: ENC[AES256_GCM,data:Y/M68x4lQiTj7nN87IEW31zShya7dxRoe+E=,iv:zuuL80neKAznQ2boO0Gu1lgo5UVxCj856h9f13Dvfk8=,tag:CcqxFppwJqzIDYcypiGUGg==,type:str]
    release_secret: ENC[AES256_GCM,data:iDjQ2r/wh5JLzDNdo1dWYTYI+8puJ2fDX/ld3khI6mUqyYKpfl6AU9SsUDz8vYAOgfImN3Uu8+Ejm4GTKwlOcA==,iv:TYhBKRRu81wYgXZfjCh5P9ARcYHrmd1OmKWi+8h37N0=,tag:431koBFZMcFta7i296rTpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyLzdnZHMxZzJNeExpbkd4
            REFkaXVraG5XQWhXdTVHak4xelFjYW94OWpzCmsvbmdjV0s2bGs1cVVNeHB4YUgv
            UVRmRFpOZFVkWlNCc3JLYU9kWnRsaFUKLS0tIE91ajdXWjVxTGl6bnh2dEdUcGZi
            MDJ1dFZlenE1Ykwzb1JFd3kyalRmdWMK2ocZDjWBMQAHe/iakVY6c1HlyQX4Y4sf
            mN49AMEk/N4yv9HO9DmfNaadavRE0K3mLVtMjeOSWmfGYXMdC+bs4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTWdIVm1TeWVyZWNiVktX
            cGhRcEVEbG5MM29DSTFDcElIOFVyTU5nUFRRClN5MUIzQlpuZFlVTHVVSTRWdU40
            Qmp5ajhhNEFoTXhHUlVjYVhFYzJMbncKLS0tIFJFMWRZYTNBZy9SQmVGUEwxSVJ3
            Y25xWHQ2dkRRdFdjNmJGZTM4QzQyS2cKOq4kDDg3zRuKjuQgpxsAIkd0N2iphw7T
            ZwwJikDX6QdC0Mq4y8sYqndoxbGDWTrgVjpDByz4ynFrOTxUTcdK3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0s4a2tyd21icXdHMDBl
            Mm1JY3MxMnVNY0VNNDJvN1VGaHBsdWFvODNjCmJXQkVrbFNyeVZVRTN4ZFZQRzEz
            N1VENGdpRHZxUUtBcXhXSm5wUFRHSncKLS0tIG1xU1VrMWpuS29GZTF5VGhtYXAw
            RHFVRHpiOW0xZzJOM0xycXVCb0dFdUEKsanWZS3pOjnSOv3fyzmmzuXegN51Dv98
            GnANwTrgMOiWyQXI9HRGEOo/8YjlsyAY08NoVjUo+JfDcVRxqruLSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:QziuaL54MxZXtoMcovyFu0xSRnTt8ZDCcFxRL1hUQ96EzwzQ2UIRhsm9gGxrEaIg/rlwAZuKjrb6UOs/S4GBMADV+7vxLFfaqDzTLZK5mNrXNN0OG0W3mbdMv9Qp3b8x3XrsIvnTXH2mDvOVDmcVZmnLM+5h/sNcaMZqg9tyiII=,iv:b3BVxYAfBZDPk7gmCSkX6asFIcfWtk1Z5CzopKjuOMs=,tag:b+IminOLUfI0SK4Pn2txxw==,type:str]
    version: 3.13.3
