apiVersion: v1
kind: Secret
metadata:
    name: build-cache-backend
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: backend
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:oSTPyUkhx+Ij7UgR8pdrdl2duLTiBf7n2Tw=,iv:sZlzS6s8Goc2jsOAuy76hJf16FqvLymuaZQnK6CKHq4=,tag:NUAEiHhvbPVPmujgtorZKg==,type:str]
    ro_secret: ENC[AES256_GCM,data:1Zac6ROO5K2KRUS0AmQhgedsjUVIva3z11fD8c4SeTvz3CAcMjbziWDGYzPNavio/LNgn8IR8s5xDDAk3ULmDQ==,iv:xnDibXvzr4LfFon1C5vQ0M8bxQ1X6HqDebzCJyX2iR8=,tag:u359tfhcFQlMxkTj7GsC9A==,type:str]
    rw_id: ENC[AES256_GCM,data:JI3Cfr8Z1i/VjmAsADdmsX7eBzIrNM6qyQg=,iv:MpL+NlwjnGy5obn30m9KO0C3Ujn+kgJBHqmfBK6O6s0=,tag:R9p2vGAYjGFJj0dA1QJTWw==,type:str]
    rw_secret: ENC[AES256_GCM,data:eZyFH5jbEA5qd7zGdTRkU2Dqs4WMZRLwBwUiBJlWzTUBggMBWGBRnT0LDZe6vou3hf/1vwwWVUMLqdQcvEMhuQ==,iv:ZemIRBtmNFz5QE557KLEdANr3cum/JEYnbqtLE53N5Y=,tag:ky1oqIzhV5oio9LkOQ9FiQ==,type:str]
    release_id: ENC[AES256_GCM,data:kesybLAXxKm4/3BGAa1UOmm69vfW+6LE1QE=,iv:zuuL80neKAznQ2boO0Gu1lgo5UVxCj856h9f13Dvfk8=,tag:HqzsL/bfBdoCspcIyHTCCg==,type:str]
    release_secret: ENC[AES256_GCM,data:DPPi6PDdZ/GwpbG9Otwxk6szDocvWd46uKblJ94XEROivdELphHlvIc/QD1rxzrOIcyNY1Z4Df+xGpYhbX+agQ==,iv:TYhBKRRu81wYgXZfjCh5P9ARcYHrmd1OmKWi+8h37N0=,tag:nN7GYO0Y2sO/rTu4clH/lA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2orY0tTK2tMcHZUaHZo
            UjJmTk5lRVViN3o0cDRuSEVwbTRvTEZ1ZGg0CjFvZC9RUWYxWmNKcDl0bWNGckQw
            ZllpbnlnUERReGNsbFE2RFVwVk9SVm8KLS0tIG01ZmVEeEFsWmNqZDZzYVRrMXhB
            TkNKMHJ1WVQvMy9GVlVyQTlTMUF0UUEKQnMurAvEd+BbLMjUvP8IuS2TdGliRhTB
            E9WlOSZO8z8RC5U3jbbIHzjdZsCYSXFG5Ov8fg/5GyYKX604oIg88w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUlk2N01uSDNNQkN2cTl0
            OUIzYlFrOFZBeWEwYmhRUGVNQTBkZHIreEgwCkQ5dGxUSHAwYjBBK0l4N1RVQzNp
            TzJrMFcvekpzMi9BSVN2OXFlWlY1TjAKLS0tIHROSlc0WXc2ek1zL2xhcTZEMkgr
            b3ZPMWloQlM5Z0YzdjlzaWdWWXBrS2cK9kO3NxheRUxF/LBkE1kfeJwG9ZVUM/kT
            97kPftmHVUvISDDS0U5KTu3/wVhUGp2G2mdcfzsred3oRo2RnDfrqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUVTeldvQk1tQjhDM2hU
            QUs4NExsR21jY0x0OXBaNkZOb2J5dUFHNEFjCktPTDFKUDcvaVpNYzBwd2hjSHNH
            VXlWeTBlQUxyUDg2Ni9qSER2TzlqSTAKLS0tIFA0MUpGZnR5YVNGdUt5R3A4SG5I
            Q3dweXFqWXFBZjZYclRhdlpUa0RKL2cKEj/e7lN9ZF6t4Gy8r+xk8RMjWjCRXV+P
            oZJu8yOXWKj0z4uwFCOueqlhrk/o5Brovkj4v/7WA42jMxrjx5xlzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:M76vplODwSRj0d/+0J6ySG6da2W47DJGJg23zmqKGk5mWbRYDJprCQ99+XlnJUiTqCI5/mHZCuSBk6sAnIomTb5GvHfV31GV8MU2VTqXVrpMZxZuXzHUsmcfust58ExeyvMQzwgokOd3RBrDaI+bUmd3frP8EQCaY14ZeLHd/pQ=,iv:IinWJUvENnfhPYGZQJlH9VpOjAEpp2Dl40Qkw4tKq7Q=,tag:veJOsaulXEjygJyTHJhJzw==,type:str]
    version: 3.13.3
