apiVersion: v1
kind: Secret
metadata:
    name: build-cache-frontend
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: frontend
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:Igr8erS/fvcfPFdMhnaOO/wj1F9+3r90uUU=,iv:IAtQVeHW5N0JIuwxZgCjIZ9JupoZrXNTi/x7TkJGqsc=,tag:BhRIJdpI8uSFgkRLPvz2lw==,type:str]
    ro_secret: ENC[AES256_GCM,data:NibKaokJKDCCQ6nDe1kpL7pSvoRV5t0vtB6Z2D0bpGFPYYnJBQXzYADmVyhhTUu5sa29lj1anN8M5Nqic7BrDQ==,iv:qKJiyEjziHZgkLQw6rE7YADNReyHjzo1a3u3WN4jzRs=,tag:bf+rZlW8e8NZlu9wMh2nNA==,type:str]
    rw_id: ENC[AES256_GCM,data:yF0i/akujhjKXXTKqrftKDBsIXrEwe/1grQ=,iv:l0SOzNGZKVO8YpQJz2L6rwwqu470G0G2WrcsHNa43iY=,tag:dTCSFRrz2CAOa4lMQrKyBw==,type:str]
    rw_secret: ENC[AES256_GCM,data:n/lshdhfl5BE7Sx4GsKvyoKeYO/rtzLyuL6Mqa/5VQjX1clEvc2l9khQZvzca6cYkYHPr59coBtIHjq5g/A+vA==,iv:4NbG747b83w9OBOfftP+stYMSi/Y9WRogd9+Di+pYe0=,tag:OvKHpihrfuT6RU0aktuDtg==,type:str]
    release_id: ENC[AES256_GCM,data:hszkRS/KrqVSo6DclSvNb0tFcG+EWYLC+aI=,iv:Deg25LOlWk3V8+U/VUHXT1Qcjtm8f9AQKUyXo6XgiNo=,tag:DCvQ5PVxgPOg7crY6gdLIg==,type:str]
    release_secret: ENC[AES256_GCM,data:5JasMLCy0SL7ORJDR3pV9mw6KyLRIVUiVpzjgSCG58VkU2SZe6ArPSJiDzx+PLU8Giq0wt3IcgfG3eFsbTYNCA==,iv:5EScLPJGjV8WQKoP3V9kGRw8dmBQ2koLVThpN4ZjLLo=,tag:uafd93kh+XUyPc6l1/putg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOFNqTmZOcWlkS3V6dkpH
            bnJYOWozVFpjWmVOYmtxU1RmbzJzbUZ3SFVvCnEvMTN3UjF5ZmR0bDVoc3BSTVB1
            dDQ0eGwvaGtWS0k4a0JZcFRFQ0VUNDQKLS0tIEZManNqeTJRNEJ3ZGlKVGcxZFln
            QTg3RTl3OXFxK1J6dGdNSDNSRVZNTTQKpzRR93sF8iqup6zNQqOfOC+g/eY7ts1o
            i3G1VQaXx0B8Jz/XcC0MpPF1k/Z/QgBJz8J3FUrDMfzGXB2BusEWvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TURkZm5lNFQ2aDZYR1hJ
            M3JTZGNDeGgwOS9Fd05pQnNjRDFZZm9BSGxjCmIwVUNiZ2IwUVEvNXd3WHo5Q3Fh
            dG4wWm50RHlPVzJWa3JlUmsxSWlJenMKLS0tIE9vT05QTld0Vk80b085WDNvN1Ix
            Z21wNXd4Zi9mQnFZRWZkZmhpS3RsZVEKZ9t1xxRAR7MkpXnKTQXIeKeu70ynyhC0
            EvLgfm1KsCYv/PjsGR7Gf5aQ8gmXevXuehYU6j2CN1khWrjBIFV57w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYk5xNWUrNysvL0FYREF3
            bnRlUEFvc2lWb1ZZS3VTSEg1clVPTTZHZURvClZiT2tmcFBWRWlIUTVPdWQwVGtI
            enFsV1lhdExuZlpqalNUcFdRZDgyL0UKLS0tIFFNZ3VJbnJ2WlI2Nm1JMW51MFBj
            aVhXbnZYMm0rZjEzT0pUNHg2bDdrd0UKI+MCjj7oIwigVsk2vEJ4d3zgOQ+zM/nF
            lGAgDcNGqyQ6pczCP9x57B5id860eNRwtPk2PR8xtXCFYAsPYeM/zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:OAGXxTGWVaP51O0AdmbeD8ejY2fin2M7Jzcvgf6mMeiz8QNGEU9irt44Tpqp3xL3acCB7uWrgbLPMN6bR1yBDZfyRxHL4TN+5nyl79e3iQLAKtqdx95Vv9STHdzFAqN+SEF2hnErmbSNHc40Aq5PFXrzCxYznu2TFLcBAirwKQk=,iv:i8EPL8ljUPTvrJB5sWTjmRBnnNQWU822MZv6knVmFeM=,tag:TyAqWMxuHiED0zjr6dGqlg==,type:str]
    version: 3.13.3
