apiVersion: v1
kind: Secret
metadata:
    name: build-cache-frontend
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: frontend
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:XANBEm+5ZIIxwVPiooEVlkvB7E+d2OOyhBU=,iv:IAtQVeHW5N0JIuwxZgCjIZ9JupoZrXNTi/x7TkJGqsc=,tag:QDHvhYaSq5QmcPbd9WKqOw==,type:str]
    ro_secret: ENC[AES256_GCM,data:403FPaqQK+zd6TwUGSofuWwbemU676vngn0fsrlJs3ljWd55aT5Zz2u9mw5ZMrEdIVBOE0J0ocucbJIUIIl0iA==,iv:qKJiyEjziHZgkLQw6rE7YADNReyHjzo1a3u3WN4jzRs=,tag:JwcLug2UMRXREvIeYT72Vg==,type:str]
    rw_id: ENC[AES256_GCM,data:w2a+1XCx3g3xlZMqLWCuaBoIQKw8a7EXVOQ=,iv:l0SOzNGZKVO8YpQJz2L6rwwqu470G0G2WrcsHNa43iY=,tag:qIZxiOI8FuEMBX20aPJJhQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:CzXR+zjcxExLGuwjX1p+pnKldomLBzy4c0m/BDnI94yb+KRaVGJ5os/Yv6sq2Mn85AVfZp01omTYACBGYAzRnQ==,iv:4NbG747b83w9OBOfftP+stYMSi/Y9WRogd9+Di+pYe0=,tag:Rblp/BaTokWP3m19eMAeGw==,type:str]
    release_id: ENC[AES256_GCM,data:xzdfKaA7W23Y50UUXVcEY/S/vwJEHagzEMs=,iv:Deg25LOlWk3V8+U/VUHXT1Qcjtm8f9AQKUyXo6XgiNo=,tag:ICaZOEQhPUusEyRf4qNRkw==,type:str]
    release_secret: ENC[AES256_GCM,data:rUaSZbhXVnILOOUYnIGHxTW7+pnduQt9AGJYywL16c+ScCiAUjFVmUlsFgFV/q2LLddBtTtZqYFrMvms/ukfXA==,iv:5EScLPJGjV8WQKoP3V9kGRw8dmBQ2koLVThpN4ZjLLo=,tag:yIFGaQwUnhlk1YqpeU0Hxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c09NUWpQcUZUcDVnWm50
            K1hnWnR5YmlXZm5TdlBlNkFrN05yVm5TS1VNCjJSSVc1N0wrSmQ0bmFrQlZ5MFM5
            d1ZnbjdSaXhPYmhZNTdJRTAvTEpUdEEKLS0tIHJjcHNuSFBDMEo2aWxWR2JSSFFz
            cGc0R016SldQZVpPcmJKa1NVbVpac0UKqYfDV8gnPP4f6dZ3PCUf0Zerw7mli8oz
            sb5X1PdCtidnDL4NO/f8muKwtuMZeioik0mtop+RSFUmxXu/lfIJIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5citYbVNDWW1NQTJrSXBJ
            amdPVEVQRnVzQ2JUS1NIV2xqRTFMaTVOMVN3CjU0aFkwRzVET3dYTU91dlAwaHp4
            bENONHRUUFhsWUZTTkRPNVNiQUtPdTQKLS0tIFdwSVVZZ2pHcE5JNUFWZjdBMDIx
            dUhCNGJvMm1HYmJkTHdrZEoyd3lkdmcKFG2rOVtkmzAhccqZrELWgAPFrkAhCzA4
            aaerN2j3srhE3HnA2syHZZ8rLwML43lkcRyewitxaBRt4PrzyJYKHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQjYxeW9ML05nY0pKa1Bt
            eHRVbDduNnR4em04QWhvcDkya3pOS1g4b0g4ClRFRGNFQ3B1OTZyTlhwMFIyZE5n
            b3pnUWNqdExUdXdqV0ZMU0JBMTFJS1UKLS0tIFBsLzBwMG0wb21zTjZYa3ZtZ3Rv
            L29BdUtEaFd2ckYzOTRvejluOFhEUlkK7Ag30Jgpj58qBXSHVfEwVKD8a5KToIBJ
            NW2BAJHbKxs8JuG1Rgc9sCHOWfAOX56U3/NEgXDjY8HEI2QW754c9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:hX+9HUZ0EEuoVQ5eBSkv0e0CLDXvqE9smhTvLgReifk8KI0vb/3e/zQtNZ+XNtpz59trGQBcqpamLYqdgOBtIzThNF4u0q62S2t6v2a99XwXVuoa6PZGyzswyyM8nYUorHxf7mutMtNySgbnfLjMgVlo4luATDU+eozzIr3krs4=,iv:2Hx0Und8XwzV0GG5X/NfuFYDvEWPhkDA09/DnmUWIEE=,tag:POyD5jw8KU3RJAtbrram5A==,type:str]
    version: 3.13.3
