apiVersion: v1
kind: Secret
metadata:
    name: build-cache-infra
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: infra
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:MNFaoeNVR1uT1j3uxi+IWUbCs2SFpoL2+tg=,iv:uukSeSzSxjaR6jwYuNookqGH68uokVAR9qzL3oSQMhA=,tag:KUzi5/OnEMmBPp83tw3pcA==,type:str]
    ro_secret: ENC[AES256_GCM,data:U6RJTLcy6XQmW3VXe9yMceD9zFEpHxVH/54AfI2JsyRohRFIygUI6cLircaKHcLwfLnbZU6aROyLSRKQn218SA==,iv:ZNeS+X8Tmzi3z3tc389tctPE88C1qxr6Fi2uiBJI95g=,tag:TFxiGgtqeHNehvHRnUHXHg==,type:str]
    rw_id: ENC[AES256_GCM,data:bpC+jmKF6B3mk0CLvwwSFnsyYsPljlB+Jgk=,iv:ExYOnY1+baeth2KdTiGX74ZgRYc70eeNw+lqWI6BKgo=,tag:GiE2rMjZheg5b4zWYpDTPQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:6b88pjahjnzW8Grc8PuK8yKV60cnPZzR+lsJhwPnbsDxmXD6vLQGgUNZlQhD2Ah60MHGr4O+2hTn3xM3zDS04A==,iv:2S+Zgx31ezMrPy625qzvUKlInDyvpvkNsLeAaAZRlf8=,tag:Bul5sWMcnZE4netr+RSS2w==,type:str]
    release_id: ENC[AES256_GCM,data:tZcJvxzTSXlSwFhD3j/LwA8XUArBRID+Y3o=,iv:wtl4GBKM6lQHjuPimy0NWY1bxJqTlRKV/HP1EM77HKE=,tag:ulv1IIlQwhwdgVtbrGlmRw==,type:str]
    release_secret: ENC[AES256_GCM,data:wkUSZSAj0elPBbT5KCdzowQ/bE2maO3liu3u6WqPNrtQnjsTCanOl5NfP1AR7EjwyGjF8dRRJ/RBJkVcPEif+w==,iv:Wwask/3LrIc0OsDDXX/+eKqUx8+YncD+FDzLXQmErdM=,tag:RFIIedjCRyVePNGNc4yv3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMUFwcG9UdkdzZDdma0lV
            Z3NtRDlOWFlMNDdiK1NUcjFhRGpqMmJTem4wCkVtMW9QcHlnWjMwVW50cTJ5L2xF
            c2ZDT1F0S3FNcU1hL1BaT2dhaVNKV0UKLS0tIFBRQ3JweDJwWCtwbkR0V3RPNEFB
            eFl1MjMzV0czU0o4ODduaVVLVUgrQTQKRuSzpSiPuwXtiY0g0/LEeMPx5RZ6+1MC
            v6xYGOBdi15ZHFUE20GnDHhsenGONSDBze7OPjje6fHeQ9jbI2xUoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Rkw3ajRkNVNtKytMdHBw
            WDVLZGNDVXduUjFFSjJkUGo4YllUeFBYZjAwClQ1bk5Ha1gwbzBYSVk0eUdYMCts
            UWd4aDVFeEtTQks2bkFDeDR1dmtKTlUKLS0tIDNqeDg1S0FvcmIvcnJFWGNlSnU3
            VU5qZVE3RHZlbGoralZJbWNpNHRkZG8KuZUvpp4ZVHQDDd15i2YP3FE7jxyY+tSm
            XpvAj3jD3U2XGcS9MZrjws+5A0OOhQuLLH30XYEdhNdUf8Gcxl+0wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YnNxOVZFVGtXZjBDQUFV
            RjZpRWZBSVNVRVVkbC9tMmoyaDcwMTBqakYwCllvMEQzdlZGcmhxcWZ5ZEI1QnJ4
            R0VESXZxQXo0S0hSbGtQRmhuS3lpK1UKLS0tIEhMaERlSEI3OHIzVVF5Y3pXcnFC
            RnpQK0kzeVpyNXJxeXNrTkxEYVlBRG8K6h4L2fKpfeECD+VJpyU+dqHPRNldCIAj
            nMVRY5gwgsB1+0lH2aqyFxolJnDl0gWkUIhaLIlIo4wTrnZLiidoXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:52y+5OgPS7+kHwx5/t1+F6TBeUEaQnhQO28hOOBnHq+t3yx2Eu0sLah7yfp8Zs10NIx6UklJxveDx6zuckUftM0UVj5odB+o3+rAqSO7nz9HoyjTxLt5Vq/N+OTpZrMVrNwj18mwbkFdUuioZn0eVipBEoFH/coy7vvsjU8hPrw=,iv:V5/TJyLtKfYnCWwD5Gc4Q4MbEdWtqw+oey4+akJB4AM=,tag:MrF/H9dWnJlJIMmDQUyP5Q==,type:str]
    version: 3.13.3
