apiVersion: v1
kind: Secret
metadata:
    name: build-cache-infra
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: infra
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:Ii9J7cjNFmxvBbJrmA1VfEDe7GUuNVXVjTk=,iv:uukSeSzSxjaR6jwYuNookqGH68uokVAR9qzL3oSQMhA=,tag:blQA4GRiwvnSZV6h3O924g==,type:str]
    ro_secret: ENC[AES256_GCM,data:OVz3KhbKxMNroJnm7Bd8iyOdiAuPvj3zN5WeUMcN2qNcMsnaaElj5K9qUWaexWNUPEQawkCprMeTvJ9sZE0ejA==,iv:ZNeS+X8Tmzi3z3tc389tctPE88C1qxr6Fi2uiBJI95g=,tag:AFBxj5Vb28XyWaVQ1fTyOg==,type:str]
    rw_id: ENC[AES256_GCM,data:K2fzBS4bUAHpB2OyfQiOc1KivSdZ7Bwxujk=,iv:ExYOnY1+baeth2KdTiGX74ZgRYc70eeNw+lqWI6BKgo=,tag:HVTrkzzbjVxo72biLC5aXQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:lXI2ru/qGJEPxJLbnUzA0zlAD6FApdu9rCgrdskv2uYzksfIuhM4xy4Ll8TWBn9S75OfQWFhy+zzSMbSHnlfyw==,iv:2S+Zgx31ezMrPy625qzvUKlInDyvpvkNsLeAaAZRlf8=,tag:4On2lIWN71ItkBYQW397oQ==,type:str]
    release_id: ENC[AES256_GCM,data:EMi+SF3FNy76US8IO97bqAn7VvkTun/Xmtw=,iv:wtl4GBKM6lQHjuPimy0NWY1bxJqTlRKV/HP1EM77HKE=,tag:POoeW/osl7Mls5tAr+41dg==,type:str]
    release_secret: ENC[AES256_GCM,data:Gog6/RzC7bx6XXRX4sRplyxhQ6Zht4aZIkIXY6v+lrKqJ1Oz42UKXqliV5LLMErLjhFnLzSWJtLTWmyqne320A==,iv:Wwask/3LrIc0OsDDXX/+eKqUx8+YncD+FDzLXQmErdM=,tag:/fLTe6qQXMtr8YGRGDHA/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc29zV24rdnBKQTJRVUxn
            aHI3UVh6dFdRTTRtekdDSGxvT25ZV0FET1hBClEwU1lmRmV0Tzg5N0VEcXFtSGpv
            bEcya1pnbzNrbWxwZ0hGVWU4VHhlbEUKLS0tIGdMWGtPeW9VZmh6UWpwTDNrZTkv
            TzlndkJwc1RBVytwaDFOUWlsQjh3ZGcKCqqFfDY+WV+/6lmmnQ7O93WEftT2TuGR
            dk57Jf+znnpq2aXvv+EYoEfJoUsy/ZeUebzEJAGUVoo/2NJB3un4fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqakhYYjNlSDk1NXFYRDlP
            RURrN1RCTkJtVHpzOHhSa2NUcTRCMlZTcEJrCktKYmFHQjhKL0Z2WDF3dTkrY0M1
            SmpKSW1CaVZIWmZjMXhQOUFLaWFFK3cKLS0tIEI0QTlCMkRudE94QUZCd09IOFN0
            Rm1VY0F2UWlJZjN6SkhCanhzN0g0Y0kKcQsFkbmXx2aZ4yvf1IhVgqDGZot1DvfV
            LLcjysPelT3U26qUXpVRPCg2N4cN28dDsjRc59HdAqRpJPvn55vVQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS1FPSXRQS3NvejNKVC84
            KzZ0TURydWMyRG1hZ3YrSG5kZVRmeG5YY2hrCjBkMmZycVprTXUyQjB4TzRrN3Yx
            VHlPOWNQSTEyelZheVFiSkttS1JYeWcKLS0tIGdmV3BTcjdjTEpqQ1RtM1hjQ0ll
            Z2tqa1hrYWpINGoyMnZuNWF0ekFWcmMKYLrHTa6SXovCbWw6mUFlfY01t4nkpm3A
            1to6G0+zFGGh9gGeOkcoIulMKqpez+QWtB4tLI1+UdAyuaT74HypNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:z3zP+R6lmT7hyT19KXBfvzPdsPuLERT1PkCBes32hFEDzMR8nz1ELsIHWLAF1J+HOj7P/9KC2RMmJt12KHbtuMjqnzii3LsSc1myfUhahcXVrqtjkqtFycQSNnEFIFEHdpltlAPlimg9b7XZ1dEk4ID8vMJoLKaN1t6PeZOmwFU=,iv:at1gRLhai1iY7s1PQWvQcW4fRRazWRNOgBrNYAxznd8=,tag:cdoDLN+FlQyGqROivz1TZQ==,type:str]
    version: 3.13.3
