apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nsql.secret.sops.yaml
- frontend.secret.sops.yaml
- backend.secret.sops.yaml
- portfolio.secret.sops.yaml
- y.secret.sops.yaml
- infra.secret.sops.yaml
