apiVersion: v1
kind: Secret
metadata:
    name: build-cache-nsql
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: nsql
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:j+M76X3lqr0AndrOKE2qz0c13XTBlr+r+rA=,iv:A+Pq0V8IlC84P3ct4R/fNNZ5wFL/0F8GHwGWcBvX6Lw=,tag:x6fzGtekFZaPs++SM9+ItA==,type:str]
    ro_secret: ENC[AES256_GCM,data:mvDWurnjfUgoEtnG/QTxE6fRvPbDvP8YseZ9UhNaWuSSSMNSjL3mHtCZAc/QL+72R+ZtNQ4ZFSEbzngOXmvzVQ==,iv:3lL2h7TCXtROA9MnVdTprmriPXjh4QR+p/c16CGk7L0=,tag:llwh8QM3oPTDd1b21U22bg==,type:str]
    rw_id: ENC[AES256_GCM,data:W/ckoHVSHpm5AUZ0iFpFjQ+JnLI/NOinsyM=,iv:mce5mhJnQFLP/kT0Tvi3A4e55kWKSulzgMyDJYc+fH8=,tag:txr8DbipSSDwL5el2ZlCKQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:FSpdzAxBHzVWRVXvBxpalOurj1srTvxjyjIhdL+ac3ruQDL+osD6R2kYvn1LLNZ/4gtZysiUpc9EUCgI5DJfkg==,iv:BPw00MhUAbr+EJ9jT+S5MXxrZcgrWfGDeBs+pabFAqU=,tag:OjT3aHhQT+g9f5yp9z/l9g==,type:str]
    release_id: ENC[AES256_GCM,data:tWNb6OdCYGPm9Kd2kUM4eO7GSoGANKj8A70=,iv:XpjkRtjPcyucQDo/n+qIzf6GeR7D5gd/vxpMT5ln6K4=,tag:2zLq8V5gIetmPU9GTazUBA==,type:str]
    release_secret: ENC[AES256_GCM,data:kQ6mboldm7NCyM2EyJ3+PBiYBtSAyLk9lcUAKc9IHnLcniK/OFPIBt0I3jJkfexHn9VBhEsciCdAcv6OAcj8Jg==,iv:ZFoxbKnLTfP9igQNzmuflqQnN02gBL+ZOQKNRy4GH8w=,tag:XCycAovzMBeHBiPl4aNw/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbTNUbnJEK1pILzFERnZD
            Z3ZnTFhMbklmaWNFWUNkZlNCUGYzQ2F4UTJzCjJxTTJTVGxOZkJlSG5HSmpjTDhH
            b2EzT08rNTZKYU40SVBMUmhhdkYvQ0kKLS0tIEFQcGYrVUNVQTZjc0FLbjlQUXRS
            aVJoVEpvZHkrTTQ4RktIQ3Z4Q1ZHZjQKXtq8YJlVYmnZzBYMB+L+klBYCASZ3pY7
            SpTtCf9aWBPwLiFEhfvumyDArcT+KWi51Jkr6iJm0tSz29IvL2Nd6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydDIyeHA1d3J5T0VzQVIy
            cFNPUEVORmFnK3lDMkxCR2J1eXlmeWVHYURRCmZVUXZtR3ZIYUNPcE96Z1BEc2dU
            aCtjZlhPUU5zaDRXbFpadHhtV25CZDQKLS0tIDB5U29qdWtXL0VhU3lDNnRFb29r
            YUdOUWJwcHByeWI3V0RyVVJCaVFKY2sKwQcxbDWF5huN5t4mxbkbL2QbPRPPkgsk
            aUjx1Rdr3qqFXBVrqnJe8Y1hLNUmQqizemLYvxhnB4xWOxtMU5JUEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMC9pazB6SEFXN01WYUNQ
            OEtLOURFYmpQWWZ6Z3VGWFNxdXdmRGRuVEdZCkh2NXVwcDF0ZkU1MUNvdWludUhQ
            MGtXZGc2eFNMd2VINDB3WE1jTVhEZmsKLS0tIHNPWWdsamR6cHRSczlkM1RBcW1C
            NEdYWjd6WFU2TXVEVUFxcGZ1dUVScVkKsuR5SY/HqXjo+T3HZZ3TL3akZwbtGukg
            i006sc/TxDbQ7sH2u8Ub351zr15UrzZDqbXcWgC/KWa2Ikz/sZZVdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:dbRVXPlra08XxSC4Lh4yTQtBmI3H7M0xL9657lZvPt81QnKO1qcqfre+biVJjDFlGuF9CDUPftYpDq4SAWR1FcSqoc2Yzc2XYgidDdIE9qMiapchCfnZBZ/bA+yJ5Q2Jl2g/WBjMvGra9zmVO4IXkI7B9ih2v/kQlXgTyBIEo7g=,iv:atw4FpglyGkfe3/GePD6+YZiNA2gKsrBzBxFkHaeCp0=,tag:pRqtmXG3SFDcbiaF4ZDK9A==,type:str]
    version: 3.13.3
