apiVersion: v1
kind: Secret
metadata:
    name: build-cache-nsql
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: nsql
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:8DwuiIIGLNcCgJYiA7lTWbZobq0QvotmVfw=,iv:A+Pq0V8IlC84P3ct4R/fNNZ5wFL/0F8GHwGWcBvX6Lw=,tag:6sGVdOsNdjZTEBPsVRGtRw==,type:str]
    ro_secret: ENC[AES256_GCM,data:Qxwmsm22EovMY9K41jTOp2eTXuFYAkBqJ+uUviGXYY4VsCOTuISg1EtGF/txKQK7a0833mgYu8fJo6XMR/40WQ==,iv:3lL2h7TCXtROA9MnVdTprmriPXjh4QR+p/c16CGk7L0=,tag:o1uM5M3tviHeBiVzEEPmWA==,type:str]
    rw_id: ENC[AES256_GCM,data:Sd6ORfsQP2ZJUSu4j5fG+vK5l/ssiHui5v0=,iv:mce5mhJnQFLP/kT0Tvi3A4e55kWKSulzgMyDJYc+fH8=,tag:oOUS7fR/+Wxn5xW4u7EZ5Q==,type:str]
    rw_secret: ENC[AES256_GCM,data:qUVtnGILmaT9G5Vkk/3ezm9oej2KQNF4+CmO8kt5+j2yygRNAa4CwyLgLTKBaV3ZuR6zttMsXCESz07HgvhjEg==,iv:BPw00MhUAbr+EJ9jT+S5MXxrZcgrWfGDeBs+pabFAqU=,tag:a51ihuwQLwWV6THlqlj3EA==,type:str]
    release_id: ENC[AES256_GCM,data:J91BnNcj4H32MUqntIJTMI5hRl65BEg6QLU=,iv:XpjkRtjPcyucQDo/n+qIzf6GeR7D5gd/vxpMT5ln6K4=,tag:N0Ez2jD/XqUItFJqKUgHSQ==,type:str]
    release_secret: ENC[AES256_GCM,data:FAhpE4mddBECpGOGZlqMgxlf/dH7Oy/ymuqyWSwaTi43Gl7ypFVGH2/N1CyS5kpKaQkXO2pfH1kGgqYubSG4NA==,iv:ZFoxbKnLTfP9igQNzmuflqQnN02gBL+ZOQKNRy4GH8w=,tag:tveVcvY7MnFFDJMsGOSGMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS2tZTWpiZVVjSTVHcndX
            OEVGMVZrSTBmM2J5Zi9zV0pqaXNpNDVwb2tJCkw5RS81K0w2Q1ZCL2V0WHRYYzBh
            dmVLaVY3WGtxVG1mUzNVY244WmttSWsKLS0tIDVadUZPU05MUTNCNTVQRy9yYm5h
            SUpjYlRBNnpvZC9xRHVBMERFY0JGTjQK/qQtXcuNDWWy9um7ZWn3PtMFVZ0H+z9w
            wZCtFfrA4lsQG+bFCvYXIoC/Mi20XWVJ12ALVu8DkaB5jZaJnHzhJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QWFmaXZBTWwyVHM3ZjdR
            MWtWQnlqNTU5RFdvTDdUYWY1L3QvaHgzazFBCkV3RmFCYzNkWG12c0t3VVNsVG8x
            d2NqcGtudDkzejliNU52cU9rUm9wSGcKLS0tIHZHMmlOeGxJRkFLaFVUMnNvVlNi
            SEJQelJCMkRBSzBMemhnT2w2SGM3Nk0KgLHs9MAW5W7ACyV6PAYL3trEcZIRMT1s
            D1+3ZUewQsr42MsQoAbNWZB6rb/j4/MMBI5T7Ech/sDzgr8eoqrALA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVGRVU005a0tIa3FtSzFZ
            R2lKcGxHVzFWY3VoV2RKd1g3QnZTcUNBd1gwCmt3U0g4VmhPTXV5T3lpRi82MFln
            eFRJMlc5Q0hoTWFad1V4SXFwOHBkRGcKLS0tIFZlYnpLamU5RDFQQ01pZnZQWnh5
            RlhEcHVvL01QTkg5RVRIZWszSGcwa1UK85WBA+dhNTv2MDArud1J2A7elOBd3Pm7
            gtNOghRhb7LpxmGgNA8+/0+zT8bbTeHEnXCVH+uHb/yUikZd3Z5a+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T09:28:10Z"
    mac: ENC[AES256_GCM,data:KBeVUOlSYZoOsfpE+nAmryuMH++IJsSuSUDHRWcRg2FBZf9Bwt9YSFGjcRUEvXlxPyPBatzhHm8OUNNIlRQQbZOsoYHkZOKsIoOoXZiDzX9Ra5OShfmX+IxXxmoW4aB5gTfVNMiCewFrNmgCUdN9FLrTm+YOYP9jTVLIDQv3bKs=,iv:bILyWZiptgJeirgJORTpayl1JW34tbEzllTOgy8efyQ=,tag:vptubEWIUOdlXDWohnlwbg==,type:str]
    version: 3.13.3
