apiVersion: v1
kind: Secret
metadata:
    name: build-cache-parser
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: parser
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:FsKkzIyp3LWIfi4KgjwpzHMwIZYQPtLR6KM=,iv:CaMbrHoIgC9SklCTOhpotS9KsGaRGpVvLcB9lRc+IrU=,tag:UFCRx0SmsKWcSXQo5XOclg==,type:str]
    ro_secret: ENC[AES256_GCM,data:B8doXOU8HIBJFN4kVH7a9Edt/0aAQru1RSEH1h21A+lzMTbc0IfvC9U1C1TNnT9zj0eHlAZhyGum3c2ttiacXg==,iv:8SV2LmDvf6slRXL2BfiJXHtZI3dtBGx2QnKlZdMseDM=,tag:A1L8tYMyOk5EXpQbrNHMbQ==,type:str]
    rw_id: ENC[AES256_GCM,data:VBPcVdMV9wcuPYv7BCVkCrx0jqTHjjGjpZU=,iv:wWMgdDbL2vEbd7rV4sWnjJXU/8m6/5m5rPjCTNFukI8=,tag:8nhLaJpKx6PuDg2at6Zebw==,type:str]
    rw_secret: ENC[AES256_GCM,data:npsYMS/af/8wAVppCMePQutXEe0PapC8IiRQY4ez+zWQOTqyJ2HMB5OlzBLYBAvGadO7kLOcc7DcMljwZxy5fw==,iv:99Yzybldg59zkLWJFe/r9qCIuvNo/nWky9kNQMGcHsY=,tag:Tt3qGTsyNagVOTwDuZvDmw==,type:str]
    release_id: ENC[AES256_GCM,data:EfEHsy/HFYsITkqqBdp405BNw8Spqk5x2J8=,iv:jkEE0EqXCL1MtyNnUK4frACxvYAsO4HBetJ/fNSnXVo=,tag:fpX5WrRkOw9r/BHcr8m4/A==,type:str]
    release_secret: ENC[AES256_GCM,data:U9v5Fme6YxhQRHChkfDjmYG0KLzHDEi4QH0/sPbq4Nx5rsb3FvH0be32xyAfy6XE+Hb9E2exCxzA9i65UGzjYQ==,iv:3aMPKPAs/rAGvj7cVKsVc1NXJBlFhl+daLrLE+sQaH8=,tag:9X1ZHkTw0FEQ8N53HO/7/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TnRabUhuL0xJZkhjaXBZ
            VTdIdk1nL2huUTBsdU5TWG9YTnVPbERMUGlVCnZHb0lIUWs1YURhVysvMVpKNVF5
            OTg2TSs3VzEvU016NTJaWkVTYXRSYXMKLS0tIGhkdXRpWTJZSE9hekxpT04xc25k
            bzNLdDhMaHIyZEpOSjBHNC9DNFJ6djQKn2kUfE9Zqdz0D4y0vqgqu2ePfxDctYlv
            auKgmyBrh9XXMRIlWZMvNH4n/iXDYVqxyIWT7eP+7vKleDf8Qk/MJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMVdrY3RlSHpIc2MyYmMv
            SmxyRkJpb0FqQ21FY0NoekxxSGJPb0dVT25BCjZ0K2VEK3BoR0JOT3U0Q2VSVFd3
            SlcxOHZzaUh5cDRSM2FndlIycEJwZkUKLS0tIDZpK2JVS2JJTVpCUmhTWnZkWnBG
            UnhoR24rYll6QjBsVDZVOUkxV0QrMGsKaU3ExpbDMhLoxIpCsNXvw+qA8rjqgw0f
            +hEAhXrS1Da/FyBdwix6cwchGaQOoZ61REdcUKW3951Xx2oqrjH9Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL1ZRdDdmazBOOWNwNnFR
            VTdPUVcyWUxoa09WVEJldXowQnJlOXgyMlZ3CnN0NytkalMzVWFvVXJmQVJsVWRR
            UFB5K3huQ1pkRTBLODBPcTErbVVtbDgKLS0tIDBJQmJBdFc2enFRcFNmb1MrYjRl
            RHlCeUR2aGJrclczNUtPTEVwaDJaK2cKGQlo4wolzShVqFecCLtjIQ668AVHHzBS
            PHDj+pUuvpL0BuzRrXGKzO95egbgPEsllKgoFYW4yreTOAMc31hazw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T23:14:56Z"
    mac: ENC[AES256_GCM,data:uoexqy2ntn0Etj2TqzSdzcOog2RyhKeiJJk0VCBufqeZsM/JMPziCGAO3n2XzSC8sHy1C7qUfuhRxO3wgEn5m/BPyuglqGwWGO1s/tklos5xrorZlKlmXMhl2d8+MgmQLMFtHaDw1gAxhQ8GI+9ZJYJhYzmhvqde6mrQBkac62k=,iv:wutNCBHr6WjDZxXWcG9HPlcQyoIiG+2CfubSnN+TB4Q=,tag:YH95bb1Mr+kH1d2HzLBMKg==,type:str]
    version: 3.13.3
