apiVersion: v1
kind: Secret
metadata:
    name: build-cache-parser
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: parser
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:KYPLBb0ck0PH0iJBMAP7YDbDJ2L247s5NU8=,iv:CaMbrHoIgC9SklCTOhpotS9KsGaRGpVvLcB9lRc+IrU=,tag:5p8pf+8OVxkJIagm8OFrww==,type:str]
    ro_secret: ENC[AES256_GCM,data:9mVZnJ3fYgPAQofhB8HKkXcTwc/FGH/TKeVD9qWyARzafj1M8W5W7j4N9n0ASp4156zJLJXbkXtmb6VFMfGhkA==,iv:8SV2LmDvf6slRXL2BfiJXHtZI3dtBGx2QnKlZdMseDM=,tag:DrgEGhLYpXxF2CIkcJW39g==,type:str]
    rw_id: ENC[AES256_GCM,data:xeaDxINfVIHHn/dBt6o5pFc32S918Sn27o8=,iv:wWMgdDbL2vEbd7rV4sWnjJXU/8m6/5m5rPjCTNFukI8=,tag:wG3aMI5JKwtzIkrdOaIcHw==,type:str]
    rw_secret: ENC[AES256_GCM,data:dA6oIcB6+1EhUkCy8OMy6fhlyUZ54QA1aRhuAGv4XM4qH61kgrmhiKN9gZYSysTEMIpJAZ8xo7CViJVWpyLqNQ==,iv:99Yzybldg59zkLWJFe/r9qCIuvNo/nWky9kNQMGcHsY=,tag:utGgYP07clSp2feKJ785kw==,type:str]
    release_id: ENC[AES256_GCM,data:ace2F2ZL3g90AzIS872j4RhK8xmqU0lLFcM=,iv:jkEE0EqXCL1MtyNnUK4frACxvYAsO4HBetJ/fNSnXVo=,tag:fTl2hwQAjtRZNTFuVM8WFA==,type:str]
    release_secret: ENC[AES256_GCM,data:OE9uFDtsuSomkGYv+aUby/kvlE4FeXIBz0E0Up9v9TrA8sKP33PA6/R4eXStSUW9bshqVZZ3zegCAzkMpSsjQA==,iv:3aMPKPAs/rAGvj7cVKsVc1NXJBlFhl+daLrLE+sQaH8=,tag:PeTh8xuseFXnp224cYiWHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRTIzd2lVbEJsajJTR2ZH
            V1hjbXE0NXdIZE00dUJYNVFRczhndUZlbERrCmdKQjQycVhFZ0JSS3dUL090bTFi
            WW9yK1pyRFdzRUVLMmxpdmdZKzh3UjgKLS0tIE9aWFdyZyt3amIvdHlzY25FVUd4
            eXNJZlQyT1dYM1FjUjg0N00waEsxeVEKy++SZtF87oZUMlwrw5R44Iiy1l/k+PAr
            B/z81ySpivM6NKEAHkP53jFz6KJH15AIecMrGRsJvZR6C93TSb0wxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTmtUQ3F1UzRSMEtlSys4
            SmdSU2FtSW5YMzJuaWpiaFZmeGR1Q1FNekdrCkJra0NSZzNzNlRHSjVFZElMRlRu
            eFpVTkpwNm9YS2VycFBzS2JqdG43TWsKLS0tIFY5c1QzeDdERVhPZlphcVVqbTRw
            cE9lblF1aVNmSVZzaWRRaUFEcVphV0UKfcUk4D1Qi3N4e7Azw0p+CV+NVRwzyDWc
            6Lp+apGhOe1YR4IUe/F/LEF0kh5gdWp3DCxoP6t413N0tnJLjm1JBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMkJ0V09XaXJqNFM4MTl4
            ZEVjMzRBREdQQmhaczEydUMvU2ZyelROOWgwCjdSR2ZVaTg2MmV6R3RVcHM3TVE1
            OThLL05MRWFxTWd5T24wUlpHYUVIbkkKLS0tIGRXamFmQjF4VGRkZCtsdWpCVnRT
            K1lwWU5tR0ZjSW9jeGlGODNmcWx3V1EKMQo7fK8c2IY5ZlleZAQJgLhvn6oKG9dc
            bl0BzCda4zLeO14w/RAiTeN/8EtrCM6+L9n+2CssLtHNdnjRWJWKwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:2JwbBVMqbbR+dZLKPbw6uXKB3n8WwQpTuIUfKWuuGVRrUtb0Ha2IylIiFxjPbz1zKtWD06p7EQG3u1Bx6ipfWq61y/K22c/SVZgIQJmm7G8pJM+oDOSNz9MoTerXGoljBx6/5/cOqoP+cFAbkiQMft8aOeCTT9zoez4LnQ2ugpw=,iv:xyyv4sluxTxdUbeMof9cUDP4BZOpg5yxhi5BB+8P29Q=,tag:WT1IOR6Y6ZxFqvF1j+1Yvw==,type:str]
    version: 3.13.3
