apiVersion: v1
kind: Secret
metadata:
    name: build-cache-portfolio
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: portfolio
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:aP4BMFLQtzmCoigVnILw2mbdXLb37aKFeN4=,iv:bl8Cxhe8uvpz33rbIyVoNCwt7JHEDVrhfWll0JxosnA=,tag:dwTLccKS572OvY+wnI6KDA==,type:str]
    ro_secret: ENC[AES256_GCM,data:Ljv7cGyHfm9lj20RDfK8UrnfMEYzpdWoeTQOfT6taLhMMAI0CPTlfIXe6f1SwN7uzDC8g3uAFJ0WRLQkYy/SyA==,iv:SDzYOuJviNOUeumv7aKYw9Gs4199OwY1Y5COXK78Qvk=,tag:tevtRVmo+GfVB7rHlbIM6g==,type:str]
    rw_id: ENC[AES256_GCM,data:7BqwK5yqSs7QQwKCpbg/rUaOoVaTidnl0oM=,iv:pjp4d5PaWiJUC31EOkFNCmZCUwr/ovNJC3yUshI6S8M=,tag:XQyFfC1SkOBOILHcUAh2SA==,type:str]
    rw_secret: ENC[AES256_GCM,data:5I24vJ+0WS412NJg/JRpqS61v8118iFDYWwrAbFGvtqdABQ5WyW9097KAAU+VJwFckWY5JGVxlRNSrGYIe2ynA==,iv:MHZrxcK8kgr51QAxlgv1nybDC5mAeZKxrMTSTMhIvNk=,tag:DVC7+W2kBR7UdQz1+GosHg==,type:str]
    release_id: ENC[AES256_GCM,data:HaJRaiWpQuPXwwUKTd0MkdM2hpIldhBr1+I=,iv:on6Ppj1QWZBJQB4ga2g+rmpLMFsAh9Ci2iR4hQtbxx4=,tag:XKduv7jrgv0XLKbjQQiX3g==,type:str]
    release_secret: ENC[AES256_GCM,data:flP0Ue+P9HIsdhhFr5diugZ0dhyIznMHJbTR8zYhsBSiryEQoLEESa4+bsVwpOjAcwv/CI18A+GeW35O8KzaHA==,iv:y4lhdRXwahBaEupQ6JS5vDbJYdd5AYgyDiV+R1eIEDE=,tag:wVmNZnjsYyWV0EPujSEk1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVG03VTNEVXp1eXZvTTUv
            eGFuWHZFYjRVcnFSOXpuKzhwMW9pYXFDdXk0ClN5Q3ZzRlJwdWJiQldPdFRESHpV
            SEkrclpaUnJZTWM5bktzK2U4UDFzRkkKLS0tIER2RXQrOVNCQy85RkV4Ukt4RkxX
            V1gycGFwaWdpeFZXcXhYUXJMWCsxbUUKTrynSgbw2xv9tyZjJzIjw6+IjrOetQOb
            F2eSyk81QXxm/U6H/DNDNdV1tQnLOYLyI+Azqa8X3TAH75APOuSMUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUDRDdEh1Z0ZDdWhyVFFa
            ZGNRcXdpZFF4bG5mVlVRdmRjbnNUZG12MVVNCkNaamNDK1B4V2ErMTdOL1p6VFAz
            TGVOL0RPVktiRW5qYk1CWklCRHVOY00KLS0tIFovRGNHOENOWVp0U01HNXE5NkVy
            R0RuTERxMHV1cmtPbHBUMGhEWG1KQVkK9TkA8qAZ4kp651vLJFypoPxjBdjLEEET
            lPypiO6LYULvoZS7Vxx97rYYQDm8FFSGBNcP9qfEvmz8+ckEB7m/YA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTVI3SmFxZFMyMUxJRm9m
            V1E3enpiWUZWWE9KMHFiNDFuMVhmbXZrSzJVCjE2dCtuMlVmSkhHdVZwYnJjS3BM
            cVk1TWRPcm56SWtiTnRLanhBRnRBK1EKLS0tIHJnZTd4NzA2REdpRmcrYUlCWkwr
            T3Zmb21TVzYxMklSMW9rOXc4NnkzL0UK148Faij1s3qol+0hbeSCUZsqTUyw/a4l
            3XAEwYXI/wlEb4PF1n2tY9XxPwbPMwlD4NXG7GqybCEPawA4KidDtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:wL+p79JMHPVXx38xo3oqQXt5PoUoQUNFpqWhdMAzTxIXKCQ1soOFi96CN1VYDEDA1hRr2+SAAKepD0TbM1uw0NFmLwNq01GeofCAGJK0OEXgGmBhAOY0T9vcClcT5KCFiqaI1iB5JNvBhnZNmGPp863UUZBEUhgDL0V7fld+q3A=,iv:yf2CEjJkbCLNBzpCDSZjOe77JVQCfLgAtAIWOPAnGr4=,tag:7xNBkAQE5Yy8WZqInU7Czg==,type:str]
    version: 3.13.3
