apiVersion: v1
kind: Secret
metadata:
    name: build-cache-portfolio
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: portfolio
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:I3HnOs1BGltnjIUkKsXzKnUdXBo9cj3cJFA=,iv:bl8Cxhe8uvpz33rbIyVoNCwt7JHEDVrhfWll0JxosnA=,tag:QrnAgfBbOWDJpDsHBDj7tQ==,type:str]
    ro_secret: ENC[AES256_GCM,data:A0Qt9lK7ln2uAjqZXVmttavZ9g4s7PHNWEg+oRsCDHGJk2F375w/t4pixpSK92KUJFesUSTdLXnrYb6byTkS5g==,iv:SDzYOuJviNOUeumv7aKYw9Gs4199OwY1Y5COXK78Qvk=,tag:WC+OXkBAbedi5XSpSuC78A==,type:str]
    rw_id: ENC[AES256_GCM,data:aZVbCZA9QtdpnHQ9dEVYoK9FECTEyx0lVTk=,iv:pjp4d5PaWiJUC31EOkFNCmZCUwr/ovNJC3yUshI6S8M=,tag:QCUPTFRJFqcgWdk3baqNzw==,type:str]
    rw_secret: ENC[AES256_GCM,data:qQAdlKwiXnakMbZwVakOZ6MLKuJXAh/XGANRyVBrU63ySkSMAhuSQ70yFOnBcpu0Al1PvupZvOnPa3QaE+IsBQ==,iv:MHZrxcK8kgr51QAxlgv1nybDC5mAeZKxrMTSTMhIvNk=,tag:mTvgHoe3YGcAy0392H8e7A==,type:str]
    release_id: ENC[AES256_GCM,data:y6+dUii6yoZpfmYX3dUuRFaG4MwlfzUTd6s=,iv:on6Ppj1QWZBJQB4ga2g+rmpLMFsAh9Ci2iR4hQtbxx4=,tag:4rx5eHPFESuE+c8iS8J0Tw==,type:str]
    release_secret: ENC[AES256_GCM,data:BTSROKHJ6BLuzGrSR3PRi6/bSDSn07vj6tlSk1+fPCmFhIOgpKR/dGT7e6J73pF+7BF0izM8hiQXoslthQCcsw==,iv:y4lhdRXwahBaEupQ6JS5vDbJYdd5AYgyDiV+R1eIEDE=,tag:NXkSorHEmcKwpHalh5D4lA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWFdJdTQrRit5T0lzSmgz
            dGpjNU9Sdnl0V3E4OHVTSlIwa3hhMzE0ZVVzCnVLd3JxYmlDZHF6WGxaOGRNY3RV
            a1NuL0ZTdVBwVkNzaEMyUm9LbGNTVjgKLS0tIFNldFNpNEdBL2pybVkvR0lEZGhE
            WlFrRkZKYUFhVCs1KzM5Y2psdi9ock0KC4YfzQw7tkblQYCATlWr1MKDFAuAA2or
            L0PWx3z6ZprawjQvhRujL8QDjG31408ZS0SrT7DQxuVmvb+rV5OExw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMkxpaFhRTlZPVHJXUVhD
            di9UYS9ja0JBaDh0NHAzZGZhZlVIS2xRTWlZCjljdjRNL1JtRWhpd1RqOWZ6VE5U
            TXViOEQ3Y2UvRnZobmF3ODVmbkhtU00KLS0tIGxkS0xTRTVLbzlkUTFpRU1wRkZS
            OVpQdnlqS1RNMTJRS08yNElabnRPV0UK6dTTPNk9CnTPC16dOnznDZDblZP2vVqm
            sRt5xT2oVOXa6Upa5h/tQaLdNJB/tyAt+pV48L3RhuncRh4t4SK2jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT3ZOYVpNdTh3di9vMWxh
            d2piREZCZVh0YWRJSm9vQzhDT2VTa0FPZ0g4Cm5XT091S3p5SzdlSmRrbjNlQjd1
            VEcyV01lOGE4TTMycnpBMEtBaWJhZEUKLS0tIGhXOGRkL0taR2NUSlZ6bmlkLzRN
            N3RUN1JRaDNNWG9IUEQ2YnRjME1xeVUK/0swr2uSkt0zXvP8kdkArzN8h2RWk1Tt
            t+04mDU2xcUzs/hrtouzE4gJOBpD6lCzKB5YEVfu6KRp/jWbFUy9Ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:Cw8emNPi+ZZa7A514lg3kGrEeWWJrVNq4Bvl9I9/4aILNwHlOZlnjy6vjtYbmKNITP38FLln1v1BztH2PheehqvdYiHbvccs+IX3LFA1DBFwCHLQSyJlSBGgCGXC4o5pngwH4ZqNUeD8CCAGylchuYhheNHABObab1mU8XPdCPY=,iv:QodjVDnudZ9wKF9tOxD4N4mlXvnsdSwoR6zQiRQeRac=,tag:C9xg+yUukwjHMYuKXaFbKw==,type:str]
    version: 3.13.3
