apiVersion: v1
kind: Secret
metadata:
    name: build-cache-y
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: "y"
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:jS8p+pVe/ROwv/FH9owiL4VqfMdGcxdJsgw=,iv:009yeDLWXLXFUwbEc64pjPmO0iBhKXINIIethooWbvQ=,tag:1YlPCJIHD/UiX46qqcME/Q==,type:str]
    ro_secret: ENC[AES256_GCM,data:QlV8yIjy/0deb6S4oTSofqW090VQ2StQtgL0AkbvB3IoXKCgzdV7X9rYhOoSSflO4px2t8HauWoZKHQH5e3YxQ==,iv:jwLUNmkFBfm3QNEK2AX70HSqgogn0Ss84QxyxyIVeHE=,tag:E/ljlbohUcnZ6Ky9LbDEnQ==,type:str]
    rw_id: ENC[AES256_GCM,data:bF7k/GQC0JWoTFOQN17cJakXeFaMWEtOxao=,iv:YICzlRFjUDmjBQ1yqDWUr0GIdhyJ1/H8c51CUpJs7D0=,tag:FHi0fuOIPvQMIJCFX52NrQ==,type:str]
    rw_secret: ENC[AES256_GCM,data:QqTeB/IN5Bk7CltcOr13DU6zIZwo1V+Pim4zb2CuC0POCHE0JRN8HR+Ubfgc8n4J/UEcZ9Yjl/C8YEYSaYOStw==,iv:ByonQyyVdIve4nXwI0wtO+T3+BNub65nV2s0GyWsQ6o=,tag:LxQ1Z3wQmRHxoI/v6g80zg==,type:str]
    release_id: ENC[AES256_GCM,data:DM5WuY0HJwGzZXJWUsbIwGcLR7B0Ntqmyf4=,iv:a7rbfAeWavq5mFeP99Jey1it+XbzIOIyzYnkR/M9Rko=,tag:jKxa5KM1bMqD0uHXBbYc/g==,type:str]
    release_secret: ENC[AES256_GCM,data:KcXTYXhPcgfBVUEtRusmsIx6RV+XKFmGCGwPcoRb58b3a5W4otu11yvTnQRPukLDm8GofTqNZGVGnJ+dEmhw7g==,iv:DY+v5f6a4QE9wHYygFl2yDCbC73i+K1WrXStlCU4OFA=,tag:et023zXTbFSblTf/h+ZWMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcWplTHRaQzc3S0JOdXIw
            eFR2ajVoaGVoK2tFTHFMcitGSWl4K1pycUFnCk5VbFdrZmNMYTk1WEFhMUtwY1Nm
            b3l3K0J3M2ZRTlRWdjVvWWZEb2JSMzAKLS0tIExWd2o4K0syMkRlRzE1MmJrVWky
            QlVzZld0ZWFJQlAxeEYvRDNiblBVclEKAiz8LkVRVwBSQmK8zBJl4bJ1ts8AuPL/
            Ss2zHbAjItKqBSZznzxUDcRJvmSnUtG1SmWNBjLfCUH3VabwBkgtcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b1BDa3VVdGlYN0g0dUVH
            VHZqNmNVZ3pIVTNsTzFxSHNMRk11R3owS0JjCmZTMjc3NTl5ME53a0RFcnhyWVFi
            U3VxUnRjVVRZcWtQeEV0b1BMQUU4aUUKLS0tIDUrNEFQTGdaVUpOaVFQWm9VN1V6
            YjVHb3pmb3VNS3Q3aWovVmpyUjg1L3cKSQ/5LLwB9ipJJ7c6kB0G+pPKeKCpv9Jz
            5iJ3Pi5JnDRxL0Zu0mlDMnjVNZ2ArIWEaRIcKsqEcn28BmyEx6jSzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cDVPV0g1YnRQREFtQlc0
            NXpkZksrd2NFUkw1ZkZxWS9QaVA1S0ZIOFdrCkg3R1B5NUg4a3NYNWtHUSsxUGJM
            dkxMMERNaW55M1haUEkyNW9ONFlUWUEKLS0tIFRqQTVlOWlZaW9mazcwR2YzZTJQ
            WnhtR21aK3hZUWh4cHZ2WXgyQmNnZU0Kr3wCyNrfl7sTrs/v1Wgf3LMPfhG08i9M
            UQ3Jp0jkhKwiWFGDyFOk2qxArr/m4y7bd9YbSIIUrjkt9+1DS4Em/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:qYq4tmHka0Qy7ewSxVCEugGaCTpSZpDY6xyvy/dzpwJjz0r6tPEk2H3FU01mn0WHIiuhgVX0iLPxT7mQrdGiTUVxsSpiEJhs06wR2dlamBP2ZAWirQkMS1KRuiLiktnpbaBoqEEgVA2SYcw6ztVw56gI2ICDb92FVr3Dc+c/0OU=,iv:Qo8Kq2qG8Jt4BRhr5cDcyIqQaFfw/qNjKziDGY+43BU=,tag:IRE7Qr4Q+2YkqlD726fncQ==,type:str]
    version: 3.13.3
