apiVersion: v1
kind: Secret
metadata:
    name: build-cache-y
    namespace: build-cache
    labels:
        infra.fredrir.com/build-cache-project: "y"
type: Opaque
stringData:
    ro_id: ENC[AES256_GCM,data:WMiC/8YQAokWpbhy9MOb/xT5bNHTchDRuE8=,iv:009yeDLWXLXFUwbEc64pjPmO0iBhKXINIIethooWbvQ=,tag:mWsRtnaINLI0YdzkpoD4aw==,type:str]
    ro_secret: ENC[AES256_GCM,data:wUiOJoU1u6S6Jwusqd/no0jIwWwtXtzExR3uENIK/OiQsA4qZuUVE1qgEfG4mL0yzMtPP6RPUBrJ9NVmYD2nlw==,iv:jwLUNmkFBfm3QNEK2AX70HSqgogn0Ss84QxyxyIVeHE=,tag:qb9dbBzK4gjTHQN54LXHTA==,type:str]
    rw_id: ENC[AES256_GCM,data:M2AeOYB/SVTXP76UJont2R1OciY+EC9eB80=,iv:YICzlRFjUDmjBQ1yqDWUr0GIdhyJ1/H8c51CUpJs7D0=,tag:jBLTje8KVNbYRbg6BP61NA==,type:str]
    rw_secret: ENC[AES256_GCM,data:t0XoMav7Hwi0HdLO0GbG5L89PkVtvuogRHBqAqh9dm3OLYSxFFJu8nB89HfPkNGumS4lTiHNzcouER5+bzaFZQ==,iv:ByonQyyVdIve4nXwI0wtO+T3+BNub65nV2s0GyWsQ6o=,tag:Nmek2wWpWgXa6gh5qW6zLg==,type:str]
    release_id: ENC[AES256_GCM,data:wHCK9zj5o0/zu0Lm3Qp+WuFc0i453qIo52s=,iv:a7rbfAeWavq5mFeP99Jey1it+XbzIOIyzYnkR/M9Rko=,tag:pBUMnqdtXxZvNv3eIZE82g==,type:str]
    release_secret: ENC[AES256_GCM,data:CRsuttQ/oHHe+kvaxBS5inoYpB1fWJ2fEJP/5Fi7ynd00O15kxA3MPRouUWoScMUnnDvF2XrfC3nfwifU6XNcw==,iv:DY+v5f6a4QE9wHYygFl2yDCbC73i+K1WrXStlCU4OFA=,tag:UaRhMdo0EdKKemdC+zhcbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRldiZXJuWUEvc2xvQm41
            NkhTaU91WGZYMnVldGwvQlUzNnF5d2QwQVVnCm5rSWpjbmNPaytlNkNZNFZwdkFk
            ejBlTFl3QUJ6V05MS3ZqZysvUTZIOU0KLS0tIDhtMERrcmxBV2lSbEZLVElLSlho
            aUZVRkZRRHBXL2ZXUm9rY2FVdVRuZHMKnC9BWuz2OyRnVwSbSGEl4rMSAYg4/Cg0
            6MaOnutOZrMFds0RHqfFZMLr1nuPqAG3q/6Kgez3mWzyT5NyrjKkwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N2JXWDFmL1o3Um5DZVR6
            Y0JicVNOU0xXL3BHVmRibkpHUk1rUHNpc0dVCjE3dmVjZzZ1NHlOVUNWSis1b1hH
            dzJrYXZzOVZSRlBlTm1RWHZPQmo4eDQKLS0tIDMyZUNPRVpSa2hLTnpvSG9vU1hE
            WVJpRjhkbkJOSzJsdmg1cHVmUXpPaVEKGF+rfuEqhLvfUkgb2MPd16Sb/JSO62I9
            0MSFearzNsYLJqi04hYWtgf6gdZVW07XBuUmmp39PWrXJCkREqhFLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFN2cXArS3E4c3NlaHdG
            c1psSXdsdGovZlJOQWtJZU02cVgzR2ZHQVNrCkpWNjNGaXFLYzJ6cGhtRm9nalNj
            MkxqZmFVVkRvREQ5OUgyQW1TNnp0Rm8KLS0tIFcvZmcyZjRaaFlOczJROUJXWVJ1
            U2VRZVhoc3IyVXhkbTF0eWlFbVdIeHcKE/sAHSu7K0W8Lwhh/kua3eP65zAWSGmM
            T219cAnPulji/d6KvscIVwJkV7kRIrenyGh2PHuU4lzvLMmwM+gkkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:eViGY9kOcnsqhzX9u7rny1N/z6abbEt8JhO1yrlLaO8C5G1eI/kuP+eyXpHxmUZz6pyY6dFs0aPYy7yKNF5aca6CHJ3xCv09uS2rkVUmDnsJ4bUra8Tg37TOzngnH32GVzPUzrmoluyGbRSQPXO8tUCtymTcpX6eWjkLcbXoLQM=,iv:xmh16mBbAZWKnXmU+8qQf00ieMS553GKOkUINJC8Oe0=,tag:d9qHaiOBEHkiwyKXBbEhsQ==,type:str]
    version: 3.13.3
