load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "artifact",
    srcs = ["install.go"],
    importpath = "github.com/fredrir/infra/internal/artifact",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "artifact_test",
    srcs = ["install_test.go"],
    embed = [":artifact"],
)
