apiVersion: v1
kind: Namespace
metadata:
  name: netpol-canary
  labels:
    infra.fredrir.com/managed: 'true'
    infra.fredrir.com/tier: platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
