apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: llunde
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:uUXlRqDF2+70OBLLbGPqOi85kOHQYwqPDYrOAIaxoEp1QmGQa0hbqs+86g==,iv:Hk+HUbicN3RSe19OOULCSagR0IdtJ+kwviaAH7xCQS0=,tag:eoamKaWZ1gay6Thb4ulJuQ==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:tDhsH5OMn9zK3TgNIURjqly4VkwkOEO0AuQD,iv:I2pApII5KGZp0DJfNkHW+aT1RKOQoHBRZG4I8cwo6+0=,tag:YtCA6axTz7XlmLb9Ua9REg==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:5asX+EFaMcDKesT3U8pTmcQ=,iv:C+AO0WolR5cCDcDWHZa3M3r+keqQn3yEiU9BpTfvAMk=,tag:pRgbEgG8YkLdL+WGTChYcA==,type:str]
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:PAUcAmyy/26HkJgyxoNSG6Y47XIEBoBkjHgCSKLetQIGPfs=,iv:JP6ndcQg32V02/wYGMH01OHq9TtVIuwELiShqmWyiAg=,tag:0JihnAFJUyA5W1eTe30pmw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:YoRdBtFQH9U=,iv:xB3R/pCv1cZGS7UkYgl26+Uiif33O/QIOL27xCcp/j0=,tag:rlYXsRYwjUJTQLsCASo3ng==,type:str]
    DB_PORT: ENC[AES256_GCM,data:kszQWQ==,iv:jLRGhYOW68CoKpUaumKM8C5BOTd+D7iI4hYn1AQB/zQ=,tag:2rs8ClDzlHc4PVamYlyGng==,type:str]
    DB_USER: ENC[AES256_GCM,data:ZnhYVmr/,iv:WhFs7DWZrkYUHcgMU5tO4+AU22gsg/zEc0mHKtehYAE=,tag:WG1atspJBqR6uuHjFrvrLQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:YPE+6jNy,iv:Eb6MvD3YfgfvQMtNUQsY15HDh6zj7earYK5BycFyhCI=,tag:cCXVFUfkNfSZ2quMDMsrzg==,type:str]
    VALKEY_HOST: ENC[AES256_GCM,data:vaOwwNxM,iv:MWutOIOZERTkorxwMhlT1ir43QRsIV3ACx5U+iFps8M=,tag:FTups221HAvyMM9+B3bOhA==,type:str]
    VALKEY_PORT: ENC[AES256_GCM,data:nR8O7g==,iv:BXiF/KzT02c2Y27ksNCfeEkg+V7UJjKUPUXVNSYUkuQ=,tag:ZocJzSTOEja1crP8958t0w==,type:str]
    APP_ENV: ENC[AES256_GCM,data:1BjcxQ==,iv:21zyx5I3zW9iuBKiN6t2JqB7iPe8vZOz/+q80U0nD0s=,tag:obHmCjjerR8FZ9+zm9mipQ==,type:str]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:j+tSc616Lfk/vPYCc3396S0=,iv:CN9BmiYbUdm/cTVibibq8wH2IMPeApLW5IdxW7mEQgw=,tag:HP5Jp5DxiyCzotmrhoK5Ew==,type:str]
    JAVA_OPTS: ENC[AES256_GCM,data:UgP+Qwa5+iYt,iv:8PKJwd/RSNf0JHj/qZHAj5dT8+2gMkoHob1jOEanCRg=,tag:gCe1vzDy2FRlzp+GP4VOYg==,type:str]
    HOME: ENC[AES256_GCM,data:Cn15gA==,iv:2U28ENnxqx30mlrutpb4w6CfqkGgtEqlfjfh/NfIO3I=,tag:Y6IzWeVpSnnX6t/2/8wUgA==,type:str]
    PUBLIC_API_URL: ENC[AES256_GCM,data:3N0lAy4kdgoiZcyIs8EQgchHUjGr,iv:daKeHgnyDdPsn5fsrPRNn8p+aL6prbuyfZVHEX5VuLs=,tag:qSuehWlOi5sceATAV2Xzog==,type:str]
    WEBAUTHN_RP_ID: ENC[AES256_GCM,data:U/mAwJZW4eGG,iv:k9dJ+jZO55ImqDOiQfFRaRjnXyqjLYNEwJq2vs66NT8=,tag:jXL5RnWcbgYEUCWYF19szQ==,type:str]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:IeYC6KYjbSNUDQ9RMLNxGVR50f79H1urcM7KGWgGcGxQgg==,iv:9hJ+EsGfGS/M9npKkS+VyBp/YSeFsPzHxdoPUJU4ftc=,tag:KITnmam/YDXCun/SOHs+WQ==,type:str]
    TWILIO_MESSAGING_SERVICE_SID: ENC[AES256_GCM,data:JNxVp3l67Epx3sKhGRLhxloe45IiVsip5FvZeoiUUWHDEA==,iv:7lQaYF/ITxC84Zb0/V1GIslD/28s8ZYP9nQMpgRLV3I=,tag:UpCbNL0/5KdE9Wip3oyq0g==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:L0/oIfheBn78Csq98AGEtV8Z31vC4xKxLMqM7JPuVv82NJydoK9Dv+hOW8XVNkfsc1xoNzo+6+3wi5lQytsQ79zsMxqqZhiE,iv:gFHe7w+V7sElz/Xmq9xFZ8OsaGtmpJ+Xj+friSvkKXE=,tag:aj5LW/TCSuAYNQHEYnlAQQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:4jpkA0bxjoJ8ph2FAaM2ln1PiA9awVGaUc52+HsFjwGSiuY=,iv:icTbjXorL9IECdTvf+pUDpjvKyu/2j8OUOJmG2t4/AE=,tag:s1zCf3SwuxyLt7dDG84uGQ==,type:str]
    APPLE_CLIENT_ID: ENC[AES256_GCM,data:Ikg5ne0WE5pf46f2mw==,iv:t1AKzhWjtZ8L7TCzVcvb7DxmoeVwqKnZ8UxRliZ/PlU=,tag:XwrHmlHYnKmdKMln7uTLwA==,type:str]
    APPLE_TEAM_ID: ENC[AES256_GCM,data:7iaqyAdRMbULJQ==,iv:2o9XbyQYnM5AuYYUq9xBZirpCutj0XqZzExSQUL/BkI=,tag:urwrsHJL8epQknLNqeETHA==,type:str]
    APPLE_KEY_ID: ENC[AES256_GCM,data:7k5tJJ0vr3YloQ==,iv:UUP7MNmqnIvAdhnYWSsmryYVKSR9dfZmexN+bIaHCgg=,tag:MTBTpGuyzo67pTYFRBmHXg==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:jUkg6JZG0MJ6UgaUcA9W6LvmAfd15hN8qZl0P51J4ZHV+vxzxzJwgmBqbn3UK85md2EkuPYKhcSo7xupV70/ELM1osf8m4EdUz+HvrSiiMQzfNRijdQHwTmo83Vh9luyTAXkcd1DOJ3vfowMEm53UOgNLbGStWLI0qrKTNYMJHbavvBbK18hiQ3cw++0+FDEPiHnu/XvHP+iYXa+/kEX0PL9zpzn7RZSUuLg0ketbr9c+1oBUxmhF2vpL55cXH4IFFd2rs8fqFaprjajm5XLchiABKsCrF2kqttcTwAOzn/YjqP1AWSBgtIIixK1p8d4vYBTCdj23rvdqQYkHq0HWYY=,iv:7QTt1Jg6iA9Q6e0We0MICw4FkOkpWZ+PYvyzIpF6S20=,tag:/Kz+9ja7RYeRNasDsDke1Q==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:ZDUGjXky1ip3UNVotb6SlCM=,iv:RFsj7O5wXiTBkwrGZpVA9dFDEWDYTuJFz7SYudR06Io=,tag:nAHhcjs/2Vbi9qANr89luQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:lh0+,iv:WNDwlaZNqTHzzPW3agNIwOjQHtIIYWP0i65Ljh3OkMc=,tag:BbN4PsshxjgXeI4823o7UA==,type:str]
    SMTP_USER_NAME: ENC[AES256_GCM,data:gRllaFxciINw29c=,iv:/RSc9fW2kkan+hG9njHgGav2kZYpPRarsBqFqXLujZs=,tag:IrgIPEb0fFXQK7IP2Kplyw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:fSvzX4fuQvgnDODptU0z8Rt2XCua5KGfKR3/EXAtDR1jAi9WzJcFOLRn5QMNEgv+GHPJFSm5tDKfgPp3uRreTqRH/Q0dnHsgZ/EhVNSY7lVrMHcrggATTNqhYjVNBfVDvm7QVQR0qS8d59/guvFUlEM/s/PYRIWDIHF4HvUvob2T0R3BiYDSiYuzjydom8w6,iv:0yTEdMs/Q3PUbHyvFS9OLQUl0xg+7oV9BfW8ViRzF5c=,tag:8VuVJPM//xN1hQL+R/gJ9g==,type:str]
    TWILIO_API_KEY_SID: ENC[AES256_GCM,data:UIdMDgyHr/HgGEi4ntTBiht+jy4Wd5F8Sn50RhGZWjKPrQ==,iv:8kTTDxZKHLRoJNlje0Y2nq7R10Nk3bitttlHX0IIyvk=,tag:7colerq31puw24OWL+tr3w==,type:str]
    TWILIO_API_KEY_SECRET: ENC[AES256_GCM,data:sKwl9yX0QRceBF9x/8Qtr+yJJO+RJSyWtXzWHXaADOM=,iv:3y61FDsR/AYcgIyM8/L+zdf1NLVF9OTKcmYggDCoA3w=,tag:hYU+c4/aOgcRzEVFPg1fRA==,type:str]
    TWILIO_REGION: ENC[AES256_GCM,data:vn2u,iv:Hd2/3N3YmLSyikuDgp/Ma6Cy9v+S5E1IZFVSTDJdbvY=,tag:iJmNUj5zpOt3HFUqM4V3Zw==,type:str]
    TWILIO_EDGE: ENC[AES256_GCM,data:v/dFzYM0,iv:IeS6YYmXh6qZ9VJSCH9EZyiSs61nNPfx8OUsqgFlAJs=,tag:uwvtdlEQ+v25DSGhcX2jmQ==,type:str]
    EMAIL_API_URL: ENC[AES256_GCM,data:gsOELNawZO+6+UpAfujtANSdXQD5xYHA+C1bgXW85U5+Sk4=,iv:CBpPCqaN9qmRMjqHwBJM66o+q0Nu5rIbaJTU0XGYJu0=,tag:fsfU6pn0XW1gyrL0x4i1oA==,type:str]
    EMAIL_API_TOKEN: ENC[AES256_GCM,data:CzhHdx2tSQlvxuEQKIrN07hMgGmly2sJyL0HPZOOmCuj5U52Dn3GCvMzcR/+/QT99W7Ly4hPB8gYoD6F9UPrsfBcJiO3Oc/ilY5tnnHqlLR3nLzwI+0T5cLabkOHTti/WEOzbRX59kmdnfmkTUHQrfirJfWg1D7eQt7FYadcnRxWe5L/QQSDF1N35KbrOLgN,iv:PH+QM4IW1OtSCxewWCJpLj3rpf8XAs9wUGi3YrucW+o=,tag:wTEJWtUh6e7McUEcF5Alvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcWJYYzM3MEpEeGZXbVhN
            NCt3NXIvYUNuRXdFd3BzUCtWdGpoWnE5SFJZCk0wVURUUHE3a05RbnpPRllrRVNr
            Y1dBU3JyWmFoTUdwVStuaklNOFZpcDgKLS0tIC9hV2wvbExmeUJla2YrYjRMRTFX
            cTE1NGNUSkN1bG80RXIwT1QrMXZxR3MKbfQkSAqgbnO6IGFPmMIa+BSDOyJBKhKQ
            +6397c9UPsXiMvYstawwEPr8FwWfPfGnhA4h/7SWUWT+IHzoZGxx2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSW8vYk9wYkVZdEkvT1RE
            Mko5aEMwaS84OWY3THBqdHplNkhMa3RSWTBFCkRzT2tmajhMUG81Vi9HbnFqYjdL
            YkUvUHhOOG1ITERlNWUva1FqTmJmbnMKLS0tIGtrTmo0dVdiU2VaMU9GWUppZ3BE
            QXJnaGFjd3RaQ01udExwdDVJalFST1kK+MuzFSt9FOME/iDJrB/7NemJ0kr2/V1G
            a5ahrQ21jm1dnYMiGYZ80yk1KtyWbfuE4Bc0NoVZi6PMJc5xuV58iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYXJVYnRjWmlrVFpjdGNS
            cXF5SkticEdiOEl6RkZvYnJZeVBIL1JaOHdvCmxxNDcyM3dpTTExTUxlUjhpT0tn
            T2lpT3E5ZzkvVlpXKytMYm9QT2hkaG8KLS0tIEFPZk1xemc0QmRxMHRMWXNHWXhp
            eHo2Z2hyaUt5WUt0YjZTcGQ4WW1XbDQKdSZRPrlopbt8bZcZzV0u9RzWXi6tThnu
            dqiZQB2VkeDfFbcJCjRYB5zeX8wh1t3Svaz95fQtA13Afso8z9Ji0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:enHkfJlK+K8/ySzyMHPcu8NBPg34mwNfxzBWZ05OCMUkDX3ngBM3FczvoIKL97/axGmg48FDy1/yDkBL4P3yTOEMg/uq578HEZRVNcZA+0LhUl+Ou8pmdPJ1glxL3JcZ2jp82Fz6byXbO1gSdda4ZCpbfbhFRmEsLD4qnVLWr+I=,iv:JNfbZSjC3dOWCirN/DPSz9/Cv4BlZV5mwgUjfBQephw=,tag:3s8Rre47yjy4+nyASRvaAQ==,type:str]
    version: 3.13.3
