apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: llunde
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Pe4FriBpTanTq+M99o5GAqvoScnswyTtJIZbgR9FQXfRHoM3Kzlfiv/isQ==,iv:Hk+HUbicN3RSe19OOULCSagR0IdtJ+kwviaAH7xCQS0=,tag:PU2wCNBp0qDANqO/Njz1eA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:yN/zV+x07Ez4SRrcXamjO7cbJENUiBL5jgAP,iv:I2pApII5KGZp0DJfNkHW+aT1RKOQoHBRZG4I8cwo6+0=,tag:JxCgcMf90T53OcAM/TiZhw==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:Fecjl4Mf2rC7hyJrYnZxhkU=,iv:C+AO0WolR5cCDcDWHZa3M3r+keqQn3yEiU9BpTfvAMk=,tag:IjGj45GsVOOkhNnF3XXivA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:O/0DNnHaytkjOw==,iv:JkJPrrVGJx++2aF1pCTX6bOtbpJVecyEI5vzAj86qgQ=,tag:zUVyW1qhYz/MrSt9C2TUVw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:1WuNJI0s,iv:Fa1ZcjbIFlj+KdfIeY3wWuCv4ytvkjWxsTR3BnkGi38=,tag:seqxFEBPKZs88RjQQI/Uuw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8/6WEG6jin95/mxZc7TU4SGK6TEdcBYzjBV3bfkUjDqFA6UoyY7m/rSvHg==,iv:2fTZslCQrhDfUuYmt8XkcNAkPdrA61mCfAd0O6Rb0oo=,tag:1gi/izKFCmQp2qgT/I+n5g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Q5+u+DaT,iv:Y52TFkrTKdOvB/uVyGv0Con10dSYV+D2kWeD5sh+XpQ=,tag:lI2uTxcBeE7gV4kmaEg/3A==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:qkBkWagzyL40H9Xr4cKp9JW48B6Fu6We2clxv9+L2raeQYA=,iv:rR1sWfQQgW0R2lrM+UgCdieY0kbio8i52RqQ61p3wfE=,tag:Y29npCrc5qRatpKfCx4IzQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0cUKEl5lPquvwuYooIQd0AqsgASs9LWyEC5MmZNCG/jbeaP/czMUZ3D3s04=,iv:GlvUcybye8INLFI962qtwl2F+6dbTqLU20dHD2FXBuQ=,tag:MHNAZm2dlaoVDuXqketWKw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:sWpQ,iv:VCwbCwrANdi7MC3Up0GSwHYdEOeNNyj8i3MAHexundM=,tag:VaJkhRVTZR66jWbmTvqs/A==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:e+Rsxes=,iv:Akfm+Saf8YpZGverGm2CQqxj0jr19citx6O9Hmyj6T0=,tag:pkgoaxmOnF6DZzPLxbaNhg==,type:str]
    SMTP_USER_NAME: ENC[AES256_GCM,data:gAHULXQUNhIgE93O3b/jdc9vZyM=,iv:A9cQ8K98TYjIwUnFnwh5Ma6g8p/i+76YXuHSDmjt22Q=,tag:VPjmVE+jSxFVsvXUwD+J3w==,type:str]
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:KVbaIcMWBLdSV3QAJmIjHDW3poAHKGx8xSAo3xnRtnKzvr0=,iv:J6XJSczHWxz8QI5emHsSLZsmi/Yz3x9uzA6Kq7x6kSU=,tag:vZwCGyWEd3pFWChce7BJ/Q==,type:str]
    DB_HOST: ENC[AES256_GCM,data:9Kq011Pgqz0=,iv:xB3R/pCv1cZGS7UkYgl26+Uiif33O/QIOL27xCcp/j0=,tag:9SAKgVGasqYKuPTpoPL2KA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:Eel+hA==,iv:jLRGhYOW68CoKpUaumKM8C5BOTd+D7iI4hYn1AQB/zQ=,tag:1avkbuzNiEe9R+1LgpuUGw==,type:str]
    DB_USER: ENC[AES256_GCM,data:Q+bUANBh,iv:WhFs7DWZrkYUHcgMU5tO4+AU22gsg/zEc0mHKtehYAE=,tag:Xrte4PmgxGoRJcIgcdIjMg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:YPsbYuOL,iv:Eb6MvD3YfgfvQMtNUQsY15HDh6zj7earYK5BycFyhCI=,tag:Q2TXEPMMZFYl8GU2uAIGkw==,type:str]
    VALKEY_HOST: ENC[AES256_GCM,data:xw5qD69M,iv:MWutOIOZERTkorxwMhlT1ir43QRsIV3ACx5U+iFps8M=,tag:68pXPqEQ6taAlCN0/cGwYA==,type:str]
    VALKEY_PORT: ENC[AES256_GCM,data:3PgLqg==,iv:BXiF/KzT02c2Y27ksNCfeEkg+V7UJjKUPUXVNSYUkuQ=,tag:JvFOnvl5np2zAe7pKXeunQ==,type:str]
    APP_ENV: ENC[AES256_GCM,data:udynfA==,iv:21zyx5I3zW9iuBKiN6t2JqB7iPe8vZOz/+q80U0nD0s=,tag:9LA0fMURpJzLQxooib+dJg==,type:str]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:APyqNuUfQuJ050n3as2mQTk=,iv:CN9BmiYbUdm/cTVibibq8wH2IMPeApLW5IdxW7mEQgw=,tag:jqVzGkmTB1U0T1XU84MuOQ==,type:str]
    JAVA_OPTS: ENC[AES256_GCM,data:K+gzpKC1xRkI,iv:8PKJwd/RSNf0JHj/qZHAj5dT8+2gMkoHob1jOEanCRg=,tag:0+VkHXlh3gCrlCrF3ZyUdw==,type:str]
    HOME: ENC[AES256_GCM,data:uAhTbQ==,iv:2U28ENnxqx30mlrutpb4w6CfqkGgtEqlfjfh/NfIO3I=,tag:qvIGw//Lv2wqNtUcuxIthw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc0kzNDhGRGVBejdOelVU
            Ukc5b2E1ejU0UlRjVDJIZ2pUbFpZdi9WZkNvClFVWG1ObjBRNFQwSVBwOVpkRmYy
            UFZhbnh2dUszMmZIcDRSQW9vbzlMeW8KLS0tIEV0cmdhR3VDRTlsTzk0MVhqckNu
            bkNLK0R5azBaVENBM3E1Y1BMZjZlYkUKoQIhafX+AJ19M58z9iDjrS0duslQhRhT
            m5i9InFxdS7vseRavhNYzzW4rJbdEB8mgMdlduoYm34WsWKJltyg2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2tWMkdrejc5RUJwemor
            UkppTnpEVXFyK3BNTy9hUDhFZHQ3SlQ1QldrCmhQcHZSOE1sUGkyS0orWkRFck51
            aU9QS1BhZk11QkpEVTJuekFMQTVzY3cKLS0tIG5VSEVqbXpFOGtBUm9odlAyUWxz
            N1ZHeWJKZGV0U0NiZjh3RHZrbm1nelEKbaSTC7IgXACrq6I3DhQk+j7+QwMPSnbF
            38XaUZBZ/p32kf8alauBFMGNaNKkeeuSpFuvUqY5/JjZvMO2f6rBhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTCtTWDlYWXR6UmxPMWZ0
            YVRQNjJUK041cFBPSlNxbW4wa2UzL0V0SjBzCklpSHdEcEpXZWJQUTRjY0xPSUhm
            OVEycXlHNHp5VWxVQUxUZDB1c1I0QzgKLS0tIEFmanc4bkxicm5CRUNlNm1VV2tH
            RTBjdUZGa0YyTWszVkJ0a3RqaEFhaVUKEf5G2+Fej8zA7V0+H9Re/7/INqfNGDML
            UVIdN2HGKeGPDNWAxoOmykfDanYyA/2P5/ed4ZarvDevxHBVQdbkCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:46:30Z"
    mac: ENC[AES256_GCM,data:W7jRTyuxeADDN9mjvFREsBK3cMMg6Fp2C5tSieh6KMt2wAgmVN3aaA8vFHi7Fruzm45SzXEDa/3/VzTTPGvg855/86B1C39K9PJzBOg+8lF9EUOYqk5X9dl5F5RqCz6ziYlPYG7cEeyEb6v3AkBTfz7eivZ4Jv1Ea/D12GEWrzk=,iv:Tj1z1yg4Lbln/CwdhPM/LEi+yIUFQUYFTZwQTYj4ohA=,tag:kviJvaFphUo0qNo61+mltA==,type:str]
    version: 3.13.3
