apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: llunde
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Pe4FriBpTanTq+M99o5GAqvoScnswyTtJIZbgR9FQXfRHoM3Kzlfiv/isQ==,iv:Hk+HUbicN3RSe19OOULCSagR0IdtJ+kwviaAH7xCQS0=,tag:PU2wCNBp0qDANqO/Njz1eA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:yN/zV+x07Ez4SRrcXamjO7cbJENUiBL5jgAP,iv:I2pApII5KGZp0DJfNkHW+aT1RKOQoHBRZG4I8cwo6+0=,tag:JxCgcMf90T53OcAM/TiZhw==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:Fecjl4Mf2rC7hyJrYnZxhkU=,iv:C+AO0WolR5cCDcDWHZa3M3r+keqQn3yEiU9BpTfvAMk=,tag:IjGj45GsVOOkhNnF3XXivA==,type:str]
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:4vWKokS7/HkNo+uIHfwdrQ9wWSTGiIhLugANoY24iwW9hbY=,iv:JP6ndcQg32V02/wYGMH01OHq9TtVIuwELiShqmWyiAg=,tag:py6pq1CsN94lvlAhTWuJ6w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:9Kq011Pgqz0=,iv:xB3R/pCv1cZGS7UkYgl26+Uiif33O/QIOL27xCcp/j0=,tag:9SAKgVGasqYKuPTpoPL2KA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:Eel+hA==,iv:jLRGhYOW68CoKpUaumKM8C5BOTd+D7iI4hYn1AQB/zQ=,tag:1avkbuzNiEe9R+1LgpuUGw==,type:str]
    DB_USER: ENC[AES256_GCM,data:Q+bUANBh,iv:WhFs7DWZrkYUHcgMU5tO4+AU22gsg/zEc0mHKtehYAE=,tag:Xrte4PmgxGoRJcIgcdIjMg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:YPsbYuOL,iv:Eb6MvD3YfgfvQMtNUQsY15HDh6zj7earYK5BycFyhCI=,tag:Q2TXEPMMZFYl8GU2uAIGkw==,type:str]
    VALKEY_HOST: ENC[AES256_GCM,data:xw5qD69M,iv:MWutOIOZERTkorxwMhlT1ir43QRsIV3ACx5U+iFps8M=,tag:68pXPqEQ6taAlCN0/cGwYA==,type:str]
    VALKEY_PORT: ENC[AES256_GCM,data:3PgLqg==,iv:BXiF/KzT02c2Y27ksNCfeEkg+V7UJjKUPUXVNSYUkuQ=,tag:JvFOnvl5np2zAe7pKXeunQ==,type:str]
    APP_ENV: ENC[AES256_GCM,data:udynfA==,iv:21zyx5I3zW9iuBKiN6t2JqB7iPe8vZOz/+q80U0nD0s=,tag:9LA0fMURpJzLQxooib+dJg==,type:str]
    CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:APyqNuUfQuJ050n3as2mQTk=,iv:CN9BmiYbUdm/cTVibibq8wH2IMPeApLW5IdxW7mEQgw=,tag:jqVzGkmTB1U0T1XU84MuOQ==,type:str]
    JAVA_OPTS: ENC[AES256_GCM,data:K+gzpKC1xRkI,iv:8PKJwd/RSNf0JHj/qZHAj5dT8+2gMkoHob1jOEanCRg=,tag:0+VkHXlh3gCrlCrF3ZyUdw==,type:str]
    HOME: ENC[AES256_GCM,data:uAhTbQ==,iv:2U28ENnxqx30mlrutpb4w6CfqkGgtEqlfjfh/NfIO3I=,tag:qvIGw//Lv2wqNtUcuxIthw==,type:str]
    PUBLIC_API_URL: ENC[AES256_GCM,data:S6JbD4qiVr4KTePjK97KQhvecUBI,iv:daKeHgnyDdPsn5fsrPRNn8p+aL6prbuyfZVHEX5VuLs=,tag:5Jm/iHekpduQf320T3McBg==,type:str]
    WEBAUTHN_RP_ID: ENC[AES256_GCM,data:myShZUsvxNvp,iv:k9dJ+jZO55ImqDOiQfFRaRjnXyqjLYNEwJq2vs66NT8=,tag:LlmymbqpC+MwY2/w7W1RTA==,type:str]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:B5N6LJS06ncyi1GAful+bjTC2vxzc5mVr3mHsxnEL2uOJQ==,iv:9hJ+EsGfGS/M9npKkS+VyBp/YSeFsPzHxdoPUJU4ftc=,tag:7hM0DRTnvcozgzkJTkED5A==,type:str]
    TWILIO_MESSAGING_SERVICE_SID: ENC[AES256_GCM,data:vM80TWple+T0LcA4M0NfjTlnBv+1DHEUP3oCdqf/troMuw==,iv:7lQaYF/ITxC84Zb0/V1GIslD/28s8ZYP9nQMpgRLV3I=,tag:GyBTvadaCRjo+b2LIGavTQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Lk1OZWPVRS43PUeU8lwOhwydKsklm82dUem3ah+epy+t5Vwk+qBy08J4S693TvLj342RqzJxZfVk+pqiiWggkh5GKeps96uk,iv:gFHe7w+V7sElz/Xmq9xFZ8OsaGtmpJ+Xj+friSvkKXE=,tag:PDCSYQPUA/JbTjrqOV+QlQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:hl9jZfdGywYUZqm1DZiIRnHTg2S3w3IuLpKlwpj9P6aFDy4=,iv:icTbjXorL9IECdTvf+pUDpjvKyu/2j8OUOJmG2t4/AE=,tag:ciVsIdFY2kZtRMqNXv4WjA==,type:str]
    APPLE_CLIENT_ID: ENC[AES256_GCM,data:X4fKZnAisyvxJkxlhw==,iv:t1AKzhWjtZ8L7TCzVcvb7DxmoeVwqKnZ8UxRliZ/PlU=,tag:5vBNTMH6ejAlRZmACUdkxA==,type:str]
    APPLE_TEAM_ID: ENC[AES256_GCM,data:zsudk/OquNlmZg==,iv:2o9XbyQYnM5AuYYUq9xBZirpCutj0XqZzExSQUL/BkI=,tag:QnTjY3HWk3+ZWR7vDRR8Rg==,type:str]
    APPLE_KEY_ID: ENC[AES256_GCM,data:Mp3jVELI8TxVPA==,iv:UUP7MNmqnIvAdhnYWSsmryYVKSR9dfZmexN+bIaHCgg=,tag:H/W8dcXqrScZVz3o1kPBtw==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:JpZMWNcp1hBhw1/GZ7t4pVdzgx6WkAo0vmqWK/QF6Rz4KRNA/mVq6xX6rIax/0GeFJgkoXMMC6jPi/HqShR2SddlGIlfRJuyER7oReKEKEBU1P0E1vFytCAxPwqern0/4jCyQAyfQ7d5c2hWTWw7BJ9DZzuhpJkK9ALOndeFVtqHYOSFeOd243qwubrdTszr/Zy2qZ5Zxa/Qfy0TjU4mbqgni2NJC5yPSVKRX1wc8Rp1ZFZCZnSJcgogzDIpVeUBi1ZUfBLaHDPf/oKcl7pyOexotJ4ORVsNqM5vPp7R6Sv8q5EQy3+rkdEegCbspOGbk+/nvrE6icZITyRlJSOBrtY=,iv:7QTt1Jg6iA9Q6e0We0MICw4FkOkpWZ+PYvyzIpF6S20=,tag:SNLiEE9F3+GirNGwNCff+g==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:Iefqev7T5scHtUnLt7PRp4eEEu8HF0yhmFJ3feH5OVbd9sM=,iv:FPTMFimxZMIF8Tjvdxn1PZ47Kgonoe7VQxmnKNO6mEM=,tag:rvrYD4A0QhldCUZRugJX9w==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:zSyM,iv:dv4ZYhYI2Xj2/FdBuNdMv7kr7kCqw0dk9Y+A+rK2rLw=,tag:IwCF2MXVsr/xco7trM6SJg==,type:str]
    SMTP_USER_NAME: ENC[AES256_GCM,data:C5smvS8GuMJhndTyx4005hgI5YM=,iv:YeAFwzRZE1ChBcZacI0dSfRLYr75amPBczuwd9882m0=,tag:kd9ZupBP665ewuI8d4Spvg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:uNLzGaNjmFnI5RpogO2IKD6aDUAFWKem/G10vaIkXiKict9GYyW7qzmNl0Y=,iv:UzbIPDWmSZGpcMOA0SibwfD7CqtWMSYrB7Znw4IBTPs=,tag:iyBn1Es5WyQA4NKHsqUzCw==,type:str]
    TWILIO_API_KEY_SID: ENC[AES256_GCM,data:ihODToXujm+buk4cfk9p0yzgiaDALEdVXcYnmz2GRc77Ow==,iv:8kTTDxZKHLRoJNlje0Y2nq7R10Nk3bitttlHX0IIyvk=,tag:18fl6zzwYbYtM2y5qhtijg==,type:str]
    TWILIO_API_KEY_SECRET: ENC[AES256_GCM,data:D1W2zFPEjnHmMmuFcucR8SeHwZ6AtwGYuTBR1TAv+Mk=,iv:3y61FDsR/AYcgIyM8/L+zdf1NLVF9OTKcmYggDCoA3w=,tag:OdDKbq2VPvpgVRnYcFeDYw==,type:str]
    TWILIO_REGION: ENC[AES256_GCM,data:uXJ8,iv:Hd2/3N3YmLSyikuDgp/Ma6Cy9v+S5E1IZFVSTDJdbvY=,tag:lDL7dfwnXiFkXO/cW3AfsQ==,type:str]
    TWILIO_EDGE: ENC[AES256_GCM,data:muN0dDBs,iv:IeS6YYmXh6qZ9VJSCH9EZyiSs61nNPfx8OUsqgFlAJs=,tag:KMTMFBk3UpoB0dufHaO5mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc0kzNDhGRGVBejdOelVU
            Ukc5b2E1ejU0UlRjVDJIZ2pUbFpZdi9WZkNvClFVWG1ObjBRNFQwSVBwOVpkRmYy
            UFZhbnh2dUszMmZIcDRSQW9vbzlMeW8KLS0tIEV0cmdhR3VDRTlsTzk0MVhqckNu
            bkNLK0R5azBaVENBM3E1Y1BMZjZlYkUKoQIhafX+AJ19M58z9iDjrS0duslQhRhT
            m5i9InFxdS7vseRavhNYzzW4rJbdEB8mgMdlduoYm34WsWKJltyg2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2tWMkdrejc5RUJwemor
            UkppTnpEVXFyK3BNTy9hUDhFZHQ3SlQ1QldrCmhQcHZSOE1sUGkyS0orWkRFck51
            aU9QS1BhZk11QkpEVTJuekFMQTVzY3cKLS0tIG5VSEVqbXpFOGtBUm9odlAyUWxz
            N1ZHeWJKZGV0U0NiZjh3RHZrbm1nelEKbaSTC7IgXACrq6I3DhQk+j7+QwMPSnbF
            38XaUZBZ/p32kf8alauBFMGNaNKkeeuSpFuvUqY5/JjZvMO2f6rBhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTCtTWDlYWXR6UmxPMWZ0
            YVRQNjJUK041cFBPSlNxbW4wa2UzL0V0SjBzCklpSHdEcEpXZWJQUTRjY0xPSUhm
            OVEycXlHNHp5VWxVQUxUZDB1c1I0QzgKLS0tIEFmanc4bkxicm5CRUNlNm1VV2tH
            RTBjdUZGa0YyTWszVkJ0a3RqaEFhaVUKEf5G2+Fej8zA7V0+H9Re/7/INqfNGDML
            UVIdN2HGKeGPDNWAxoOmykfDanYyA/2P5/ed4ZarvDevxHBVQdbkCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:31:17Z"
    mac: ENC[AES256_GCM,data:ohUvFFJFmrUXmMv7hlk/t79mO6zaBkLAc74cFHjMXhRNCcEi6ouMhasHAav0NSzDHcGlMImDzq+AYlFSP79rQI+4X97mSL5GSg5jvCtCZf0TL1mz8c3LotG5oXKCiUY4apexEtnE59JTxz68If8spYyTakPDtNmK40OcaaVvP1Q=,iv:Ei6mYloBSo2RxMNW/IrIaTIpNdx6wHkvBRH0Xb0GrQs=,tag:3pLv1c8N99i9jq9epB7aKg==,type:str]
    version: 3.13.3
