apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: llunde
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:Pfaw4k4u,iv:6c1kcyVVXb2eI8w1BmsOT9Z69KOGwrReEh0oJmx89G8=,tag:ZU29Lgj3ur9K3co4ir2dBA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:I7STmmwr,iv:UAuZDvlz4uQ/AY4orAlm3w2gGTR5Wsrp1yEYN87/3cY=,tag:+kX92Y5ZDLNp9e010OrxiQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:y8hzaIAj0gZHTgltDcJGPPFPvxZE6ghySbHpHkyNSpuqtbj7Kv+8l4K4Gw==,iv:gm/NJ1lWLR6SROvjuRZR0v/HJL4Me/sS/cBoSsKG08Y=,tag:kRPNI9e7vE17be5XDICTRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaDUyTVZxRWFYN3lkZHFv
            bWJYT3dzdjlDd0JFOXY1SS9WbDVlQ0VyQndBCjU3dWVVREJYbC9WOGYxVnRPQm1u
            MDE0OGlkT0ZRbkZYV09wSzFzZ2RSRUUKLS0tIFhuSW5KaXRrQVR5b2kxVnVmUjFS
            eDI1MldwMmVIWHo0aU50dW54UmorVDAK7CfPQ+UcizYvWfUrun+kTGEOYIsKmIMq
            ptQcLgySXKca3S9/wuBiyEzJU9icm8G5PKAjZm+tG/qKKB1GfKOwsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM2tXN1lsUFE3WVpIUHZH
            NkVvQVpZMm42KzBsbDRENDkrcXpRL2xpa1NrCnhvZUhST1JvU2JXS2tlcWFKdm84
            bllXY1dBd3QxWTNxemVOOGlxWFgyZVkKLS0tIDBac1ZKeFhOb0VWeDlZVUk3R1Fv
            Z1VsZlpaWnZwRHRpWWN1R0JrWC9JWWMKAV4rz2SLldrKTHOMjmvl9zsB38sWZwpX
            xol8U2/i/TLR7GFJsZhBupm6PwssWrZae1t5mNZ/T1pnGwg5qxZuPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RXVweUh3Wm41ckN1T0hF
            WjM1VTVZQ2Vycmh1cUVpKzJJTlJFY29GZENBClJZRkVJckpjUUo3QmxyZDdDUDl2
            cXEydjJDODdLTjIrMHNsMG1mOCtYbG8KLS0tIFR2end4Ti85ZS9uM2tpOWx3ZStq
            U0dHUnhicThTdzFDdUFEaE1GN3VBK1UK7iknMsUxD4WV8gY6O6252GQk4BcgEyjw
            kcUizDIqXP+6oVNKS1QhKqZBD8bPumUwftiVcOhTJ2cEz2k+7S47ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:46:30Z"
    mac: ENC[AES256_GCM,data:PbGk9uGiWgcRQEfOJBnYohjd3Z1MCLXNLGGHpunoCS3t9CXrdd9A6GOiRK1UjmMHHFYIZbRGDn68f3nBcnV9SlOnFJR8bHiN2QAjoEVouLAsonfTuBP321La3g38K+QadqdQrLi+EQxGUm4PN5Xrs1v5HWbT4dCM7iSVvd9wsac=,iv:23UQHv0UQbcveD6Ns/SW0YKSrKApoV7maeolJ42Q/5w=,tag:FM1udX6WqLcRX9EUUfaqcw==,type:str]
    version: 3.13.3
