apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: llunde
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:iGo3n7CL,iv:6c1kcyVVXb2eI8w1BmsOT9Z69KOGwrReEh0oJmx89G8=,tag:AQ7Oyzbx6ZrejH/BRc7qvg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/FVLeSkV,iv:UAuZDvlz4uQ/AY4orAlm3w2gGTR5Wsrp1yEYN87/3cY=,tag:PnpXS+aSbruyFd9hVlQZMw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:b5pzeH8b5+vRscbB0qC3gX4mWsGgHKZR4RtjJ70+IZwLVW0X0Q5Kkf4TMQ==,iv:gm/NJ1lWLR6SROvjuRZR0v/HJL4Me/sS/cBoSsKG08Y=,tag:wzz0eINz4F4HJP00/iD72g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Rm02WmZGQ3drR1d1YWJJ
            bE5FRlJBeHRWUGJGeUNOTnRrVllCUTdEaVFRCmpibUNub0drdkpmR3ZScFo4OXVn
            Rkx6RmtFcG9vRWUxKzhNTytnekNFQ00KLS0tIFhqZHVJNUdCc0ZUR2pFNlppSml5
            aGFXb1JrSjU0MEkvUUdiejN0akFGWTQKT/kApP2lxISezEmMTexwVm6N2IPrtba1
            PTwy9xfhOcb67WkcDO73z+ppK/eWOd6HQeunJCJLvbcIkUqDKL3LdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSW40dG0vQjMxQ0FDQ0NO
            b2pLK3Nzc1VZcjlUejBBNmpHeGU4djMzcUdJClYxaUk1WmdudWtqN2pGWExFWlBD
            VndjV2RkWGx1dldjRGpCdm9xWHhDeFEKLS0tIDJ0NnRVWU5RNC91OWJ1ZGxOOU5V
            c2kyUFdDQWJ5RGw0STlFcGJIY1kvQTQKYqWfW0q87IcZRyIxSGptSI7UINWh2eJh
            WNswfOpRfc5c5V+vSsU0nCGqTL3h0ftqjhfwEwUj7ZVBnKcgBj9cNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNWVkdlVnaE9kOFpobjJt
            TUVtaGNSWTVkaCt4cldaTXVLZDA4WndSbmxJCnpxL01LZ1BWaHkrNHZ5MHlYdlpS
            N21oWVZIVVVpcHQrVTBkek5sNG54QmcKLS0tIGFpVHZ4bGF4VDBNelBwa2tlWS83
            Yjdvb1plWWtDZ0h6SytwSVo4eFRTcVEKQYB/tqJcG2nBZ1B5lqtNofl6ux3XEI/A
            nGqu3Rdrc0YQc/hO7JZPSZHKzRYp8INs0+KM57ffK40x/JM94Ov8bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:H9St4jlq2WME8rj/+KIhjgnDaFa8itkwqkweppo8dmvRTW+z3viZev2AQG1KZ9pX5uYYPud9sQ3rDSm0Wxgrx/RMIh+y2IVRZSQwz9UKnGbJPU2mGrkn6Xr42FlV2fj99wN1Q1HE1kXaYwqWZDTKuArUv1mmjV1zjaJ+bQsoJoQ=,iv:AZvarYWWqbjKn4d2O8J6XTL8ys0tSuncIqsyGa6jkAc=,tag:ysaAjcHpAO2EeWEOBTkA9Q==,type:str]
    version: 3.13.3
