apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:yZL3CLf4PNFGJ2JowkmAzAtcVm+6J98CyXTbu0fFW5sp7cvHqNRtY5Jhzee9BLCV02I3sOyFktriTbwwvkG3zCXFKjF+lbDr44hyPPx5TGyXaiBPKOahLa8NmWebB8TTIZg=,iv:ssCAmzwoqmzmnRxqqvIURfx2/0Ge8uvYs6NzZth81Nk=,tag:g5TDrv1RByItgHofoz7HmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSExCMEtjVGtDaWxKWkVZ
            dnVyZEFldmNXK3d1dXpqZGgyU1krdkpQaUNjCldWcStwMDVENGFaSTl0TUh2WU1C
            VjBjdkRvdmduT3dHSytiWnVuQ09JT2MKLS0tIEhqZ0h6WEx3L1o5Z0d4bnB2YitD
            ZCtKc2FFSXFlcXFNdXA4a3Y3KzFvZkUKaue64PCIl9Xngcab6uqJmwbpWZmBKYnT
            3fgsAFIMhZ2/WCXnapOgSr9TpAuj9v3w0ThWNNOKRbpJ9zCfl53+nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML0EwRDgwWmNhdmY4K1lu
            YnBsTmNTQkpDUkVRVVlXZTFjalNjai9Hb2dvCkpWM0ZzaDRHRHR5cFUycXk4T08z
            dE5VOGpsTlduelFQZ1dqTlpiTmkwYUkKLS0tIHlYdEQxTnl3SkJiVkJEblBma3hN
            NXQwV0kxNmZEZ1puaExSUWZ5M0lLamMKuACNAV3EqL3qbzjIq7XS6UwN70dgUI+w
            PcWI9mV0zJcBFu9KXOP9BlGCtY2qqFkw+v5MNMpy/C7QI9H51a7FGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZG5HRi8zRWlRdll3S1pL
            UjBBeWxHelZjTlJHZFhJcG5tR2Faamtza2owCmRrSGxoV1NaRVl6QWVrTEpFNmh0
            Vkh1cFNUN01QZTJJbDJjRmdmdXpTaXMKLS0tIHROZVZLUkZwQjl5TDh5QnBlb05y
            Ync0MVU0OVpJUi9wTnd1eVo4VklzckUK65fMmHX8Pc8Y8LMAUKhaBMn2nEdb0hXV
            4mEOj32TMVLh6EiaHcfJI+tzzzorImLan4UX9NHp2F8YpDmbTlENQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:46:30Z"
    mac: ENC[AES256_GCM,data:yUbQUV2eJL0TQfqPgWo8sIHg56Bnq41dX40GNEWL6t/rKMjbTmV0aXIc3Z2chPc7pHSvAXoRjHqKrzopo0tc678wr4IvviSz6QUhzkU+mkKUH8eFD70XQ6rbEQOpqwAIB5YXWSsVpdIv4yANaZw88g0LyS/atvMOuXL66wI4dwY=,iv:Ww55whBosOyw0O0PPSodquAyql3Cp5Qi/d5QuvX9rQA=,tag:6rumQ67I41jC3BLhsnL+1Q==,type:str]
    version: 3.13.3
