apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:65HdH1siwchL/93kYYHxYmKGlikOWhvfVWzera/HjcVnLYp3WJinHXKfid8n86fnG5PpudaUXVcpkPQ/2y+l6kGm9kOXVUaOyTFXbpSH6djzKyhTmYr2NiTYg6dxyEwb7A24QJzMja/dGSLgHYyKg4lccEeOUea6tvQT2H8m6a94ZmA1DdAJ+gUbL0NhuNwkP23BCGMUhhjr01ALtGnNo846g0e7xULzYYbSlw==,iv:jv19ilZBBUfBwelrLjWIJdmLBnmGOrU1lTnPF+ItIKQ=,tag:6sZPnyFh463Yh8iUSB8osw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcnMwZ2hveW1kemZ4T2VQ
            WTR1RWxETU9mcitDZnNUVkJZczU0a1NoWTFBClVkT2k5WGVvMFVucXFHWnJ5S1Rk
            SVZjdHFTcEdLRmxWRitjdHh6YTFnOE0KLS0tIFljT2ExUmNNRzc5YVpoSWN5MW9Q
            TUw2azYyYU53YTZ0aEtmak9Na0JqZWcKSTJ8Z0zTt72j2+Kfz+i40YmgDiGmHt01
            abO5tNHu9cz6OUSfO2p10yZiQvICX7IyMe5PXkBdQkGKutqyM7gifg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUJ2eGtCQ3V2MnczSHlF
            OG5DaW5JSVBXWitFT2xpeGFDeHVaTWFKWURvCmNXSVd0dFJtKzZNcnUzM0dFNG9v
            NnN2S0ZIN2JIb0p2UmdZazVhZlRVSHcKLS0tICtpUUZ3a25ZMUh0Qms4cWFPWXlD
            dURZZk1IVCtBYlZ3ZTJnUnNMMFlicDAKcqBmbMdNJpjRDJ4TmSPx2S/BiFgwBqvE
            Qb4audOqd+T7GqNFj0KGsFqZykm6GnaQBay8ZoAujDQy0zOYleolaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZDJDeTk1MnRGSW1RSE9C
            cGY1WmV6UERXTlgyUk5EMlhPTnJNa2VZdHdvCi9sY05mNUtwZmh6WXU2MzZvWFY2
            dXp5UWNIcXdqMVJxYndSSUZMaDJheGsKLS0tIERaYmFZN0xDQ3BScmw5bkgyMnor
            eXB4M1g3bnlUUWlxb0x3bmRKeDFnaFUKYjMMu1+XAXYdGE7GxuyexETAiUokYg2g
            bb+yAL93jNhtxNDRtH80FLMfUD7xvIHnnE4DyxGsWJ68wHzQkjgvEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T13:33:18Z"
    mac: ENC[AES256_GCM,data:6v/BDX5oPXcsFUC8XSvyIWCmjSWkIq/+MowG5ZcpaEdub6N+0+9aq0s1rRm9uIuRrA++mtxR5B9667iH3UOkeH7pElwN4nJrGvwe5g0xdDDEKz7NizP7yxm/LYmPM1WxP6bREjJyejXwrkndvlafwJ0Q10lJUykfboYEIJ1xlVQ=,iv:+CRfxCCoP6aJ0c/nB+A3EhlKI9WmCSoUiuml8TqvC/0=,tag:LDEh4SL29IEwoygkBIN4vg==,type:str]
    version: 3.13.3
