apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:09bACqjj5ShtfLaUW+6GgD4HTSnAb2g1npZpRhVagOiY/72aQ/Txc+atYqdniuBZgJltxxdfvVzJNvyfCxWQLjs5NdZAFbYd1dWvpl3ovLgw2t6YnTebsVbpw/ylH9tX9YE=,iv:ssCAmzwoqmzmnRxqqvIURfx2/0Ge8uvYs6NzZth81Nk=,tag:QxvCMnj+fOdUKw/oB4hwgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcnMwZ2hveW1kemZ4T2VQ
            WTR1RWxETU9mcitDZnNUVkJZczU0a1NoWTFBClVkT2k5WGVvMFVucXFHWnJ5S1Rk
            SVZjdHFTcEdLRmxWRitjdHh6YTFnOE0KLS0tIFljT2ExUmNNRzc5YVpoSWN5MW9Q
            TUw2azYyYU53YTZ0aEtmak9Na0JqZWcKSTJ8Z0zTt72j2+Kfz+i40YmgDiGmHt01
            abO5tNHu9cz6OUSfO2p10yZiQvICX7IyMe5PXkBdQkGKutqyM7gifg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUJ2eGtCQ3V2MnczSHlF
            OG5DaW5JSVBXWitFT2xpeGFDeHVaTWFKWURvCmNXSVd0dFJtKzZNcnUzM0dFNG9v
            NnN2S0ZIN2JIb0p2UmdZazVhZlRVSHcKLS0tICtpUUZ3a25ZMUh0Qms4cWFPWXlD
            dURZZk1IVCtBYlZ3ZTJnUnNMMFlicDAKcqBmbMdNJpjRDJ4TmSPx2S/BiFgwBqvE
            Qb4audOqd+T7GqNFj0KGsFqZykm6GnaQBay8ZoAujDQy0zOYleolaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZDJDeTk1MnRGSW1RSE9C
            cGY1WmV6UERXTlgyUk5EMlhPTnJNa2VZdHdvCi9sY05mNUtwZmh6WXU2MzZvWFY2
            dXp5UWNIcXdqMVJxYndSSUZMaDJheGsKLS0tIERaYmFZN0xDQ3BScmw5bkgyMnor
            eXB4M1g3bnlUUWlxb0x3bmRKeDFnaFUKYjMMu1+XAXYdGE7GxuyexETAiUokYg2g
            bb+yAL93jNhtxNDRtH80FLMfUD7xvIHnnE4DyxGsWJ68wHzQkjgvEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:ukoaxcrtzhHnPzTB4e6D7mLWr34rqL3W+34oMKLsGSqST11rLMVAFC2f2GvZYHjDfw52mBsRJT9Mk00CEruICZzgVNS7vGdZ6KKOwX2WCn/jFrht7XtWyFdVAKkU0CepCtj5wD2Vq+94Tal+uXWeYAwprdTrNJgLk7912bejBeg=,iv:0K3XHlW1dw7vO+r1mvQpdl52dONK0TPGR2pSh0AFPak=,tag:QvCh0l7+rCRzSeitYcapjQ==,type:str]
    version: 3.13.3
