apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde
resources:
    - namespace.yaml
    - database.yaml
    - application.yaml
    - valkey.yaml
    - ingress.yaml
    - network.yaml
    - database.secret.sops.yaml
    - application.secret.sops.yaml
    - tunnel.secret.sops.yaml
    - ghcr.secret.sops.yaml
images:
    - digest: sha256:05b4cff6f2d66dde3ee2d0b7da64f7ab0dae84bb4016d9a9bf7e7469ad30daf1
      name: ghcr.io/fredrir/llunde-backend
      newName: ghcr.io/fredrir/llunde-backend
    - digest: sha256:6a081fbceb94d6177fcaefaf5e1da853710a70b29e41702291427817c2c3f8a9
      name: ghcr.io/fredrir/llunde-frontend
      newName: ghcr.io/fredrir/llunde-frontend
