apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde
resources:
    - namespace.yaml
    - database.yaml
    - application.yaml
    - valkey.yaml
    - ingress.yaml
    - network.yaml
    - database.secret.sops.yaml
    - application.secret.sops.yaml
    - tunnel.secret.sops.yaml
    - ghcr.secret.sops.yaml
images:
    - digest: sha256:0118764bd0181f08c07f1402f9423aee814931b0499abb7bf5de37e6bcfc7cee
      name: ghcr.io/fredrir/llunde-backend
      newName: ghcr.io/fredrir/llunde-backend
    - digest: sha256:5a020d64ec9ef99ec2d8fd6d74d765dc75f252c72fd3de908c848db4aeb12141
      name: ghcr.io/fredrir/llunde-frontend
      newName: ghcr.io/fredrir/llunde-frontend
