apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde
resources:
    - namespace.yaml
    - database.yaml
    - application.yaml
    - valkey.yaml
    - ingress.yaml
    - network.yaml
    - database.secret.sops.yaml
    - application.secret.sops.yaml
    - tunnel.secret.sops.yaml
    - ghcr.secret.sops.yaml
images:
    - digest: sha256:b1fe2ff7917a9d7b9046860606334d54d190d35f3929cb57ca6c8df63e7752f0
      name: ghcr.io/fredrir/llunde-backend
      newName: ghcr.io/fredrir/llunde-backend
    - digest: sha256:5a020d64ec9ef99ec2d8fd6d74d765dc75f252c72fd3de908c848db4aeb12141
      name: ghcr.io/fredrir/llunde-frontend
      newName: ghcr.io/fredrir/llunde-frontend
