apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: llunde
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:8BsDYP3T4ZH2CJciQoT2GeoNFI3DjdAbjGSRNE//O5r4REy07nmjBEji7D+qVPbpm4zAU0Nu1vLklSV4Y83VFV91cy8hd4RyHSyCeNeeV1aJR2+5rP8/XW3Dho2V2opBxL6cp8VW82z4IRM9c/nLyoqMLIw8m+TCua+wb8/FtrVGDuOalodDATzwpCmUbYgYCyYaWYpVhGoFSgRgosfG+hMEXy166FNC7NDWIyMF4XbPMm12dAwJXXwxj/gQe5m0fvKFf7Fo43hfYQTMYp/xl3MArANSnJHcE85Jh5x8VqH5UlMaRBwLhyyxfLtsOvPg,iv:pnzlmFdY/EhDXMZA1rTeOJfYIwzRN0vBXRKOjMpgyhA=,tag:9zUjjHiq8fPRSwLhkhYprA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUUJlbHZYYld1UEpDalow
            ekd0NUwyWnVyL1JjRnRPTElnUnMvcElzSHcwCnhYZTF5cmV4UjFWODV0TEZzcnZC
            eHI3Ui9vSHJTTXJiaHVoN3p6UDd3V2sKLS0tIEhhV2dDbVdUbUpkdGphWTltd1hO
            azNSd2Uyemx1aWx5bFE4UkU1UHpuUUEKpAGwWYPnmiFXvVbg7cbkOU5SZzUqT3G8
            W8BEp06HHwNHOl+TU1QgdBYFd5MJfeXiQsxL8ZRvZDPvuLnQXz1VEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaDl3d0Qrb2ljUTdzc0hF
            Mkw2eW8zV01Wb2UwOXB5ZVRKelpsRmliRXdZClJFQU0yTnlpVlRIVGVhYm9GTHRi
            OUZMY0FlMktkUzZCSHc5eDl4eGNJMm8KLS0tIDIxTG9YVXAxRVN6V05COHhtamNY
            SGYvVTNmQWlXSW1taVUxOVArMWg3NWsKTbOrOATXvzk0CzLr72ZOUeekj6DBK4Bj
            NzGEX64nRe8aSHWb7vcYs7gKbpSIAqoEVDD60z/3eDNrtmA5/hWq6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS1N5dEsraXhIVExPcThM
            NjlZamZjOTFnYXpBbFF6RW5UMmpxY25tNlZZCmVBZGZGTW51aUtIYWhTU3pJRWx2
            M3QrdlBSK2NYbnV2MTVSenBYV3FUUGcKLS0tIE14cUZ6M2E0Qms2N0N2anllT3Ry
            bDhnOU9Yc29BNkZJNHVtb3o4OC9ieG8KWRaaOJMNiLKQO8MdxnHm8Ion3YILOXPy
            m0QjCeKpeeGkt8GWQGoEFmD+lgXckwCfCbLTVO34qW88XROlqbqS0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:XXRrbTEYEUGt3c7nmTq7Q1eXVwJj2oxdos0m3ZakoVSr1HoB2/MsvQiNOBKs1nv5p7O8vaJ+l0cgQlnD5p6rLrskwsdFMYQsvskIIrYg5J67kcbzqgyl5YpCBAqYrEWZa3KbRfytZ8Oy0vdEbHM3TikjLvA/y7aEg7GURMLX1Ns=,iv:RzzeB0ZUAlbz3vXEPH5cWi2LeR6dEvZP+J4fZtcNc2Q=,tag:6lsl+rdm4F52USg9ku9b4g==,type:str]
    version: 3.13.3
