apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: llunde
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:NC0e+SrFMADVfWJwibBsDx9SA6mEiOMjt6SoAZO545gBnEV6tLysQoK2EW+BqzuOtN5dHxrGjGqNl61B41MqRAYqOYYt66Ud13Su+FNJ/P8tcFPBdoCH+zkAX1jz/u82/et7fRXuOysHd7a2jp8/3h1LPZwluV19zxHJx0y0aeAWSZ8YEQJL6xIft4fGywomrv15yfc1o5/FBmiI2sImmoyjVNm2eDdXJOs3+NlQ8Abg3wBffhXfYbmoIuqf4rOnHTRa3k1y8tfpLcKn2BLPk26BmYN8KR4RaX/fjv8tDJ7+NwXElyPxIxAhXr1OmUtI,iv:pnzlmFdY/EhDXMZA1rTeOJfYIwzRN0vBXRKOjMpgyhA=,tag:XPSDvapV/wOYoXVqPrmZUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRklKOUtCdEJGVk9YRkxK
            OGJCWHJFazl1L3YrMmdqRmwzODFPR2o5U0JFCk9QNFVWOTNuVlM4bkdmbUd5OWhR
            T2JDYUpvTVU2bCtYL3BKQ3A1U1pJK1kKLS0tIHJSRXpoNnlKZmZuckVHQjU1dlJp
            VDAxb0NCUU9FWU5VM0wwTURFNUE3bWcKBw/uO6KkFsn6DQL8/qo0+IP8JK+5s2gi
            dzpMCDh0kSay/cap9gHOy46+utCPbTtFrB3jSkvOHwNlPe4koJGVeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN21uTCtYTkdwZGR1Mlhl
            NTBFZHY5L0t5OEx0eXd5NUJPVDdveXBlNlRFCkJ3aElNSXNDVkFtRkQwWnRndHRV
            U1g3MTdLLzVibXVEQnFDaCtxZGIrT0kKLS0tIDh3MGJGR2pQZ2o1cUNrOFd6QUVR
            dkJyemNxYXRZbHZrUkJLN2xZNmdLL0UKcwEFheaxcGYWYMbdSF7n3pq8PSSKi/ih
            5hOwBmVyV/z7Y/zZ3TurDJ4/18OHHWDFRTXcAj+u+kMFj5wc2fNqsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubGlWWXF3VGgxbWhPamho
            VTd6Y2VlWU1BT01RYmEvRWUyM1NJMFIyZUNzCkU5cHVNSUpPUkg4N21vQUErQzlQ
            cmZjMVl1N0Zrak9ucm5WMUFLWWxyZ2MKLS0tIDZ1b3FpeUxtVTNYVWd4cWRWbE9Z
            V0ZITEF4TDBGSnhoVjhxSEh5YzJWa3MKMkFVek1JJbpw1nwKcWOBFolIOUh1Y3Fg
            hiGZg87TmKrvE2FitI6te9D0mGHJjeFxcgHrlD2V5hkMB4T0RB5yyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:46:30Z"
    mac: ENC[AES256_GCM,data:EoIgE1r9376KlxEuQ1k6ADVpiY3V6as47bPtlB4PLss33QoZov6XIUjVxCgY5U7Vmi7uDopYrjTQlHQtwv6fINfuZq+vDKuNFfT5ijX17fHQJDHicH4HDduj8hEVVLSLfEcQI9D42pxKI+XzJNKglO5ASR6HZh2yMIDCpYLk1jo=,iv:xasG4C9pCsdXp46qP2TjGXpDt3O831pwkEr9tjBTC0s=,tag:EMTJVaTeolTehUwJyLzUHQ==,type:str]
    version: 3.13.3
