apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: platform-backups
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4ml6vYF7p04beAwRRaX/cH6RKQSGua6uvuUCYywl2sWh5mJxj5QtMM9y4YasqaDDRG6LLdclGnN1mPt89hhTCSRX2o578BYbQL5XN4I=,iv:dPmioun1vlCy9X0FdliE8XnObvRsIS3D8GoCgpinhSw=,tag:qR2TMHKYKzJfAESR4cB8Ww==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VXRqVE6EMDy9bTZ1g9iYgPzkzRgTtdAhFXWRWIj4wtTsCbVa7m2qtc31iscp36fLYr/EjwTHbjfx6EDsHZFSBQ==,iv:eTjK7i+GqJIxlZ6RY8TlwzalgLwTU2jnhG1NL+bh7WE=,tag:RfYBOE7hpb1clPwQRCrucw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Kr4+DIl1+sAz9CY6HlCG+FYM/aA=,iv:NUDWq67XwJdU2grE3OTy0gmbJrq7QBGK+eHOVGuiFDw=,tag:jiJKv1PUl1o9PT1/peiacw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ATMiwBX/54oxupsSW+LuYU2aLFWbpshYI11rBw3+Mjg8itnWY4FIow==,iv:W3xRRcfERoZFpr1UFNLBbxoQ/H/z/Qlt80slV6NHKG4=,tag:g1Xuhnz4a4v+9vBtW6a9ig==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:lRMujCZ1g7hSQw==,iv:qQiiUsH3VUuAUiEubjhYyI0OxP7z8kpRdtFtVATttdM=,tag:WkTL2IJX+SxdCUu3VSMW0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcldVUFBHUXBLM3Jidkd3
            R1NHb1gxZWdza3RkK2pFdjh0Y3JxeHp0cWxzCnRTbEJyWHJ0c1UxdURCVDR0T0pH
            a3AyR3FrMlQ2TWJjU21Dd3BvUkRyWTAKLS0tIEVVVytvNG55cUJzb2xkbisyaCtE
            Nk9PdlRRL3o5QUp0bjNZQXIxVHBBUmsK4na/u0UgkZwAx7Ryv1ko1dkr+XKQzfsI
            VkatInw0wjAKR2WFI1CWrZv4yoPQOx6BmOpbkBRXuu5fniNMVNIzZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUTR5V0pZZkViYnVybzRV
            WnU1TFUvQVNiZUFvRHUycFp2bWtDNlc5VGlnCnJBQjYxaTFXWVVOcm53V0U4c3R1
            ZnlLTU10VmdiTCtGOTdNR1QwY3k1ZGMKLS0tIHg1RHBwcTJnTlVON3N2S1Y3QU5v
            dWhSYm92ZlBhS2FObkJTZ1NuVEt4dlUKk0v00WW0f5++YdFLwIJWHwB/+bnNsC9x
            ff4xiPnYpZaBt0q4PqGEtKDTIX+uosa3erKkMcjFY1jYRUpDs245uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUG8vNzZMOXpyMnVpSGtL
            QjFidm1KczltU0hIeWVFYmRvVkNHR0cwY0VBClRhQi9EOWUyTXNSZ0piUGk1a0U0
            R1VKUThNdVF1RDkweFN4bmhtOVA0WFEKLS0tIEFYU2tmWXpyQkZHOTdsSDlXcUxm
            RUl5a21LOFZvY2k2WCs1Z1doRzArbmcKpc9l2UDhLXxUO3LIZIRF49Z/i0k6AHP1
            IgGexzyXVytxF/avD3tHt3gXclQ7hqQFXcQD7WU+FoRR2lXTxYiNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:06:13Z"
    mac: ENC[AES256_GCM,data:+tYGdFAQZCIOrv8AfXvxWJBCoeHTgAOotZzP0gAUBXVkrBWc8FAz6up44+T9tq/rldJPRlfiS0R/NsiBa/zfEEL1F3DFCVRSzguoT8QkXtF4gEY8CTepX4rb3K9+lzcaQFH6YGNGsO1I9NbdZZXS/sHruiaL7xgYhGmN5CRViPQ=,iv:oyB8Drh+gwETNBdVfMLVuoe6/iMAyURM53mUa4UYpf8=,tag:Kz94VYkFD6LKZ3ehlCcy3g==,type:str]
    version: 3.13.3
