apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: platform-backups
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:iaFt4h8j4wThnthvo5opPJtZP6gebetpee9HO2AHlyXFFbCSJbK7l1CC04L0lKaIY/7oQLp37bNKgNglpGc58fx5rd1sAlFqIN1IjM8=,iv:eL+T/C2ovuBv1HyeZ+JaLY0tb56j0ILzGkP4o8Qdk6k=,tag:lR+EmsfFI6Rpw5A6a1if2g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gjts2L2KuO2FvmJ493KfI3zIG+KtuBuZ9kLU1SmRBn2L+TSGZHgDuV1T0sazto4FS3AP11rpwiSemwRuBuUlsg==,iv:HhLc/XtDaPRgWyVqaoStNVuFuerFZarL93SUuGIpobE=,tag:ip38uIznlnSXc9VVl9kD8Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2z8OpBsWmwz8V485i96w9pCCuyg=,iv:4C5/KEAFHT4QB+dcybhbmesBbXKwHzRXvfpElcdNXMM=,tag:42yiasG9Pxp5fTgDhHJ/WA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2Iaw8+ndtkCddf2kly10lprEcqNV82ScflueuZBc2iS3SLIsw+99TQ==,iv:4I95FDBMVKSUaQsXaGs3kj8H0AEJCMuhmcyaEAU6xMc=,tag:Af06TTaRX4oxNtbfku/SFA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:hcwhNBy20ELefw==,iv:E36cTFJbJvw13k0wQQ5Fh700gvkKK47ny3sj4D+2KVU=,tag:v6Yff4BIs1U1BBc24Cksrw==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:pW1nCtLJsxpDpZuDh9n8bIAL7F2el2g8HcsV+0crTNXHPrDNVcC4qkToLw==,iv:Iaa1XArNKZprewgtfZjnEnDYFwLsZCosBJTOmCVB1vk=,tag:Gn6CJ6PTU4L/DW0NsEXyhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ0JHT1k4RzFQdGFuM0t6
            K2VLdUZzeXFWZHN4dGQyeHUzdmNRYktObXc4CkZQb2JsMDR0LzlGaEkvMmswaHZQ
            SlN2WVNUWXBxNnU4RVd4ZUdIRG1UOTQKLS0tIHAyODZ1M1ArVEY2KzlJUEoxeVFy
            L1dZSjhmekFoZXZyb3ZWeFZsSEZWd1EKuUzc+mayJS9LTJVEDp4rQXO9u7Q5yQvV
            r41ycIEE3vF3RpHcS+AuQameyI7TDEHnFN+hHIGiWxNjTcPHBTT2qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0tqdGV6czlsSk1oZXd5
            ZUdveEJUc3o2TFVPOXI5STVobW1BY3lkNFhVCmhPdE5jOEswYmpSTitSS1RyOExQ
            VFZWRml0VjZSalNOMTNmckdNM3NSMmsKLS0tIGtEK2RxWjVMNHhZWjNITEJKb0d2
            RzdsdDVSeWh3enYvdVBjTCtMTUV3R0UKqA+RdcH9FvHHVDG6bY2cdxdsgbuzUmFj
            SZ6DKsYeHGzEadIcTXQxc/nE8IVbCC67PxHH758hDFPjec8wIYVxrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZnlBR0N4aUM0aUhTWWJJ
            TWVIaE00WnFMZk5GZzFuMExWR3hlNy9KT1VrCnlQcG9qeXY4SGxCcytVd2NaOFho
            Q3VkRDFHdkQybzljWjVYamRnYnBkelEKLS0tIHV2VVNKelIvd3d2blhQY1E3dU9n
            QnozUmtuTEhRTmpWMkVOb3dVQTFITkkK8ADCIr5S6Z8VzBpYI7SqO+rUl0kpwVHD
            c41lbjPTlGUh1CZ+lvE/fKWz/B0P9jMkkoJt/SKHGJLFlGkiz8LM4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdkE4ak9FdUNwZHRSMTIv
            RTloZ1NEZE43ZXorS0FnVGFaQjNYWU5iZGpJCjZoa1U2bHBLaUdZU3hVZm5HUndi
            eTU2RHd1TFJUQUh0azZxQ0wvOFduYlUKLS0tIEVQam5sWE9Zek8wVU5OMzUvemZF
            MGZ0M2FLQjJSYTRGMW1NMEJLMWNSdmMKSgdZnNc6caiAaUqfc7/sZQN5UZhP62j5
            S/sQO5sGaqfZsL+/wBmNXAVQH8Hy22xP79YMWhWveCrkXRZ2P6wzcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jm6xj8qlmfjlhw0vdseaaqkpt3mqj3yl0upx3smwutsaghcq6pesvrka2t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T23:22:33Z"
    mac: ENC[AES256_GCM,data:RoMkFx1nRZuYpuiq4HseVaEKO/qfaWmWlaKB3J/lyK9KCd1JAjzcm/Q52ea8e6gqig7Oq+8l4Aaa/mBztS2OUQxgykNSFa0wEPpKjPmIMcS39cbRmYxMBOKmKTyX316gRQ2uAo3HF1WFEkySiJrlfZd+YW7jASLhAqjJoy8Kw24=,iv:MxSJPQjO2Ds0KFxwiUh8YW5wPNe6bcMMN5aqUbwf5PA=,tag:g8eHYKb46yIq5smR0T+Xcg==,type:str]
    version: 3.13.3
