apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: platform-backups
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:xuOeS8eii80dmVbaJKBGuf6jz+qjbNtwH84d6v4QEuyHp9IBmWOyfCFEDWwdzx/BnxobCINYdAar87TC+fvtTfmKSO0Quuz/C2cTib0=,iv:eL+T/C2ovuBv1HyeZ+JaLY0tb56j0ILzGkP4o8Qdk6k=,tag:dgUV/8hvdfMYh7465Otd6Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:4ayJww8FJQNhBPeJx2kAtV2sdbsSpT0KUWiiITazMhzFQ8U8EAZGBgzvxHmQ+kzhXRuW2mSm7etKrHN8zxhT8g==,iv:J8Q41F3BFieHw0fQ9wrsh1x6btby9QbtOKI+1vhnRYE=,tag:K4NEjwvXCdhUDKhcgDdmBQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:oaEyWs2VVPvqTvhx1IiXy/DOGWw=,iv:jG8I403nuC2RmVyE21yKFA04OHO3F0je+RH8G42LRWw=,tag:TK27ucIYBjKbB0MzNCce/w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Iq0GFQ9iywcuEq1Rxfs2wYhx97bxiIVlZpih1iOne/AuyxS2yzcUHA==,iv:h+BZ6kzlBPDR41BJ7qxYftIkfW08JS+zKNn8fWUkmv8=,tag:HO/+nwn2tIBggRkf3N0Wxw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:vqF/0rRB0GUlrA==,iv:E36cTFJbJvw13k0wQQ5Fh700gvkKK47ny3sj4D+2KVU=,tag:IKp+NbFtjGTv6xISee5b0w==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:w8rXMs1epXK41j+N487BRXR7zqQBwvOSA3I+pH2jhN6N0x+wfFbXti5aeh12YVieFeGP4QkmgO6hT31akgNBMg==,iv:IP+UVigz+rlZqT8/Wc2M4uYYlM5BVL1ymZqBL7hSIvM=,tag:v9D/xCv+xgorretg+O79vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoLzJtMmEyVUdsbElmVU8z
            RlYvUnViUWxicDFZOHpiaHFLenRNaVhBNXhnCk9sdUtMaWxVKy9xQkVOWklxNkpU
            TG1iU2EvOU8yUlNPVGtZbWYzYUtIajgKLS0tIDZDclFucE8xb1lqYnNXb3ErZkVs
            cHdFN1c5UmZlVkdKSlVFN045b2Y5OHcK+aQwONhAMm7eMLULN4CTPWcJ8XuQ0VCZ
            Wodo4DFQuSHIvsxJvRWVCC7Tuu1i32Pvm4yfazBOVgnVHi7mvlZpWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V3ZHSlgvNDI4WnNOT1BR
            aXZRa3k0TFptWWdxdWVpc2F6TUUrVzZoaUFVCkpEUC9EYm1rWGdpM1VmZmdrSVpa
            WlV4MWJUQm93dlJ5UElHbTl4VGNqdUkKLS0tIFNBVjVreUxJT2czMWw2c0JRVkFk
            RGRKVS9hS2hxcHFsYUsycXNCZlFyU1EK6xYo7kExxg4+TON0qvWeYCFuhz06EJuT
            okdIs+8skaeL4Eig4XN6Sr4nWGm1lucSIx7QFir9yyMUCYFk+4tjJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXk5MjFPMzdqYmJOZVp6
            U1lndTBSRWRIaWx1Q1hlRGRDN3dLblh5QzBJClhxaWovRkpnNTE3Vi91eTRTVXEv
            YXlJS2gwWFQ1dkJwUEZrVlhoajV4dGMKLS0tIFJHaEFta1pyVGdVNlVwdk9Iam5R
            UWxPVlQrbHQyV3U2d0ZnK3hKSHZEd1UKQADOLiS0oF1rjoNJjsp6sBRbbWfs8gQ+
            tra+/Ikr40+G7RSSaT9UMUD+vHfXFT0GRrXjoh5kRGLp4LqSUzS9gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T07:10:30Z"
    mac: ENC[AES256_GCM,data:uH7/A0ntSQ+eFZdJGuViJ9PByN3/qk74+NDbDp59vkU2VP/bkFEivqts67UxnMD2+UkwK1PBgFKHkFHozVsJ30eSKEyJCH/LxJRKHoORDLUaUWSj3VBq1rdz6KJeBlzETPHGtJuzU5uX2ydxbS87rKZhZWscLv2LlI32qvoePIw=,iv:kOW4ipF7Prnk6KcdWILrrZhjMuUKHqyM56Ci3z7S7vI=,tag:6WHJEnwXx7mpUy87O7DNlQ==,type:str]
    version: 3.13.3
