apiVersion: v1
kind: Secret
metadata:
    name: llm-database
    namespace: platform-backups
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:9EX4hyXeR91BVRS5gTIcUEyjOMmRA1ZaPClHhDNJR5FngQxmsGOZlz8+DW6fUPR7Tr4q8105pu7O9EVPbc/R7w==,iv:ZPLHe5Kg9XmyUniwoBmErvyD/cwRH8SE2flbDwxKX3U=,tag:5pPM3bGGUshs9Kfk4kz0cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvczlUNzdQNGNSdDhQYVU1
            bVJhRU9BTXdWQVRBTzNQbjN0c1kvUkdnTFVzCldNblR4QmNiaXVlVDhGREZsWVlD
            ODhDdFhZaHdwWnZXZitnV3hsOGMxRUUKLS0tIDg0TW1TYVR5dUErYjdtR2h1dncz
            ZUFXZUVBNnNrVmxzb3dDaFRiRU5zL1kK3siXrKk8FrRJGVzLk7YQ1D0YEYi1LUC3
            0sfElyxAUW7yBDjClFk/JMe/uf9G+ytqivO68t6C2Uf/4YKwiGftRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdGhVYlBRTHMrY1RXTVZT
            UmFnRmJlc0U0UDJYZDhVUVFSMWxIdmdtd2pZCnZ6NDlrUlUvZ3RjMW1PdTd0alRG
            V2ZOeGhsYWZHT09URDJ4bC9RbThtMFkKLS0tIGdadnhMY2pqUllZMzBhZTFZa044
            N1pVN1llcFZHWk9FcmhUOW5oSEowZU0KzeylF/9hVzHjvEm5D5T/EuT9ZJoyUUgK
            Hak7/9i7SHJR2R5VEz29EvIXd9I8OYq8RrKfcvenX58PWwQhSFRXwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTVk3ejE1LzNUL0FMbThv
            cEs3T1VlTkVTc3phNzhzeW05NFFwZUl4Q3lnCjVMODZpd2d2d2xHdHRESXZhOG13
            ZEJTdkkwN0FLUzRtWnYyYWhoRHBZRXcKLS0tIHZrbmVVNDlxa0dyR05oZzl3d0R3
            VVF6NGllTnlaT1M3ZnRtc0JKY0VuM00KmRUz+jCMllUAcZUpL+whfhzb/Jaj4ynT
            Suz3P3QoyCxdZYgmJ5556rpXsDTwxVEy/1wo2/2RUyJUPpimCIYunQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:45:22Z"
    mac: ENC[AES256_GCM,data:R9gysKU7Al+2YChGG+lZyEdnO5s082fWUy7ZyKpjgCjnzmzaV0uFHlv076yO1dM2wny5tJ9+YnPyLXjn3rgKBK6Qkv1HSOnT07cjEuYUgxpmiwjkw+l3xApuU0UMMMUoOeldr7Ry9C6Jq1kSngu/Q28O++kspcDTQUjzA/ge+7M=,iv:vNLFasDbOAO4JBSqAMX29a0a/B+I/FmW2F3rS8PizB4=,tag:X9DSn0O2BohwlLx09ir8bg==,type:str]
    version: 3.13.3
