apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: logs-redirect
  namespace: ingress-system
spec:
  redirectRegex:
    regex: ^https?://(?:fredrir\.com|parser\.llunde\.no)/logs(?:/.*)?(?:\?.*)?$
    replacement: https://${GRAFANA_HOST}/explore
    permanent: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: logs-shortcut
  namespace: ingress-system
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: (Host(`fredrir.com`) || Host(`parser.llunde.no`)) && (Path(`/logs`) ||
      PathPrefix(`/logs/`))
    middlewares:
    - name: logs-redirect
    services:
    - name: noop@internal
      kind: TraefikService
