apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: ingress-system
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:jzLxjsH9FZpRFFa8jgvJwsQmqkZj2pN+xQ6UrhcmLasohf2BlFXrr67mwXVHadydIEQW8zn3SP8ZELoYm8pLtnvQw9R3qwGIRPrtrGeqEHqoU0mi4yDrtddpI+h/+YRouFvtqsdD+ZHUdfzOlyXpW6xJG0sfTLyFnzQZeCDE12YE6Y3dSS/0P2xyrlsZ8WGJVd1pAVLOFGRhy5A7a4m5dfykTA3rdXGkSqnkkZheoF2C7dZ74M2QP7MLteir9xpBRBDv3xloKTGpK/wlTyR56X4rytPRxzm+YdsZc7h0EOi00mYfCNrFUYcBUanGu8YH,iv:JzDTg6z+B5eJ0nuymaG218+9GxEewOXB0izlGOBP6m4=,tag:xMgU8twK26A+qy9vuksXIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z05jQXJxdUd4eG1VK0Va
            bXhMZjlsT05QdmllWXdBdWJVSUVWSVZlYlRFCmRyZFNoYjcyMGxheTFMRi8rSHdN
            eUVKRkpBZXBkd2hLODlxM3MxNStNYncKLS0tIFpobjhsTVphdkxEbDlKNWtGV3RE
            UzJUWC95U3Z3c1MreHVqdFh2SU8xdnMKVbRrj/C5sKZfMxA3IRCWvyHlym3P+YHB
            UbQUVKVLfNxfzYn3+mDaaGeYq8XY5E5eNXfck2epL9ARJdfKTyIIaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVFMvZ3JqbEhCUjJSMTVM
            NnZnUTUyQ256L2FHbyt4bUV2U1lITytQaDFnCnYrYWFKT2wxVW55Wk4rM1E1bCto
            R2RhN05DQm5aeG1JYmprWXFjeXlOTncKLS0tIHN2ZmZCd0k0NXBPdEVSTFBvblU2
            bVVodjRqa1FScyt0UjA0djJSTWl0YlEKSu26PRqSOhsNyRjVmwBnB4hDpEz19hrf
            yjRwx7NNsxOgv1+6uyaCqQDGKg+7YOWhvuGbeHq8csoTtoypzex4Ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcFB6ZnNOWC9aSGdaZzlQ
            bWo3UVJMK1grbWQ3VWQvUHNWNnFnNlZ4dFR3CjVrcjJGcmF1aVNKUCs4alNmWnI4
            Y2hQd1kvTGc5STgxU0p0dGYyanRVVHMKLS0tIGR2MU5zNTRtK1dkc1BXaUtRTG1L
            SlF3QUVNNEY5SGVQaXlqWFpBTGpNQVEK13aJ6GcXzFE/g+LkJRKOnA+xUOjnXmjr
            evUaicxzHHO8Oci0ejM044/OKKnRhkgTuXW6pZMzLT9t9++TWUfKnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:12:53Z"
    mac: ENC[AES256_GCM,data:RaclvsKvi6pWQQ8hcxZZRLc1iuJKnNx1aLAB4Xz3o97RmNR1RhNb10SV5kCpZ3RtRsRZ9AT0Lwu+USjTjm6AQ0YQwdZdklvAko2j6wjaGUmzKTdLp/CIZnPrUDUOoo7nB68ip4cGC17pUmiRmF3eZQxgCj1WQg4OTHL0el3pcSQ=,iv:b84DfGCfF9su+2VZPaOr+1i9BApdFdVtpMBuScBJccA=,tag:s1Yw6bJ7IfIxEVqHOKYZOw==,type:str]
    version: 3.13.3
