apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: ingress-system
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:5XpyLoXpt6Hn5zff7Ba2LC1X2ecvXCEdzx59SZCccWJ5kcUbLqcaxBZ3cVvAGlWEpONLwnGzVVLuVuq72+kqZLnhJgloR/ADKife6WF1OKWiTb2Zd3xYLIZp7TzTF93aqRXwB8/4lPLvn5gRZqU5ZZxY7Swtt+O7jR1IHYzRPX9mnL/5TUsaMVsuN+QXhCTME32iRfITVwy3e4E9VEEW4l4dSkHaJkB0YaudU1sH3NAJONHjIYPr5Oatl5FygFdxrNVssl593MrsFKVdB61KkTDjkgPafoLn+2UdWqP1jjOREHYdLp3BB4X5l3Ho/lgx,iv:JzDTg6z+B5eJ0nuymaG218+9GxEewOXB0izlGOBP6m4=,tag:A059DTud9YzbCi0zXwzfqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSUJub2NsU2cxSnJUalQ3
            aW1DZlR5QTdsWmR1TjIrNGhNY0h6ckJub3p3CjJ0UUtEclhsbkhBb2xzUlp2UE96
            aU9zenFBL1JKV0d5d2xCQzAzSE5GNnMKLS0tICt4bzFGZytKN3FVWDJGdnpjN0o4
            V3BXdFZPbXFLTEw2d1BLRHdkekpZQjQKGDttjjQvN2hV1+nSV3sQe70lvdiz7QXz
            pk11EQ49QjYoM+y6OVXzGaUuESd8/EtaUY0o7ZwDlr1qh7Ov+MzgGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S1VHbWxSNmhXU0E0OVFO
            ZUUzWm11aDRJZnUwV3Y1TWlxT0lpeE1iOVc0CkhCOVdOZ1VhQkpGdzFHU0FNSWtH
            bk9tRzRRcEpNeEJmSkd0aFcrRndtNVUKLS0tIDk4R1cxcFR6Z3hqMU5sbWUzVm4r
            REVqTzJ4Vi93cEhlSDJGeCs5TEpqSlkKn6kcdDvYRqtRmDOS9aEsdyfcjdxEI9Jk
            VVC9BSuXGR8EQzPVXBvIkpq+TzTNdXe/0Mzx6WOtSkNdlDmMTDoRdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK3MrTDZ6cXFaaFFjTUJH
            dXRLM2l3RmdEbXZRcHhhcXcveEs4Q1Z2U2hvCnIzcFhrakFOZEZFcUZ4Si9BblMx
            eEJheEdZSk5UQ29Ca3Y4YnBzaHp0L1kKLS0tIEowTlBweXZiZy8yaEhpVDNEamVo
            ekN6ZVJCTnBWWHVkTWR4bkJOWld3TVkKqi2/bRyf9i9dFAS9dghr5zneyJWiHxsg
            M7cPaAlDK2hyF9vlwXw7wuc4iVEiJ07YKdgGOuf6R9pQKbAoyIAE3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:6Y+C5jgCUVPRu33T/Xeff3MLeJktJWIzmLR9iM1LsFcUQu2itMHjf7F0UAMrQBE92cqCcdVlSlioc4YKw8tw0P/LS4jObX5CtT2y2gARiQmeDZhKiiloXldwWMpJWyDrj9jrxjRhNQFb1zxMrCoohtil2UT+mwYrxqxUoQBST70=,iv:WJCgCW0Dn4Vn8anh7tNG3zHq+ZwNIR3qH0JVq8fzRqw=,tag:kk0+BIWV3lGpPpRPRg6UYQ==,type:str]
    version: 3.13.3
