filegroup(
    name = "policy_testdata",
    srcs = glob([
        "clusters/production/flux-system/*.yaml",
        "components/**/*.yaml",
        "projects/**/*.yaml",
    ]),
    visibility = [
        "//internal/policy:__pkg__",
        "//internal/reconcile:__pkg__",
    ],
)

exports_files([
    "components/backups/tools.Dockerfile",
    "components/observability/build-vm.yaml",
])

filegroup(
    name = "promotion_testdata",
    srcs = glob([
        "components/**",
        "projects/**",
    ]),
    visibility = ["//internal/platformops:__pkg__"],
)

filegroup(
    name = "arc_chart_data",
    srcs = glob(["components/**/*.yaml"]),
    visibility = ["//internal/contracts:__pkg__"],
)

filegroup(
    name = "sops_data",
    srcs = glob(["**/*.sops.yaml"]),
    visibility = ["//internal/contracts:__pkg__"],
)
