filegroup(
    name = "policy_testdata",
    srcs = glob([
        "components/policy/*.yaml",
        "components/runners/**/*.yaml",
    ]),
    visibility = ["//internal/policy:__pkg__"],
)

exports_files(["components/backups/tools.Dockerfile"])

filegroup(
    name = "promotion_testdata",
    srcs = glob([
        "components/**",
        "projects/**",
    ]),
    visibility = ["//internal/platformops:__pkg__"],
)
