apiVersion: v1
kind: Secret
metadata:
    name: litellm-client
    namespace: llm
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:Q+iHwIEbGEoupw2791xAQOJr0HAn1OX7PQ==,iv:S04hVbcKwPwMcwIJhH92CsNpWXK8T/aXsftssG0VOSE=,tag:7UairHlww7BOkglaPRd5ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWkRHVE1waVpjM1hScGZL
            aDNrWmVTaXdqdk5lb2V4UWEyZDluckxXeTFvCkdxQnZLN2RpNUIyaXlXVWw3L0tu
            Q1hNTTZ3NkpOUFRRZ0ZQZmFLcWM0bjAKLS0tIEpBMVlzdmdsWVB5bGk1Ly9SU05x
            TFFIZ2U2OXRjSWRsTDNzRDN6S09aV0EKy8yCQiUnCanwgoNwGmhsjm7sqb1f5rrI
            4pf51VCblRRawYd1MDd343fTeKSqV+Cd2JBV7hab8Ory9AuUM/eMzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM3ZDcGZxVHZoQzJ2VnVl
            RDk5R01vdjZ5bWh4T1N1OVpHM1ZpakNDaEhFCm9zR09UaUNNSXZuUFYrbGQ2b2M3
            ZTJCTGtXNzN5UWZxUG00SU1mb09mWjAKLS0tIG5ldEVtMCtVRkhHMDc2Q2FCdHQx
            WGVSR2xISmVlb05GQTM5d2NZK21tMmcKg39jUciCMlJrsqi/+NFLIzx2/EM/LbaY
            VKNridqg7wruDziWjN7hfhE/iZrFMfQQJLqz2HAp0rFxkd+2wUVSnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZXQvUE00VXVLZFJMU2c3
            a1BDSDBxT1BOYVVjNHVNZGk2K3FKa1E0eENzCmlyR2djSGdsL01BR1hzODZzZTdL
            S3R4bWJQK1BEOG56YU9Ya0VQZ3ZJNG8KLS0tIFd3ZGxNWVB3MDcya3dHamFVcXgy
            VEg5TVdaVVVLSjcxbmhMdzVLWUJYMjgKtSjGjgzeE8bZ/Dm9TLw960Fq6Ene2mXG
            QZjuyruEXanrQYhcf5F7CE22twFg81Xj2MyEDxBWWzaCCkj3LKgMHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:45Z"
    mac: ENC[AES256_GCM,data:TqCVniogEHTvu519w39bFQia5WgG0hSmRi7KnDWl488c5EIsiGlaz5aev/xbkj43yhB6SWtKkcOff47tWc5i5mUDWGmSNUoz+ABBiZ/shfyAgqw9/94RmsuwMgZzKMbcmDv+7/UBs/eBwGpzCjWOhSoc16mz9TiEpHrs+OxEI2k=,iv:+jJKyuEsHsNax1zS3w5YvVI6zYgUi8cETU4xHnd9g+E=,tag:RT+Uq5YCzWDGpO8bBfMgyw==,type:str]
    version: 3.13.3
