apiVersion: v1
kind: Secret
metadata:
    name: codex
    namespace: llm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:9iOFuDwwe1gyH31aid3T0sy3zHQZunk+/CGeCk6Rim7MV+JTPIVqrRG7ODjkXYbcxYU7einSjwcqiKg2U6xN3lWJNg==,iv:6aXMLj4M9vk6P192PAPrgV9PbrDTImemj9KZKIv4Zqg=,tag:YKKZiUFJAEVPcWj8vgf0vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaExpM1NxbmZ2L042TGlK
            dzRwV0xjbkZtdm1pRU9ZckVqcXp0U0t3bTNVCjNacWFPV0wrR1hLK3Uya1Y3cS9N
            SnFLR0lkelI2NnQrZHIwbFhxaUlBdGMKLS0tIEp4dUd3MldILzNqV2J0V2dwck9N
            OFgvMWxocHloRXpycGFLcDhmTWR4NWMK5j9Dq692CBqRfZMZ+6EmziYRU7/QSxIg
            eJ3ANhOHKI2tZsHlsKQ2OoMB+szdwf/juCj6xCIahVEbIMhXkvThsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTGUyT2R5UjgybUVHQjZv
            dTNMZmNWREJZTkE3eWVYS2VyYjArN3F6Y0JVCjJzaUpSQWRmL1NvSVNQR2pZSkdz
            Z2N0NkFoUFRPdTFqcTNkU1JTdnllT3cKLS0tIDJqWUo1aWtLZVppV0h2aytNNmhn
            VE0wMlh5d1R1MEg5S1pFTXpzdXdEeTgKrnyXGz9KHS+Hb4MERMoMfAPh94880/s9
            WKcWbCtgGZpxWB+bky21A1CVuPvqWlwayUQmhgqld+0y0GTraxo2zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeGZlbkVtb3UzWkpyMW16
            ZEU3VzIvR2NXN1lYMUUyL01zK1RUaDQvZkVRCndJaUJlcnZ4UkJ5MFg3a0VyTUwr
            UUd0Zmh2NWlGalJPTFNIcVBjU2crdW8KLS0tIEtVcitHUWxYMFVPcGpQV3pOUmtr
            RndpcWNWN3N1eFhZWW1acVBKTi80SGMKpirtan1Eo4NuY0yIQa2IZq7U1eqb4BYL
            D9L0xsO/5MMhi0gcqppKPTrc0Q+jVlysheXqCUqikqfM+grMqf9ayQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T17:35:38Z"
    mac: ENC[AES256_GCM,data:UTtyVHJAKPigdYiap/sbmTPS92lDt1NskC0fFqUCwpFDojBrioP/apAkoyE1+biQFXfJDfEKJYOZkBQQE2tjbMx3xPX5h5TcYHWzY2s3XklHStrucGtxmVEpVZs5zZAQ80ZIqcReUmj4emj8OXB1mssIzLOM50jyEJtmKiMANec=,iv:iV12o0aAIWSs6zQPH1YFH323dQCfCQjTtovU44DOTrQ=,tag:km6Ywlp3PLb7HUkt4iuJcg==,type:str]
    version: 3.13.3
