apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: llm
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UJDTQXvyFkv/asZhAq/7QJ0L1n/vqBa7XlWvWEaaMqF2ZTjjX4dAANfK+RD7tkCIOGCb8CUZ0RmCEo61fKCPjg==,iv:m54eFxcYSJoTijB+hazqTYDozJL3hREFZIMBd6AvN/s=,tag:lZgyZ7Vj5LW6sU4nX/jCrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU04wenpsMVpCSHpkdkN6
            U0VYSnFqcndzd1lMRm1tV0o2S2NxY1ZFZUhFClY4U28yWVVLQ3E5S2tBRkQyM0tL
            ZWNkcmJtdXVTMlgrblpNZ1plNnBoTm8KLS0tIHNxRVRpYVV0K2NSWU51R1dHbEVQ
            MisvbCt5dTFGWXZqRDNEUG55N2NMZjAKROjyFmS13wrGDO/4ws+ADTNI0mdQ4gF1
            DuA8D8LAF41CzPoudkGNpnjQEB31dVX0LcTjwK1kEFhq93G37begkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZGJsWFdubmRlQ3E3eWtN
            QVFKUUxFR2htMkc2dUQvNjlXTzRvWjluR1FzCmVPZkRWM1FTNldrZDFpUlVtTDQx
            RmRvOG1RSEdwckpVTkxuMStKZEFNUlEKLS0tIGJVL3lWQTc5aFlWL05NWW9xWVJk
            SG04dC9pS3NXMGZ6Y0xGc05FalBNNFEKxjdQS2rRzCHOKBS2zfpHEjSI67byCz9D
            616rIBFezWgRlPpWubST8mxEGGdyptbEFJwLAo3+Ch0zFgYODUqdCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdHJZNThEeVRrTXRZQktR
            MU1HbGc4SlZYOHRUblI1dkhMbUpKNFBYMG1NCjJ6Y2tobE42eExuTTh0SkFRbUNT
            SVFUR0gxMTg0L0xnVFpDWm5pc1UydEEKLS0tIGNST3JrbDlLQzRmbCtJRDIrOGd4
            bXRHdjJrUjA1YzdpNC9mK2tXZFNMTUkK6nUNtO67+ZwYCQpNJcX1I9JCG/jKZg0/
            L8fUQJFa9PpoUcIkWgOBeubGWv/P5FGrc8pBE9u/fjhKyB8VeJDcrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:45:22Z"
    mac: ENC[AES256_GCM,data:FpeVjy5MUfLeR9UZhDtGbvJYghWTpYyNXGYELNuehJqutlFETOy7uXIsGkOzS8IwmBbq9ZMo1XrOx3ZTRFOlOXRDQzXwVoL1vuCZRtulraLR+K+3VY6/gEM9YvNzYmOWQCGI2+d3Vrs0F/kU3/QMIQJRlw6a9KNzRX6xIQJOu0w=,iv:6nLP2KUR6f/wBzs/0SFuxCnixWHmVw63LSoiEG+HZZA=,tag:KzxDIauqZH3wUS1Adkyy4g==,type:str]
    version: 3.13.3
