apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: llm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:RhQXFGdA1p+oriJq9LKHHQXIwg+j27MPCE/FQcK0BurGa/GdYb7I+CFuADAGcEKwGnmy1gAMMvYOhBp/l8SrvGYBRg==,iv:gsPo/ATcVoNAhbBGg46X0zrqV/MXskRRfjzchx+ow1k=,tag:hIKhWpA8FZcNfl5hL+qLJA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:iCeMhZJsmpyQQPNjFpyy0h1Ttt4UaxKVMu/CF4mFUAuxkoO6XVzkumgadobdkElvq+IWQ6NMmE5B5e5ft7oS9lr8jw==,iv:rUE7GyAw03ZEN8GXge7zYqNkT0ydXJzI/zFisAXLnS4=,tag:HjnG8CHpFmIqlFxTNNT13A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LcPGrBbd/zZu2j2Majq5knbbWUoKzuSArXUoHUI0uVFLy0X3DidFikjFS9fJUvyf0rbgBnQSohqFmUW/SpCRgfT+Vv96qqe8uNUmwl/VnPqt3HSvXfK17feBzXVQx9XsxKaFFIpqPwHUwug=,iv:fJHI2PH6uQq3/20qSupoml+rQ+GI8hMJeCZ30/eZEfw=,tag:U2sSCU3MBxTfDv89iMR2qw==,type:str]
    GRANITE_API_KEY: ENC[AES256_GCM,data:2FvfpGlIYaAoA2UP498n8NWev3FQJqAek/hdhCE2hXSs0Hr5bGWaZNxN4B4B1lRtF3qQjr8YHnIK+RX1qC4N4NtEvw==,iv:6DbLjdxILaTPj5cVn3iVXhN32vV4W0jxLzShQUJb6as=,tag:eBWAQvDFOPIVuDQLsLmR6w==,type:str]
    PADDLEOCR_API_KEY: ENC[AES256_GCM,data:lVsT696lbqqB249djP2c3RJY3agSiZE4WR+TMesqGVZBWjnqfpb4o81Jm5B7BegilLiCw5e5OxmKiYK55N9Ex8CiQA==,iv:7qf5eu+d/J5iOxY3FhLQ7hnRkFUyMrnnoL4J2gzu0PI=,tag:hFHZQUNQk7qH2DXJJSniFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVDdyMTZhcG43Z3ZLWDA4
            MXFURnlVeGxsWUNnWERWZUNNd2k0Um1ka0RrCk9rK0VobkZuUnJHbUVrRGN2Sit4
            MU15bVY1SU9ydG40YW03cGQwMnkzQVkKLS0tIE5xVmtEMmYwR3V5UGUvdW04cFZI
            TWtRNEdpRndmV0Y3eEZ4dWxWbWRsNFEKqPrE4LT52VSXheXpXjmrDsbhL2ZmnyUF
            /JVFX90kExjbqIZLIvuwwEnm07ESq+r1csljt9pqz+vSIoeg/EvcZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYVpvL2dGSG93MkRadlBs
            SFR3aFNvUmZKTzR5emZoRVZQMHJCMDJNTFcwCmpadFhiSWFaenJpc0ZnZDFQdW5h
            Vlg1TW9tYlFnRytOT0ljQWtUd0xQckkKLS0tIE8rOHVJZHdVczhUSlp6ZndDYUNv
            SjA1bWpzWng3d0JaYmZCYndqQlZya1UKZd0ZMgZb15OqcCUvcpX5hBtkSKXrUE+y
            sLaZbRBPLTZpGv3ROrIOrMoNxKLb7eHapz0bGP4VGfe01OBmC8LY4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucnAvaXR2Z2VzaGJpYm9z
            dVNnbGJxbXZpYm9IcEREZTJQaHJaVWlVZ1RzCk5YQllIRTZQbmdGYTFCaFEwUFNR
            RWxRN2NMdWUweGZad3JFMzcwU0w0L2sKLS0tIHlzbWt1NnV6U1Z0OTBFT2RpV2ll
            STdmQVRoOU0zSlAva2F3U1R1WG8vcnMK2UhQ31tgXdaT8u51JcMqHsJjCg5GeUmB
            byAIwF9puYRBHjwfpX3BC27EkTM5aP0b5K8F3KZr1X0Q3GO6ujNiKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:45Z"
    mac: ENC[AES256_GCM,data:6iJd0/KoLgf9B5q0iMOUwPL9f7dz1hipWJMZxhGKPGSuZcV1sSoboRO93Z1uWY8sZHpD+x2LX5F7MoIEET/eyu+tqRmowf7kT6zpbON9mxIEXn5E1c1kJYMwCAYLsWTCwq4LlfemjcZ8T62ofNLpSey1brEDhX8rINdb/PGz9EQ=,iv:HKYeTwH9mw3MBBpW2NbHLua1kqUCN9C3GTZujfaEV78=,tag:TFFsJC87+i5bV38iuX2fzA==,type:str]
    version: 3.13.3
