apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm
  namespace: llm
spec:
  ingressClassName: platform
  rules:
  - host: llm.fredrir.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /openapi.json
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /swagger/swagger-ui.css
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /swagger/swagger-ui-bundle.js
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /swagger/favicon.png
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /v1/models
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /v1/chat/completions
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /v1/responses
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /health/liveliness
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /pp-structure/health
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
      - path: /pp-structure/v1/layout
        pathType: Exact
        backend:
          service:
            name: litellm
            port:
              number: 4000
