apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
resources:
- namespace.yaml
- network.yaml
- database.yaml
- database.secret.sops.yaml
- gateway.yaml
- gateway.secret.sops.yaml
- granite.yaml
- paddleocr.yaml
- ingress.yaml
- monitoring.yaml
- model.secret.sops.yaml
- client.secret.sops.yaml
configMapGenerator:
- name: litellm
  files:
  - config.yaml=litellm.yaml
