apiVersion: v1
kind: Secret
metadata:
    name: model-credentials
    namespace: llm
type: Opaque
stringData:
    GRANITE_API_KEY: ENC[AES256_GCM,data:GzQMCCdQY0UPvsLykRWcHxvUffctBiK4sgGLZ33yAgBG6uhHXxKzxRdpbZyhKgqICPN5M6XAp//RcxDZTqCFqx+WpQ==,iv:D07s85uuy8yTq1/dldzzljM7jIxeqEZWSKM9Icn6hUY=,tag:Ayh19+MuPzq7Gq2+qPE0iw==,type:str]
    PADDLEOCR_API_KEY: ENC[AES256_GCM,data:9kM3qRASTvKAVdyX+qSEE3N46JLLplXFvbZktSk9PdXenkdUUrfsfrvNxAb6epCYOwHrGX/n/oi3T3y7a4cvjaAExA==,iv:cVY6feNU6uXrpUlVGC6MoScX2bWPAPBxufph4Z58i+8=,tag:vKPqL1hHROY2mXKnGCGtBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT1B3ejV1eDhjYnJJUHI1
            dzRMM2dzOGdNQUpzZTBxOXkvSVRldEQxV21rClhlWmlpbVZGMkNVcVRXb3pBR0Ri
            N0JuTmxnQk0rRjdtNmcvaTkrKzdoWUEKLS0tIE04ekQ3NVRvckl0dDNXM0JQWW5v
            emdPZ28rZ2FTU2g1SnBzcE1JUmtFb2MKs877vw4+vJYRmQ8W2IceIzwfg/ZgtOQI
            2IyCazFQXhZ/VGU1hTRISxk9btowjBQ1IOvmYei1MBBXlAvf/wd13w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArKy9nK1J6Mm42VlJwbVdI
            Q1JtU1VPbmgvWjgwMlZldWtVVEsrL0RpckdvCjl3QTFPbkhxMmVTSURoVVorUWly
            cnhRVDc0TnlsaXZqcmF6TjZUYjBPQWsKLS0tIFpCcWZZNlVPWWlDUVlTKzhzdTJS
            REJZN29iQVF3OGpIQUV3Y1ZvakRPdEEKqYdmp+teVFGT8pQ99eK4/saACovAKWcj
            542RyEUiqkEiw1AvOmU8h5jH7jRgLr/PyLJ/UmE38zMm07JJzlGBzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VFU5ZFBkclRTcXMrL1dS
            Z2ozVWVOT205cThia2RPc1BCaHV0eDlqQ3d3ClFsRDlGV1Vtck13QzBUTWJYbnVO
            S2FnYXQ4Q2c4RE9Vckt1cFhWRXJWODAKLS0tIHdGN0NrWEtzNzNHNEk1dFFDUFJl
            cUIzZkxNbGZ6cFVCUmsyS1lGd1d0Rm8KqIFfNhon+x/GDkkSL9sGuzvSHh8/9zmj
            5qZLU4c7p9U4VI6FnBnVZFoOONG9dVIHIacy6u2+hBjIFEBHlCwCig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:45Z"
    mac: ENC[AES256_GCM,data:RJ4zRCXQ0DM1opprqCIQ9sTwHEbDNJM682ser7WtHRzSNv9pPfQWMhenVHIOPYqUFjweVtQyrbg9GKf1iN0paZp1PcrguSG67z/pv6fJYAHHkJMkOziJT1jYzFMdrB8xuvikpt2OAL+ShRzd+JEZ3fht3IU+A0sscPcEGW0V+y0=,iv:ECqtVhBA7EM+ssiDUt2tXQhGvWEUQkt4LRHToY/3mI0=,tag:WxyjQgFxKJO3yPYf0zpgSA==,type:str]
    version: 3.13.3
