apiVersion: v1
kind: Secret
metadata:
    name: tailnet-auth
    namespace: llm
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:C+0QwplJprrA1ekkA0vr0lkCbuSqxsvUWclCm8mbEMQ7ZdF/NElENQYswFhgzUtiOm/MWOBot+cDaVoJTLY=,iv:47WmTPWfMwsS4Em+pLFA2ud7FRDe3G6wwJufqttIadk=,tag:KZfXz49AZvPq+2p/lin2bQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUkZtZmpQS29RNDJtaWJK
            YlczTGltSFdRSXZoQWFraUR4UnpmSDI1ZTJJCm0yUDNKT3c1QllaL1pKRjJTb1h1
            c0V2NXF0OXNoaUNxUnNLaDh3U052cGsKLS0tIEpteEY5MHFUeUkyT3lDZ2l3UnZD
            MzRycms5SVBXTndaYjJUYkltVU9yVGcKPrydNoAbZJ2a7LbGMVaNeCtdAx4WBSTt
            zZLupY8vMIklMp57zJ2pb5gLD/bH1JU8x+IqIiwTof8AP08HrD/64Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQWZMZUplRXB5RWFQK3VV
            VlM3cnV3bUZyMjk3Q3p4Wnl0TVJkR1FCTEVJCnlVeVBBK3NKbmlBdFRZdC9zRzNi
            OElwd1RpMkhUT04wQS96Q0NRWkVNVlEKLS0tIElOV2ZwWmt3WTNkRzhjNGh4UkRO
            UmdUMitwb2kzc0pWTEVrNDdVVXQ3dDQK0NVTlttNYAtKO3tnmrfdZqyCBm/eXupR
            0acLkWx5D4bq11T7yDw2J49xrWxZy5XAta/mqct57OJBVEiTND1xDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU0dzOUVLc0pMcFo3ZUdW
            Y2g2UTRxYm5WWmsyYnQ3d2tldDFEc3c2bEFjCjYwbVdQOUI1UXQ1R0x6QmhLTzFo
            U2Q0RnRkYVJySnNFSEhaQ1RBc01YRTgKLS0tIHBhN1NwMkZtRWF6MkRkbURHaTlK
            ZC9QUGNMZ2ZOM1doT0J1cjJaNXNKSHMKAYb12JOWRPmmtT6krTbN6J4ZwhzuW9XW
            Q76vobh1cxExFN0lD4x42illd/zoGKnAa+QO4TtrSoZLiR5o1UE9bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T14:15:15Z"
    mac: ENC[AES256_GCM,data:PFGQQ2xEI0d+12zijwJvYtV+nXPCqNePdv5bxqZtfXRWpxIIjEn5nKWVJDuxajcO3Fbv+zLULpNBGrJMPlxcV/OuPmOMYI9oUzsJNpF1uhjCl6FYTOon29MEXiZm856tA1gRP5QgCGu/FM58b9vM0A+Iw/MLI+CAMFcn0apOna0=,iv:RC2vi2iqiCmriS4MeY55VzJqXkC6zU6Pnw0Jblx2i2M=,tag:ulQ9LCYv+a4lKg1MnKG+rA==,type:str]
    version: 3.13.3
