apiVersion: v1
kind: Secret
metadata:
    name: garage
    namespace: build-cache
type: Opaque
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:yF4B9IEVZ0R5xvCPItrrLdQzZc8NrGkH9PjP4ySt4LijEUbWmq1WxTegQldv8MHSdt3dRaxtSlXidWjskMSNQQ==,iv:nk32R3ctwAtnPXWukiLgatsE8H9PJX5Bh+DrsVl1qzs=,tag:bXzugAEGySTcUEHdrxZmuA==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:smHwMIvjRPe7yRBx8JhiRAIENyflC+LzC2WzUkUaqzmIfnntSuMlrvPtx/p31N11hwTqkuY0LrXhBBgNKUoNMA==,iv:gyBmkwl/6LSuSZmyZjm5lSp0cMBIDeaJnYUQq60070M=,tag:kMT8YyLuksKzeig0D/gAVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWmNzNkdrUEdNV1ZiMEw1
            ZWRNOFRTRmlqRGtsY3ZGR2VBUnFxemJnLzFvCndjT0dCSklUVGU0SHVValRWYzFo
            N0Z0eFdCd09xL0NHMEtRbVphdDhodjAKLS0tIHFRZDlJU29FbDRjWllScGZWdTdv
            dGZWQ1RGTVI4TmxDNUZjTTBYM3VUcnMKpo5O9DrZXx3ESMQREOa0cg7SrUqXE95F
            up1V21atMgRKGmkDVBwCzK5k+OqdU6Z6rRSyk3oZCrz6Jo2kVeVaPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYmNUb1M0NHhjUFhqMnJ2
            WWdHVnB3bmhWZ1YvanRCVmpsZjB1WDNLTlZJCmdVL3licUhHKzZHSEdaVzFXTkhZ
            Tk5MQzRCb3NWMVAxWURXTUpBVWg2U2cKLS0tIHRXSTgxSEwxUzltTDVzZWhvYldy
            dnRXcnRCbEE4SUlIeW5JQ0lTU2o5a3cK+YeVnW1z2efBi6VaZU/T6mbvKPI02Mpp
            sXu73dGqJ9agtu9cQeIUmSbIl/7Hzn13gWlqhFSAXV+nIV8umM3bEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0NMVXcvNWFId3ZlL0NU
            RGNRcFVZbkkzdTAvMm9QVklXV00rVDFEU0djClp4aUJidXhiWXRXQW9ZcUthcFRV
            ejlOcE5Qc0diZmcrR09mOFRRL3p6ODQKLS0tIG4wTUZ5TDNsYjJDU2g4ZXk5eFky
            LzRuWW52eXR3SVNZYkZqdS9Wcy9zdFUK8jEZBdMp0bhGyRkP+BDLCfEUuRonScCN
            FLOU05dhuX4DTFb1xYbsB746BzkYAare2T5I+GLV0r4NSwWuyDHOvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T08:59:10Z"
    mac: ENC[AES256_GCM,data:p6/rJRP6Akx6GtX/p1oew2FjJ+yioi+zjiPz7eTylh7tDyj2dR0zIvkUT3y3mCTQdWKlLkj1MNeBkYygHIG0BaEXEGqyHtEOljBwKVllqJES+yNm7TTJyU+6R+YVM1RgjOt4/XXFuVzVOMCndVTRYOi9Zf/VSKpCNoQAKKjAe/E=,iv:SX5eDprLxi9Ld8shaMF4bOUpgE+w6MGjdzV3u1u7G5Y=,tag:9wN6DYnZLOkqBmD2m1WoUg==,type:str]
    version: 3.13.3
