apiVersion: v1
kind: Secret
metadata:
    name: garage
    namespace: build-cache
type: Opaque
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:SJuFmHVYlMgIUcNzuczMp6VW7EI0xVwvbZhA6Mqv8Sowc7EmCyyq4QVqT6sJZdhQLb2bKngQysFffiCr+V3V/Q==,iv:nk32R3ctwAtnPXWukiLgatsE8H9PJX5Bh+DrsVl1qzs=,tag:2l33MEFk6sXSK/Kan2ZMqQ==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:jfOp9bp1RVz8/L8LXPLEzMR+uhhai8MWvqTIvdXfhS7NPOd0XxOtP/Lx23D+ZNyPlclx6Ba3yuhUzivUWxXK+g==,iv:gyBmkwl/6LSuSZmyZjm5lSp0cMBIDeaJnYUQq60070M=,tag:4ex7dk2Ch84DInSw8PkUzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcnRSN1JFaEYrY0gxMzE3
            Ky9mbnBTZDd4MFZCM3lsVzZnK3YxQ05Qd2pRCjZFemluTURuVjczaFNZNHl1a3I3
            eDdQeFBRUXloWVZKUk1aN0ljbjBsWjgKLS0tIG5tc3I0dm13eGVkMDBpbGtxUnBv
            a1BhZVBFTFVna204YnIyMUI4cURPVW8KDspFgmHFqL8TKVOpIrRDdjPxFKY2QuaB
            MK4QDJdhs2DYCouC7QQ/ptI/gKWPjCdKNQb2UCZbt+mMKupr6mV5Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOHM0NGRHdTlwVmtUWDM1
            Zk5zZ0tPcUpOSy9BWTN1bkVkSVVZMjZrS0U4Cnk4UTdLRVZIVzVkOXZEdW9yUkw1
            VzJXWU9tZjg1U05QS2RDcElWODd2TE0KLS0tIFU1OUx6U1dRUFA3NVBtNVREVURW
            em1DNUMyazluZWtPd0FxbUx4Q1lGdVkK7MlBJX4G5XyJ4f22nhwYKn46o4TFIKSw
            Jh/AoDksiqSaUOX/dkapClXt7TvpYOX84nBisjN1FY2vrsoHksZIyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUWFreEd4SVpHQzVqaEN2
            cS80V2tIY1k1Q2g3M2ZJUE9penMvakFhY0hFCjA0cVZqZGlVRmorU0MxUDk1S1Fi
            N0FkRGdNdytJTXp0T2J0ejlpTEFkdDQKLS0tIGtNeC92UzRoOFZwbGtLekJ0U0g3
            aWpzWi9RdVlBZitRNjh0Y09jb2FXUjAKX4/g0MItElXjG0gpOjocH4EmZN27TLvA
            vMmnU9iHr/aLS/dyUd0Iyr2oc7gwUgsoATJXfIJ2MHdBBJTA38kz3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:cuH6n/OHKTLho0li1jM/HKxCwnLscwTQlmc1vZs7mVNpq4GZ1mbKXEeZlVB/b+130k5KhTxnzmy5qs7xPv5mhBhEqzLGunLmwcvoN7oE/+ZgLsLBEXrd38o40ZuC0L9Qa1o60XM7HlKl8E14jB9m2sP4BoNDU4DHFVCYpCT9eB8=,iv:i3qF8L4LfkZvxEK1d/kcSgzMH0JV8rhYw4KAXj3nrc8=,tag:oqRZXLytRPnojwFjS+vI8g==,type:str]
    version: 3.13.3
