apiVersion: v1
kind: Secret
metadata:
    name: build-cache-provisioner
    namespace: build-cache
type: Opaque
stringData:
    id: ENC[AES256_GCM,data:hFQcidEoruzFTPhsS+B6xazt50eq0MMXS+A=,iv:ElHwk16Y+vI5+Uv+qnbbkyiQA2Cj0bsCD/opI9uR0ng=,tag:owtihPEtCStanF7GZenKfg==,type:str]
    secret: ENC[AES256_GCM,data:391wDYomLNPVtGPv7bxgq12mDY2Whtt0gyAvHUm/EQUE4Aa3n0tJSKQME3cITzA/NplXv89tgKdQA5iE3DXDTw==,iv:D9ohuyMcDbS8D8ygztIpTlxkTsUiDZ3rLPun8YbyiCA=,tag:6kiteh3b5vMWqtvcAtrZWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ0kxaXhiZnBRRkZRVE5Y
            OFJ5c0JHaG9UWUtNWW9BR3VydzVleVJNY2tzCmZHSERId0M2V3k1NndvVjBEYVhs
            ZDRac1Z0WGgxTHRYOHVGcWpaUXlGQjAKLS0tIG5sR1BnS1hTQlhDQkxOZDFoMlVs
            VlI0RXE5VDNOMmxWKytCZnlXSGFEVlkKOxP6WRa0pM1GlWpCAWu/csAbVORnLye+
            iO0a4Nn6xGvECesJ5CuAzvTerF2qFgYyxyzngd4HYDfNq6e5GxfaRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVXdyQjVNRGxoR0VzVVZJ
            OXdOUWZuNGRMc2c5NmFFbTdqMmRLcmxwWXlZCms0Z2c3UTNHcWlTcjJreU1CS0VT
            dXBjRnR5YndZbHh4aHZuOU9FQWFXeDAKLS0tIDhETm54dlNOc0RUNE1BSnlHZ0cr
            anN5cjhCSjB2L05lUWFBNmVZeFRiaFUKJk9Xdk3VAQQlCFq1Bwpe1AMrJfi9Xp7F
            PrybUg+QuJGwZiaL7buNawI00om2EP9byfp+h1981dDoWq4zlScW1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQTJ0ZDNpREFzY3B5VjhF
            d1JWaTA2TktXVEZubkl3VERuNWFFMzR4TEZvCm5OcTFyUTI0QjFKbTJtS2UwcVVy
            UFVqc2tZTkxlaWRWMnFvNVg4bTBnUXcKLS0tIE5XYU5oSHBkR2ZLbDdvY2luZWJs
            Z2NTZVhjaHNkZXRFd2tXcGFySVByUWMKv1VaM2ieRtT7sFFrlWHz9uXk5gkGmBT7
            Z1aPPjWoqryap9V/I3wcFN2E+Ry76uA+pTWURI+3cC2QY0AC7kbocw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T08:59:10Z"
    mac: ENC[AES256_GCM,data:dIfxHicL/JLGuowXWxBKSsZCOfoJMx6UBJg3qyVxh+gEcPp7we4iuBNZn6Xtt52TFpKS+XTyZBSixlbimhSeJIkdtN8wnsrX/+pIc84f1kmCIqMVCciqLyvuTh2Dv2h6n3SPgOn1oOqr9iReWi1k2Ty6e9eaLbK3//f+Xs+Bm1o=,iv:/Q+DN7SDH9sp04CkLMF0MqhyTLUDcecJrxo5reEHN3A=,tag:LddUwtp6W2LALgbgmoRwAA==,type:str]
    version: 3.13.3
