apiVersion: v1
kind: Secret
metadata:
    name: build-cache-provisioner
    namespace: build-cache
type: Opaque
stringData:
    id: ENC[AES256_GCM,data:WLRsf2cB4lOUJseTrFxUcPvxfKBqxVpqGCA=,iv:ElHwk16Y+vI5+Uv+qnbbkyiQA2Cj0bsCD/opI9uR0ng=,tag:gFUQQx2pWo+rKAPNjeD4GQ==,type:str]
    secret: ENC[AES256_GCM,data:7B0prrPUycuIImwUTT2fuB+wgbv418A9BIVj/wV7REYshoQC2Bv9Ubb/cr4if1PiqeE7TWSFwwGpniLOP1JaYg==,iv:D9ohuyMcDbS8D8ygztIpTlxkTsUiDZ3rLPun8YbyiCA=,tag:X19J4DccL/c9/p+JlDefHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa2F0Z0M0WUxpL29xdjdK
            M1hsbDJpNkU2Wk9LNUd5ZldXY0F4Ni9YcVhZCnhHVkR0djEweDEvYWFJWnhubWJa
            YTZ4LzAyM0FodHowNXdDRHk0R0tPTjgKLS0tIFZhb0llSlBVbTA2bTlROW5WM0dz
            djBZLzNjNVpUNUUxU0JyWTU3bXRtdlEKhj1iHIf9DMQo9+0UoQQ+Bsr81pkDyzq2
            lbtXHpvdCdCNGTzCRbD9jr7wkelzhWKLxJQg+jl1ab+SJVxnie2ClQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U092MmJPNlJSK2pid0RD
            OWFCR08yZ1FkMDZDU3lwRWk0QnoxTDBtOUhVCnBjUzRsNjY3QkxpRlF3cWhsQkNE
            QS9HUjBvVjFSOWxqd0hUT1llT0Q0S2MKLS0tIFRjUmduUmo1UlE5MEFkM0VhVWlS
            cXpqbTR2eUdqeEtmTEtCOGJ2c2hTRUEKYRZ1RvOgSQdrS6Wc8qqayTAIeGuYYI7N
            DYz0dDoop1wp+jglcmByjrfmJsxzqxXi+1oJd+98dOyP/SeVCxNbeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRk1zMHkrVllNWnRUejZl
            b1RQMGViVmcxek5qRUlkVU4xc0xyaG4xV2p3Cnh3NU9aT0NWUEVwZFpRNUQrTWgy
            d0tBai80MEJydWE4eWYrQ1Z4eG5KRkEKLS0tIEp4ZEpYakExZFZ0SDhvZDZPc0lj
            NHZHOFpnamJna3VIOTN4SEVKeVlkc00KK5wXWRD028lWxIkEU4dH/tLQTz/Bm9F9
            hz0WyhhPnlR+gdOf3FgUVYtlQGb7QULaYOfApfK80SyRyhUBDaSuGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:cyyPFHwFjNS/OLSr1SjulcMsGeJ59HDRxZaZpinrrtyAIDOUWTwZePJxXQhOQC99A0szsC+RzKw6yPbFJwMbQXgDl5UDcueFYsS/p0OxowvOMXstw0fAVaPT3qNp1CvF61VR43oW84jRvWMOC7CtZv/XbezDHDzMI2ssofo79Xc=,iv:iCiivr6dhbghyjyEmp7BQyT0jtxV16LdeCG3Foywp2I=,tag:FkHa3iO5f1Z085MJro2TGw==,type:str]
    version: 3.13.3
