apiVersion: v1
kind: Secret
metadata:
    name: deploy-receiver
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:UP3TpM5Mk5LGohJ1wdBLR65XKPRFU+pPCRX1fP/WQyHBnoHBjPp+CHpx9gty1bHP3iXKjEY2sBcOI4qJp4wIzw==,iv:fhL57JMuwCv986A/U5mWeBAbTkyczCxl+LOEHhzRMFQ=,tag:8nbBAgJADfmn0GfHY9SSWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaXRSejFVMDhkUFI2T1N1
            REtPMndlc0pRd1R0bGtnZGUzTnNmWTdUR2hNClNmQ0pCbUU5Tk1UR3VEQW9tNzJM
            U3QrOTBqaU1pZkFKZEU5T0Nqc0lFK0UKLS0tIExqTGNPT1ZJTlVPSWpNZWdCQVdW
            U2F5cExxNkU0bTVEbjVCUmFFdXpLNVUKvohdxF7S+6KXHJKjDiG4t3KV5TUvqf+W
            aA8fGQZBUUjuVJXvgAtXQWVcZ+MajoQqr4mqz7rA/CXoZdRFN58gvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZWhmWlFaTjkzUWY4VDNC
            UGQ0MEZteXhSMFFDaW1aMTgvYWdSYytDN2t3Ci9uNnljbGFFWnpyQTN6RGpCRVJS
            eFQwZVFrMjZqQWMxZ2NIUHNnbWhtOFUKLS0tIFI3amEyZWFhNDR0MGllcm0vTjMw
            RWpWRUUrQUtCVTFhandmeEcyRTNNbG8KasPVeZokkbazOABgLuc7uvonPMRTDQOA
            +Qln7+WBJrS+1XrD2z98EVOFqsFRbGIlCP1pJ3KPmC3Ty6VfqQBocw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMnAyanBUVkVQWlYzSW1z
            UWFpSkdJUm5YQ1RsUVRTOTExaFJRMThRNzN3CjlzQklaakpWOUFTdy9tZEZXV0tz
            VTFQQzVnUWxEdFZwbXNMUDhySmlnNTgKLS0tIFpiZzZTbzkxLzVvU1hRTHdXQmtI
            b1dMc3ZrRXA1MklZZWR1TUthSXBqZlUKeuUBWpmcicfy4KvWh5Cyj6ZfJljcCXpf
            LRBQ5WItuUKKDViLXqAizoBPx8iuMx4kfzLM1JAeC/lww68RTq6R6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:S/7an+Js6I6nsEpkzau8JQ4aruc0gp35RUB8OKWM+Hh5oRe0kGKduIIC7dND5LHPMvrl3hu8vblZHfrEIhRU/0aIV5p6y6xa3dTEDfH3Pvtbx3Df9SIGCXSqD0MKrBDZcCnpPa+SHpI6Nb83GV7K/UhDuPfeIWk04FD6ad4NMk0=,iv:VGPMZ5yVerw+mDbVYoTWO7aqgOV8jd4qqFAzycPKqYU=,tag:GHvMTeu4Vl7Tv1GSRABkuA==,type:str]
    version: 3.13.3
