apiVersion: v1
kind: Secret
metadata:
    name: deploy-receiver
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4sTZjDDZxdpH5Dx4rf6wJjGLxNmz3g5q7SuYRmMiKsyTAyDBHdkUzSIVBBsY1z/uQ9zM/i2Cyj/qZk4eS/jxlw==,iv:fhL57JMuwCv986A/U5mWeBAbTkyczCxl+LOEHhzRMFQ=,tag:2ucSTqPedEGrsbwDQy0T+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY1VsQXNFYmZ1RDAzVXU5
            bk56OTU3S0VmTFl3NDc2TzBydWZlUExtY1ZNCkxqdUpua1lWeFYzb3RyL1ZxZ29J
            c3lBdVVEU3VKb2w0UXlaWUFCdVRkZGcKLS0tIDhqZkhRSWJSYWhreGxtQTZKZTF0
            ZVRrREtKSWhqbXEzeGtPQWkvTkpEME0K/JOu/5YYqtwuTyeIhGVOh2Ydp0gwzfFa
            mHW3ybu3b7piu1RReC9YxB48MyqCAhG8QPGMNqQu4ukSf1fHXbNOlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVTYrN0tDSzBIbTJjUWZH
            Q1RJcEJ5NWJqaTF0NEJNOWI4aVArK0RoZ1g4CncwM09jSnQ1Q0RzbFAvN3dtb283
            ZUlQVVpEYTFObi9EaUx1eXhGRXB0bGsKLS0tIGpHYzgyT1hSWjJIcDljWVpOTjZX
            ZGZ2WjBwYW05UHBkaVRSeXhmZkxrVEUKD8CC/eY4C1TPTy2CwM5krBgukAcR3ez6
            Uw+87a1tb9wOJG70Ezz/O0B8uJoESuV8UF5UBVak5DuWTUZxpGQTsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVFQ2eC9xcnByRXhMbTZD
            Szk4WlR1VWJXb1BjaVh4OTV0VnEvL1dnQTFFCkZ2VmR2QUFrTWl2bTRTaEl6dVZS
            YVhpWFZIR3RlZEdEdFpwRExOd1F1elUKLS0tIGZQb1dYL21SZ0JaU3RSR1g3RklW
            cjdORCtheTc0UUVCMFZVOVpSbmdpa1kKz177maWVZnGi21ybhR2kOX89qsaU2/Ay
            LfwXbNaKel/pqZnl2SYQFiuUXMmjE7MR1oX5FC8sx5/l4CK1DlbFzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T16:07:46Z"
    mac: ENC[AES256_GCM,data:hwRjpFz+3sDM0EaSY+kMQ7KjZCgp1CGrNKZjKZpzJFRU5ADD4JdYDbDa/V9i3uTvkuNwzb5tb4AAEuZEiqKbVx+F4oPaF5QWKi0xWFVyYeSQMBEIwiS1blx6Dp7XNMrmmXF9YWdX1Zr5hEG9dN2TsE+Lxk8SP+CloXD+7fY+xII=,iv:ig0HxARuTP1L/peJZY/7WgEj0jJutzk3yxVhkvyrBPM=,tag:i+pOaf4wjQ7m25rYvk7Uvg==,type:str]
    version: 3.13.3
