apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1-ci-nsql
    namespace: object-store
type: Opaque
stringData:
    CI_NSQL_RO_ACCESS_KEY_ID: ENC[AES256_GCM,data:ySY/4d1RHeHC/ydGMzoflXqxiE8=,iv:LDxTox9KvyUKeoRarwYJOsijcDvLHPm+vYFTYUSSr2w=,tag:XjNX1y5idCznMmu63Rb+ZA==,type:str]
    CI_NSQL_RO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jchILXz+HFCkoVD5YxIlOTSkSTcXTubz+j8pSS8hnOkC5PbcTSp9iBVlh/+s5GhRsQ7lLNB/LWVremqB9Ex9jA==,iv:Cn1CO9SMKmU67nLu7wOmBOfESCL9zDIM+jvH4deSA5M=,tag:5LagttueNppiW+ExMKMb/Q==,type:str]
    CI_NSQL_RW_ACCESS_KEY_ID: ENC[AES256_GCM,data:WokohaAHqu9Eu2yea5xU17OgyOA=,iv:8DVGgfqr1NGFCjgUFcUxqPwqVkzdEvTxoSAFFezl+/o=,tag:8ZTRHpp3X3ukz2ENAjDiXQ==,type:str]
    CI_NSQL_RW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yC/kYzJyOGqs3SPT6FGMfk7gDUTfa+DMUZUH4huvWfzn900HxaULNwWqquCOMH2K7PtoKhU6p/vDBu+iGSbiMw==,iv:xRp6/dqIUN332tmaOVRugA/jTxQrvJH5tyqRYEahbH8=,tag:zErhU3SxlA0G9DJYXihsYQ==,type:str]
    CI_NSQL_RELEASE_ACCESS_KEY_ID: ENC[AES256_GCM,data:ThNO2cVtf3IW4r/Xasrg2c7jyN4=,iv:TY0rQwWZ2q3NghAY8Apkbo1Erd/ihJ7SuvgAAo1Sfpk=,tag:6J5gBwhG0TpslM8y5csgHQ==,type:str]
    CI_NSQL_RELEASE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TP93KCPb706I6ia1ySJONeRR0r10/a2afu7vXegF0bcsZFoyqpF58VG7NUYnzg/UMpj0bEj1N/lzJQfrkrmoAA==,iv:FXll0YcV5NACTKlXelbKIeO1uUJFROavxEFS2HJCifs=,tag:fr+R4U7sBLkjC3R7E46vZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVW9PZURwQ3pyblVIWFp0
            M3FyQnJad25wd2RyTWVpd3cwSVd2NzQweEM4Cmc0Szh6TTVLQU11MDdtcHNDeDRQ
            VHZ0eXlKM1NnMFJTV0VRZnpTRHVMSEEKLS0tIHRqYVBQZzBWS0J6aHh1S3dwYVZz
            bDd4dG9WbmVHenprSm1WN3JWOWZKK0UK7vDMlpFvIHEmZFNb3zw7r7hT6Dk0FRQ5
            A7wtGPQ3Hogt7NWBP3ES99nTSolQen7yweF2IUNr/J75qxF/YxjUsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdW1Hd2IxZ3RHMGZ4WDBm
            M3lWRWYzM284UHMxb21nS2FTRVNTY3A5QmhnCkhwRS94RVl5R0FjVmZwNkgxdE8v
            RWZyWXVIaU9wNlNjVno2MWYxRDJudlUKLS0tIEJIMnZhWHJ2YXpzdHRPMjJLMHNI
            cTNRTllrNjN4TE1TRzRZeU93ZWhiQjQKZV+hxe7zEORmWzQXsyn04BfUDVRxWlGM
            cAGvfd7t282okN0oIfoI6OpSICPQzAmkshRWYxcDNPchqTnuHXfxgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z1VqWk5LZFFpSUtGVGNZ
            R2pNc29odkdYTHF1U0xhcnpEd0h4cnAxNFVjCkZtY0gwVnRBSTlTZDFVc2hycXVY
            aFFxeTg4bmxDcjN4d0pUeUtXRkFiOVEKLS0tIGhka0NQR0psN1ZEckMybjc1SjlC
            cUlGQS95TXppSTE1Ti9KUDFydmRidk0KPeWMwb6j1vRnXb37I0MvjDgwI1fQ7fJw
            FrXnbJPF8Yhi1cni0V+fZE72KHKIERTFsDHmpFPjlL63j4bWZM9LBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T19:44:27Z"
    mac: ENC[AES256_GCM,data:+SMkqULfnbJ6HobFr60vEmxWGmn7mnyiH5yRV9cxOk8/69szaGDTCtBROleYZKBwN5PbI0yuBc7g+TVSZvfpmwqYEor/4g8Y8RtpG5H1z7WipkuFGXeEqmqcucU5Ml24iDsPfEStc1WRiGrBCoZId3yXcVTJE2xemBEWzsMdamg=,iv:ilPLA8m7lKsBCw5V71TkVmldeSVKeoOmarwksIhDaTU=,tag:XKpxeKTZDjkNZBcCixVc9w==,type:str]
    version: 3.13.3
