apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-backend
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fOmb1J0r0GcIvFGHoUqTo8ZHmSAFj2OP+bo=,iv:GZUvWO3NDWgCia9cJTtWoOwWdHe5Vg3DPSJrsN16s50=,tag:bSLVL8r+YIkgnCHdO38qvw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rpn+TF1U0XZbDbsbxqTahN9qXbanydcH8LFLcgXyQSPllU8Sp4XrFgQNNuPXMnsVyQfEFkoqPd/z6/woFPezlA==,iv:jJs7QV+i3za4v19k03daElu5z3sdfx8m5UjXpYeY31w=,tag:u4v1TuwSMLYm2iUkFiqsNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaUl2Y0R1RVIwM2tNek9r
            eVBZS1VIRFBwTVdjSDR3eFpJN0lIekZmbWtzCm5ERWw5dTM4NFFkc3dXVGh6bTZh
            U0VvTVB4OWFVQ21VYTd1VUlXNlZGUmMKLS0tIGxoUFJnWVd0UVR1Y3hTTVRpVGFQ
            b2Nod1lHUkNoNVB1OEVMcnJiU1YyWkkKMsJf4v3okJurix1YctCNNQeZVz/yB0Wz
            sps2ETN9FMKPEHbyhbUO/mHI7TpuF/M3T/LAZn6QgXaLx39fcXcYdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aWdpZm1GVktyQlNRRkdS
            WjN6VXJYckxEZjJ1cm5FUEdjek8wNWpQd1hVCmxteWExS1BycmoycWxtZDE1VUZu
            YUJVbkJtdldPK0ljTmwzV3FmYmhlUjAKLS0tIFJiYUFVb2t4dWM2UUgxUWhOM0tF
            VU05RnQ4YXQ5dExXTW1XWllrdGw1cXcK0/s89V7mMzEtG/PmnqAFJ7hs+Jix2GWq
            kja2BZukL5xG8aAaL+Ps29+0nl6b+Q/avXX/vrAKwtwJINf3HNf+Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRGtqWHRMZ05QUC84YUdS
            c2p2cktBTlcvL2NqNG94dzdVbU1DYjVGeXlZCmlISjhqTDJHaithcm9MaThKSity
            eVZBbmtKWXdYNEUwWjA3d1RUeHFxNlkKLS0tIHpvUVQxVldaR0MwUU5ESm9BOU9w
            OFo0QW00L3cvazA4WXV1dkJwb2xOOXMKVfyWhi9qUWQXHsWhoGiRgGJvPD8EIl8r
            WNYAIGPlCaeky5ZLjjowRs6Ow5LHPdCvdvYBlkRDtU6mO0gx07gmAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:0jWnC9w+5EVi70C7spZqxgNaohRlOdCWqs/pIqpdQ173eIdadcPY+NatNsstbzAGZ3/LZyP/l5y4Mo2QYFBV8YapuSEHQJG2TJSmk3NBEJ3MceOwU7Oa9+keXxMmgZxstn69apd9o+s7Wo73EvyrbU7laqIbqcyAMI0u9FnacsY=,iv:hiOkeAq5vSIq8t4u8AjYkp6j6UIuV39VCxvKAl8uNMQ=,tag:j461zl4/IiLRuPe/RLkaaQ==,type:str]
    version: 3.13.3
