apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-backend
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ExkuKQBzfmHEfHLw2NE77ShkzwCfrC7FAv4=,iv:GZUvWO3NDWgCia9cJTtWoOwWdHe5Vg3DPSJrsN16s50=,tag:vyAApAsKL0wA75RefNmnnQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oqcpbPbl4WPkcGM1a8VVoWfrDqM+ezvuDkn6OPZ7EUPqKGCXz7prRPUruhwyS5Gdtm0P1gV/R734mSVwV086xA==,iv:jJs7QV+i3za4v19k03daElu5z3sdfx8m5UjXpYeY31w=,tag:O3wvYb62rICjfByrb3Tavg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dzVPQ1NlL2hKS2xtQUc5
            b1puS2tUMGVMWDRyRlJBMC96SUxaVW5lTFJzCmxQazJUMlBENldsVlh1MGNObFJS
            bElFNHNVQVM5aFI0M3FJc2g2WkRsZGMKLS0tIGhVVy9VczQzc0szdzRxUmpyeG1M
            OCtUZ05sTXpzWE9CbzBCYkMzc0lnc0EKt0oiaIHoZzOp96o0iCmHu0uwtQkLApmB
            cf+4JZJwx25ibooVkAghG5bZbqvybYIfgglCVa9YFDNnoMGe7mv/UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dGljNmIwMDcvRkdseno1
            MGoxSThOWWNVZUUxRFp1anJsdzBrcjE5SVZVCnR2My9NV3RodHhrako0N2JEY0hH
            eVhVU05wMDhjWkZlMjljV1pHbXd2aU0KLS0tIFprL0swUUQvK1JBdGwrVFRpVkRI
            NkNHcHJlTm53REdBenZzZWtRMUUrQjgKVD9PQsRzVkWdg+k8PjBYC/djhw5Aq5Mv
            0FH07uNGb5XKFzqCCyuSx9HWizf2Cq2i65J7dPlAquYvyR5BcC+R2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YTdiNmhqZlV1anVubGRQ
            YU9keTAwR3JSTVhhc2NYTUpGeEFXN3VuR0JZClF5Szk1RnNlVUVHUkNsbWxsT0RF
            NE90a2Zwd2xJemQyNmxtaGFOWk5qNlkKLS0tIGpuaWtqVCt3cXl1cHhhMW9BTzA2
            ODRibGgxMmFjUGVPSjVBWnE3QlBHSXcKgA/BmAQ+wRey8QADuLjhxChxMjoTQqy/
            /2qq0mu5PnZwAeRGiAhXODReLl3TsDF4i21TGOC4ksNWd5TLJMIihw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:XYf7+SfJnx3zETfhvg/Fi17wZ+RjhaPA+tIQkNacgwjVkzwpdegKWG+M81Xe4+BDMAmDdVQSe0iyCP5cASPCP0b5HVGYNn9oBLwP0Zo5xerVFmlRqlOdNeRxXhmZJ6023arqOjCRL1eKLLa7u4Xmu1zh8ifmhAA9xtTE+UoRm/Q=,iv:OB6SxdA6O/zVmuBCl5h/MQoEG+ds1WxfuPB7oLtdAHc=,tag:jGh8fjh9fzx3Fp63Ud5MhQ==,type:str]
    version: 3.13.3
