apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-backend
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:WTYscWih7Q==,iv:AB9lMP3LXE36/gM7UitCHCHShaaItWn12WWL6hEwDwU=,tag:gCt6m7A+GgBYjn+pogUBRA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:dlmpqvhDxshr,iv:6Q5b+H/P3IAIr9TWXOLEQRFiDedUN0ND/NZ3Q1I+uhs=,tag:ejTBbikTeuwg0SJGMLsZtw==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:7/ExxHb7ejb1i7Pyosl5K/MsGNfF67sS+5M1KSOhGa4+xUqz64Qq/YyE2zDXr/3gnBl5Qg9+KcgAqCZzq/dqL0oVi4xm9TJ0/MuwOrr0eAN/bYL5OU7vlPBdguFZTRAf08a1frOwEMluF1Hmb9IGaDLmvknIgkwFYpK/sRSzHqJ2+4EFYmMM0mx6lCJ3xShpex5ajI6Xqb+FbZlUBV8A7X/nhFIFjmk4kWBsSqC+1LSRCmvRoJoW9sT7/50GAw1iAmYeN0r0YLhUeSU3xVRmsKcv5ucjmm6wyyGs4kbHB2bnd+h1YWQSALg6U7SBdjK6RyzAf+WihnV9FB4vvj956GJvtnoig2dHX6vbpXGI7NphI6AXtidRGrfUeiaUeCppTiXAds6NEQnjix6p0jSC+zbyc/tJkjvzQaqjw/J9WzkbjDa8gaNcRvh4ibQ45hVcudmPozwPt69Kn+dvreOVWrG8NSKjEcA9Y790w3TwIhKm9BDdDX8f/8fPk+kHvs9+yVnBeCRcQBsYb8uv3FUH53/jFAFxvOroaxBGeqq2EvNfLtuQnnASBfYXCVx662aRDmQMCzYglvMLAdTwtNeOczzhWfLw7OTJK4EzTph6c9qITsznqrY4YZ0C2IriQwl6yv550vpyTPZjVwBbr4YV14rzknQXgPAYm6rqhFQ1vmD+ExkMLAorsRN/bS/Oimt25qTqvq7Ho1RB1zYUCBo39i3FsNvQ39HmYY4VK60xuwq9hKEmBDwEBgf7uEb0j1Rjc/mluZTSHRLIcEhzNNwm/k/dJZnFCXwsc2RmpjF/ix2mWcbgxfOdHE/Mm09QlyXDm0d3Wp7i/Gzxlxm4R2WFJhxRKk/supzwvo9uuM6eqIlrSTMIVUkeOHRAlT5JdMbCc3sRt3Q6k6KoTyPfAQLFSTEyXt3UJELLquaZpfq0zIhwdWbNjyD7XuB3+g8188o7Y33uMjRRt68vCUAzh2IHaNCagVWAFdrGNTtZI3H9MQ/mQg0xqYU3NkVjW+eLx3yPit44g4UwK8mkaRRCi74Xkp6M4tm1JuM9pi7RbPf5iS0phPIfkg7Kahb6aGw/z7HKNLAJFMU47o07V9raG1O451NBwKaDTxQDork4dQWxw89rEbsveV79Jb7I9z0NZrSHzf2qJKMuXCrZ/ZIU8QB7iXTXkY42Og2YyeJynck0LzkTx0k/SlgJifp6b0k2Uvvg4HNQyBP+lwhDF/ZQDvE8GqNAjJwZQgf7fyogxPFl3trJFa/V1XpLVrEGNZLq9Krcmij/Suiv61SaYwSItVwGvADodff0GcpHjmLQoCWnIjNriEzeLiDYZG/cS8h52Xcb+sHeWE7FxZY5pqmWcMPUwVJx3zMdF5JHcVrfNuxUjcolQVoQMrpEs9ldoJDfjsYWGjFZTGSQWfQn/IAA9kC+mltW8Z3SO/QxkzGp+iXaeIISPzqpu23h+u8suHy47HBi519BM7vchmNTTOkHk3ZxQhmDmPuCB9CQMcAtudE6F+TDfc9ZO9MxlEN5FH+90uAyy7vqybFdYsrLKGzf9X17Kvs2ghhfERc+l6ar1o8kAUkxboR+81jLF3PO6bMkPJILgPeLiD3c+oNhRl6/uQrps7/klBHu3XMviCUkRjHpGW3WBDn15qbZfhDN+9xgULl1wDKMr2Fqld3Ube0I4+tMlqp+pLQSQ1txyaYGAFmumsBKceoSIKcZ6PK8+Ozq76iy2PBlPF5LZx7atocRDdxPP8IYQT+K5KKkt1Y4O3/h0ARQpVaqMV9fxrX/RFrpjW7/BJbILh3Fa1XHXHAvJq+lUJriWQCMFPsH302i3N6RK04KBFHOkq1G7V9lgUfFZsk0WDoKpG41gyGTbYl9I0JeYTlW4iAOmBJ/wk0Cw6uwrgYNcAxURVhZfia6X/KtLWortnI4zicKc9DjobTkDpQTYCQf9IB6RJbrVV/PWN4Wga0KhYXB9sFHtsrBDyOQHXSF/1XAvEjdCcNCh3zq2v2DvKK9aRe1CcqHxt8mCWzcRYlKNafgDgSO3ZySXcxyC60tj5py7NPHmwCO8kb5VWlsNlnepvWVhb6xu1PU5uUQ67RlyIHFnNTgatyGujnYhndOSD5+ZfCykloM5H5RM356pVx8+vV1/Km/C7ZkuxoICbktRDJOfGdIEu8jKu+QBMV6afD8FdUkNgr8wUhW9ppperNoT3cxs1j+c+kgRQ3gj3XIABw5N57A2EtiL81BmA==,iv:bN1dVMCKv57MU4dQm0aYHkU980ugekIFXNnPZ7tfzV8=,tag:Ak9iHTOOLYqIGByADw78/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTGdRSFBxL1BxN2NBKzlo
            MkJCWElleWtzU29qSHV6TTk5U0N6ZlRraGxnClJEbkFCbTFyYlF5YUF2ZE01WGVh
            S0xMYVRYN2FiUmpHR085SlN3QkM5aTgKLS0tIHNsaE9DTEdCNFc2T1QvdThUbWVL
            SUFmcnJmcGVUQXVWQ21WTlpHcCttOUUK/aDS1tLI2jPp9017XGZeEGuh8AovvAJl
            hp1atye9pqy3sIwOpMHr012CcMWdsfvvo6S35eEyE4sdMhfo+ZgT6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZDQ5bCthc2d2bTc3TlJS
            ZmIzV1VScHZnZ0hsTDN2T3FFOFAwaHVrY1RvCmtqQms3ZU9MQkRXRlV2QTN5MVNH
            RkFTVENOelVXZjdIeFBCeWNscmlqdEUKLS0tIGlncTZmdDZXMFltT3laMkJreHJw
            MFE0RlB5U3dQVDVmYVJ0OEhuQnBSdUkKa2TrZvyhnBb+/Jh0lOqLUDhQRCvX5t3f
            dlCipIGCUH/mLzDCJZGJ4Xgs7EwdFFDZx6EVZjYcH4kt4jaoSNwNjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNFo0QTBKclFuYWNtSDlh
            WUMwdENVczBiWlFSNGhwVzRRWWhTOSs5eEhNCjd2Vk1QNWV4NC8rTkJBQnhla2pW
            dXJsd0ZwNzNBZjh6dlFScW1zbjU2eUkKLS0tIDRqNmVJallMaTRtVUlQUWVmK1NS
            bGw1YjFXQlNIQmhhQzZITjV6SmVkeFEKnOVSbRvF/91a3vfTUdolke4EMpTjf1NW
            8mDD35eQ2DYqqbCqu0tdy/z1y02+Wl5lJwwyL5+Sm0wamWuRPPPJLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:ui7KSddimemEjOmnZUngMiRUJuoE77fIjissGxC097W0og3TfWpCVHqLFtVMEdDw2oucFPgfw52irTr+wWyM2waDY3v0hE/PORnAccPU0tenxYQjPSThJGowth3MWEzwM9NYMvoG627WvvLP4MiRpGc6Y654Zs3HqukinBAkGXs=,iv:OENUpTkoUeGe3ZBhb1/RHC3+3LP35DobCWBNlg291LU=,tag:3c/ruSIUh+1w6kymVikXSg==,type:str]
    version: 3.13.3
