apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-backend
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:LlX2vHA5Dg==,iv:AB9lMP3LXE36/gM7UitCHCHShaaItWn12WWL6hEwDwU=,tag:iFDr4vwzAHI/YIvitZo0mA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:Nhw5VSyWc+YU,iv:6Q5b+H/P3IAIr9TWXOLEQRFiDedUN0ND/NZ3Q1I+uhs=,tag:DY+aDRmD/z6hAEnAuVcfZA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:XMKKK2CPu6duAiuRzEOAWRjrAmJHV4v5IYu/KHjho4vDjbKxC35JeYvjeA4q6q2AUNQZM6xD32m3KJtbIwIbColYra0gPwkwW3ZDgciOKB9EY6KcaXM55+5exikqwUH1xm+nfIii5MAYGuSfLfgn4M/G+twmJyA2gVNykSKSUnHV+XvVzi21y1CogyF9LzkHrwYnmPi5zUXesc2zZmCdRH2wv2G7rDLGMzvb4EPsSNrftaTVm6dtmuuVSkZsk4C3fdWd0X2i9XmlcKROWGnPnxpVE4Dy3hE7PTrJW06NGYEV/C6UVerD6UQmGl+5z5/b0ZbmunkDE1ByRZEjHKJ7kIFODGHleUTX3dCRSbLUWvwS9DpY8eKTs20VTHjl9MfeSEQA7DfcSr8xQ5Wraw7BM9HjH7ll5idKxgTVo0rmXdlBScD67xYCqG7IkjSm0SrBSEtjJaTIrmL8W0EsA47/jkxi/FaC+XbPoN0gwW9EHO70Mh8LG0FXpVhYoCRyU/jD28Dp7QmzWoMQLbksVZNv5MTFv39TM+2YzXlh2A3/UWpEiyyXVRZ4PWy5rrPynWQT2W45KSmDF8AG38CgG1vxzc9vXSzIWRCg4Vk08EN62QS4eapj3T/2TSF3Nb/4eNTv/xu1POJOGVUrH8OgwRMrdvy5IPwwJsjBgJpQl9RrPzUT+sg6exRx3sGoMKrrw/R9G8hZjh58fdX11aaGKARAdhcFMfAM6hzPynFD5WbKP027GTsOIGZKF7+agWkD32CytvR1mTlYUVW+ojojjL/yOAjvlQmffvA+Un8DCR7jNWzQZKVp5luDjSxmbRpBE0adDOIS/vrwu9rkU2USBlzLwEgBcpMH3nYmjOOgZbocXN3LPxwFeNOvRJgw0el8T2NO+KMwLf7oJgqd9Ww5jdpJr8sHUy/YW/2bySZKriYh4UFHDv5BO4zZRrWKrT+bLf24OxEJKYMYLgMOuDTmvJ9DkJpqTv15AUeRw6/hCx2JtDMr8JxE7Gm3o2D4kMOX8++u99JpZcmFiGLDG3AxC0Oji/41XJRx7tsJzMofyODRcbs+jHlUdFmVYiIHVwj/XVMQN15T7h0tRpSAMw1ssZQNIuuF+BVk4wr56nL2gL9v3sWiOn23t5vCEYg1aIi8YhpLOYpwxoBs+V2mKSPsSA6LYMVXI3Nx0ij+gG9li1BR2Kdx3nNU+0NHqmjV7QHGYfW20QhPiRBu3xJ/8FGxLnyOUIs5Shl11HN6OsIQEbPq7b0XfRExUFkXnkPag9GKuiPQ6rH2Xfz3iKWgSA0cTiP5n4ta5RziMKHV0Fg13lK/gMRV+6ou0GMo1xn3SAkgN1q+tSjSwkZXWNQVD7XKUa8JhFTMElN0GDS7MnVzR62j0z5kbJnQON5rbZc83BqswTexJf9/wR6iZpAmJAALTBCZv/BD2jGX1JjOoVwvEvHCai0+IyXyNTbr8uu2x22nazgPG/5OwkvbzXZ1XFjAzg2ECZ7PKqmUGCN5Uvp0lBOXLLL6bKzcSRe6a/pMTgbth6pLaccjcQJehVSUzn5JYrxKeCO65xbkCGW45lMX6HsfVtFznPWUb1LXbKNz4/a938Ncz1TLyh+WLjPEDIvu3lW164BqX+9dSqMOjNj8Clde3XVo4PrZFQ5ZuIhbNmItpmR1PdJqroI11W0lyYTdNqvW3Fs5XwBUPOpHshc28qdYaBGGka9GLOKTdSAYNoK/HqnUKeVtSZLxjqxVZ55XPk4fiYn0XmUM9Edvx5quN53D7vSDspHxneukLRPMTPeDj/wxjdrWNLxXnUp0F8C6ZVQMSP++IjZ2qVOI0f6xOc88mp1G0cv/P2Cy1opXbcsmpQPRhQZbkckuFT2DEU2eAG5lbEJimsC1td5NL/pwPT8GS98ilvnbDskAwuSVOEUyAwN8maL+eDCTExbPcgB26GwqMMGEPbUBa2Z1orp8EiUg8dOCDvFHcfzQQ9I/Uc0ZfhOG5yf2dnqKkuCm1pSqz966+YUmb+eXT32IUhKrF48D9pwEjq/Qj0C8vdRvvwySYQHhYHSgNOm7mauGghv2Qbo/rcO6DOpb3wVW2ux4f7h3ICNryRpC5h72irSyCKxstTJb0LEca2zGuaMzge9k7iM4SLPlkuQ/bwKUJAUBi8niWD+kCa5wSMUgu9dR2H8ftMuLmpXfqOvkru+v17at+79N1v0Sng4W5AlKoRD9gGkfntFOEr0rplhcLYHEkSSHEg==,iv:bN1dVMCKv57MU4dQm0aYHkU980ugekIFXNnPZ7tfzV8=,tag:rPrX4aipDl7eUTp5lPf7yA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZU5FY016TmpBWFVFMG54
            SFVvU1JDVGNBQ0EzZE5MUjZqQ0VWZjFhb3lZClUzOStPRHU4Wkt6eUV0QUFhcnc2
            TUU1NGJDM21qb2FYckNvR0FicHdtanMKLS0tIG83dTFrY2QrU2hHdWZBb1ZnMjR0
            WEJHTVltVlRwcEhJTzRLcjlOOXdpQmMKaLWfARdkZn9ki2puZnv8Vppo398/7IBw
            Cm45C8Z17oEyUm+hvgd+NpFgmbKWjgLyjfs4usHNQhKNQkEMtxh6DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZFpEQnA0TWFEN09qK3BX
            djVLZElNRzdMSU1YYXhkcUJvM1dwUk9jeFRnClNxTS84Wm1NZlpEQkRHL0dFNHAw
            V0crT0VTeCs3SkRmbjZpS1o4UDhPRG8KLS0tIC9yUWFwaENVb2V5MFMzS3JhY3Q1
            UndSMU9xSmVub0REL0tmZXRhTkZPNXMKjZjvFMk0vch6OVrElRvzyXyHugH8BBqM
            j7T3/kyNls3J9+EuUJqTKbQ2EoQ58Wn2LZ6P0LculZyTOoqf9V+6JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbGVPOUpPYlRnbTVnSzVz
            VjhXQ09BTlpsZUNlYXR2OGJITU5zVmNQUmlvCm1TRGp4MU1LQ01kZk1vbW8rTEFl
            ZFRaTllrSmEzVGN5anZTUDBjcmdwYXcKLS0tIG5CZ3dHOU5mdU1acTIrb0QyUSts
            QTh5eWhEK252N3BFNC8wYko5L3htTWMKcTEms9h6fKETSTCcF26He2ZR6aeK5/Y7
            ImiK28abmsWMBylvdl+gQv7fJb8hwels7sloArQILDUdBhzvQLgY1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:32Z"
    mac: ENC[AES256_GCM,data:YXDDmKDn2RASLA0UJroyuc3JosGpTDsrDrmNBnDMrcVWQrQiWN7nl4aFhz+cQ8coI00xu5lFinrEJBb0573Q5BdKuVTqOXuEuYLsN0Mc4trbYL+nrJDyfvBEm6b5+uFNCqu5IEgOflnkeRUxG76uFkx1Zu4010qZCiypSWOQ1MY=,iv:YzWcn5Rjrlo25ZobUTF9gEuFM34XQjIUhJziM63fooQ=,tag:2QPQ7xQjVaA/sY69xKZIXg==,type:str]
    version: 3.13.3
