apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    kind: HelmRelease
    name: rust
  patch: |
    - op: add
      path: /spec/values/template/spec/affinity
      value:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-restriction.kubernetes.io/kata
                operator: DoesNotExist
