apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: llunde-pyparser
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2M60my2+n4SOotrLNiflO7t8XX4=,iv:0pJs3scw5YLCfRf65sVNZ3cyas4FvuwrLWx6cb5az1o=,tag:VY/JeNP7BiHgDz4K0Pgoiw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:t3I1mPm582n0nQ==,iv:0APWC8FyAyP1VK0q9KOsIokKzfSrjm5SItU8mJ83mXk=,tag:mrtb9bBJwoojE2gcMNuprA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u4veRqHBkjwntI2A99d6d64YA8Iz23OQtxeLYW+76HUhj84MpPcPkQ==,iv:vaX5i8mK7o3g28UMgr7xYKxOb3i4sKIdRy+Qww9WaaQ=,tag:lDpfOGJJEz2yyxtG8VJ7mQ==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:Nu8GsX9sMM7Mgqb6foZrNMCA22ELd9tBL9deDCNS/6qTlr0=,iv:11TYhTyeUKbsSIAekZC6RMmLCZCqqz1bEa7s6+ov7A0=,tag:9U2ZBn2aH0/DV28FtEZV/Q==,type:str]
    DOPPLER_CONFIG: ENC[AES256_GCM,data:uiI5,iv:xJheUZ0cqWSvs33Z8x5UCiXKiELPepAE20fOXiUABrQ=,tag:9AMPqGSiu/GXyg3RSVo7Kg==,type:str]
    DOPPLER_ENVIRONMENT: ENC[AES256_GCM,data:gC43,iv:rvZFQUQUxC05jL2idxT+YfKl0fHvRynhStTWci6P0bg=,tag:Ze9akCh2crCE9fHmmxDCdQ==,type:str]
    DOPPLER_PROJECT: ENC[AES256_GCM,data:aiJ06jt7H5I=,iv:8+9+UwUOR9MyRzkSa2tHn4kBA2YPt9ScpBdDENrT7zo=,tag:K/dm8v/89avow2Letn/4mw==,type:str]
    HF_TOKEN: ENC[AES256_GCM,data:1em73hUFYW7H9bgpiR8oQbQx75vtJOOBjuOYJoH2FivS4WwN1g==,iv:tsVPqQt4b9zZedvNjwCogmOTpJIggZlWmHz14ZBCbb8=,tag:fbohrkmWAkooP4PzihmPGg==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:kxPlRql/IldU/TaAzFq1zONShf/mfzYMRUwRW2SU2Y8=,iv:/ihGXqjNq6Z5zXdxCdoo/acEUi9QnGj4aBB+BLj8O+o=,tag:0E7Ugox/diib0oiCaCTooA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:VW+8b93hee55dY7aoVbhqNZln6MVoB/TpiPRya/rCpPC0N7Z/HRX/2VNnJJW5F0oqnSghTCVRPnu4Lz74YYDLxyhRJv2I+quzw==,iv:HEL1x5V/dYVbyWyROGXLmvjWfrhWiaWFwBXKA6Z19Xg=,tag:o3gS/74I69zhWuTJtlX5bA==,type:str]
    PYPARSER_ADMIN_EMAILS: ENC[AES256_GCM,data:R1vNuBnSSPbESDnmCW/J7PamsWOvkcmxFsK0YNdBlAIjlWyfZM2ZvpJFg3vweRIy/kJJS3NadlMuHY2bbGshSawG//063Atqgwh2RaO7sSdO1GWpu4JvZGmlR+9wMxDyMtSuc4TYywiE0FArpXgxhZ+T6xNLA9hIRwRPP5El1nPjvixZpvjRLg5UupiW,iv:JZxoiYtgGVUf7xwGJ+TX/kpSrehcOEBHlxaGlUFwX5M=,tag:yPUFl7wTjSi1QzHoM/RgBA==,type:str]
    PYPARSER_CF_ACCESS_AUD: ENC[AES256_GCM,data:myJSszzDzvmUHajHRPhBBytTKiGzuCmb0BUE02cxZBbtBAFOuSHnuhnWGIAHOnzPTvJoMc/ox6TGhHunQxdWbw==,iv:Rtu0F+BrX8lJBsCLlOlP9aGSIAninBv0v133raJR1wY=,tag:wqKFF1kN8aNK21if25qfXA==,type:str]
    PYPARSER_CF_ACCESS_TEAM_DOMAIN: ENC[AES256_GCM,data:musNp8VaXt2GlgcODYkeLFbCaDB8QdklaUo8,iv:O1qSpqVhkCRQslWlT3ZzRT9Brh9+GZ0Fzm0l1zQbtb8=,tag:kzmN7hat7NvfX+ExoY1zyg==,type:str]
    PYPARSER_COMPARE_CONCURRENCY: ENC[AES256_GCM,data:oQ==,iv:SBqQq8qTs4nynfgZP0Rvb2AWBZnw3W/eQHaHRyTuja0=,tag:DLOi2R7KnnU4LJlG6SRVyw==,type:str]
    PYPARSER_DOCTR_KEEP_RESIDENT: ENC[AES256_GCM,data:8+QkBQ==,iv:QIvckJmMB7vP/ohdRfiB5GV6xUe0r/r3L/sUKWE5oq8=,tag:FQgmyvobkM1xQAbimTLMbA==,type:str]
    PYPARSER_LLM_ENABLED: ENC[AES256_GCM,data:ue4YOw==,iv:XinO9PMAz4Y30hdsmvYqbk2T/6o/BW00O/98UBDaTMA=,tag:OhiJZNlk5MR8/bkhTcirwg==,type:str]
    PYPARSER_LLM_MODELS: ENC[AES256_GCM,data:ARJWpJsXJMQ1hA==,iv:QQe5FO2Zm8XqePuBN3gKcWyO6Q9j0EcmOl29TDxFdCI=,tag:UrjzjkXEFf2MlPH4IRkB2g==,type:str]
    PYPARSER_LLUNDE_DATABASE_URL: ENC[AES256_GCM,data:DPNkay6mkQGr+km5MUC8wd88AJNg+pzW0qCGtATAEUAZFG1sVoYtMBhrywlKDRr6KDHlrtLbI19JzzgckjFzWnjxJCJwFGr05kiYeufqbdGFFamBLliR9uFakh0J7xS/Fec=,iv:mv1Q2wwjcK7mQJAs+cYls0at0x0OXzrK76seb4gnqrY=,tag:y2LbjNBsZTIQWha9Sc55WQ==,type:str]
    PYPARSER_S3_DATASET_BUCKET: ENC[AES256_GCM,data:P6hGPXgnoepzQUNRON3U1pXdHJDaiw==,iv:sjX6onc4zIOI80xweZg1PfXwWFjd/iAtB5JDUlIH6PQ=,tag:1/36YxQ8Z2HKd8iTrt3mbA==,type:str]
    PYPARSER_SHARE_BASE_URL: ENC[AES256_GCM,data:Uma8I85X25TCrinryyac4KX7GM4G1WuPt84=,iv:946cMXR3eKWc38iOLp3wPuM2pnOyuX3qn60NLuBtsbI=,tag:V6FIURbeBVHSHuhyj7sWUw==,type:str]
    PYPARSER_USE_EXTERNAL_API: ENC[AES256_GCM,data:icX7fw==,iv:BPERAEBgM2wBv0VjOwiyB1+w6lloXJk7zdlgbxcTt7w=,tag:oYu7BE8ipse0UyseBu97xg==,type:str]
    PYPARSER_VLM_MODELS: ENC[AES256_GCM,data:KvDAyPjaAhogl72wAA66eZSQG3EdvDCMxzc=,iv:J1oqyajW9erlxurStGzVDP9r34vKjXEk6hhTcKjViAE=,tag:qRnwdQDo5e7hVdftbM5xLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREVaaTlVM0RNbTd6eUJ2
            SU9XTlFlOWgvcnM1VFJWQmVTdEttVEdLcWg0CmNUWHdLK0xhaXlkNjJkUytNWGdJ
            TWZJdm5BYzRkYmJnTUt4SWo4bGhjN3MKLS0tIFM2N1V6LzdTeDlLYUpjazQ2Yk9P
            TVFQQXcrQzh0VGp2S3loT290cis0MUUKzK63ND8zMpyM/fOGRJMrD7+dy/Nz1KLE
            l1lfRkr/WdESk6z/vFBjcOM6E+NS44Rt0wbrRAvPqJP56Nkga3uurQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadm8waVh3ZC9yZllWR0xX
            dXJiYWlzZ0xiWDhadTBWTGpUWVA1eVpHMEZrCktqM3lRT1JpdHhiNTNKRTB2VnBX
            V3pzUGIxazVEM21Kc2NQUmZqTWNtV1kKLS0tIGFCVTNIVWsvR0FQQ0FvcWZLYVVP
            TndjZXREZFhHUEpBTktmUlNxT0NQQmcKYrldrhbn4XpEUTCROCcaIw6RGV3qF3/c
            G8zOv60o3WZOR4Q3hUTReorAZmL+xqBtDOSTiRQo5VdX5KCquMphAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWFltODJxd0ltTGMwMkR1
            Y1NucFhPZE9adXpuSlM1TmJ1bWEwWm0wWlFVCmluYnY0VWx4MHZJa2ljRklRdUd6
            V1BVQlVNSTl6UzFTK2l0RzJrOXpUa2sKLS0tIFA2M01Yb0ZIZzBVcVZ2dVh4NlQw
            RzV5a3NLNDJZNDdaQi9LbkpQZkkxZTgKaj8CgmBseVzZhql5V8S+qVMLdT8h8BUi
            ati98fzgGnQqHrY5T0/wlhCAxlCK9DePyDjlJt8UTl5h7KcLbYzsHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:02:10Z"
    mac: ENC[AES256_GCM,data:BqAcsxYft4YTg7+9JXv1VMo+WAVCmxBu4cQLq22LmFo9chxcZeR4b66w08QpW4T27ZspW3Myjty5KcclJ3SfFKZQgKndMQig9azd4m8MNkvbNvPYmqj6Jtmjd7QIWUIuj3bMzgqBozzyWhChXAjgI6FlKwPuhw2pwKq0GT+AvlY=,iv:p81sj8UKx9Huu0BZ1UI0k0wx+MzCe43CDdwck9Rtm9s=,tag:V1YG3KBl/O76dw5U+pz0HA==,type:str]
    version: 3.13.3
