apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: llunde-pyparser
type: Opaque
stringData:
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:jyqNmCH4wqjzUaN2QP4YH++Ic4D1Ps2OffTgzySIURNAp5M=,iv:iuHnwAm7K1u+8jSzfFCBdQZc3PhXqJZuoohiXbR74K4=,tag:agq8NtVmGKEse3eX0TNgvQ==,type:str]
    DOPPLER_CONFIG: ENC[AES256_GCM,data:ywnt,iv:5aTVenVrKO9IHEPmXgPevk6rWcVvmSe21AFvzGOMe2Y=,tag:qtHIfgx8ASzX6ZRckHsHrQ==,type:str]
    DOPPLER_ENVIRONMENT: ENC[AES256_GCM,data:yRMq,iv:gmCybR7KamYKda3/bIf5/OBTl3nnQShgBgWRy8e+Big=,tag:/n6kkMo9MyXD887oqePmuQ==,type:str]
    DOPPLER_PROJECT: ENC[AES256_GCM,data:h+sFpKsuYRU=,iv:Jjt0o+1+is2VbjThDE7d9WOGOJNPMvIE9DFBKfvnWrY=,tag:pcPkCgL+KCe+2ZiaRNDjwg==,type:str]
    HF_TOKEN: ENC[AES256_GCM,data:dP2Xscws39CgCnXKD6nXyV7K8sxGi5ydqMqDyccpZqa+9SRJtw==,iv:YZnHubFzBgbqW1W9y6o3q5dAc5BdV2Bly+cTDvkbXj4=,tag:+M0SKBtwvwaD9joOYrUiqg==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:4q05BWfQMk0Spr6EmEopm5XfYltMgesziVVhHG1W3PY=,iv:/Dgz1+t+OsCcsTkaaWLxhmCpyA8eyOAlJTSPgVrfRfQ=,tag:OeQFqJGie1QIAFVvms12LQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:aInG5y+YT0F2gVvkCnQUAskGYttAfNhbqvDXRLUxtnq3OhqmKiV2wo/r9E3i8DQdeikzpyGSQeExvvJSGtjbtxe86qEBlWJF4Q==,iv:i/CUxy5Coj0xFF8Hw1EVUsBncDqE1GMTpOfFWGHjCmM=,tag:wu1aAB7tSc1IQ7+rm/tIlQ==,type:str]
    PYPARSER_ADMIN_EMAILS: ENC[AES256_GCM,data:TB0ZJGxfJwbdi0WqpwAfCsS6SFeKiU6ITfqEua8NRVlfydIzWYi3yGlbGlJuNZeqn7Tn54b+DzZyvAcjNBCpOEN2CpN2stEHLlPcAeufyqGMSJoCwsV+4za+gLidHq5EzaKtJxrjGS/IG7jNWaQOBxO3r5kRfZNrPN8AhQQ80XVBPnIx2rv/lYpkq7o0,iv:Cklti5w1HBzRYoK/CBEHCLPqkGX8dJDBmDKVr8kOeLE=,tag:UPDNx3zOnm/QQ7FCcW0Dyw==,type:str]
    PYPARSER_CF_ACCESS_AUD: ENC[AES256_GCM,data:QYYlX2igZfpKcKPFdNlv4bcCQGpVkvfDnE+S3IDIVFbAxqWCRfYMquzYl1DfemXD+i6crn9L/mQQUzgDdcGp7w==,iv:kfFwhF3gBmnqtb4ZxLUCJZi1kobjCgXAvVqH+aMD9Rc=,tag:Bu+SEsvT8v6RRidzf79cAg==,type:str]
    PYPARSER_CF_ACCESS_TEAM_DOMAIN: ENC[AES256_GCM,data:ZCZ01bsiVmRoN8IEc9U57P+Q0xnCnEFRfLb0,iv:dB/kB8L0xRRe3XOOVg3mhWrKt72Uqw1Naf9PpqmtwIQ=,tag:ogweOAk7N/g3bsz4yjSlaA==,type:str]
    PYPARSER_COMPARE_CONCURRENCY: ENC[AES256_GCM,data:og==,iv:5zK0P2Slww1PG9UB9lPDiWtYZxyGDvF2k09qPqqMVbw=,tag:c8YfZlAZeT7tEr0zVHQ9uw==,type:str]
    PYPARSER_DOCTR_KEEP_RESIDENT: ENC[AES256_GCM,data:mOwV7Q==,iv:c3jMTFNR+EraKgrONupQGBkC8SQSTe7Ie+sFBeXZugM=,tag:yy041VO89T38oatlC004OA==,type:str]
    PYPARSER_LLM_ENABLED: ENC[AES256_GCM,data:6JAWqA==,iv:xKhTOyUWd5q0YQrdLH+lgBvxatr1nj+DrHSmRzXFk68=,tag:3TuUDhm9jkWZXP9mG0Vvnw==,type:str]
    PYPARSER_LLM_MODELS: ENC[AES256_GCM,data:P65ONk2OUUygNA==,iv:8gdnCA/5gFAV3bSU7woo9JvyEBVRoXl5dPcIHLN2+3U=,tag:Nl7sYXCsRh1Wt+GOZptVVg==,type:str]
    PYPARSER_LLUNDE_DATABASE_URL: ENC[AES256_GCM,data:dJaeSluDhZkk3IXb08rsHNO+5TP3aEm0hS9MHbH/uXe0mFGgL+NbimG7MvMZzq+dFW7QV+9e3Nu5J7zjf5NLceJ57lhAuTvhjfw7+r12F8XrClsMZwhauxbMU75iTW1HZys=,iv:LkqBFBVpNlywujAra63uAZUstT8D0mpsRDPVv2x0Iiw=,tag:kOnqlJna+8A2bBqeAwEdaQ==,type:str]
    PYPARSER_SHARE_BASE_URL: ENC[AES256_GCM,data:WRHzif8Y3EuhfpQ4+pH8n8eETCtcrBnr3to=,iv:lr57djut1YsRO1G8qiuig37mxVgyK1JljAS6xCdZ5VE=,tag:yru0zH/W90LLdaelYOZN1A==,type:str]
    PYPARSER_USE_EXTERNAL_API: ENC[AES256_GCM,data:7Di5Gw==,iv:g+/4ELx0zfKE4aKgIjraiVYH2g94kUeba3EXqXZmu9g=,tag:bzCis1rsTLFKu550uqjRpQ==,type:str]
    PYPARSER_VLM_MODELS: ENC[AES256_GCM,data:5BOifWCVjPdwJmqP7pvT06oaS1JZyjJ9ygc=,iv:4MK1ir1UK9Iev3PjtviBbanYbHSvUiDgNou3iq3KHK0=,tag:MsneWOcIvdwfGJCHxzjKdQ==,type:str]
    PYPARSER_STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:WoYo8T4om0JW/OTMxBwUDWXsc1o=,iv:shQcmhMfr3FBCs2/YGkJOGKFEhKqCgyKlohHnurqSHA=,tag:8kbLCwkpZkm89bTY4N0TUw==,type:str]
    PYPARSER_STORAGE_SECRET_KEY: ENC[AES256_GCM,data:xCeQ0iaGSetV9y8zzy3gwGmj9ewItutopAE3kwtAXmoSERHezH+2jqbVpljWFhEYQOXeaQtH+u+YABT5wPjgYw==,iv:oRLOdmApRFwtoLMYz6asM7Yhbl2qyTEQmvFvHIyiEQ0=,tag:rwQ1EfdACDPVzqgYQpfc+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cTA3MkgrY2VhOVhQSUxy
            NDh1YzFOK25SelRLeXdYdk1jOEdHUFlHMWpBCm9hQ3Zaalhoc0RZMEJqcHVlSDY5
            andmYi9yTzFLK1M1UGR4NkFTLy9OYkEKLS0tIEZyb29Bc3NMUE9nTER4bHVQeHdP
            cnM2OTlPVkpoY1k4Y0JaRHRDK0k3UWcKEQM6XPnrGoIvD+AaQFFC/UPpFuMZ1L9j
            L2Ssty6SMtnEnE9gnHdJ84IGdvZZPgvdu6C+DTrsAZ8ZpBNwGH6reQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQjZLazd6ckFJeXEyWkx0
            ajRyN3Q5VDlwSmMvajBGcE8xWjdjNGJSUnpNCmp3Qk1wRUVhcmhiSllIaktqUDAx
            MVVSTVh6OG52SXBUMXpLLytwV3lFTXcKLS0tIFh3RHZVZHJaQVFMT3drb2ZwY2ZE
            a2RKbkRCbk1WY1k1anlIY2JCQTczNlUKu2CjejR6Nc5wDEINd7lspgs+wnCKOsmc
            UDHOUoHr6Pl4S28FqGweJwlR9hQMyKZPXpdo0THD06rfqlmBKKNwnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ykl2elBvZmk5UGRISSsr
            TlNmSktJWGxGR3daV0VoUWU4ZDQvbjRoOUM4CkNzNHJUV3o0K3ZSWVVOSTEvUzd5
            L2pmTi9aYjQ5SURiZ0VxRTZOeng2Z1EKLS0tIGtiN2w0U1JHR1E4ZnRSQVIvbkFG
            K1RFd0lHWTJIUkd6Y1dTTEducTV6ODQKkIEpOiXFqCmSyIwEMaQa487gReoZPsuT
            6h20hTO37zABdhHNCV3ii8FdKFu1EC8ez3ii+yXOkjh4P60wdmPB+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:07:58Z"
    mac: ENC[AES256_GCM,data:D6u8gGu66jG/MRryGDb0HcsfeZmc0Cio40oiaNPUbK3Crzqmyo0zkfeMO1AuSH1LyW9S2iLOIYjIrVs9TJMI9IdsORZB5IhTMZF90U7+qf+JwAQ82QSUqGTbrkkMPJmzvHZnpC0H3jZDAJw5v+nWI8s1TzrgiTHSzXGMQ7sE5Ts=,iv:dlRJIg1xCz0bBiki5mTqiq8IpZZIJxQZ0F6t8/bntYM=,tag:QNMWV4pc50uX3TlKWpTrzw==,type:str]
    version: 3.13.3
