apiVersion: v1
kind: Secret
metadata:
    name: backup-primary-repository
    namespace: llunde-pyparser
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4jCg1hL0JoES+kd96icXQVc7+7lZoXa3KRcZvGCuLUB2gj3MQ6FD9xY88yCxEqxjuzOiZU9xAO4tSMqoJtF0vlJvkp4qgEEdmmVz,iv:70Wwqu7ro4MJ6GpmYFiBJaPM3bqD0y05Haq78nqxB5U=,tag:LZEgT529hkZWXmjYplzYUw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:kIdPEaROuh3/CpUtPkfyuZCH/H5QB2wlYm0k2zsPv0XT+sPx+A4a00AcS/KkjS11hkXyAcoGAAIpuL3iRry8Ug==,iv:oLFR/dZQikIXp9t6Yj03cpkCqvAVyRWo5Dg9jDqJ3Rs=,tag:t+MC9HklScTPCmW8/HQxgg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I/6T7HmV+PfYBUA+r6fv/Lh6dJI=,iv:XOqnZuY6vNCBgOGPYCODsnWhIIzt1iG7PsR8Zx02KNM=,tag:tr+3IjPqwQjTqZYwDlwVpw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:p0JTA+4EDkPzzFOztAsuzHQO+DhM1yXWcdY3UHh569qCyYLEVTi5asDPx9Y+wSV4Byi9Sp0ECdQTlWI0VrIyKg==,iv:patv8OFNZNa7QRu5KCXlQToWCfvPFPzMyO0CnNLgQfQ=,tag:qqGP9S/bP5L9tG6NsQUU/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUE5MNnEwamgvcFlKc2Ni
            UFU0Zmhrb2c3R3JWM0NJMnI4U20vWFhBaEJzCmd5SUt1d0dlTy94M1dkRkovbnpL
            dk96a0JBMTk5OEFSaGNqbHBQRU11WncKLS0tIGVtb1REa0NsS0dYSU9QS1R4WmI1
            blRRRGdoTVlaRzM0aWxnd2xiTGZpT2MKBNSF9Tgk5VTjwjFxKQhgD1Oy3tkjdxOc
            aefmm6HLFp5C8aumnO3aGDSTp9YSMoMb+pPrdb31dRbFU9liZx9AnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NisydWcxN05VQ2VrMEhH
            dnJKSi9EOG15UTJFYUl6TUNEakVHQVJlLzJNClltd1NHK0MwQnROK05UY1dPTjl6
            SG1pTzByN256T20wKzQwMTdTOG1odEUKLS0tIDBFU0hCTmRYUkhvKzVHTC9wSTdz
            ekRWYVZPSlV3cUtHNitlNjhVeTBOYkkKtM3Ek8Cigh4YrqHC1TASv5VP7JIPLrT4
            czubmddJnlVs25sLnTk92PRp+4a0gGQeyQQjZtvkCPw/pHD2FPuVyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQXlnVkx6UHVOVWVSd0pK
            d0M0ellickxOdUxKMmtkcDQrd2RWemZnVVYwCnBXZHJKemNZRDlmMm56T2d6UFpO
            K3FuZW1nNzlheFF1eHZqYkYwdHF3cm8KLS0tICtHSGFZZWxmcW5XNExFK1NPaDFq
            ZG9uRzJObVNucVRYQ1FTdFVBUW5URmcKRnQVPeKC9d4XMAS0057AtYYXQessICrq
            s/FG9ugyTL2oIWJ01t1vWaTJeAyCm5s0PGmFiE94oIqIPdNrsEGGaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T01:48:23Z"
    mac: ENC[AES256_GCM,data:7GNlBn1zJdrkk2gtOBBMSVTymjopptWxb3biXfkAgOxFurF7UlZ1CeGJd+TFfAK7+o6m4ojhih+u0jP0ofYAcUV+CevnhY8g3SbEW5WaaLXGDW/uRQCiW4FeqjT86xKCWFbPSRTlVn2CGP6A5RSkZn0tMYshPusbjI3hApEbDG8=,iv:nnBriCuQSwTfLVOhIltEfWObG8Kdb/+fCrdNhrdTOLU=,tag:xSjC73Y/7AwFwnenMH4z+A==,type:str]
    version: 3.13.3
