apiVersion: v1
kind: Secret
metadata:
    name: backup-dataset
    namespace: llunde-pyparser
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:nmtGJHhnp6ktYGR/Jr5xq+HHINs=,iv:Tecc4OONVrHrEst6od5+QXfbhva8GTe7fc0kPzOlAk4=,tag:6OuKjOi1JmuT04gIehu7/w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m+l5R+aHNWAjsPBuAcX0XlRcr+3GhfuRKsQ2BwcRsULJsPLmv8HLdBqd8YfdeB9aHX0WZu9JRYlddXajn64zbg==,iv:Fbc9+Wn1OiqvrzEcZSft483JaOfWkeUykjDe5BjNeG0=,tag:uuFI3GAZjgBT5+WjOxd6Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WHBad2NHdDk3NWUyeGg0
            RExheldLS3cyKzhUSmZIME93RGV1RHViM24wCkJhUlIwTjEwWlFMWjNJRkxRbENa
            N091M1R3ck5hdmliSk91NlhwcnVQY1EKLS0tIDVySVZoQkk0T0VyUndGUWlOU3R1
            UlRHcXpQaHNJVnVzSE54b3lEa1dqQ1EKFIhLk/Dm2+If6PK+V+Xhvhyc7l8zCUh6
            1qvhlbPMg7/DH1DbhRz0HMlXOWWRb7X7XclPSqE1QReQGzq3NFhh3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR2RjQUdGVldsNzJUMzlx
            Y2toalNWMXBtcFJ4aFhFbHVnNG9ld1c0SFFzCnlZbUdrR1RRUnFQejdiN2VIZHlE
            YzJjdDdvY015RUx5U3JaTURiU1FqSDAKLS0tIFJYbTAvN1gwUlFYMDV1V3RzaUl4
            K3hCa2RCQTdLdFIxb0hOWlJGZHJwMGMK/RbzuMcbRXuKOn3x1Q9xgBYTvBoKIpGK
            ZhTQeV+9oUm911Kh+ZKALSXyartOpy0Yjhu0wdfZwQa9YmI1H1pWvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU2hGaEZ0bkdvVXNKcm9K
            QzNhMmpycUN5SURNd3ZNVzZTQ1JtZjRmNlg0CktzMWtubkEvVCtvclBwYSswK1g0
            WXdqV21SdzBkNUNxRklsMkVudGNvZjQKLS0tIFJuYkFyRXVUZzVoOFRzcjJWL0Ri
            L1k2Nlc0VDY2ZEVRZlA2NnlTWFdFaDgK7FWtAxMZPH0A8M80/b8PkCE6K8v695sd
            j1RM8UqY+9JjH3JhxA++kGLTHMU2sZfNghElXl/jgmr61bmrX4dCdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:07:58Z"
    mac: ENC[AES256_GCM,data:bysDY7LXcPUgKbNwyA6y28hyWeIDFiECU/qGrk/s0/ZtS66ftrxFRu5BYtJkU+xPYolxyMlU5cjt7zq4rTufrHY4W7aHdmpJCbReQwWYo97YUhtvy0YprZiqgptlGc/AkAAipXQenx0f9+nZddnoFUyuOmSznSR+AebRgCT0dfw=,iv:8BZG/8fdpmo71xtD+UwdOHztz3zfxgG/3nNSLiVL4jI=,tag:OiFoniYZ7KyTx1Vmu75XLw==,type:str]
    version: 3.13.3
