apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: llunde-pyparser
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ljtEdSPf3TlDUNe2pVWSLF14D/Ba3D1Yn1jsmsaHYQDJPMh5pqhjKNCaUuxw5qY3m3UJiYUIcqICPoy24hCnA8fKXiEjAIDdb8RefQ==,iv:qnpmKN4NzlR0mSYbNXeKSqQSCiodnKn10gfVuG3Yveg=,tag:6eahY6Sn2VWgJK4CabEV/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WNuiRTBMzADDQrNOvjmO422HQChYC5+F2O4+FSV0Hl4pYhBUyFEeNlC3t3wI/UstuJZVzShizMEUgYSoB4KOuw==,iv:xT5ecCOn7tzu7bW71UF/9uJ+tNRfA7eAFmUH5mjdigo=,tag:OnBb7KkiJh35aYqcowRwyw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vh8RfW4sf/hq7r5fQ1xswCph384=,iv:CRoFGePYBF4UJ3axhib4esTMGruh3Ay5BHokzowAAH0=,tag:dsNIWfu/H6/QAqf0VzNRoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lxh1r3kb3S2TNpeBK+6BvmOTNUEHdbrbYuY8ehBN2eVdgZ9Wse7mDg==,iv:RhgHNYWmtq/njKKjW1ZW1YweO0oKf03z00CE163d9BU=,tag:Ed2KxoPBomtIeWMw2aX0rA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:e6vg0jbYYQbOvQ==,iv:S23IkWIkpWsC3hkLlzzrSSYGgSs1QddO2AiT0h8MMGg=,tag:R8rjtA+MabhcI0UUX3+xiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cFdQWEgwMWdLRlFqRWtx
            T3MwUVkxQmNKUHpFOEx4VVlFMlZhcnY0U3dFCndNc0xxZThrVGxWK1FJWldjZ3Bo
            QnBEQ0RnUysrcWZqcytwYkZGMkdJN3cKLS0tIHRqTGlwWjlhdEhSRlNmWTdqSFln
            bzZRc0drQTlMN3VaN0UzdzdqN0pBclkKZpOzUc8joklnGM8PThZBzZwo8P37HkGV
            hEox9I/Gh+RnxCx7raqkDCbwbAQc3ObdfIy/4ayAQY28XfpH0zstPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Rnp5Y2NwSCtuKzhxd0FS
            U2FsRkw4N21KSDhuOFJ2aWhOTUxlZEphVkVJClY3ekFzczN2WGQ3c1RNTTZCYlNO
            d1lNdi95ZDVYSVRmekxvMlU4akpucTAKLS0tIGZUYzBhVTk3L25pZ3dyTXBpbC9S
            d2NrMTFNd00xbkI5V3ZHcm5GLzNiMDAK4AgjcIjEcY7zDQj1HrfNCtsMNCMTRSIs
            TDtXjg0MkktGdZ8aJTEYl/H4tKPzJr91KgaoqM+zFxSAKvk4jQnPCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUGU0RngzMzJBeFNwWVVF
            ckZuWVVpbGlBcU1kZTdWU0NXSmFzSjlYZ1JRCjVCTXVHd1lrQ1UzVzQxWjJMYkov
            R3Y3bndnOGtiODR5RGFCZFcvWGpRQ1UKLS0tIGJVNzhLY0dBd2c0ZC9GOEUwbFVl
            UEw2TjN2dGdnZ3gxUC94ckZTa2lacEEKbljXtuIM6bPbKJlHWCAoXNkEXVrot4uB
            jtZr0QCizysNiog94hPzURxhLH6OqBnkuSXFeC7Y0mIONqbgy7g1Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:06:09Z"
    mac: ENC[AES256_GCM,data:r3onFNBNF7Hay3iiISsvFih9Ab1CpMCLapnXrLz2GCUZjKqb/RWuUSjYB+Uc7VnYmaqGXli/FnFFmdwzkIFNcjvMNaQDiN17JoI0RpruInpzKXCqQAdRe8qik8ayEyIs8bGSgedtBtEsaiyiLzhS4L+/BGJbwh+rMrDGBXNKXZw=,iv:MEt3ZomdzV+BLNM9a4qPmJxGclkdXyudV2sPR3Aut44=,tag:pLka5Yx4ZO4gQYI8biVyAw==,type:str]
    version: 3.13.3
