apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: llunde-pyparser
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:o43nZN99MdmMRZPNDe9W1jN7TENF7w6MPTUVfYNdP8F68et79Wgm0ETM6oyixLYKqGBSOUMf9mZjQ5NsDvP9hJebVYyURU855+OC0w==,iv:la5ZIP/o74NiiIBWVWj4i9kgjjetBa0SLEq6TkVJNI8=,tag:eZCrBFX8uh/cVD14baNMQg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EQINSL8yqxA73prhzQsk1XdGFdSjq3iR3ncPO4k9O6yT4idPeQ7b/1/WFG/aq0frIN1r6cJCEuIu9l+W1v8Acw==,iv:s7pPK36DF3DICujv0vDEwB92XhtPBf/2G/C0VMQkwoE=,tag:mnLKkdqmNiGEkXd6WrDIyg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cYH39zBRTCMr0WOMkh/biXwi7Mk=,iv:Mm5zeEM47x1x5BiUhricIPSsE7gq6YekMPFfXWQmkN0=,tag:wWgEEYXdng44t9dvn7IjFw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FHEOHrhEQYIWn846A2kvFLFxlAc22JabDzVtPoWn3F9Ain4VNxIMfQ==,iv:7bSRfcPk410m/O9F0KnBvSBm0laN7OqQULLJQWjb394=,tag:CopKwEUYdmaofSKoEuL7nA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:3EFBI+WFK1Lmpw==,iv:fI58StdbSz1WWJR9sg/M4cQF9MreQE6mTlVrzU/P4gw=,tag:nSLQcKiZRhpVqWrzcS7k5g==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:SdayxXfpZ15obQ7hP0rH3dL7Q0mrJp57oU/NxKlLMN9qvuCKg9lHnU6SZg==,iv:HEZ3jXDHj6oo/uvHbXbdmyVWbWyWxKA64Wy8yPWZ9Tw=,tag:QwB9kuf/YeGzjzEX6+0QSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRHI1Nm93UndRQmh2TGhX
            L29INkoxLytKMVlna21rYitwLzdpTTB4SWlFCnhjWHpyOGxObm14STdpVmxtVzFZ
            UlRucGtreUtsTG9iV1YzSGlwckM1RzQKLS0tIC9vZDZKMURweEx5ZUNQZnBsTTcx
            U0V3bkJXZlFtbElHTHloaVZYT3JHN2sKTib6WosEhM37WCJWkdKfduFo/yM68ilB
            m9g6Tx/0DVJDA08yWuDIrwBer1BJosjH+9z+vVdf95CEH1XKXbyKqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN3BSOWxBeS95amVscUVp
            QU9yZGdxMkU1d2J3QXhVVi8yMG5yK2NZOGdRCm03c3JTbWZPOGoyY1RFQjNURFly
            TGJFMUkrUkFaR1dLSzBHdTVEQVNUMFEKLS0tIDYrTUdrRG1mL0Yrc1R1U1lJdzBq
            SjJmN0VWRkM3ZDRKeGV2eGp5MU0wcnMK3zW8LAo0Ul9nOngvT+Y+hT8R3IKj2191
            PU0D69QWwSBEelhXE2lIgvOmeH9joUHCYjKhla38A1z5amrO/6UrSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNVlEU0F2cFUwa1dvR1dn
            clZlSE1hcG04TDJZRUt6YjU3TE1lejc2aHlZCm1tMTFSbUR6TFFxcUlocUNERjhI
            OVV4ZnYrZ0dZZ0lCUS9kZEdGalZWeE0KLS0tIDJORXN0NitZNjRVZ0lpQzhxMWVu
            cGRVOGM5VnpHd0tRdXFPT0VqUHlLM2sKODrVtEx44llnQRvxa+/NMTSekdOo15+g
            P+MN3aQYs+gXW0HtD3tcVgCRMx5cAzVJG8Engxfem4RfsiOpyHaybA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:10:37Z"
    mac: ENC[AES256_GCM,data:mSDJonvSIaW++Lq2HqMpkrU2oPAywa/rX+M486AMMqMhEklvoPWhl6/PHZqGeNSRGljgvU13TT30AMAiKBx6V3S3Qsu+TCipnN9vIWDWX87j/zfcD3NeOozG88OiIpwI18esmJ95Cw9vtGSxYdTo6wPZCsu+1r9NnJ1NtF0HzT0=,iv:SYcxKTPqBnhknaqByLtHnBmuXStGlgsf/zripQROHNk=,tag:BAgS2GCWsSU3A66kDigrEw==,type:str]
    version: 3.13.3
