apiVersion: v1
kind: Secret
metadata:
    name: backup-primary-repository
    namespace: llunde-pyparser
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4t9O2raQypZ53qazharPjAnO56EONAcQMvwiN+4U6tQaaBPu85uWLjHLIIo6hH/HL395bfiZ5r5lCUdKjkLVDZecFUZvSEU5wFCB,iv:oAYdQ0wRk18VLy/VzJJBK1TgBofmUBmY1KYZsiR0v68=,tag:3hsA5zMPKQKqVY6Lr8ynuw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RXeQIpbJeqnB80YS9NBgp829Wtb4YMm7TnZB4xOVUCWeqMogtGnkhlAARU7/b485lIDuHN7AD1czFjSlCWSbnA==,iv:yEuwBju2gHBtb2dLKcZl/pr9okv1wuap9oFCCpCPhWs=,tag:5G8f40HhAYdQ19QPkjJjQg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gGjvxQ3ce0fhWWYTjNXcg53uVwI=,iv:z75329PbHQiFXv8f4at4rdG9sOeQSxLpecEDn6QOtgg=,tag:KopTx/GljH2ZujM/zHpdNA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DChr4tOEG9pjGyaZCd6UQgg8CY4JzmqWAKnZKKnHYyzwZQmnKxJGkyLyFbXKuQ2hIv5UZ5cpx3wWl+P0W1sZyQ==,iv:EdIgWKmSIRkL5g440XT6/BeTOKMW0IC2hBh9y8D3RJw=,tag:1Pp25CPBkmdl3j25j7VMjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRGtFelJQMGpTMTYyaW9u
            bG44SXZJZ2FQOUpwM0xBRXZCYXJ5WHY2L1M4CjRQNWxyWGFXTmNiUFM5V1dwOVg3
            OUJnRUVIVmZWNU04bUwxclczb1dxWjQKLS0tIFJIdlZraWIrZUhId0FzRXVpZFFN
            S0Y4L2Nia1lDZzh4YjVCSTZVMElrNEEKih3lYjx2kv2ewA2f33kMliOHUcFtffyG
            6VbcTe9OTdXH/ZRLjrseSrhSnTEFwwb0iuBWmw88EB7D+2aaSQhqOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWJTSTVnS0JrZ1ArNUdq
            S2pKSzRUOXd1WkdPZGg4b0JqSmRVdjFKdUZNCnhLZGNnWjhTamttWXcyQkNxanBN
            RTMweDZRWFAzRlZ0Q0psMlI4b0Vqem8KLS0tIHlBeEJPVmExblNPdEFONFNOanF6
            RnE2ZjRXSmY5OE9lcXlGN2JHMVJLblkKHdWPvrkllF2y4P3TQJiDYzWGd0Rosvwy
            GX1R2XAp5Npo0iTggCGlILVPYNoE9q6ANqWj9LcQv09JBTnJEd5ARg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRjZSdUFETUJqREJRWjBp
            WHc3RTVzMGdWWGVjak9JR3hHTGc0RjhMM0Q4CndnRWdlWDl3dUo1aWRlUGFKd2NC
            RThFRU5oMDdWaktyWFo1cG1kVHdxY2cKLS0tIGRWcFI5bmFwVlNGVGNJZTVsUmZE
            cnB0M1Bnellac0E5TDF3R3VVUldpcEEKVyiVsmFLjSk2wwjPRmF9ZsgNVLmRj9L3
            uR+tWeEQQ/2/aiGRyLDOqPhEkZtdF+6guntH1zlFeN1wDGhI4g4ntQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:10:20Z"
    mac: ENC[AES256_GCM,data:K7v5y66LHq5xMnhjEpiKbuCN50hJHUr1/jC8BqSf6mEdHdyEDXTZ5paEZCzoOUrNf3vKuDedOWOcaeUOrXgk3smX0Rd0mgJTHL7UtLAE6Ak+qh1EKCoiVZCQIhAE8Y/KId6GK2qbHCbA38zIl/UFqo/BZZS9ok0D852TV6cgiXI=,iv:cCxA27mCPvKleZuU0DeHQremCTe+NIRUM82Vp1IO5O0=,tag:I61+71bl1HGS+hvw5BGqrw==,type:str]
    version: 3.13.3
