apiVersion: v1
kind: Secret
metadata:
    name: backup-repository
    namespace: llunde-pyparser
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:NsRYfBB2xbaD0fAULo7ud6n7LcP+4KeyN39XDtss3fCJQnqUkQzXFxsbakw4AflGiehtczIgdleH7EAen/u5PcVYIbU=,iv:/gSOHbfLiqA6oWurKwmuR+sRMyv7uPNX92Wu6ZWum+4=,tag:dx6THBo9NVi7yr4iQTucYw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:f2Cq936NfTsczkUu/PnPPk2kp3sf2iUMPbXCcmMMmsD21NzKHKf6fvn35gZtNb3f62QwzBFT2jwu9BgXwmLnoA==,iv:PPYqr554BtTHePBChWHdM6dmdaGnKuwoBQ7Sfa+gUpQ=,tag:BzNkD1b+nbJyK/chPOkyPg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:awDV1OB/TeQTdmNV4tEoH0vISTU=,iv:ykmg8XWjjyQ5lQRD7zrauzMi3p5iPpvObw/KWIhAb1o=,tag:ZAnPj9qHpPC0Ztr8IYJ95w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DHXMeSCqDaTlWH9r+P/FM9NHKi8waNVyiteEADJBLxHBM8dolYOplg==,iv:/KHp8bTEFRTqpjHpv6rK0jPDaVNiUnkj1Wtb6n2AmMs=,tag:q+0aZBHqcbRWPY/VUjUxfQ==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:iRTDPS9/DNiq7w==,iv:pztXFIyZGPBin62dJqFRhoTOMbXPz1q5qLmKIT2wb5c=,tag:oFxywI5Y8ciKMGEIDywYJA==,type:str]
    BACKUP_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:ZZshf8mcNjPyc4sUCk/rHvLJV0W06BnZuguuCogEf2HqC5bWLo1/SyEKgDxCPl9K/PcDDO842e1HU7qTCRaRRw==,iv:AThy0OWes091sPj9CKo4ug6jkhG8SSnRmFEUiZ59AJE=,tag:8OepAZ32vhu0ZkLOT7qtSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RGlnazlOYTJza1hESVM4
            S2lPdVVtOUpDVVF5VTdBaXZ3MFA2OW9iSXhvClh6K0xrWnJYNk9DZzhwQzhQbFdl
            ZUlFalkvQkkxRHJpUTF1algrRjc3OEkKLS0tIHpIZklUeWlYdXovTEdQbVpOcFF3
            Y2Z5ZUJoUGVtbjZ5TDRTUmV0L2JKelEKw5qJo7Tif3Q4a+hY0OCfOpi4VaxJuK9j
            x+9SRug+CDtQIc3FZBulido5nio0ypJ1F3RbFu63Ne3euPqueP4Emw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc3dQWW5kZm9VcmRac2o1
            YzJ6K3FBM09WWGVpbUtGMlNvS0s4Yjlma1VZCldIS25BR2ZVS21KRDVaQzloV0hr
            NlNscDkzV2RUU0M2MFBSYUpFUFJ0aDgKLS0tIDRCMU9ZUG5mNmEybmVZZVB3UnVN
            L294emlKRFdqc1JmQXFEamZGVG1hZjgKEz3laBZxcC0PHtYzyu9gzdEQo8GXdM0a
            56YhfMjwvx8vhUusyltn3KjWOAOMLTDldvkxdnIkEZLLNPCsUMZ62Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFY2SjV6bkpYeGJRME9l
            WG14eWtSSDdiOVc1aVF2UXdUU3FiQmZ2Z0VnCmNDOEx1ejlOWTRaUUYwU0JyTHlD
            dmRwSFhsemlFT01ZTjZZd3RFWG15amMKLS0tIEFhQU4zUU4wdDVYNTY0bTVQdXVL
            cW4rdHlFNmJXQUd2ZC94RTVLakd4WE0K5iOPRqc/dcX4Det5oj+Qpdil8YP593kR
            cvV4c+ycJmLcKkDXZ3VZMAZFrmYyvOAESk6dDpegDT3smcjhHBjDIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:14:04Z"
    mac: ENC[AES256_GCM,data:BngP9dEqECgdMfZ4q9j5yw++kFkXo8g66ThQvbiX2F/Bdombv+XZtcFkruVBMhs2jpYqmpJlnotyT+jodd0Oo4V44xr4OfRNwVDbTVCoOKs+dLR6vmsxik6evGrlF/JqJKVGl4K9j+cX5GwLDgVXujEOymIJloh54TyqAMPrDPM=,iv:zO+xWvTXZrQDOlCmvYzLeosMYDYODrQfwhLrWRjzI+M=,tag:He7FEMBe/U9cCCPSn/Ki0A==,type:str]
    version: 3.13.3
