apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: llunde-pyparser
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UE6Z/CjUjX8KAUxM0gJtd1SRHFJynf6deHPC3FK5pXmu83BgCEON4CPRKpm5MlXp,iv:BHjRlfi+RQ7u6pwAUy7UcEuwZ5G7cUZSs+iCT76dqYY=,tag:kHaEfIKH8KdKd4fvn6FtlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdFJuaEtweDcwNXNqL2Qw
            eGJKb1d2Zzdpc1dvMTg2M2F5WjhwUHlFdlVrCmp4ZktHOW1wVFAzUlV1SVA2VFkw
            TDdMckliM2VHQTNTZEJZb0lHdXowSGsKLS0tIHBDemhwUk5uSmJjZFI1OWtwb1lw
            ditWYW1RSEdtR2FCTG9VTUM4L1JrMWcKateDA1fuA0S3kXpUh/679j+wGiixGrSC
            AwcTlaXUy3BPAlRYVu6VvSLDucsWT8ObKUGUsNFw22xKkFXlx1NETw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdDQ2Kyt2TFVzQUJCVDVW
            RXFJSUZNMG5qRlZacVUxZ3lKQ0NIayt5b3d3Ck5iaDgvd0hEOXJsWE85c1JMYnJr
            SUVROHhBd25YVWpBR1NvNlorODlTRzgKLS0tIGNGZmFCL25OTTV5b1hMYk9IZndW
            M2t4aHFCZElib2FpbkNjc3ZBdHh1SUkKdEMd6piEzw45hu40Xs6LWwJuupvachgb
            DmpszorzrOlf8lmwCPUwCtetkS7fLL9yjJp9d39JLaA2KiKBHRPV6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQkFITUU1Rnczd0s2b1VS
            NWRRd3k2UmUySGl6QU55ZjNkU3J3RzZpQVU0CkZORUxnOXVHZE5HT1dkbk82NnJl
            ZGo4dE9Qbm9IL2lqRDFldGM5WDFxQkEKLS0tIFZFRVgvNEZsMDNpSk5tN2VHbWVE
            amtXMjJNanlqalFLMUdwc0VDY2djZjAKG+wqkjxbbwIbgFChQTnQAkAENut193Nv
            C9xm8QjwaME9qADhUOvEG3QBDQetDAwxWKcBS98c3gX/yB5dovZAKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:8Z6686gB/k4BtjhJHWw00KfwT1j74li9k+Lyr1mejBVE2mYGjJzxiAmYH47uDNee1fHHGONrvcDSchtuBR2ZzMtEkWtqMafdBPSo5JiS/cjIIhrpn79JVRrn0kdKOd1UhaTg1OgwppRiP4tzcjjv7Ex84n+5WIODu7XvlLBmc3E=,iv:J4igwgoq+D9bjH1ig0Qz2mUOAiNT29b/spPCuE+EnLY=,tag:bNlQ7qTNaSgGoh3ALv/RQQ==,type:str]
    version: 3.13.3
