apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: llunde-pyparser
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PzBrLLXjemq8Zxdij82ly/L8RHoP3epfL5MniTeTwXWiZ/q4peHKQuym/n2dX3Wi,iv:BHjRlfi+RQ7u6pwAUy7UcEuwZ5G7cUZSs+iCT76dqYY=,tag:WoU7VGTZ/iQicZNK60wTrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMG5kZG5KZnVzL1FPbHpK
            a1FqM2l4U1JDY1VGS1hEQTUyTWRGRFlrMUZJCjJxcFR6UytxU3p2NGc2VElFQ3Rt
            dzlSYkRYSU1OYkhHeG93K0JHKzdMeVUKLS0tIFNUbW8wbE1mbnNRNWNxVkdXZzNY
            MWVaT0xQYmJoMGpLOUZGWjhkcm45NEUKU6gwIQMD5BQ0sjLkMoNwl1A509Q7LrGz
            mve4q7CoPenf5/62YBN+yzbynceUeIlOinaKbEHAV6GXTIEm8CuB1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3RQeEVaZXZ2TTc4bFRq
            M2NGNnVVNG5TQkhMcnk4MVFKOHpxM3hQaUdJCjJlOGpiMksxOWI4RTY4empVVFli
            UCs1elZ0L2ltamYvZEdUSHJZdGx6R0kKLS0tIDZ1b2R4V0s2M2ZCeDQwNDRlMXJw
            TFBVM0xpT29xYytCeFEyRU4xUXpGancKGclSm+xOGY2k/Y6r5Xodmbhrhqx9fAtK
            3GCKUm5BLvZVJgLYXMy6xwBvQcsUqh3H2MQ6JxwUebXgvN2j2RwqlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ0lReGRtcmtWWTVWNlZX
            N2tDSTFLbGRPRkY3aGgrcWt5cm41WFBOVERZCm5vTDE0RldydStOdEh6WVh2dnU4
            Z0lSNmErRVVLSnFXdWpMcFppV2pqRkEKLS0tIFlUK1dyOCtLYmw3c3dHRHBabC9l
            Vm1TdHBRMUJUSkZHWVU1akpzNkZDK1UKFIeVbZkww1UXjrKYJURt8eURDIJWfj7y
            pLDcnN253imaLuTTNKtFssvo+nrdcIp0PfJQrJNyGq9GYV6hYmryjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:02:10Z"
    mac: ENC[AES256_GCM,data:2kecPYEhGaAcuHTOh7YeNC81FTAtWaRkXkJAPBhFKhU6gRP1ouqx+cbc2h8VW6pnQOmPmhPK6oP31nkldkXBx5Ad6CdNBrCsfE9omaumYDYvvLZamC+OmrXY4C2Kav1UG2G5EBM3MPBDNr5gqBPDei6dHfzVf41aW8HhxzlzT4U=,iv:MPqK9+U6M/K3aTQUs5K3yHU9J/2zHFa3MT84g1uL3Ig=,tag:/JO/lUDcJyqSD5hzi2AKYQ==,type:str]
    version: 3.13.3
