apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde-pyparser
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:k/E3BkOiRQ9Dn3JldL02+hxkbNL0pN05LRv088QfQitHcsVI6LXqe8u+C13Q6c9m4H4K+NV9/bBoLeZS4SacZT/ODzTHEZg1EzRTB90KDEmV5+PuTla6Fd7cKszkmzGQbGwxLAFP86rdezA0t8i965Rrp7LXcApE+dwhx06wWTFY6scZ,iv:l75EWH4PZZGjRVJ5utv5VblXPLNS014eVeiuhfK1wOY=,tag:MZoIkKN5kDtpJ/nte6nnEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK1Yva1hnSlNaR1NZOWkx
            SzZMMHc5MGtSOHIxbndwczNyckt6MWFFdHhRClFoNC84MnYydGcraFRVaHFTeGtR
            NktGcWx2SXY5c2lTUlJ2SCt1OWV4d0EKLS0tICtzZzk0M2F1MW5oMnJtbStrNmFz
            MHE2VjNlSmh6bGVHL0piVkk2SUFiREUKiSaeOf5sGf/U7s1PdGJFyhMpsaH9AfU4
            zxFNnoTHlCQhZqN0cRr0MwqRsVU9XJuqdsSg+iKXun4GCfMW8zVuCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdmh2NDl4MTEyYWZXMm1l
            ZEM0RUd6eFRUTGFDckFKS3JEQ1NxSDFnL0ZjCm5TV1FJU1BveVJRTFFORnlJcnRp
            elI3S1JyeTAyc3NXR1ZlMXhPUkxuVHcKLS0tIDB6alZaZkFYMGJWSXV4MUxrS1dE
            VnZUSmZ2M3M2c2NBcEt1alI2elRWemcK4Vzcmy2QPmuNF3cGM9QU64Qg7iNb4lIP
            vm/SfBLMV8sQBgwSUb9MqQ77ANGgEzq+o/06Gwhr5VWM14kmDZ7Y1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MmYwam9POUhPT25VNkk4
            V3hLb0I5a1VRWXhickRCWWN5WkFISllGdEZ3Cm4vZ0Q0OFNMSnk2dVM3SjhvNmth
            WDhWVTdSNEhzWklZai9YSEszZWJDamMKLS0tIEFPQUpDOTVVandaVXNVbGdBb2M0
            T25tRE1KWjdudkRPMmJDNHBna1hGaTAKffsVpqfL/6XkGdLRJCL/9nBh7x1Ddn/S
            hmTzP0pPUANg8NcsSncZBjSZZ+Uzkb9PnG5MrmjvSlOjxAH3++8SRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T23:55:56Z"
    mac: ENC[AES256_GCM,data:4oSVFu2DPD2AMMrQaMIopJflp0m8EMGcMd3mfLePY17uM4d2r8OBV60KKMt53cf06Wrp4vnC7tzut36JZUJtSXT4qbpHORSVEziT1G8V412c895Dz8reTKsSxhY8ErYTxxwVZYEviulNeXSFohmAzI57EUXKvL6pLpz1sjJKub0=,iv:DgtPmGsulJcTnSl449P/MhJ1ehneHh7j8xAZRWqmhU0=,tag:EaAUgM1h2Tmab0Jhxz7Yfg==,type:str]
    version: 3.13.3
