apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde-pyparser
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CrqBX2LdieleXqdm7Y5q9O+//nXLY5CANPoNP4+zk3CaIIqru96GqDBIzYGxEO3VtL/PY6GSyTki593fi4Ma3KTsv3WlXfEx5Mzplb/qAAckWZSd48oqYbm0kvo5Uoz/lDMqQA+dXz05eVzDp7PCxK0TBXo2Y5ZQrtHn9tQLSk1Q6cIxaeLBwA==,iv:8UrePUcGvDMzXYAu7mirgnrOp6aT+l33suGxj7nhU80=,tag:qR1k0kduu1dNTb7moDAmhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQTcwSnprd2V4QzFtS0VO
            VmlWb21jWVNiSU5ZK3lzSnRsVlBZZkxMNlRNCloyTjZSNW1XdGQ5R2l2STJ5YVBP
            dlZpcVNaYXFxQXlNM1F6azRKWHZlQWsKLS0tIGRCRmV2b1lxUVFuWlU5YmpQYW8y
            SUpMaVBEOXA4cHBIMjEySUdXVjV2bDAKVA/r/iobh17RmUHliXeFiY+84wuJEsVh
            Gn34VWM70EeY678S2cf3KIQvzKyULfhupI6UG9fjx/Qkq/W5s58nbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR2h2N21tVE5uQmU5b0R1
            Y3J6RHRVU3NBSE11dkRPMDEvNVpxWDdHVVNzCjNCdStXaUcxTjMrWDQxaDZpcFV3
            amR5dGxZYktFc3FaMjY1QmNFWFVMbHcKLS0tIG5naDVKNlVIWktXYUtESk0wZ2Y3
            YVUvOW9vZ0pRTDI4Sk0yVFFZK25oZ00KBPOhgss2Er35zYSwk+34QUm2COlf54RA
            QBdMEw7Ubkt5bptURq88M1hIWgwiQ5pkmnvSRmUwacJq3uVLTcJVVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRFRaMnVlamJBWUhiNEVO
            Y1hWcXpabk96azdEbGx2ZXJ5VWR0T3BHQWlJCmVtOW91elpQK2g0c0pMcGM2MEtl
            K0JsVjBLbUdzNlVReVNCY3V2cjRXT28KLS0tIGg1KytKRUhPREcydm5pNFZNeDJj
            bkFBek1LYzRFT3FhNUd5ZkNoRC9GNGsKCA/jXoygnPlNV9KKknkhJi9e6VVCk3az
            LZrUvRoUzmq8cTkha1F3knpm+lOVZb2OctBrK5aHL7DgL0U7xFpPSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:02:10Z"
    mac: ENC[AES256_GCM,data:P6xZFORo1cRSRopZO/NniDqXQtOq/zzt7HMcqjAna6W86yecG4JwHmJSmAfj2SfJXtk+rRiNC6wr3qrBtvZYdEiHTkrpWjfhAJlpVBySFDg5iUMeNC41DfFcAdY7UtDGwqhWlDMl5n0sEQ/96cFfq7aPQgfuZL5Gg2/D24MwIQw=,iv:NwlDY/fpA2en34U6GfSTqBAfZuh72imlJWWwzimg7cE=,tag:dDqertbzwc+GKV3KizmFOg==,type:str]
    version: 3.13.3
