apiVersion: v1
kind: Secret
metadata:
    name: ghcr
    namespace: llunde-pyparser
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vYrxrpBQR2McQBCkiWBgCueEcrICRfqmQAJ2Fvtxumvevcg/AyuLTg4OUD3MmyEqkx4P/seq2NNV59CJVJ7SyRsaPS5HkFP/zx69JrZMjDyr8NMfUHnqlweIe7R6rybKqNAmQH+h4lRCqkTW1xrKRi7idK6k6kgQBwTHvod/uFbT0+Znf+GNI1P14anQcADBNvY68KOExxf/Ii7yR21m69wcYTbOFSVYZ1HTv5ZkAd6Cp9JGTlxXDKBGOpSnrVY6fZWARwQX2yOSQFNBv9af3luRYEf/EAq5Zg4BfXFGc2mo+UM1SMhzOQ==,iv:B1Ccup2FUJ39QXqlTX4tUdqMJ4JbHxk/Cec9FhsGnf0=,tag:KB88jKNg5AUmbstQJoM3vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK1Yva1hnSlNaR1NZOWkx
            SzZMMHc5MGtSOHIxbndwczNyckt6MWFFdHhRClFoNC84MnYydGcraFRVaHFTeGtR
            NktGcWx2SXY5c2lTUlJ2SCt1OWV4d0EKLS0tICtzZzk0M2F1MW5oMnJtbStrNmFz
            MHE2VjNlSmh6bGVHL0piVkk2SUFiREUKiSaeOf5sGf/U7s1PdGJFyhMpsaH9AfU4
            zxFNnoTHlCQhZqN0cRr0MwqRsVU9XJuqdsSg+iKXun4GCfMW8zVuCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdmh2NDl4MTEyYWZXMm1l
            ZEM0RUd6eFRUTGFDckFKS3JEQ1NxSDFnL0ZjCm5TV1FJU1BveVJRTFFORnlJcnRp
            elI3S1JyeTAyc3NXR1ZlMXhPUkxuVHcKLS0tIDB6alZaZkFYMGJWSXV4MUxrS1dE
            VnZUSmZ2M3M2c2NBcEt1alI2elRWemcK4Vzcmy2QPmuNF3cGM9QU64Qg7iNb4lIP
            vm/SfBLMV8sQBgwSUb9MqQ77ANGgEzq+o/06Gwhr5VWM14kmDZ7Y1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MmYwam9POUhPT25VNkk4
            V3hLb0I5a1VRWXhickRCWWN5WkFISllGdEZ3Cm4vZ0Q0OFNMSnk2dVM3SjhvNmth
            WDhWVTdSNEhzWklZai9YSEszZWJDamMKLS0tIEFPQUpDOTVVandaVXNVbGdBb2M0
            T25tRE1KWjdudkRPMmJDNHBna1hGaTAKffsVpqfL/6XkGdLRJCL/9nBh7x1Ddn/S
            hmTzP0pPUANg8NcsSncZBjSZZ+Uzkb9PnG5MrmjvSlOjxAH3++8SRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T13:33:19Z"
    mac: ENC[AES256_GCM,data:18bgTEQRrKOfTgPgYHfB5jc5BAkBnRT45V7ZclehwLvNkKn0xKbpEELLlY77P1YpkgfTQV83yAP27+yL/HGbV8ykuERdKos+62Ql5xwF3vM689trjW5qAlTHMTLGhPMOtDolWbMBWsBcOUCzHH32558VZL9aAp7fsU9wVgkH/3Q=,iv:mtB1uzS21T/39ZYcq2a5nWGVUtLzWAmkdoQ8pMI+5h0=,tag:vkG6t0evAC354A2m+8enXA==,type:str]
    version: 3.13.3
