apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
- namespace.yaml
- storage.yaml
- database.yaml
- tunnel.yaml
- network.yaml
- application.secret.sops.yaml
- database.secret.sops.yaml
- tunnel.secret.sops.yaml
- ghcr.secret.sops.yaml
- backup.yaml
- backup-dataset.secret.sops.yaml
- backup.secret.sops.yaml
- backup-primary.secret.sops.yaml
components:
- ../../components/backup-job
- ../../components/backup-primary
- ../../components/netpol-gate/egress
patches:
- target:
    kind: CronJob
    name: data-backup
  patch: |-
    - op: replace
      path: /spec/jobTemplate/spec/activeDeadlineSeconds
      value: 12300
