apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway
    namespace: llunde-pyparser
type: Opaque
stringData:
    PYPARSER_GRANITE_API_KEY: ENC[AES256_GCM,data:pxC4kznLSHhsVQ5uWR0NZ0UEvVrQdEOyUA==,iv:aO6Oqie4peWaZ9IPB0iwxkNuqY8JPUtKFRpw7ycq9ZM=,tag:Y11+uDUTjeo+IjPEB5aGIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTy8ybDNhNkZyU1dIVzBD
            YlBUT3JGODBIc2xDQkJzdHNKUXNENUlNVTI0CmFrWWQvd0lzREFNQ21aNy9VZzVk
            T1d3WUNpYTZ0UEN4QXkzSkRCZ2dVbVEKLS0tIE1ZamRJemRzT0p3ZjF4ZUlFN1ll
            TFQyMVJwejRJRGdyODBmOEJ5dUxTWkkKtCs18CnQ3+ZJccVKeLzdwaQGaHK3Yt+X
            NvbquVSdBttUTMFTIKFsoGRjHzM3Q36qgyX3gyv2nxMyFqlKh9U6EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT08yTE56a2lCbFJ2TWRN
            TWF1aXBmM2hTOVhvUFF5ZUFtekp6V0hIUndNCjJFT042Uld1OWxmVXh4RGRKU3NJ
            WlFMaUFRQm95K0RZUGVvbU9ONm1SNVEKLS0tIFFGemNmSXpUdzVzRzFYRHl6TG5I
            Qy91blNIcERmcXpMYmlnbGI3bHlIaFUKK1Iy73bsgWeSd8+fSBx7VJBJntDOYvn9
            Xb7RAT6/paMKaQ3NyD9z6wLyYWCJNKdwhQ8UdxTTTVKj93NOxBKbtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNThCSy84QnNGT3hFV054
            azEvNjAwanlrVUc4bnFlSkIvOTRVRmtqa21VCjhXU0pWVTFsWFZWZ0N3dG9NYkt3
            citBaVNRMWhYckE5TU5mN1VMWXRTYUEKLS0tIHJzQ3BIWG9JWk1xTG1OQitEQWt1
            YmMwQnI3Qm1ELzEvdnM2Unc5U3ZNQncKD5adfGj2c4GX3ycR3ooTgAOsYrrO/c/S
            ofaD7B1O9IcMpmlv6oPcsNXmWuruwDjAsb9Y/iCzSdK7s0h+MbGsyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:45Z"
    mac: ENC[AES256_GCM,data:yY5j6tYfpPzzguZsHnTTSEozfGjpkMiERWxp6DmydD6Kw5hKRLCuGJ6CfTQBH2oUHqW8ugp1sIsYT3OOI3ckYyExd5hgTVSZc0Pv4VYNMg2osgBQS4rZciyzKD3dddMsYm1f4XnyRiBEkY5cWG874s35V+055PNxv96Cjq6UdlA=,iv:e0uJMjMLd3V7MTNSNGhrS1KjgcfhYwK5uhlFoviarAU=,tag:NC2PJmnzgd7JXkw2Re6nSw==,type:str]
    version: 3.13.3
