apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files
  namespace: llunde-pyparser
spec:
  storageClassName: local-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: llunde-pyparser
spec:
  storageClassName: local-ci
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
