apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: llunde-pyparser
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:HFjh8hyUyfICbxFnv6aJbaQaDIVKKU3isYS9FQWGU74+Hjp2oHQwlU2LLeUaXvBAwtclvTYzMQ9nYd1o4ShK4k+EgRjArM0dt73UMxa6waaPV2DckSQCD0EMwW4BRIRsD2ifloXo4r2f9bXvMU9xXV/zVr5XTZg6jJlJ7RAg+4AhXdf/sRtW0AX5hx5oci2HgrcjrwMBz4l3j1DwzkyXcmEixSh2IhQDxVkli3rbrc/nesAyIFmX545OhWl4jlWktGFmNjcECpcUR84mJgOdwQ==,iv:KVY3ycBGaFbP/D3OiN4dxHURrdt+4pl9ExX4Pbb9aE8=,tag:KgYoQ73RzrMwD7I/Y6Ak0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RlE5Z2Vsb2d5K1JRYU8r
            YjBRL3lRRCtXb1VZem4yNzNPeTB2TU5qZ0RnCnZhaTZwOXBvZmhUbTN1cFl2bUc1
            Z2xRZ05tNkFuR05zZHVwTCs1dmltOUUKLS0tIEhGcmJPdFQyWjAvZ1BhNjg2THVP
            ZW9HWjE2UGR6VldWeTIxL2YwZk8xT1UK7oIcWeQ0zbUR2eVQ5gBuJJCHn/mhHf71
            lDWGOGY7MU8z7vRcAgTcwJYZDsC1iav1tRHT0KqNbQMzMyc5dSuciQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclpoNENidkxJYUYyc3ox
            Vnh2cng4VmJ3MzZ1Rll3TE1Kb0QyOWV4dVRZCkNQNC9LakJhcVZ1NUZMV1lHSkVZ
            UUlLTm9sNkZpZTB4WU9KNUNTUktGRG8KLS0tIFpUMHJFQTNtYVJhYXlDZVB6Rzd2
            MDhNbS9UNHFxeFdXZlc3ckl3N3RibGMKRkjKZuhhNcxxaRmd949+eE+Qztg/2NI4
            +88iBYpCB8SqTgGNDMRRGOHdRKPdVAZ8zRoYIc7qh4P/ldPTaCwz3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV1pURjJmZ1doK1BvMUtY
            UXpCQnVSdno2QTd5WmNuRkYxV0FPQlpMaENFCk1oaTVtU0NlancvcDRhQUdodnJj
            YndqMWNLN3pGaUlzV3lQa0FpR1AzQ2cKLS0tIDJ2S0VYekUrMnhiaUl4TWJTNTJy
            NFNWWkFCNjl4L3lnWXNaeXFoZnhjcUUKoFTaRbPoADKgNLESV4w2OSkPB31AX/Wg
            F8Nrj/t5ECve04aQvVJws96NTidDXB3Ck9iA4M3/kpzbRH+zRjj7CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:05IsKZ92TXADIE3PNnjjzyn8B5aMOWQ0ABFJoc8Z2BkgYGBC9E4MfjwWZCsJILrbTT6oqniHfEx0JZK4HjxCNyE1t1Yir6iQp3WgZGKJHaikZMYoGk4ZvhNjuuK77fFoSDGaioT/djuqhesNkO2kNgZ15wsVG4DJCP0CO9rWbzw=,iv:fqFPnGKVZd065CubO76KjY3ixItTMWCO+52vX3X16Bc=,tag:rpjMnxh9bWMtigIaar5hVg==,type:str]
    version: 3.13.3
