apiVersion: v1
kind: Secret
metadata:
    name: tunnel
    namespace: llunde-pyparser
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:T5I9y2VSa1KOIo6SCVBRTHV/kqlhG+F7WP05u2IuoWiMwS/Rpty+nKrb4syvp1jezqXtOmg4Vsc0tsMHot8A8zhzcFt5Kyj0BGkFp5uMqAzJmuxSI6XG03hQdTwQDdmyJ/au86DI4kgrVs890Gii6uslU0W3yUZZ5vBtJJy3+6XRf3m9WOhkJD+rrDRvSOJSuAw2jOWNM353ci/Zq7jmzZpu9kH7O57fW4RcRVleY0DkCP/GzSg6q73FagsxfW+pd7LFfmsDSQwSZQUC6XBJcQ==,iv:KVY3ycBGaFbP/D3OiN4dxHURrdt+4pl9ExX4Pbb9aE8=,tag:wVLRfIQRCUXjbFi2TQ2QkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NklyOU8zZTFVRmM1Si9o
            b0hBYXJwQUlWcXZMbS9nUlFmNkR0QTZrRWg4CkszWVhMWjg0WWpZVDRHQ2dZK3VX
            YkdJYTMzWUVxTjY3V3g1K29iaHJjbEUKLS0tIFk1bmRZKytJclpHRDNkMWxTU1pW
            Z0w5ZGNLQnBaUE1wSUgyL20xV21tVWcK9hxdczQYSjVoYLJlStfMUJGxFiZcG2dp
            /j4Wh48LVhExojIgr+wHi+BR2p9kgKhFFZhVeUnCT06A/Wp9MtYGpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsellvRkRGaHF6UmduYmdn
            dDVCK0JKY29RYldmdVY4QXpjeTVGMjhZRlJVCm9ZVXJidEt5WGdDK1cvNW94aCtr
            NnNmbmMwR0xxcTQzclYyS1FVeXBJV1kKLS0tIHRwNjFqcnQ3cjBaSXFFNk1CcWkr
            R09YamFJRmJBZWdyOWlQN3owSzVWNkUK42N8wsoYkQ+MiXqY/EwWhofxyo4dKrw1
            m6+56oOzymbDKh/zIN4Sc/t1TA6xFbs3FxAT1PqXpIrjyGKQlJLLFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQlZtYy9mNUdiUTRqdHdm
            dzNCRWQ3UXRNTjB5S0NCSHlWeVY1OXhPVWxBCmYycklRMlJyeURwbDdKaXU2R2No
            Szg5Tll1dlc0SFkvWTRoaXV0eTZMUWMKLS0tIGl1SG1FU1Uwc01sa3Z2SXNuN1la
            MWNBcTlka09ueWlSRk5wUzViQUFuSmMKrfnqU8vff9xcL4rvqaAC/x9/3xeC2Lzm
            VrOKqG5kU1VS7IgDNt1L+SEKtVQolR6J76D80v1yE5e3wG4BYhG9FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:02:10Z"
    mac: ENC[AES256_GCM,data:d9WyPieq+MzqRLiYD34KB/j09XJfyNBkNbZ52KWReRRFSzllhU9G4Ncvux3spzQ8Gi1mghBp3/hgJiOOA/VGKwoMpfP8WfGSvNxBpeYrFw29HD+ni9s/vUTav4LNqtrLqWaD4MK5HXAMwmjG0j2MFSGiBWWaYUYr+KkWsQGXk2M=,iv:STnbcqqj4yBeFhUCXL+qTOyHialiDwqEfc5jtZdghGs=,tag:9orJ5g0lI4WF44MnCGF5GQ==,type:str]
    version: 3.13.3
