apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-portfolio
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:530oIxATm6G79qaac7/8nTDbG8ysl+UoCfQ=,iv:s67OB0cLFwURUhu1hZPnwxZK+FS+7NZyAXiv6zDj4n4=,tag:0s/OLsp0mVsnDeKN2BMkLw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ev6jKTR9nVK9pVMQ/+dqhpPQQH2+bLRPJ3+y8LEPj2uGvjc/r68sckYi4H0YE73X+6GUssbLtqAFmxtw7hPEBg==,iv:CBRzcqdVIrs5lb6x0GUcP63AHwFqHnslLC8wz+7ZLOs=,tag:s8Y0/CY66x4pp1Y7TjReYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRHY1d0xuYnJROFozL3Bj
            UmgrWE0zQ3JBMU5MSCtPU1crSlR2R3pOT1RRCnA3cnhVNW9iUk0rOUk4bUUxcXB4
            blZ4SHN4OFB1Q0R5NVE2UHlyVklERUUKLS0tIHlHY2ZaWFI0NXFTbWhQS2drUVlC
            SmlrYkJYTkVYQVZWemdaUXF1R1h5eGcKXqeQsxAmMVw+xL/95dWFlXfRi93EVqhP
            yPShLoULN7u1pOggwp41Cd28Icd8l2NG7tOjp21naLYl+qKnmjpCrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMW9CVEorUTB3Q2RRbnF1
            ZjhySFJEdWViOWt2VjluSWVLNnB6aFpVcnpRClJWV0ZKdi9HNUhweW4wdEEvYS85
            VXNDYXhRaGd5eitpVkV1bFhjeWIyUUEKLS0tIGhBSnpZNHRBME80RHJYaWlpZjV4
            bDVJNzRPdmM1YlNqcGtPSWNlVnQ1dTgK5sopjCpnw4EjdfbtPIvzb9jsjIY5SaDB
            ONnYYezyDAxa/9MBTlOzDIX723OaMeeNJurGQiy7K6Y9WzzqumA4Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeUJGWm1EQW43eEpTRDdX
            NjcyWndleEljendnZm9mekdTWXpoa2lYSW5nCkZYTGtOK2s4Q2c5V3VmTWtNbyta
            UWVvRUhKblNFMEQ2QlhkYXc5YzJSaGMKLS0tIDVVQ3Mrckx4SXQzbWVDOURNNUpR
            ZkpPb1c1VFVQNkJyOFd5TmU0ZGs0TkkKtIUQO5zNmtSMwNgCb49te3zmK9kAczS4
            6A7EJSLGM+omcyHwgNUcIv2wmmcMNOSWLYdjmN+uvctRcOr8Iq5d8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:ma3afiW12IJ1qkC3n6FLgHaPdm51cVG3dLy1I1GERobfnEDLczAPwEltDPdSvWrNlUrxxXlCm8MMRFcmsrIGIIN9qi0t86kqqGsTXmKr397Db0ois7epXjzXO9XtUPsplm0ISNeh0feQ4Ok9qvVj3cYm7wzVehfXRc4KespKBQU=,iv:DzwlFKmOhDSALLoPCWqvVbILs0QdYHcEQEFjhNsuOV4=,tag:IF+Xg3yuoLLuob8OQlELig==,type:str]
    version: 3.13.3
