apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-portfolio
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:Kxq9JGaH8A==,iv:og8yZCWY2ZNE1odXmTbldn+bXWvDScS7+p7iLcFWkRI=,tag:zFqP5PcASxkpkAUwIe/hyg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:+GXNe2eyovr9,iv:Y/o2R1dJBxuOfUJQ9We0whJcysQrtt8VBD+fO069Ryk=,tag:PmYJmLG5vDYtayUHv5GPVQ==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:V/ECMzgMJxzmf2iEAG0HNzGKmGZoyJSbmKB7EcYRLyw7iXVyvyEgwPjr23x8OSjjkLU9z4ZrE+Ooh1bkc6kCK6zLYppaOav/Um24vIyjNNHq+dLJaPFAWYsIaMmeBZ99PylTjDcq66F1lDb78DqyV13+oZ9Mg7FqoQ07aOEdk6SeMmoRz12sSr2qWOMHfux4+IKJUwdME8a/fS5GrBkbBPQcdVQvOEcaD33ssDA4R+KCyH1xv9XvcP277yfPnC4grHU6o3AC45phpWo5bpYqeenfHU1KzNXnksG9Lcq0r6/ldv54qZSMM0HDR/BSUjdGEl3+/oQc+F8Km86I7qyXjeHwN0ADVeI/rvec+9m/u3Z/y9vSe/oVLrm0o5fqIhJzPCo22ZKsKw/sgchFS4lAiZWoK4qiIlK9IiU121yqvgGx4CykKOyeUemkDBSQZhYzU6PwW73WtgJZ1Pg7BxQlblu9lMzDKx1D7w/RNoyqTlV6oOWgqbW2i2VWIgxHFqQJ8M8UoiVse0nm3NWWRAwIUTREf4ZJ7hd2CFeA65y/yeEKa4yVbocl1mlinhxOjYaD7d7j48QXwzE64825NQzEC6+oLFZUyEjIYY3qCKfbtPyL0Ktc1h6z0wXD3jhbxrJbJELRsDVnz94Y27UIouFLzukbz824rWROIxzf7y146xw96e2reZb1+IdGkxvWWkoQkhUDyMsJqTRJbAjtpw69jyOCav5ajrJS4bAnNs8cnsv6uPKhr+/XKjVL237kSAS2oMoXj0b3uckMlVh90Tgf7eLFPErkOohpxRXeh9JAfA8AWhlWf2rPmYiKk0SoAYdykkvdYNybZ/5UrVc4RoNB07yMLd6oV56TVXGeWp3WqQFZPAufOYxWxNJDMf5NH1pK0DK50gaTq1CbfMQr2OCvj6rW2PaKKvXQ0Z2L2p1r9r3NFWnjZ96bXNy6RbdFX58frLC0BSxwQ7Y37+opfDP1+svjJdbOxThgs9YaGw6ERsIAIt0gAcXYcQbOO2Zap+ep348UNVfcSW5SG4i/231U/blD6wv3Q3w50AksDBOmEQwL29odklzGx3IEoEnJ7LjmNtBNUM/8WosgveYqy/jsziFWPLzWHlUad4Z/Rh4KEJiBbenMmMfUrdYTfhA3U34aaPMqAmn00dgeFYUhAXbYTeCXPD9l2JUtb5r0yRqcyhVUoSG6e24m9sw1LGkpW+jvMpOzPVZflP07zKDjFl2KPWY3djoThaW79n6Z9JlIzEzIrYNXuAhXZMlMtaiCosRVg5H7ttVM6x3/5Na6rwc+AJnhE8RgG+0NWQsEHzzeiFQ5uAM9h976hRPvFuNVy2EeJ6TUOW7QnOtNwWL/yNxV+Cexy/9MRv1DZsMpjK5NbfP4OzWo75rqDji0f1P4lG3+HJc2SyGKhaUQsK/vWSYif6F9lDWW7T3k6finxQyqwltanFdr73EwYhoP5jnXNwfvbYL+ATvhHEbp+AH6BAbl5/UHy7KEwW+fl/y4oijtCc7EWnhpzn+Ck2v98AUuYyIulQRA3KWpt0KsJFoiKuSsLZg5vKpPjYcSG72+q4kQUkVp/ZPkJr2ua6vT/59buAbDHPmxTMmZ1mmj9IPH0KvMlmj3Xh61OGoTKRelYn20BvS7ldEKkPAM8L4cqL1ZqWeI4UZMKORwfH1m6U69KWdS0ycBj/BrnhTuY6W3rKHeK2VHxdL0LkhQMoa81swteDYGFX55i4fOyR9xoZ31HoHggDupGJdH+xmatAoNJeyYeG5NTMQzqyTgpF+B6JKra6jV8Iw3VZ8t0Hr1uD1LpNcFZ/Ks0oWBSAIelZm5jaHH4Sp6PR1qhC7Zo26S7r4sG6jTGpfz1INANRd3kwETGKq8S6E2erv3nnUXg6y27M6MOall3eTQjM2C5S74S6fgA1hRShQOlk66a4FQWGK3FpQ0OxcutR4ZL7ClPTRSVk8DW7/hC+zvlvdbw61FMnTeEa2gKY8jPtOm7N5nlefZKKCZwRB+0VX5X8D5qtbZsIJRDiTmmwcHqTcG0ANfko5TMfIr+wJKLGM38zbr+yTq2c0UsIZkIYIkSE7HEPHQzRWnHK+zfEyDuzvQtsdPDlpNTrDVHTd6mRPKsNKLZCq7T2GEUfCpCj0+H0HZHiDFvVvo5ZNLP61oeU4HLJyVFOZwz7CcDQJ6HNdPsLzc71/JxpZmrkvztaxFlMIzCSy4aIqgit0RSKIzdGorKSqU4SjS0g==,iv:rpD/uzj25uCbChxZ1KtS1ooOsSKEMWdG88/YdKcIck4=,tag:909WWfmUuWcTn1tIEJkZTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQm1uOU1EUUgwazQ5RUZK
            OG5YNGthUXI5ZTF0M3F2bmF0SVRPbGs5YmdnCjUzVFdCWUtPZFB6SUZQcVBjWVVw
            QTJyMHhVaGROSVdhb2loNGZ4dVA3Y00KLS0tIDQ5K0g1emFUbGgwSWkwU21tQlAy
            cVY1a1AxeGJ3TUhpTHZlbWIyOURHcDgKwA8iifem68gu5OEyj2aOjZqsTLbNQKKA
            Lpv3hLIugnBz3qp5R9m4duU5Wb+VcF26HycHWqmF4vFWGNXT8acFpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a3N5N2ZobTZ2M3paaGlP
            N2dWNmF4YkFCUHVQK1p0S09yUjJTMlp5YVdVCjI1dmtXL3dadUlnTVJoRWRxNUtY
            U2trVE1RK1VaK3RDQm1WTm8yYm9JYWcKLS0tIExKbEcwM2dqWTZoazVkRFY3czFO
            Tmt5S3RudlZRa214YXNqU2hsT2hwTFUKmx5VX5Tu5aGBM58pJ3vVdWzwexj9Cztu
            6ydYueOx7umiGrxY+JgRw4ULU6nNOeNUL5PaGu/LVc6pk9a+GxkzKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVMremNJRG9NNGkrZ2Vz
            Q2dZdDBwMHFBeGFYZTZJNFlBTnBTaTIydTJnCmZydnFmQW9hMW9ValYydTNlTVNm
            elMzRFpCZ3FWN2gxbUc1dW9QYkU1K1kKLS0tIHVsSmx3RUI4YXMzaktRcVp4cVYw
            QThQSGQwYTg0amNmbDU4YjZiRVNISE0KXL1rkD5aU6TXqaqXbhxJ3R+rWsMvecnY
            8TsmdzbZbCinYiotBX2fjpNwFRTJF2J56KNSQ6WfNIHNtdCdOzaEug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:33Z"
    mac: ENC[AES256_GCM,data:4zGv7I+PruV/dY4EttLbnaWUhJ9fpqeVdDvGJqcjQf7IDKUAh59gVo7Ey2mqZO4t2pt3O5j7mIQUYlpbw+t2ogDbvj59RoUuJ3bBSVRafglB2GtwPsxJomchAO/iBUopJ936r4/+4Mtqye2EqXXQr+pvvfpECJlienvIi2VAyqU=,iv:1gUBjU95DgH4JqUwixHambDEl+/VbInFU5mwMsro4q8=,tag:B2eUzNvc/7ALB5NTG8h3Cw==,type:str]
    version: 3.13.3
