apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-portfolio
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:eeY0UhGTKg==,iv:og8yZCWY2ZNE1odXmTbldn+bXWvDScS7+p7iLcFWkRI=,tag:7WP5WpTClKoK2yM+C2c37g==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:uuK4fHbHov+9,iv:Y/o2R1dJBxuOfUJQ9We0whJcysQrtt8VBD+fO069Ryk=,tag:7Wn5ndw8qefGRjOrYD6PMw==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:Ci/W+Ijosi48dU+Pyvgv5LSVssuKE/PZbrtITMtc47N6+gYsiTaO9iNdgJTxSDpVD7OFfbtP3AeRCoq7El1+bpdLyl2otBlluyax9m+91NRCu7B5pJ/unfnIj8QaG1+vsQBs7NVOHRChpczoMZp0z9vrESNmUtaRVp6b9NGraWPC+F45jcTSAiN5wKn6ps47PVjG70Y1qIH5H8dkc6gXJkyFyN9TjghKrVxUhhcNFJ50hKMC7olKSAXPYbq3tJFjXugQk+NQYDla7hRlS6fWNFox7IvXGvl/d7uYRcx4rc1eirbptjj8zP6/YbDA2xhWHOZ/Ha43vkIwvZuJ3c6v/XsbrvZsgjtTURg/60yhXU5UzmYcUhC+SxG9PNQisb6IGgR0oSfGP7MECHhD4TOwRRA4zvUA8YHtkXso1Yj24BlfUZK4WgLBAYS1vKwKC2ZyGcv0M3p67vP8mx5K4YRmYAXbX+DG3bio2cAK7sxHwlPQXMDqcywEyOCU2ZhsLzE4qLMQ0g+mYQjFVfsNDzWb4+2q8ejyBV60qJ3fKgUev8gztV+4Cv0z+SuZmvO35Xs+ASVON9TyiINrqhgn2QR1AJL2RXmBE1riQ2wsi8jul1zx2xcJ12whXV0wkz+L+eUM6E2ucFpYUeRuK5VnOOnQ0cs4fmjebTT+Rs2Qq7RkZ24MtWQZFgBb9PsOZouCH1Iu7OBf4KBTE1Imm4bqoFUPW63zurGHpXwl+UlA+TWJh0kJM6GncsGTCXDJPwuZCPmTjU55EmxlFOMNmSXZhkOdc+/SKj0LGJrIK5hJvYRJf39gtcSKK9J5a4fWJ+nUNbEUwFGbxWyAToNVfpYNPFLMXCwO4IyN7gd9XlApAFVWbzBvvWN4pTEeLoY1otYz9EuTzKBlj3uZR2zFLeT803FhSTDnY9QT/TIIktVeW+cHngTZZK88QohecDApz2AbASAAltp3Y2hHYDd7OdFgnZ46Gvrl+MoP7v4W6xM5lxRTcSW42t4ff+MELtCoAslsDXpGFIGwSMxQYzHkI0motv+hFwNkqZAn1tUfH8KCOknWK2M+VPgCpQUzofoVIkZjRCOIadWNsHsFlzgKshiTgIlutfPC7fI4c51orP+V0g60hy+iS0nOV5Ra9l4QXRvmD5okBUfK4a653OLyQhq3MkK9Q0mdG7/5TRe26CCdSJPu9MMMy4875EjxC5UQb1TD5+DfPCezQ/cOF3oeQ0fIpv9Xnwi7cXFF/toqpCKqbrqYy+RtIqM5cQvvkmepb15s+nbFaDIx8IaziIc0eqZuE43btmXzMAabciLGUb4ba6sW0bbWZ+udm84bBVvjGRSq4xW4xb2umaBTUSIvVSj9azcUnweMwxPw2hSk3Y39dP36LXZdjgcqYirFA1Vnx1pmjL+ywrLGyZxvol87MgdqB3zG0LrdujgRVW5qWKI1HzrxfvL+QoPYsgZFybVItop9KWnLXVKkKPbdC7Mp7WB0KV7kCC3N3tx7OfilgfXvkdrd2eERYaW/5FUA+aLEyt/WjCXQtoj/As44psxefNt6z4yjzk/uFfuSlvvyppflVIJkZPrK5pgQ5u2lS43y3JNSML+rARnGOfOLzaPeGzee/wCm26De1LJwShG60xCIl/8nFf5rc98dgoT+4MwIMc5rbyY7IxNmEfP6pPEhaBpI2Y6sB2Unu1u2TFIcBX5rHj2806Ok667zmoSt0VmIlcB/uwfaWljqNXaroq6QanbPmwHmA0sfQ9hrENCH/oGSCT5gleaG4ekymtmNRhPIWKwy7mqin4xCR+bZfNiH6wxt7uAw+27ehAl2azTPXHV9eNPkZOVAIHY4xui4uIO3q77Ol+2tFvX9/XBqsZgO7/++ebSHwp7tNYRIxEtpK4d83F3sq2sjAf2RfcDo0Hscs3fzSOr8CUjhDf4j7f4xgvtrPVs/aYNJzPIegmNW1BjwgK9ZLUreoYwuWh58GMITlXM3m0idvAim9Yu8JrDPHj+nUhMd1RUZ5nzRs65eC6qw1a6DguFNl6etv/K2FooUGKYvh7eREsaLl+e1VB9hwd5Pn+n2qAnfeXu7D+3RzoILtsUoSLcUl5RYZX4aTJU29NGXv8pwxYZ2aJCAOf2Q1QBMuKFypEw0cOdGtzfjIIVPJ6jqD7BUMMWUXkY6CK+iz79itmYj0zT3j51areTjJT5iJl0QTH8KHsoyg1OvqIIpVtMGLECW7lUH02kvtdFp87bL5Q==,iv:rpD/uzj25uCbChxZ1KtS1ooOsSKEMWdG88/YdKcIck4=,tag:8tZdkUN3go2Q8hTygs0ZjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNDdmNTRlenV6OFFtVDNO
            dW5qRStrK050SkxkNkYvMWYrcCtIamhZWmhvCkpFNlNZWXROaHVXNjZPZnUwUEw1
            OHRXbkVKQk5WTjM3eG5YblpNZHl4VTQKLS0tIGtaZzNFbDNQalpPbkZBTSswSHUz
            UmdDeTBwR3ZqcWVuMGcySzRCWXNkczQKzzqZyP7Ql0bVONsfkcLfYY3AJn4tchcX
            J/G8ur2VPONZRToXzOkuI0TeCl3ZvlsmSaxJ55y3qpn6kaZ86oXXSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbUhtcnh3UE8xaWxVdFNB
            ZkNidFl2MDVjRUprT0N0R2NQTHpwSStiZW5VCjhXY2t5SHJjU0pFN1A1cTdXNnZZ
            RHZtc1djcEVoNDdydDgxRE1mdGcwTncKLS0tIFhPelZhZll3UjlWbkYyUFhLWkVL
            OUt4dUhZdk4rWnh6QnZwS1BqSDJBVlkKi1s/ed37Pl3+fbh3wOpZlI024PUSL5OT
            0Q91CBPHQlKJV2W+Llk9pUy/mWHzzbHi0RxxoX8IS7+3vBfuCgsBzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITGUrcDBEdEVzUTN3WEI4
            SjAwa3JzS21UUTVCcTlPN3p0OWZlYnhRYnk4CnJxcmpkMDFaUEZqYjdoUU8xeWtL
            K2xWcXJFSTZneHhKdjNRRnJjeld4Z0UKLS0tIERWa2dTRnpLRms0R0FWWVpEM0xB
            ZjVTdENJRjlvNWVEVUdQbTh6MHRzUVUK6vugMU9BLyorYOOfdvzw9iUrIHajT5FW
            VT+GdOwjhpmPt3HCbFbHfSjIe8t/uB7cfE9R6g9bXoJQ4xhmGiK5jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:jHdk77m/+MK6woEWO/gGHpb7QxqaN7eOYwSJkgVwu9dPP7rSahzYKLSu8Uct5YEd7EyB3LL1ypm9Nio6ftRv0RRFeh/x6QDLrKdUBDGwCOXnkdFOVYgjV3Hd2wLDuHLI4r/XsK+6OMA4fFr99/WL4eowW2lJ6VWsoM2cC9dHbFQ=,iv:XEjP6gn9fVUqBiim0ZOzHUD9P2+Khk8mZKsTZLrmAxY=,tag:LCtiF9TWZhz8+nX0jTiVtw==,type:str]
    version: 3.13.3
