load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "fluxscope_lib",
    srcs = ["main.go"],
    importpath = "github.com/fredrir/infra/tests/infra/fluxscope",
    visibility = ["//visibility:private"],
    deps = ["@in_yaml_go_yaml_v3//:yaml"],
)

go_binary(
    name = "fluxscope",
    embed = [":fluxscope_lib"],
    visibility = ["//visibility:public"],
)
