apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - migration.yaml
images:
    - digest: sha256:fe3352986b8c9f4a5bfcab6b5a2b9a3c983a514d07f057f6aac3856f08834794
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
