apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - migration.yaml
images:
    - digest: sha256:162c87f2b330def3cb21238d9df996279260f860c6a77154c5a6b3d506c066a2
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
