apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - migration.yaml
images:
    - digest: sha256:9b0fba265c122e4664f11738ba9d9af01b4f07809c139e1655e6baa40a472edd
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
