apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:/RCN63UjdHif2sgN1DHIXU//dvNgwSat+ZyU/BbxUSOlSxHsSatNeTO6Nov/bXmE6oKZzw2rSuO1nmND5qydR1+8vv9njriNJUbKGSZJEE6SWtmHcpr4DLcad90am0MlFm8BtY79N6Ch5RlafVTv/8aKcUDeax5i4sB2A1SsVYwiKPhY8g0sdtCZZseaiStUEbuppm6zPMFivNog4jgc/b6TmwHAnt7KhoBqA+lRFydTEVDUr7DBUDfRQ4ZIzTeJ6e83quFvbzhSiYJQLLcr2PjqE299gWgv0wtXG/09A2guhw47x5jHKjD7R6uBtmE1iTfkJpOIJbrVcWa3s8uKJ7rRry1ZIJWBvRHVzXb3Nf1AaMLgMJl4zHkgX23Pjh3YFpcG91AGyoB8D2Wldjzu3rnSaInyKw8syXO6LgVK5zwrSjI0a7LiqhHIK9yYLg+cQqPNWoob1jF8/q3IBPsX78B64wBZJfGgadlM3s98Ex8ovDrRb980jGSBe+krUfMFufkgSAwHK+LRwmnhhODNPUKl8BiaeiknVVZw+NstkPWohf7qP+w5N8UUAeFUAESzsG4JgSpXYEZgzQi7yhszqAkiyUdyVQCNSl8yrWIKB9e4c3LJr6T3yH26Yh95K7v4IbcljAeXsBi6G7BrwKz0Lu0GHLHfWX6mMzTpUfLOGYg8M81aEZzc98Jpi6npCiwrIAPkFAhFGFMt/3P8dmEE2r5xfuAtqp47vc6VTCPepIRQ6yf36/eiLIlUUp0xxJvUSk3x+F4oVe506TeW1aroShOqLloC9ndC9E2mxtNGd9e5bry6SMnkCXfuFCjKAGfm,iv:iz+LNyyp2f60QC64ix70nvy5UGC4RbCoRwKrDoR8CdQ=,tag:73mIN6yh9vxsd0NPT1YcDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlZHeUZ0K01xVlhqby95
            TUVGUDFBSHR6bjF1YWk1dEdIbmF3b0ttd1JFCkNJUFpmT1U2QUZENG1zcTByWndM
            OXhNamdSSi9meDZ4TGpNMHpqWmlYMjgKLS0tIGdLc2NsUkI2MU5PWTBoUlhNanc4
            V0ZCYWNLbTVSVk5XcXBaS1psTHYxVDgKWe6soays/GoWpJ4zArVc/Q97u9f5Xd+P
            Ay0BoFXjgFRBhSvF6NNFZ3FxwalZDwigkoCfiVwxKWRlI0IdhQ1w5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXRsZUdURUd3TE5JQ0Yr
            MUdhbTNwZ0RsV1AyM3J4MUVqN0luOHczOWtBCllucldtUy93Y0xJUXJzMldkcjRp
            ZGpkOGRITk92SVJRVG5HTThoY2d6OXcKLS0tIHY0SUVOd2FmakpMQVVVOFNCa0lD
            Snd3NGdyM1FyQThwOVdURWJFaDFxY3MKQLKAkhpDMX/iJUwhTKQzf4Cg9g52TAqU
            3Fn9HyQ910NAjKrX8fFvcX2cpBbdL1LWoybpFzUOGVVhELI0A0RXBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZmRmdXJFU0NteXRUQTdm
            VVB1cWZMaFJzbTBiL2haS1ovelUrUWQzU1M0ClM4Wk1TRk5nV0FIdFBxelFUWFpk
            U1BYQWpDTmJKV3puLzZ2VmRMTVlXd0EKLS0tICtuNHR4aldTWVAwSlJyL0NpdXZh
            Mnk0bE1CTklwMXNEYlc4Q2g0clhXL0EK7FwzAjRgyAFXcQey4DB6Sjv0bHnXRgPy
            PWBZYet61lflpA8Yn2sxx4PD4fWjoDt/r0E6fmfF0Td4FLki2m6uvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:1OuRLqoaO/bJ1Dlc2VZhYAp/tBabYF7hthQ2Z/6hKOgBACun9h0G5gSOQ4R/4icxbIKX1K5DFNJRTBCCuMCfK1iU13hxtPB7M55PglL3xphEQyU9BiDWrANBZMkLWlkXheX8c5oX1PDh/LPLx+0A4P5h2bmWe09XAGUW+EBEg0Q=,iv:qroyotU8ZgAZjAqSnqIFkVGwMusJ05rIR9GYcJMWzME=,tag:SNsblXqhXQzbeJPjombvng==,type:str]
    version: 3.13.3
