apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:kNQtsB7SKGVj5UxjYUo847TFiOaMrpBegXEmC63NdARtU2mVxQsCzJNQdqzX+/vHhz27E0YgTEBM3KRS0zLL4UpBnMcuvkOlx7AQwk6SkTPAYFcB5uEqyZUGmtS3snDK2D/NMgI11Yh/rS30B3HCv026+rr2zueqBhhTK7RhXTMjWkizqSqTTkzYE4mG2RZDh5Sld7U+MX5fwHF6H295BQh3gv8on3eO2uSdKmzqHzxP0jjZLu2xFp6jaQPwACf7tldp5ouMIUMSFyqB/Jfph94VTX0wP4A0CWMY9HL954b2LT0m07PgzkgL3u1YXc0onT2hD2OOcuNv03zmYfDEv//e1t1a4kv1BGRm8YXKdOyHsbyrj5X1sB0PEbjG5oIM+JqWf+prUlVoMx1vmvhRhDthegdW32ZI79Kz/wteiD9nUiOFZDGciebWSOqdVbITJ2FrhaTJR0KYsjv83llOG6NWCfzY9AX2Ei1hcbtERVL+28uuUXeWsMmNP4N8ADrGWts2azHQYu6i9E644xqsjR00923BxsPSEBmmeefVITaCXn0jsgf++vD51lHRgCPC/+wbr1eIunpkf66PfvYRGI/SxJ8sPhoYSWLE3ymedugnKToe3csqvTkNr4LbZ8YxljMFF6NROzvln3i9ko3TjB8eYTdDLUAdrAK0ehsr3v37QbJz1a1YAfBPjD1uMBGlkoOcqIRQ6z/LdT6oxuWQmUEOnEWnafLaZXq+VOU2vyE8ZjjSWav5m50vXmM6m3XwCfvIJ/5VEsUfdXlZb40jxziUYCP9lc0Mn7gWIz2rXKLv3AtopmAWXsMDmRcoNCjY,iv:bUOR10IQzitaJP7LLyeVYN4iun8i9w73GFP3MPRlA4o=,tag:/Us6tO/KweW+PTpAHEcy0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlZHeUZ0K01xVlhqby95
            TUVGUDFBSHR6bjF1YWk1dEdIbmF3b0ttd1JFCkNJUFpmT1U2QUZENG1zcTByWndM
            OXhNamdSSi9meDZ4TGpNMHpqWmlYMjgKLS0tIGdLc2NsUkI2MU5PWTBoUlhNanc4
            V0ZCYWNLbTVSVk5XcXBaS1psTHYxVDgKWe6soays/GoWpJ4zArVc/Q97u9f5Xd+P
            Ay0BoFXjgFRBhSvF6NNFZ3FxwalZDwigkoCfiVwxKWRlI0IdhQ1w5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXRsZUdURUd3TE5JQ0Yr
            MUdhbTNwZ0RsV1AyM3J4MUVqN0luOHczOWtBCllucldtUy93Y0xJUXJzMldkcjRp
            ZGpkOGRITk92SVJRVG5HTThoY2d6OXcKLS0tIHY0SUVOd2FmakpMQVVVOFNCa0lD
            Snd3NGdyM1FyQThwOVdURWJFaDFxY3MKQLKAkhpDMX/iJUwhTKQzf4Cg9g52TAqU
            3Fn9HyQ910NAjKrX8fFvcX2cpBbdL1LWoybpFzUOGVVhELI0A0RXBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZmRmdXJFU0NteXRUQTdm
            VVB1cWZMaFJzbTBiL2haS1ovelUrUWQzU1M0ClM4Wk1TRk5nV0FIdFBxelFUWFpk
            U1BYQWpDTmJKV3puLzZ2VmRMTVlXd0EKLS0tICtuNHR4aldTWVAwSlJyL0NpdXZh
            Mnk0bE1CTklwMXNEYlc4Q2g0clhXL0EK7FwzAjRgyAFXcQey4DB6Sjv0bHnXRgPy
            PWBZYet61lflpA8Yn2sxx4PD4fWjoDt/r0E6fmfF0Td4FLki2m6uvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T22:54:06Z"
    mac: ENC[AES256_GCM,data:yD0Gqr1b/7lsEyWfkRGIHTA/wQT1AlXUFHaII/2c5CxzgeS5oRcBgyVa1gl6+o8RXv7eenmnYKjwZvbdhi4G5JMNuzuUl+CViBq4ETc7shZTrCTsWGFvK6zWD6xW9zWhTJ61UPVHdSI77lGpPoKh/L9YdbIKuIxKEmhpLwmxQ9E=,iv:R84NNtirVGvL9eQS90dskPPRVkS8ASR3OwKhAQKwiTQ=,tag:78KlyW1zIoj84ZxiFWNexA==,type:str]
    version: 3.13.3
