apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:N1JylfIaujwIN7HGoap187DK4hoBw/EH+sgMlkUlsKJNsbLJ2mQ0ItCNY5NwqMDcNMm7EWvl8hn6OVbikqs5Fu6eAvE0F50QX+U89QJCsX+uL8M+TWK8rHa1g1ftbI4AZfTd01cFyVv+KJ1P06uOWhyCLCkGuXfcviM9Si22YmVOF/AjgkgYCzHLH122mZ7cI2ShfEVH9k7kcRdRk1IgXKgkGg6EIMJxS91TX8fAxvscWblkjDNupeUuyoEnjvznXqub3CoWHXXa/FK8KpzSng+9/iq5m0tvC1oljPFJyR2ivM1lgALvH47FcC1y09CpQkNoKzVDIL6GdlKi+M6oJ1+oRFTl/KQwEDuhyuOpxgXb2va6AdbigeB+QzwDPorq7oj91RUTyhSk8EwhJ719Uc+1wUOtnq9Tnj6EVLvoMpB+5iDZypSgH/vm/xNQ0f6tLeuwGyhmgreNKzwSMDo5bd5FKmzHKCsD9GgVx0K8BtuLYslLZadD2lOcMyMUDfqoStI10HfV/91w3VpBqQNIS3ZdwePyQmfU8aXQXVsHz9DVGk9+XCPr+sAAc8T5GY5dAX190V3qgpIlHsgeAijaAA4J3WU6e9e/pA7x3/XAIOscuP0Yi6HNAHrpBwRti8XuIMHQHTcHF1DJ3+/tteGam720HfWWkuvlKPASBcfzPcrNHLEFJv1j4Rd9mcVR6ptyvRJWK27Pa13XUbMPXcDg4sLupUQxAwn8vvZm/5yIsgA3wu0wXGhu5WDXLfLKgpKL5tClLAhRL9XPUt/NwD4dNFVHPlh1Ac4K+TyBVYbgmmKx6kyX4zGaAi285rlWOnq6,iv:MqS2d2RIRc8CWSoeJNqLm+ld0jubs+qByCT2IKh87gM=,tag:0SFGyFmWcvjDEpXUkWABcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVdMT2VQQm0rM0ZkTWNq
            d0dDbmRKY1M1WXl1a1VlVTlhSnA1d2F1SW13CjR1dUt2YXFUUWJKQ0xBZUxLM2ly
            NWp6d25IK1F5cXF4Y3BYSDBCaS9BNk0KLS0tIG56V0hRcW1FSWJnT21saDVZeS9Y
            M3FleXpZRW5hdlpPYUN1aFNId1BVY00Kw/L4TfJxwKohCnMK+4dLnTxhxgPYz6PU
            LbeWY3KNOLK/K1Fm+Dh/iPOvqRc6UQvRx83R5VkQN0c+aus6OvGErA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vkw3R0hJV3BuMVptYmNP
            QWt6amNHL3ROeDZoSFh2UXY5NXFLamVkaVVjCi9BZFR0NlRXMEE5YSs0TWRkNlpO
            cDNFVHpjV2srWElzalBSVjlJMFBqZFEKLS0tIDBjSEpkOFhNd2g2Z1dyWXZabGdX
            VkU3WnpUSDNmQTBoclVRdXFnZHVjNUkKlx02+ntMK66Q3A9MOIONuhf6pxICZiUr
            qc16Jruv4uacVHAzPeElRzOl1cWpJGmQxolRm20+RXNaSAfQPmD62w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dnhjZFEvbXRuTHVKRnJm
            TDZ1SzRJUmxlclI4Zlh3REo1RDd0U1pHeUNVCk1ucTRyYXpCc3dVMEswSjJSaVJJ
            VEpCc2krQkxYY0g2ZWQ4OUFJVTNlWGMKLS0tIGNWblV0SzgyS1FrdDdIelNYRi9O
            Z3VFZWlJZmtjT2NlbjYrY3dNQnBFVFEKRXKaGvCII9uk7WIR6YlEpuM+SeIVWKwW
            jPypV6eEGFQQpnvR/HrttU/ZEeFSg0rXLXdVad+Rdlb8KeBYX5GPqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:37:11Z"
    mac: ENC[AES256_GCM,data:1EFkUdZ/pIUARHELnUUQYh0899cL7Rd4Z49OVkyX0CQtgJSGe5FnOEla2M7BKF6mxh79ImH0SauOoCQDxtYY7So0eCZlbttJkyM0FjXEwY7SWQapUBX/IAZSYDbxh+UDtMrUaht5ioedl3DyfgG4YGfjE6Mx1gIOw9uNQzdkp3Y=,iv:Me1lpSV7wNgEl2YwPlwoAgDIm0I8eyCd7wsrNmDaayc=,tag:0AonauA+c4GTi8vq9BESYA==,type:str]
    version: 3.13.3
