apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:46L/r5c=,iv:dFjakEvu9dNrsZoTDnGtwWUFysk/+3Q+AZvGkYWeHlM=,tag:FuUu4TBCwVBqvgKA9+piwQ==,type:str]
    admin-password: ENC[AES256_GCM,data:+cYXxU7fQ2OE6PqB8H76SZkeALxY7zwbVfn2CBeDnVh/h+fw2wfyeZZdvg==,iv:pKNLcU1wjCMnDX1tgvQ7R2M7NT3hJkCqtDdKUXcHMuE=,tag:bwprwPj10wLJ15CeZEVTtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bDNVR2tJbG5uNzN1WXdF
            Rk5qK3RFUDFmb3l1WGJsNHVPbXVZUktiN0VjCk5hYWVrVjluTWlwb243Uy9IcW5P
            dFdXRng0LzRTL1A0QXhSTUZDOThwWEkKLS0tIHZUUEswZHd0RWVpZkhjMWl1MXhQ
            TU5kYVp4L0FITTdhdmJvTENtSlhRa28KlSB9QOKTtcVtBfZviyVKQ18lLT83E5Di
            a7XOpOFuZTK1eJwDFxXQy4QgB83BBd9LHEgiN8k0HJ+gvXQjk/dtzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY21JSU95Z1FQWXdLT0pJ
            NU1kOFFwNFlVQW9ycS8wNWtWWVphSFlHaGdVCnlNSzNyeHphSDg3eFc4Y1RxZ3hS
            S0NHdFlibG1DT0lzZkVnRTlZZyt5YVEKLS0tIEpITjdyRGlqSjdHNHpTUWsyU2s3
            Y3ErdmIrK3JzU0RXQnBPRzgyTU11dkkK3Dby6cwyPXED69huKQ9ngtPg18Priq65
            ujBf/ancHX/L9gW2xgV92u6LqENUjN31aA3dKYhSz3Z059txzjXGIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2hPZ04yNlZCZTNFelp2
            MmNYVkR2aGo2Q1BpOGF2TVlqR1IzWUN6WlZ3CjJGMHdCVll1QmhRdi9hTUJ4SGVS
            VnhGOWcwcTVuRXd6dk5MUE1STmhoVHcKLS0tIFZkc3h0eDZ4TlMxOTdKSTR0YUZT
            UzNuMUFtNXF6UFJUNzdPNmdXVWpKT0kKLQsDshcdxozgdghgW5ii45zBirSqezYj
            B12hKrDtvj4BSBKIXLI5eCpmHc2hIvYOJ8evEnDKA0lJVNTZtF7IIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:kYjJWiwu//TtGSP693aBwp7Dme7X0BslKBbSYsU7PPux84aNoNBcxXLO+it0A+Bi80m7gYpqqyix/kdOXqcTEpS1B29UqokJMJnZyHlAiwpsSJaUa9b0jZBpFAHWalJiAZQzOv9B1laM4I5a490DzEMoSBzpENT3kLvjqVNTXsM=,iv:6EkNdQk1mvjH4CMerTHisye0j0ASQGcixvvVdCfQEXA=,tag:zYMCZJut3VVFapjgNI4fHg==,type:str]
    version: 3.13.3
