apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:e2PMtmQ=,iv:dFjakEvu9dNrsZoTDnGtwWUFysk/+3Q+AZvGkYWeHlM=,tag:svSPbuTj2J5zTg77zAh75A==,type:str]
    admin-password: ENC[AES256_GCM,data:BbWA9IPMPIslm9NyDYU/R41VNOybht3X9Jl97cCd/zbuzIH9ap/V2eN3bw==,iv:pKNLcU1wjCMnDX1tgvQ7R2M7NT3hJkCqtDdKUXcHMuE=,tag:J6fRk9PRpm3qOg8xgytUOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMG9HSWs4bDB4SmNjTjlF
            NHNJNjVjMERDejNJc3A2V1E5TVYzOC9VaHlZCkgwYUtTeTRWeWZyb2duSnVSLzls
            RERUTVRSbnZtRHBBWC9paFB1UGNHTGcKLS0tIFUvUnNkeUhFUDArc21URi9ncStw
            T3B5ZmVBOGlISW5mS2ZEc040WlRPaVEKlXHghUHwekpYlfIB3xvsBw4V9I6Tbdkq
            HWnrGdWwoA594IFdAHVepcnkfEEmtONbGoiKwTzCeIJDC9BVVP35Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU1c3YXNIaSsvcTNEYmFt
            UWNYbFVqckJtZ2VJT00rcUVEUWdzd3BDM0ZBCkJScDQxb2pUY1NSaENoMXQ1UnpT
            dnMyVGRQYXhjWFpLT0c2UmhHSnBVeFUKLS0tIHh6RlJjVnM2R3RnNlpNZUNLWGxs
            OHZSSGtLZExwVmhUaUo2Zm42TFY2clEK7FuWkB0npgfbg7TyV4X4gCBLvfsE6QhA
            424mD4JoqDIwpV78oTuCvDBSDKfg+c64vwg0U6KgT9vCJMtZnJLhrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VXY3U09xeTZENDJDbWMz
            VlJ1ci9FSTR4MnYwZC9VS2JBK3Y1MXFYQkMwCmVkaS8wY0RlWm1jQ0loRWZBdVVv
            WXMwZVNJdExhY1ZqSUsxZ1BCZ25hU28KLS0tIFFKanNIWHVka21vZzVKTVBDaEN0
            ME5xYloxWGI5Wms0VnhMWFBSSWQ1N2MKxWzdvWbwUNzlyzBcX30gkrBFBeFw83wr
            l+FPjxCBTPxhz2lpAhNlSSiO1QAS/LWX3cB9glQFgeZgyNesY8t6Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:37:11Z"
    mac: ENC[AES256_GCM,data:bZrV9DaGS7Wg6+juGFavr7NddL0YEOB/CsGxosheQmkx38HLZSqWw0MaRIIJDDmrbGG/0judbtaxuk2VLxzRjcyFpF4ilgl6Y4WBOHQvw7BUaRYX7SIsu9O9u+V6P3mL1got+jjgOWGbevSzIwcP6y5nOnr1Ug8AgYw2TNm8CmA=,iv:xuciZlu7A2ObLM+ZopvXYUQkOApqm5V/pS4LQMkJcng=,tag:AntH6Us/yK0U7jG8s5IMbQ==,type:str]
    version: 3.13.3
