apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observability
resources:
- monitoring.yaml
- loki.yaml
- tempo.yaml
- alloy.yaml
- network.yaml
- node-exporter.yaml
- independent-monitor.yaml
- build-vm.yaml
- alertmanager.secret.sops.yaml
- grafana.secret.sops.yaml
- tunnel.yaml
- tunnel.secret.sops.yaml
configMapGenerator:
- name: alloy-config
  namespace: observability
  files:
  - config.alloy=alloy.alloy
generatorOptions:
  disableNameSuffixHash: true
