apiVersion: v1
kind: Secret
metadata:
    name: grafana-tunnel
    namespace: observability
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:K3vamJqCqb9YCEH1z2k/DqW4imER/LFlgz13oIt7eNDrXg332800dK7KbSA+xIk7DDGF1jG3VMId0gOLZvcNKKxoDdNyNooP82JAi6vcC5mZBP1tlwb91iQOqE6DBlsFb8L5FMRAMziuc2pCoEmYINzFg1pgJ1M6UZKYk3VeBIhdB/ULgv3SA5Wk+VUhzrHIYrYcxB7/lLgNFrHKVeYr16Tzkr74M3XEah3aq7Nj+MrafB4XgvKHPXJAGB2MT0Lc9N6duq+2qaFMppQGeB5C2np4bVU0ggebekQza3YxdwQUV3zB+UZu211FANNTwR8f,iv:hHsvirB7Fv2mZpAMx9jqqweVwF9+MlZ/4CTc3UDiYSY=,tag:+Fh547pCUP/uOKfk4x+TcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdWRsWW1INkN2cG1saXpS
            SUdqT1VKQjhCV1RlTER6aUZkODFTVSt0WGtFCmRQRHIwejM2Q2VpdnU0N09XeHpN
            N3JXeWhOS1Z6dTk0MFdTTmlSSUJrNVEKLS0tIHVub3dNc3Z2TmZqSXcrUzdVcDQ1
            azV0WnV2MnF0Sm1CenRBUmQvS010Q00KT02EbJMB6NdhveYuYcxnoN+pFgxhafhg
            d2CFY6NfPPTjstofOwgGiKKoKR0gT3PEA3laPUPin9Py693l+rCAug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXdydnBHK2t2bXpQTWVR
            WWZRbnBCTzliRWZzTkZLaVBxZTlRczBTekZvCm1ZU3V0QyttcHgzWi84WTlFdTZy
            Q3BVRm9rR3RsMzQ1RERwZWdxckc4dEkKLS0tIDdNajhLL2FuUmcvYVUvbGdQalRZ
            QTRSdW9tTFBGdUk0cFVTZm5pWS9JUm8KxX5AFyvBFigQcb6n7Y3Ec2cq/sqFv4DB
            NgniY+dS5h/0fhuueDgzonJUyStzi+00yCz9fXvhqKJz5izVEVb++Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdG96UjhPSkl2T0J4cGxk
            N3pjajJrZXBGeUk1VkI5UHdjbi8wVG1OYWhvCnJXRVBGVGp2Tkw1cDBzVTV0MktD
            MnNaMk1VQ1FtNy92bW5VUlhJd2RYaVEKLS0tIHJIRGlYU3JVM3J1YXp4QVVRSE9N
            ZGJ6SFZ1VkE1UlhscjVwbzladngxcEUKp/emMh43IEdBWSQWbA7NHiaI8RD+sH/l
            4zgeM479k6liodWwYOIMJrtPBafHsmmXjLr7DVdR2rKkk8vZzIkqPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:39:50Z"
    mac: ENC[AES256_GCM,data:3OW/GVYCLZBWSttqkACgxAdn+73TWAxLS63P7qfe60UDLBM4pVbXZOjko8KfHi5QdKeS0YpB5dd7LGCApdA03DFWwpbMViQudJHaWkU/1GpZ2kT0hL6I5oX3o4KcL7fbc2wHbLmBjiXSUahJeG9+ROecJf1mZ62ghuY5x5YsVgg=,iv:bdwabpmGa+ux/IrUNJWIaZwdns63ORjAOPU2x6/GYOE=,tag:taS2rNzclUSY7hMgOBuwrQ==,type:str]
    version: 3.13.3
