apiVersion: v1
kind: Secret
metadata:
    name: grafana-tunnel
    namespace: observability
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:TZ8/w98C50kEJa6lC3FTv52G5PF1p7ZPzBuvvPyPe1/gtU/wrHk+5R6y0oA2/93IwagfyM+LSNS6+kV+NXw3oJDhNWeLI4F1vtqfCiO4+Pll5qawNRELO+8eEK7QltpdbFA1ofz4qZO9zwcNt9FO2W05HAFYWgOKhFQN8WCFG1ma0tQ8/qrZA141+SKFzJmAEgetyc/eDN0tOjgzDRPoIC6yasDd8aI+kiUNvkkltax0H44YuITrcMAjpM5XI1/SmaY1U5F218j5Ezag4sC7lPvUY+2QWZ3M3k0ZV3BO3pu1O1dSciq16ti3Ct+QvuuC,iv:hHsvirB7Fv2mZpAMx9jqqweVwF9+MlZ/4CTc3UDiYSY=,tag:+WcZEOVOIQAJRI7EESx+Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VFl2RU1pOVpUVU5yK1BL
            a0tsNW52MU5IcCtncS9pajRuWkRaNUx3S0E0ClBMUXVaRDg2ZGh0bG9ISzQ0ZzJC
            bmMwR200Zy94eEJWMnJQMkMvQ0R6c00KLS0tIENXRWJBMlNKUE41QzE0MFYvQm5Q
            bmF3RDBmdTJNUG12UHNIY1NCNkhrZU0K+slZXs2e1b2UvpI7RY8KasP6A7NbNcwK
            Z+nhQd93UMHm5l0IgnknnMdyEs3nxTcPx/M8vuaXzq/XHvaBS6Szng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZEhINTQ2dkltUjhWclVN
            ZmlsUFMybTY1YXJ6RXdnK2tRY2xIeFBsdFFzCmdqWWxCVlVEa0pZY2toem90YVdQ
            L0RXcmdIRFd3WlRDejQ0NXZNS0JldDAKLS0tIHZmN2VtcXVzQnNOY2dRRU9LUys4
            bnpkbWpkTHNsemExRlpNK3NCZmtraU0K622fXk+JQYFRxwdcRoanfmv26xN3pWoA
            1yQQ11mDMJSIr5bfh4e/vyOTvvnZWzCacIW76G4a7gLMCdfgqfJS2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWY3ZEFmcWowdU9mK1Fz
            VkQ2NFJjVUY4d0xmL25Hb1dUTGVBMTN4eUJBCld4eHRHMXhCNEpsTFBBRFZ4SFp5
            K3BwZE8yRzhpVE96WWduWFUxa2EwU3MKLS0tIDR1RnpqRFBqNW8rV1M2dlEyc2JX
            cEpWZVBCV2xSYjYyNkVIL05Ub2U3L0EKzZWUhBlye1Omb93FU3bRe8CGAXJeedto
            ICvioQXZcKSEIaMLfF9Dktz8vhOgO0+R/T984bi5oAC4Pyd+8bej4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:y7d29giQNpDakog0pRC3zPOsMYSUIsnKbO5Ewq1M/p53l1COUGGrqdZ1IyXjvVJQNcZ7PXkku2UGqUNtWvuEI3S0h8e5yht+y7lnvhhYHfJoyOQJmQu8d57B1/gdgMopc5q5hMG5JkLR4pkaqyT73BOiyqnStLcyBxCn1vxNzig=,iv:mSdKNm9ASTshUgz4u0HV0ClODIy1SnqlZSjZArBo1Is=,tag:EtfopQ6c6dO88onl/8n4FQ==,type:str]
    version: 3.13.3
