apiVersion: v1
kind: Secret
metadata:
    name: attic-client
    namespace: ci-infra
type: Opaque
stringData:
    ATTIC_SERVER: ENC[AES256_GCM,data:g3wOJDU0A3n8t5CgK3YcM4UpdH8QiXAgIEm71ka/eNZPGt/kCzp+FgolJLng,iv:nColwVlkGpchbLwJyS4NM94qWCKrV1QjdGS/RfUl0HA=,tag:LqgEo8pbWAYl/hRzyxRitA==,type:str]
    ATTIC_CACHE: ENC[AES256_GCM,data:pkl/+RI=,iv:c29rvjKZx7TNpPy1TnarlrtasWRVgBJ/PRfsJIm5TgI=,tag:pWFg5oxOUjYZatBTa1sTvA==,type:str]
    ATTIC_TOKEN: ENC[AES256_GCM,data:JiWH2U2x9xDZMPH3L7JzEyVx4sZK3aJpoOXokD/jHxUN+A4wHsq0tqhDxJdPzEChti6UiHQqK3njsCo7/BK+nM/8lDnnxru4OEIi7HvWOR+Fuxcsf2ZYgEjfSeAcc2wW3aZ3Eb/XzPDeCBNLx1oEHQ/0GfL+o1DqA1hwhHDFdiWJElUmxrUf74e0TDSHs/o9Fy7yKuBPjbIn4zRLNU9Hq8VV79fjNzkikvpA29Sa1DADHW+91Wf7hUKbw3jKEtP6H+r6kfz1eJ2TJCi3dWvE8/XMJwm5nO6MauOrVCm3GybdVvb5byELQn7SC/WfkQQXpLkVjJNHD0pbMPdrKHWeuU69lAZ+15cqAW7x7NPMI6sqRLN32Bsq5EwI3M7vNGzbZTGgudNl1CWD0jAc4/hGR5wqNSzS8uuOPTQSFhFygZCv/DmemQDc6H1dXc2BHZ97lZYMmRmPzq3uDHRHv3y3Uu+2xuAaemSROYPx9iBQHHCG3rQJqyTleywMNLi4QS17rNoAziIJdMrFmaNVmkCmKDoefQRQyx5RalWv5kkJ9K7Gl/lExp0r9iFZkl1FLlY4K5tyKnt+I2GWD1j5Hz15coaG0TOl/nAGmshvQtISm5DTvvihfeT4KcoFtoO8zLws/lYcB60bnvYG0joKBgwvlzSIWZF3hiOgAb9FPz0IY1Yy3i5YBfKvvg5XIDpSzbpI9gMdH8Y6XOBQmM46d9pdSDQO9ktISjye3ho7lHGwmLJ7RPucEnPVBteq5lXAgNn7pYAI8uUqHyJa9YAVdbmy4KoXhqvbSJFE/mSdNhZeP+0EVussx7DQhxkiuOh+nkFsAuU2BcyFzUMAMjWP3sjbR3Z1nEgI/qFL6xIckJF/2NNrc7gVYFT8/cSk8wWsKtmmVzc9Mz7kKFX2whe7oXSLHkSQjQWQpUL9YnkOUw0f9VOp3d4jJ+rvg/sGfcRR5HlB35oDSlsNPN+m2twBxvIjTCIba2TWHIYaU3+OTism0rXE/stdOYeQHSdwc4N2CUyZuib9qpxOdiT/icRDgpIW3jHrwN3afkV6rjQ3X9o6Drf+vlNQzqbiPW3x9GQ4ovfkEGmlzWrbO/0xA342t8KHWiHbHybbceDLI89cKIIHYgs0oowDDzYCWCP47hRl8w8qZ/nJdsTIU/M=,iv:8vZz1WY3O6OGEtGDPbDxfM6HcRfno4SA1Oni9oZvWlk=,tag:N8Jo6S4cIf6fVVM3GgJ+bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QWpDVEt2UllBaU41Y1dw
            eHpJUHgzSWNja21ZcEVMTlRmOVFnNlgvWVNBCkJMVHd2QnFkNEppWHRNSVVHaE5p
            QXVtNm5DSjF6WnNIbG9peXQ0blBjMkEKLS0tIGJ1ei84ZHBJN1pyNWFZMlRJQ1Q0
            YmxPWElNaXdyeVZLN2dZeDZBUWNaTjAKGuXVYny6493r6AL+S7zYD3/V6DE2w+GN
            32a6WRLgX7n4tPLBtuyYEediZ1CTvm5senwyhTYF2/bbpFSAEbTFsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4LzNLaS8zU3hFdUR3dmEz
            WHhUN1FkSGhyc1FlNGhvZldNRHlXTWVKTkdJCmJiNStBV1lqUFF6YXJyN2lUbUhp
            NUdHeGJaRjlNYTZqOWp6SFRybXd4dFkKLS0tIDlQZzE5bjVkTVZUVzhHc3crNWd0
            MXhXeEtUZnd5N0pRV1VQTFBhQXBsSEEKbKQktDAYujxga77L3lch+3C36BB4I05N
            YMTRSgDS/5uQkyXG1rBDp51Q5UHPY7wOkAzpJTNZ9UCPw08r0DorSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTG1JVHJOR0F0TllsZG5Y
            WnNKVkIxZ1IrcGpjODlYdkZ1WjI1emVhVzFVCkZ0OUxyRWw2Y1RhVVQ2VGRRV3l3
            K1IzM0ErZ2dlaVkxa1FXbUdpQWNMUVUKLS0tIEgrNWU2T3ZYaWRKRlh5Q1JhNnNM
            QXJiVm1ObGlXa1FZSWcraG9peVI5Sm8KsSEQ21YEf51hNbjlnW2xhfo9NJkzL4sF
            8D2J5rB8DB7A6MwB/KXK7Nx2s9UTF0FIdF0bfkOGJeU/UdSxBhCuFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:a3tqi8kKa1TFz2mtoXc6S2/CxXBuRLFnGE/Dr7crGCm53aOnJuiJYiFGeZw4x+zaDyMjt7bDL1gYzT7Ogl6oflwlair3Ai3bLTzQZOsdHzLaQ5DGVeTvCfc+HtnY+NdjSHPXRVPAXWfCIrXdrMY+KE5EbftLk9z3v8aXRVmgaMI=,iv:LsumpiM/jMVV4TQJm3zJCIJY964h/Z+mJ+tqd8TjFxM=,tag:DlpxrsQvouOfoWJfaTqCdA==,type:str]
    version: 3.13.3
