apiVersion: v1
kind: Secret
metadata:
    name: attic-client
    namespace: ci-infra
type: Opaque
stringData:
    ATTIC_SERVER: ENC[AES256_GCM,data:zOhaHTlfA6qyB2oePljXYU8HLb8v0m2GOol1Xu+atXU0YyJ+8zr5OYzGnWEt,iv:nColwVlkGpchbLwJyS4NM94qWCKrV1QjdGS/RfUl0HA=,tag:98s4Uy9fnrwcCU3ARyB4bw==,type:str]
    ATTIC_CACHE: ENC[AES256_GCM,data:kWYYhJo=,iv:c29rvjKZx7TNpPy1TnarlrtasWRVgBJ/PRfsJIm5TgI=,tag:/Jk/OeEfiuPCaqjSHo1Atw==,type:str]
    ATTIC_TOKEN: ENC[AES256_GCM,data:1f0dSN2qxG+zyaDfP2r2zBzl6V/E79eOPYR9P7fp6pmecjBPGvG49jFVNjGrUc8LjqTy7aBIuOEws5nzIX3yIGRPboFfvCQ48vWfCUFJ/DQ082BQmzLOK3DZgQGMlnXTHGrXZFMiN9x5YUJm1J3rXJQmccl0hjbZHAd1H2Oz4GgR5ZJTtLM8AzS9HXGPe2ywsODATo03t/LcEN0J1i5L1wGK/JiuBuLEm7KN9gjroYv90/Fd/sLW+ZJSI2l39MVVbPrrdh/h7qcPizHyC8CFN5PWKGmNfy8TQehLUvYIRxO2VYv7kkrUtLBME1UVsECtvdfWXRX0GqU13pS16cE7v11sPa82FYFp4tr2V5U52xyidyiGP53fJjxs/MWdfAsrbxIPo7FXusHG1yribWgaX8e/3DjnuigY6e5js/tXZ09GFUuoZOPcv1Sl2v0jeNO2okqCZjY3WFeBjHTvkyEwFVrrcUDimCHC+CIW+c6v3ewZAdaqbemWqSt/cyUVlHLanPmstiZgrCd1oDIvNcesP/jgbhv9DRLxaPCF2xQ1Me7Jt3x2ulUsOhcyOiqu/upvzIqfdPVYKyN966O/58Ca/RhO98wRBjQ0k9tmP7CH7nHh9XckTr11+5hdbEtlLxwPW4HmjfEXW1MWcIRZd5NFfDygplTW2440prrF9SaWpERpkxisxKAtiNZpSH9j1PYUJjhHUknQzF12cOXqi8QHHSfQWh04uNT5oXonDZRVHvxpbN0anA2UpA0mz/eZi37Vgn1jcLdcpo5jMIUf2TTuP9tpSpD2OgRzmglTVhSgaMlWID5tYNdVP/elaeneu7jGmd9NEzxDgCsAOcwyu2FQ0c6EBomjKnu0iCH8HCAEvSekxY6SsXAfw1S/e3fOXcJpAnu862yxl8fLCi9OaJRyRxggeZDUgmV9hdV9RPTbSbc2kTNWVRWvG5gvO9ZyhJ+umWMFxJ5cTwCa9FKi+gMi2KqohTjX5TEInCSNnbgeN0OX1i9G8znZLjrWmhTSQMVQ703FxhMGZlcNHvvrV0NagTAO6jFFtlFHsk8aYtwJ5M11Yu7jC63umJNoQXd9RjSmZLgzj85Vf/BAa4eD6NY7/Vd5D1O9cj9M02wc/mCxRbo2M+LS0fAbMEWj8JKzSI8jzdbDaEvnYwc=,iv:8vZz1WY3O6OGEtGDPbDxfM6HcRfno4SA1Oni9oZvWlk=,tag:OwuZJzEX2PJT6ymmGQVThQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUWhDZExVeklMcWs4bVB5
            eDZJVlBwMHA5ZU5iUzNnRHRhaXBpTHRUWEJNCkQ3UWdZOVFVYi9ycjNjUFdGNDZT
            SGFRTkU0elAzRDIyRitnNklTQWtublEKLS0tIGFWdTlrNkZQRUNQck92RW1LUDR2
            WW9lbjZzb2VlWWxBTkgvaWFpbk8zOEkKj4pFAEsWl/ZGo4XfREpa/WXvE97u7wFO
            xqyHNwaRR8H4ksyIOioTZljPJUAYXgCgDbkuiSw1BcVUYb3ViBqWCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZE9vZGtleGo1V1BvRTJk
            dHRVUUhNU05ucGUvaXM2V2ljdktwYWxYWWdZClRGMGdqOWphZ240VFdQSjZRbmRj
            blB3N1F5bjIwNTQyOTVpSEtiZ3pvZTgKLS0tIGt0K3RhVzBSbFk0QzBQMXVnazNt
            RC9yczZFT25XWStseDNTbVlkdjhVSnMK6xOJxJ3IoXI80Y15iiGof1fhgoJANbdw
            NDAAXFkG9yUEoE07THt/JlxaKO6z0mESPs2YFD/dkdhrIHKFmJkBgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ekRCTWg1b20wdnk3Vm9X
            Znd1Ly8yR25KTVlnWGw5cFlFS2d0dTBacUhFCjNka09MYnFvS1FLb1VyWklFb1FI
            TXN2eW1QRmttc2liZzJPRi9CYjBKWmsKLS0tIE4wdUxaV2p3QUZwRTZsU0RibmhU
            TGduQXdVM2dtR0RudFI3cTJnNitkRkEKlEZjbYWWWHtscX0/T9+moiuvVdd4iSN7
            b8PS0F3ZnzRtq7SnGf/J+mj7ejj6/pq1Vv7t76dZNM3BFK5ALX9SZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:00:00Z"
    mac: ENC[AES256_GCM,data:0NzTLGAXPXftzxWVEZAV8P/5HVgk2TBh57WC/fBSmdSkKeGy69JAYH8ImtfwwsmsJ9MeIDbd4BLf/LjRdBC/Au0Y+dCFtmwhYTDxvjaAZSjbIMaH3ooL3QrXry9LSEyB4y9dFja11WYotDkXyZ0SfDwsQ0KHaajf8XvdtqmtY/M=,iv:WA7Ie3niHinc/xq+3OTHNiuVgz39aHxh0tcroSbOBeo=,tag:rR/GiGZwtWBdhljVzrXObA==,type:str]
    version: 3.13.3
