apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-infra
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KzBvPW+kGYUOD+Vb217ct5OR6Sa0kPXomqw=,iv:LC+EH6Cb7JmI7+PusJxVEaWuhtL71+ica28dqBmCbVQ=,tag:DXoLNNLJAtRwG0o0vbaPMQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MJQ63YelAM7KLnRAkTU1z+vaNhGH530fVUo9J7J3nNL0+og6QE1HOtIEIjuPITLUSmABpQtCLO8pi2ebDUWpyg==,iv:ZMLgTL+4YpP1WXvaDgLfcbt0febyJgxBQc/KcYgUqzg=,tag:01K7JfeI3TukbzR54v3mrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMmRpcUxORzhpTTVmQ3ha
            eUtoVUxDOGVjVWdCWTNVMVJLZUZaRUlLMXpJClAvSHNQTlRQZFc2RElXSEJDU1Vh
            WEFLZlRYeWdjUzJYamp6WTZKOFpXVGsKLS0tIFdZYmo4SmFFMEszdTBZMXZrSnJn
            R1M1bEdhRE1MM0EzSU41TTZidHZEQzQKOqHILfHblD20w2j5z1NG61TD5/MTjufw
            q07lLXwpB1+OpLEWGJtV6jqEleYpKUSvEtkll0bdbhQxByQoFJkCxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZFRiMjBxcE9XNnBMekhl
            dHVQc3AvTWhDekx2L3hqTk16Q2cwekNxTkRJCnZlR1p4QlcxY1BBUGVLb2FGRjJQ
            TFBwZEFJUjFPZWpSVmE3dXFzdjFRM0UKLS0tIHpKMC9HVGhxVGVZaDVzT1REa3RK
            RkJVZWQvOStTUDJIRUxOdzdTVkxoNGcK3ByhAc6P+jmCUjapDqCcBocQjLDncOt1
            LS8XxndX4vn9EoYQXbhizv5KmGuKVM3pfjCtPt4sBCQDWKP+5Pm7MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM2tpYXhTUFFmT1o1RUlR
            UE5BWWJaWThWU1FlL2J6QVdWTTV5L2FJWndvCmY2UVExZ2JNZWtDMHpNOEZ5ZVc3
            alFpRW5zbTlxTWwwZFpiaVdZcGhPbHMKLS0tIGRUZ2l6OU1kVnQ0eUgvWlVPZC91
            VS9EV29VNHh2TjNwdlAxeUNWaHZmOEEKi1aDmaWDaJ7a4O5SvwtGe/6Z2e01odnt
            s2J0Fm7Y0oTRmRCG+Jrzm+dy2hp99lkgzDTRPlNJ1NwpqHrtbYaySg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:Hxc6d0saq5Ln8QmOgpK7rTf+r7WjN5ObT3icQSdMAjLcQaqFXmPfN/iSXyE03GEbUdca9OpsVu6oWiH+wXmgHo+jj1top4SmrU74EcIIXyfU3L4cOVL2pdJNDkXAF38Tj4xBAyumv4SdOx9UdfNVGNt28raiSkzJUWNsF4sHSo0=,iv:/otmfnmIh+Gs3A/wS6xYjUaH3RJWFQut1HAZHAd3iV4=,tag:U1xh9V3eu0TFyFcWhvff+Q==,type:str]
    version: 3.13.3
