apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-infra
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fpfST71RiTr3aftN0CFU69QXH259bXI+nY4=,iv:LC+EH6Cb7JmI7+PusJxVEaWuhtL71+ica28dqBmCbVQ=,tag:YVH8RcK2oUQsCt2MSSr8Ew==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uRXOG8URCj1LO3g91+i89UiqL/NfjfRDwKnZRGWYPubfGru5+gTd6ykI4LsiHMWMoego7GELHj7mvLuFZ678IA==,iv:ZMLgTL+4YpP1WXvaDgLfcbt0febyJgxBQc/KcYgUqzg=,tag:IgUUqcQg+vARVZ99cVqJ0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q3B5STE0V2VlSFA4cjB1
            MVNzV3BOVzlpZHVHYXdmT1h2cngyYjNlUm04ClFWTFdkMGJjWE9sZ1hiL09WZVpw
            cjM4MUFNdGw4ZFBHZXovVEU1VkJSKzAKLS0tIDNtNmFiQVM1anQ5VWkrK1RQRjB4
            TWxTL3BUc3loV1pIYlBQaUcwOWY1S0kKn4vYeSQumRmIKR1tP5MKFDSqMJke+t6J
            L2vki4XUSwmMlpcmiGZ4y8619t9Vjdc+5iTT9YItWVpL0BzvoVKRDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZnV2K3kwR2lVSGUrVVg4
            bXBYd2dDV0lOTnR5T0pvZEJoN3JMaFRvMG1zClhmVUFlZGdwVkpRTzN3aGpDUzY0
            Ykk1aDJlZnMrL0srMFg1andhbjRuWXcKLS0tIDhQM2IyTTBQNTZUejVydndpakd3
            d1dUd1Nwc0xmS0VCYjhJak1NeXlaczAKFC3YuXUoHkHjjhXx+51XwkvuOJ9Pz7Uj
            0aeUKcYG7VUbLrlmlvl08K588Qau9YfJdcQs5apQFXCBpQwIDqaEbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVF5Y3Zjbi9RL2FyMFFP
            MUgyVlVyZzZYcmpOb3JubHRXWElSbTBSQzBRCkJLSm5PaEhrTGp2SUdJZENRcitR
            WldwZHp1cDNwUndwSDg3TVJJT1NXWm8KLS0tIElzYzd6cGhJNXVvcm5jaUlDdGM4
            SjZGSzNWQld3VTZpaFZtc0YxN1dkckkKCvhQohik7kkER3lf8AVYY71ciWdFr8XL
            QAHbb15JzcEO4OgplH/tX9xJi4BjCw5QV7gGKAFA6Uo4o6wpsjGUvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:ZvZV9iyjRgbW+zR/MXkrKsXFKuoOktj2UQ9NsHy+cNazRqBmmzJsM+94YDt5udarWIHR35JmOp62NMC4ASAyz+6pxO2ht+YWKIOPe0Oeap1EfxnBqdjdGkE0UcXdcvbOCGcw/2KlotKkuzSPSqQeowfrFqLHAKYP9caZiocHOlk=,iv:t99LMqofF2KA8mC3Owrb1cxvUxuMZCT0pweUquOCcZ8=,tag:mNSdaa38azRxYA7X3Qdkwg==,type:str]
    version: 3.13.3
