apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deploy
spec:
  values:
    githubConfigUrl: https://github.com/fredrir/infra
    githubConfigSecret: github-app
    runnerScaleSetName: deploy-amd64
    minRunners: 1
    maxRunners: 2
    controllerServiceAccount:
      name: arc-controller
      namespace: arc-system
    listenerTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-restriction.kubernetes.io/critical
                  operator: In
                  values:
                  - 'true'
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - name: listener
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
    template:
      metadata:
        annotations:
          infra.fredrir.com/values: deploy-values
      spec:
        serviceAccountName: ci-job
        automountServiceAccountToken: false
        runtimeClassName: gvisor
        nodeSelector:
          node-restriction.kubernetes.io/gvisor: 'true'
          kubernetes.io/arch: amd64
        priorityClassName: ci
        restartPolicy: Never
        activeDeadlineSeconds: 900
        terminationGracePeriodSeconds: 30
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
        containers:
        - name: runner
          image: ghcr.io/fredrir/infra-runner-deploy@sha256:147b39afa11db231c31ce87a5ad7819b47117609391827c402b13ca96ce23e26
          imagePullPolicy: IfNotPresent
          command:
          - /home/runner/run.sh
          env:
          - name: RUNNER_ALLOW_RUNASROOT
            value: '1'
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: '2'
              memory: 1Gi
              ephemeral-storage: 4Gi
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: node-restriction.kubernetes.io/kata
                  operator: DoesNotExist
