apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-infra
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:ofb8B2a6cg==,iv:Vt8BPP2GIMJbUGgA7PBAsVlT1v0AbgTnd62sqceLiR8=,tag:u5PGC2SI1xySMZu2U3S/Pg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:QRvJMB0yigE5,iv:nXKliH0jfEUymEXgsEIkE2Iak9ww64/C9WFlVPYHcT8=,tag:YDJy6h7DJ6pPmKY0mtJwag==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:FQrzJOJg3HseSVz1mUVMyJ+M5SlvinQs4ikV/5ofOtu2RcLX7DphgpEwSPz4mHk3rVlsbbG3jnDC3ZFpMEY4oalPh9YbH2/mxyfd8mqOcuAUfTqGji2kDOzqXSPdgUt53uGNWaIX6zXnzv88I8/47nRyM+BjIiZtSolo69LV1NyDhiQjGnAugnMiWk/rt2ZSGwwPzZ2QP8dvah5WTGCBObZkn2eVyLjPwh7SRl1MTyysJ/Y07WZHHi2j2BeYWj5s1PrHRx/zR20INp+I8cBu7qRw0wbvI8Pal8IfxRjRQKPi45u2tHIwN1nIAWzt3mI6f5yXamiCilf6LidhF+t47eWAQh0FQst8g6mVHC1N7UBaUAYRJjLvyXu17KL6uwFR8Ve+WYsQMHBTJmUmR/W5X7wPA67Uc7WmF/Bd2BGwONr1Eaz753OGsnxDwpszZxrdYlCaLqc1mzJ749kfGVkHQbE/DU8yAn6cGG5a6hdLEmJeTK5XXP3FobaFvstoWr6Mkq9cckVws4WlkvtfFXatE8INQIEriPlNte93cdG3Iyw6+ACBgHcQIt+fNMRElRDP2pgK14VNajB7zeFTY0eOggj70Il25A+3ZlLrKk2g0vw/Ec8fmkTZlLxfYRrh2WsWpLgiEVW9nEdhTsEEgtg1o3S7cjEPmuoCPglGCLeqvXVzM6C0FYd+4WRtdLCjoOkEL4WggGVQIZMzE1kBdV6f24ulB89mhUGMs7VQyjRT2g6ewYTIq+ONOm8fAmXFzUW5oNuBKbA4165orPDMwf5rde3r82sYKuuiO2PDWpKYmnDaWTfR01M1UZ5cjY9gECDkXjQ6KEa63b7msaWUn5cbLekBm3v4i/sRbahJAS34NG1CC1KfuiM7deCps+s0pyxtJf05cxwkooY60p/PVGZAkOlu9zucvX/a5Ff+CRWQwQ35XaIZDu+0TQTbVww0dI0j52OLSmlgxI1c1fn7IrojnaPo64gvRCmAaV+iFIClc3xGK1J9VQvRGLOTcTv7XNW+VpkwNDq08EFySVBACLOHRgW8B5d5wIt3sD0zm8kgKxQEn2ptXoHA6KLs6yVWFR2xbFa36OvczlfZZzWFPSWD3UTv5nQMKzjWenhgYTJNr7N9sMyw0zoiAQOWaQd7R4bI2xG9nq89l71et7SIxOA27n0ylWj+4QuPrMBvl8ul4eSIhV72iSA6st2k2/6IwpsbBp0bvdfCJVIMMKJ+dmnNXuU6S51aSuLI7GaSFjqBPa2/7PynOQyuxgpDCZrzyubRnUUxvcBCqXCB42ZJzdKwDwFtZIAAh027tj3B6JxInvHmYLUU5z+2XYlwfA/3koeCOgoGgvIhEc9bTHqL7EbWm4splTKc3tSZzFJ/Rb0/PB3rYo712tpMqYzvJGNUIZU5vRxzn0qVRl7pZJ21WTu4dxIgTgnDwE2RMEeTb3Hwnoa9mEDA3YQ8NsGB0iwi84De/dUy1HSEuT7CJvYQvpH5ZNfoEK1TtH7gmsax/HUrOTZRY4w07WUGgBSCY9Nbx5Bo54RHrFixw6o0OQSAIp6WVbVlnQ5oaH+z29tY4mVXtEXmtZK1+fa6hP/Klpan1oxlxNa/Gi1hSTVOGPLeqkRp+BjLb3vAQmX50Ci8yZMkcwaqNJ4zps3a7RZpx5NfWD3E2Db///Y9x6Rp/RB8fWrb+ub8cXFbAG5KjLLp3vj0NeVXZsb20iEEm/o898ZlmFNk+7+yoSvrd3vmb5mj89xyZAiQAcOKc+O4hi29PUgOw8SxG4gEZ3nGey3YNbElzkPS5qNRRuB98it9rUB8ZnGVD+f+eEAF5qpPZ7w9erHcNZp4MOHLxPEoP8LOxu2nkZRe3z/7P4J1RjGTL7zWe93ROtAU/Vjqq6RoNAL5IVGdJlqPm1Fd7KZxrNO7WYL1f6rzoxkMvbbE5yrzGtv2yh+HTe/p3xseKu2keWy6roptOY7NNMq00hFF8gbZpcM2d3fotTsDKFJvz4e0Sd54Dod3OpCVK91xACQz32D9gbUBIWypIJGCOf6baP0GLmguaB1YDWtslgTfhDNHatmmDnIlMfKf1Tpoq491dzkyzk3ZzcxmDTCNGxPiCibu6nW3KBMStspBitEkmgC8JdUxgGnBR09DyvOFrAuTQXKd/hZZo5GQ5crQDJ5ytqAASVTKhHQGKsXFk/eepEZ7Lvzg5gGfOezOaz51OlZE7OQ/GUyJYvV7Uy/Zg0cl1dBN6lRPMA==,iv:IzzFKY4xVCBk50S0nmOUfbsY7Eg/kT2iUIYNipCjsAc=,tag:7oIJj6tarAiFkTYin1EXQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYamJSUmNZWEk3SWZUeVlw
            ZUFXTE00bFFlQVI3T2MwQUxUTlBUVFBaRjJvCm1EZUN3TW1MbWxtVDFlUWppbXVK
            YjJpTzQvM0MxaXBDN2FXTW5xK0FrQkEKLS0tIHJERTdEZjB5WndlamZDVDE3MzZa
            Z2h6UVJ5SUJ1U2E1cEE1WFVMWFpPd2MKUhJOxqctVda1gSBUhRMsvG2+4jkMKjVa
            QN0/vVFIcZrj4DForfzCyqeIvZ0Skt2c0f2Zr4ZGhUTTvlVjadvbdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3Mwb2RUMjdqK1BNd1J1
            WkdDeDZWRkwvbHZHN3NNdVQrclZYUnhpUlRBCnV0Y1RwRWhYNlhTK2orNkxJdTBF
            RjZHcUNMTzBvQ1AxTEdyMnZjd1cvblkKLS0tIEtlWWh1cU5icXdkamc4VzVMeThQ
            YnNtRFNOWmFndXFxelhiYVVDMGEvUlkKri5WiLZa8ERChjTeQ+NGEBPUCjMQTC5r
            saMPQHWi+aOqO2vFGwzHZx4MN9+0FhAYHDIvBJlk1tKrpT7avgcWvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZnZCMzRKNkVjVHNQb3k0
            azNrbWY3UEloTTJiUWhkNEJ5UWVJM3ZwNmhRCjNTTGR4eExieURBeUJyWXZRTW5j
            dWIvOEdNUjFkemxaUkRnMForVFEzejQKLS0tIElhWTFMWkN0K0JVY0tIbVZGa2Qw
            SGpBZDZsWERHcnZmajU2MjRQY3RlYVUKdYVEbcN0jsmP0sHW7gdctCSUxNVTQzn7
            +oiU1hcEMan+R15BF34zcKxbV6A6w4owcVR7M4o0+QafC8G0t+td2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T22:34:10Z"
    mac: ENC[AES256_GCM,data:ohKVO3UtOhJcs3MC9GnWevwWlogFRGllTrOA+gnB47YptCD7OyIQKgEVl4p57gomIEuxelMfz9oQuibVC9+5O7r+ik72FobwlUDGDxk8EIwj4cCJN6r4rqHmSjnIFTNlwQE2krhy+6qOaCKi8DkHpzrAwChR6RP6cSQcxLHQ/PY=,iv:K015K4I1bEo/iuh8lfpmUIF/PhRQV8xhAlhlWP51Xko=,tag:fWIaRtV2SpMZeviaK/2ZmA==,type:str]
    version: 3.13.3
