apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-infra
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:bZRYwpMRng==,iv:Vt8BPP2GIMJbUGgA7PBAsVlT1v0AbgTnd62sqceLiR8=,tag:RvXF1jrfNVkD6bA2R2T1qg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:tKVAYgJDLjuX,iv:nXKliH0jfEUymEXgsEIkE2Iak9ww64/C9WFlVPYHcT8=,tag:LDPsuy5I/jBk22GMxaqgVA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:b6ex/yutZXsVk1U1yUc2cDTrASD+n20Ho44cBqCC2XqXnZM3gfZccoekv5JYIlYJHob2A7RXxvFnqvEv53G+pYXcl5kv7YRRq+6o1MwrXak2aHdF4kC11INYnWbDTalhVnZO3AkodjpYhC461owL/DxJQVWJvAwwBcTOHTiox4mIacGOXGMbAbQMGBhYgY86Dt3mpFz5+pGhvtSLJgDr5uxjh2ToInheCOCRcTAxmvVu+Va9o81DonH+cLLTO+jWTzD2G6NAhnu2SYAa78wOs3c05G2rN0J50Itbh3c0+Hs9pHai1BibQ/yReyb70HN1kO/UZBevPo/zAHMa4UxlAQOpa5a6PBx806aTbrknlzZlnPwyEu/5tgAhCT0n5VlgjxrCNf/bKmPiQZxKjYV/2g/OxC7Y3TcHh0hxbEPNyYbWmNUdyiUMrQpL4bSiGPzuDoRMTzM4tZp0BG+e5dsCZfmqQ6r+3bHASTzCfeqnBqNOBhEzBBDvHy6ermODvrYV+G4nbxn/j/uTwpSP2k6UYsPKXu6a5tB2ayxVMcAYxy2drdCCHd6jHTko562RMjkyiC78D5mCC/Ok8Bzhd+QNyPDqBC9X8iMbnHsZtZAwRW0TfVW/auRB3yMpia6LrDOm7eHDJJBwqxlHzxG1YL/aA/RbeVDNRlJBSjliz+Zz+OEGF6ZFmZAqff13CqVOH/YGAVKV8KAaPfNp0CHXE7ymBPYZrT1hRyvG6CKtEH9770JRZReRieEVhTziU3nJIYimu2jyPRH05TjE0X3z5kHrBxCheKAzki/lgOCkfmeG9NQmGOgvuxCrp+6RLLXODKfZdHQyE+EdCLylLllkkPmdVcPmD8FtG4TkFXTwoXQFMwwGt1xAPQG8o7THrFJuOTqUhS94qufzHqh8YAMqqS3WW+upWvwRJvv+Yep9O2f90fN0PW8MlK6A5jv6DpqziBH3Ux9NLAz9+H5BT41gZsAU2psYZ/mE3brkqXpzBnguDnxlvTmMXf/aFEaA8OjEs/S8xkO/gZRlMXOtTP7cI1xt2dur7tVGKlrRntWnbEZvtQ6YHn/DtzI1BJtxAM3cP9r6e/sc6J+zEyhHEkuKNgbWK5Grw8Ga7eW8hTnYq/iz5DljJLGfDHaNnu46fFMetBYx/wa3MklLBZPMjOhEJQNvPo9UdEVoxpFhLwc4kS0woyclJbnl2EPrpnliOwa8K/p+pMHBMCLG9+JX44N1oaYHLGbc7N6OO36uw8rapDG35NxaJTARMm8WtBXmCtnewANsopsAr86Bb7QqlN+n/fx2DWzFogWFsfna4vmptgKi0/ZzMFF3pUpO0SH1RZRJT/lVd1g8fPclnPvluhVN/mXcUkH7MpolraTOpIyiNYT3PkKvpRcHXNMgD2TRkHcD9AleVpM9M5/5OQq6LOUufZhYYQgS0ydY8pOz/THX+yIFyFgM2204RM5t/G5ZoDPdE+3tbmPTSLlxRjHPazJZAibaI/fvl4ZJy7H7sDxw87WrCOHwqLUIPlkGHfmjjdbTU6UaaW6hqoZbIulFy3JxnN3/Gp4MXYMg5d06e6cDjF1VbzojaH2ZVOhtviHgXgqtPs9b3Q87/8GJPXXu6g1TFauW6dgSZSdYoME9FSvvQEowWMDEIlduaVIuXRTA1m473yEm57ORoehGRJlax68BTZOvQSNvtYiNDrncAN9DF09Cq8HK6SORvsAKanln3giK073dWQ0YRAHw0gcwnQBMEEgF5iXVjuw/cMmCF0Z0Dj1N31mxs+RP9l+fwlPcbJJQFEmD7vcPb2YLJLNuKZyTSbK8nLhkEFgR5u2CNO2qd1gikO1jsn79Q7qGDFF1cdcK5BolAX7Tw+OdF3Nmp9iwy4e0uLCkR2DJ3q6CCHghNQPIxof1/e0S1l4ATBHcvOumO9Ey5sYOAX3Ba2AsP3R9vIb/oK+rRSWuUU7q5CCAIHLfXxGWzMYysAaKlR3mdZ85GepO/W+cZsT8GyO8fGCrh27IDutE1GGQ2uzGEcxQ2RXkLWd1/x8uTutz+IWRXvA/151cCQakd8FfdajTGG6ZR2rlS6FZomPJFLFEMPGhysGuRADc8TW9UXWz+KnnuOAzhYOWV90IEF/xAp5lH6jhRGmzWoPnp9qf1wHDcvTM8nC8Az0n5htpiPfoBEVztETu/D06ZJuYdRKCCXN1fNueDQ9s6gPCdkf7gAMNGHJli8gb4yuliXO4Qj6n72vUBTJexg==,iv:s46QzSEBrPwlYnbXVMUSBov+/5QJtah5Bf7tw3aVm7o=,tag:92HGby2IsqO2iwdJ1QWE0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjM2alkzbSs1b253ZUMv
            akZSN256eDVZUTcvYXBtSVNNSktVWkRwMldZCjZCaWxlR1VnOXNVWi9KcFlMVlJz
            R2dtYTlvRHBRb2J2Z3VOTW5OL0N0VlEKLS0tIGhxaU5PbU1aWFhpVGR5UUh5NGtG
            UjBPd0d6U3Z3Y2h0ZENlcG9QYzJ2bEkKLTySMtoN2amI+YQCYMxR9PsQ9ONXaTv/
            BDWbKcDseKagKZ3Io8qPZtMqFbWNTlX9+zhxHSDuuZeaegQ8hnE+8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZnlnRFV0VUhMaG1JdFNq
            WWFnQXlKMDZvMlI3NlJTTDVCdG5yMDZZSFhNCnRjdGJZUDZWWEV6WlBsQU8reXFy
            eHZGQUR4dmpxKzF4SnRseXBta2NSQlEKLS0tIDVmaURuTlBVTXhuaDd2Y0N0NEE2
            aWNVcGJZOEY0V3hmek9yakxBL29WS3MKV0fIAQ9d6+yY3IRBvgqQAqZrrOoFaWp/
            o2UFjvMixcZ4Qdx9CRs/z8xFBGgmPyZLlOUoDZ6G/lrLabVAO/8t7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ0FTTE1VWnRKaVcxTllh
            Y1VUNHVhUUNjR0tuL1pSYVJjc3RFTHBiMkZzCkI4elZlY3RKUFRKZitjUWlOVlZH
            b0JNZHdDOE5jbnRCZFAwUzNlY01WRkkKLS0tIGtodDdvMENMWi9ERGF5NG8vcjlN
            MmpkNXJWT1FTZFppcHFUOEtKc0JMUncKOSAAMnJGKfj1WWw2oHarpInZrDy5aWzY
            amUEFsdefd5t2Tt23jRwi+UCo/rfZlUJi37rKT1xvRaVidzxLvwSEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:32Z"
    mac: ENC[AES256_GCM,data:hBJdx2btecMZUSkUN9EoQKzoBr9rNTkhLJlbcgvI7mqY0Pxzdfs1ObXXUN8nmvwMfv0IWBkpuRE9mACwgVpV0dy7W0V8V0N/Q07VGvEtlpBNAbEkLAhmkiqZaUf4Q+eBiUSJ/oh6aEQa80Auxpm+zJDX3nG38s6Ic4v7T6+bM0g=,iv:mwpHo7r+ihsnNwJL2T0BZmE1Zv62spzH7spJyTuz9eU=,tag:oNDIghAL84J+M7YG4gSzeg==,type:str]
    version: 3.13.3
