apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-infra
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:ofb8B2a6cg==,iv:Vt8BPP2GIMJbUGgA7PBAsVlT1v0AbgTnd62sqceLiR8=,tag:u5PGC2SI1xySMZu2U3S/Pg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:QRvJMB0yigE5,iv:nXKliH0jfEUymEXgsEIkE2Iak9ww64/C9WFlVPYHcT8=,tag:YDJy6h7DJ6pPmKY0mtJwag==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:tXArv8T/Zre5lWB1vJWIjFYBrwSxLjCwaIRYqsrZWV1XNyRAFjlCs5ZMz4MrTUeM5lFz24DFuKvF1Qe/SDbQhJYsiPhZPSpZ9Ps0M9OtDl91fHSapIcj1bdtg5lscGasIGx+hGlEfUdCboBzlqpokgLYpwccM5VDa8IQUCmWjcfOrBiuUPKLTLKKvCGcUtzbd+/CWlZDcKkZUkI2i6ltCl6srBz6G63/c8UXPX8hsTYnFhhWQUeBgNMGwY2kvthOS/7qx0RiKJJTi5OLfh/yMSW8C6152jZ3LSBlRHo4J+d9+m3qXKW/kLrMG2Yr61lJVZwJ61feyJE61gaMkmHIM/KtkPwHU3OhU8C+RZMGuiRx+03eHRwH2LBKhFr843ucVXkai4cSvVEje+f1TMt2MSL0mZIova0iBULiir1OVqNV42UkH9N8ArZ+19FmWAZlb3PyMLAHpaknfTrBoaNSdA9pddDTr4nAvLuquDyOcT0eHPuEfppBlbfQWzRybGlVWI2i7W8UEZVyENe6JJ2PU+PfFEiJqsILbmQ4NtD0dHSH1oO402VGbInxHGTurkhKK8uT45iNPzVwMG9MrJNiBCfW/nhxlvgZpA2Sm2BwLxnV/upg3tXzWFsKiGPubUMw8yoKsWjpnMYvQEJT79x3yJIfn2xyCwMy9UK9dcX2ehsDthQVDGiLbv3j8jPp5OV3s4rdRTHQNzAOwanaAjwN4Xx0fFLm/bexL4JsEk/RwCbtqtMDtUtEd1qloD+J/FUsClFwLs0Ikcg4cZESXi8dFn8v9WqXKxIsxlFaDGw3/uTYiSjWsjHE1iIuwI3tStLBjkTSJc8cjlfLU5GAB+rkukqGEfGDVrpd/foeGVWQVwJgKHHyTmYNQJ9xuF8i+vzNaK0QT2bT+qoxVGkVRNLLunx4yoRJp0Y/VQ1aItMymHrWhdANHCtMphwmKlsimeziGViQ7WyGP/YzoHAZ/V8iM6HTuigxqFmIMt4HRjQPKqcnFO/fEchgCXysEKYuwnHkfsHqHW/PB360y7eFEcn7NRrYQVrlkkhSBJuxX3Dz9jorKyQWwslaNkf+RgPDw+Wftedk6lcn6MD7RVV6BvG/GJVy5m0R7uC351g3PgKwgfZPP4dGnHURuQGnDd+xHfrLxrue41c41ilNYDUDQ9VmG6ODFnNdfOH/XkbGxSUFC8U0UcRxI6U222P5QuHRyJ55J8YcphOBfUg1nxjqpUU6xdz7kDPBzqTrbqTHbuV17YQ2r8VHvSh5kWjJYURtTUfOWsOWuiv0ffJ9XMafy7HodrML83YiOH1zou4Wd26wIF4Tu3ShTUrBxDIEt/wF0Hqqv0Hxu1Bjp4RwiHiWP7DHcmPONYV1TzifPF3H3LbNKLEiIb4kmeb8pN6Y3JGV1On5KiYCOJtGGj2Lu78jOQOrRtf+cdj66tSVxduSOS0D/nYbBqR+bltOn5vgiCac55u0YrEi0TsUQEU9sZP64S+3UoKks46iva3LElugkqT8g9Jl5gcRMl6BuNiKhGGXys90FpHlz+yPl24KUqF4T3GHKFst6BS0TFnU5TkGDwT89IBE+oQFYgBz8GClgrNm94SJe45zP8Yt0CuyTXGmEO2htoI3O3AnWmeju2Hw4pZdplAq/eNHWpWlM0M+vhUs+Zdun1iD2+nvkntMXkAl3MnAuczLmzri0je5uNDR/941l1fc3mr4Bz0+xeLMLhH33ZQoMZCNb7ivB7fSWAGkPMLXD2bgKBAizW0M2iNAw4PhyyKi5qqV5lUhFDb7NIWmgXTfbKcKcn2X4GvxmhRUKPcoUiLP6iVhdUVJ/5P9IHeoWJ8O1oSbWhV99wVNPbeiI6+yzfJy/qOrufOYgYcA6jCno/xN/NZ81CRPY+0noT2ePqzIeAX87Sm6yA+IzW4gNFij0+Q8yRQyYfW/8QX1WfcH0OPFsDCPwnv5ARcaTXy8DL5EBXJyLUOW1/8edPMMRiU1l5nMM9zx+EhBOSeWUoUk/H0cOj1hgijN9yDk0o3x1aNWU5VNPmB3QtvArZv4XNlB8UYAQ2QoD7tkgOuP7bkr/90vNkQERP+Tjm9Y3kopY7KGVpR6DWm+tqyJWjDxw7xTPVxKMsuw0WrieMpL3qo8SFCJZOwuXpZrS7PEfD5Atpxz/o+vgobwuW0SpvzIfSJBDO766+mv/PWoSKlfXRpiRhoaqm4fBt9IdzpYskXS6ZXXqiDSZsskJ98Jto4fRA==,iv:s46QzSEBrPwlYnbXVMUSBov+/5QJtah5Bf7tw3aVm7o=,tag:bRVLiECjO0eBNvFUOyLE4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYamJSUmNZWEk3SWZUeVlw
            ZUFXTE00bFFlQVI3T2MwQUxUTlBUVFBaRjJvCm1EZUN3TW1MbWxtVDFlUWppbXVK
            YjJpTzQvM0MxaXBDN2FXTW5xK0FrQkEKLS0tIHJERTdEZjB5WndlamZDVDE3MzZa
            Z2h6UVJ5SUJ1U2E1cEE1WFVMWFpPd2MKUhJOxqctVda1gSBUhRMsvG2+4jkMKjVa
            QN0/vVFIcZrj4DForfzCyqeIvZ0Skt2c0f2Zr4ZGhUTTvlVjadvbdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3Mwb2RUMjdqK1BNd1J1
            WkdDeDZWRkwvbHZHN3NNdVQrclZYUnhpUlRBCnV0Y1RwRWhYNlhTK2orNkxJdTBF
            RjZHcUNMTzBvQ1AxTEdyMnZjd1cvblkKLS0tIEtlWWh1cU5icXdkamc4VzVMeThQ
            YnNtRFNOWmFndXFxelhiYVVDMGEvUlkKri5WiLZa8ERChjTeQ+NGEBPUCjMQTC5r
            saMPQHWi+aOqO2vFGwzHZx4MN9+0FhAYHDIvBJlk1tKrpT7avgcWvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZnZCMzRKNkVjVHNQb3k0
            azNrbWY3UEloTTJiUWhkNEJ5UWVJM3ZwNmhRCjNTTGR4eExieURBeUJyWXZRTW5j
            dWIvOEdNUjFkemxaUkRnMForVFEzejQKLS0tIElhWTFMWkN0K0JVY0tIbVZGa2Qw
            SGpBZDZsWERHcnZmajU2MjRQY3RlYVUKdYVEbcN0jsmP0sHW7gdctCSUxNVTQzn7
            +oiU1hcEMan+R15BF34zcKxbV6A6w4owcVR7M4o0+QafC8G0t+td2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:jmQtR5V72ynmuBPOi+dGBCgFnrAyAtM6BGXaO6uc+cITOM5vsyGHuQjkueuOqLs12JyoR74VtHoEYpchOT6slOgkOkbhoZnvXfyGxr/FmLEOQiHMr9VDBHRcI29OGW4D7sCaJaAwwDfsPyuVAnY2SMxv8aXS8DcrGW/RDL7ggmA=,iv:8zovq0+V8ZXKJIlGwSAa6iFJU/8jQ1DBZXynxrc2e8M=,tag:292MgZAfbkPhWkcvlofc/Q==,type:str]
    version: 3.13.3
