apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-infra
resources:
- ../ci-namespace
- deploy.yaml
- check.yaml
- network.yaml
- attic.secret.sops.yaml
- github-app.secret.sops.yaml
- buildkit-cache.secret.sops.yaml
components:
- ../buildkit-cache
patches:
- path: quota.yaml
- path: check-values.yaml
- path: deploy-values.yaml
configurations:
- values-references.yaml
configMapGenerator:
- name: check-values
  files:
  - check-values.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: 'true'
- name: deploy-values
  files:
  - deploy-values.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: 'true'
