apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-infra
resources:
- ../base
- nix.yaml
- network.yaml
- attic.secret.sops.yaml
- github-app.secret.sops.yaml
- buildkit-cache.secret.sops.yaml
components:
- ../buildkit-cache
patches:
- path: quota.yaml
- target:
    kind: HelmRelease
    name: buildkit
  patch: "apiVersion: helm.toolkit.fluxcd.io/v2\nkind: HelmRelease\nmetadata:\n  name:\
    \ buildkit\nspec:\n  values:\n    githubConfigUrl: https://github.com/fredrir/infra\n"
