apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1-identities
    namespace: object-store
type: Opaque
stringData:
    PROVISIONER_ACCESS_KEY_ID: ENC[AES256_GCM,data:JvEfeypo/pRGd0Htk2gTUvWIt3s=,iv:UdJrrneowC2g0ToZZ7eMRVnSeL3C/338oPRbgMUl1yA=,tag:R9ft6kPTDBZ1ej2fBvcDTg==,type:str]
    PROVISIONER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:angf5n8H5LG93+UQ1aec6FsjXVRoqFDWbffUyXmteR3cpNvUvNgeb7MWe+AycUW7ggYWZ3QCu1R2OZpLbRdn5w==,iv:kAeKixYhJD3Lsf5J4OEd2SkfB7risiDXf3KI2t6sLIA=,tag:45XbBxtUOFjYCgcm+gE7og==,type:str]
    TOOLCHAINS_UPLOAD_ACCESS_KEY_ID: ENC[AES256_GCM,data:f9fGCXtUMIgPvb2sFlsjyW4iWnw=,iv:2BwsieGbWeayrPKIw1UzbuwqgWHaoL94rvdYPjAtiGI=,tag:5BZX8QSDfvF6sg+V5JQ+BQ==,type:str]
    TOOLCHAINS_UPLOAD_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1KNCspHQS7lAIkQ9fBwdXFvGYu2neabNIBW/UewBoh1hhg2jz3knsEfGKyLsDQAo6Tbx7l4V9QSZBcp5NgZRUA==,iv:Z3rExiJeoLfvlOBXCWXwRndLwGaTVKjnc4w74uetaXk=,tag:vLjOYdtU905dzHeM04ZBCQ==,type:str]
    CI_NSQL_RO_ACCESS_KEY_ID: ENC[AES256_GCM,data:FT7zhQnPue/047TdKB9NfMRRY38=,iv:fkWObat928hGAyhjOp6DVLRUuqBDgxotKa2YX79Bhm4=,tag:tY3AGTvgXQGRwXkq2ds23Q==,type:str]
    CI_NSQL_RO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c2nR1mq0XIKT7nmU7s90kOo/oLf1u1lTleNn+S17WZou3TUqf70wtiNvcpAOTUetQnmAocmrdDTF0axS0BJG1g==,iv:wDFLb4cnQNQwE4Ipf0WVfeLjZzIXyv0esgQgqukLrB0=,tag:mr9EKButypOeflRJGlMzCQ==,type:str]
    CI_NSQL_RW_ACCESS_KEY_ID: ENC[AES256_GCM,data:NS+fy/PcsmZ90q7Wd93sFJUs/G4=,iv:93GYFv0Fm47lqeVTyCDC2p62bubJHvAn+cc1Bbi/zTg=,tag:wEjHQsc0L0DgUxKX4rb2YQ==,type:str]
    CI_NSQL_RW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x8NZUyuaNvWpLqk3BQ79lIPm/sEO9DjhT8aw8QEMK9yNKChh5ryLvOqCsIew/R302M7xE9fvYKVBbL+BZrfSJg==,iv:2Ggir3w4EE+glVULTXzVYykmn5UgOePQCPFp2uIWrsM=,tag:m+1DU0nNoWugUWujOtX5gg==,type:str]
    CI_NSQL_RELEASE_ACCESS_KEY_ID: ENC[AES256_GCM,data:vpCSlUzUQ+E6FrAUqxvhv+XtBEM=,iv:imtt7+bARAzTsqMRjxc7nSF+0ECf1cMAbUKGfvx+LbI=,tag:JsnlIyorsMvg29TQpLd+qA==,type:str]
    CI_NSQL_RELEASE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ywfosRc7ldHDfMuWsWGAtH287K40VfcW17QGZPbRucAUedT2MXsvWeGcTN3kTYU5IwUPyNG20Yv7TrIKDEzKBw==,iv:3sXUoyCPSX+eSjNpg/4BcO2/eJw+GF864NmY1tb5H6g=,tag:IZrX8hTwVQ/A7lbus9ckdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQmZKWWkvYndWME1TQ215
            dG5jelBUN0NlYmt6RXM3TnloM1Y3U1BoNEQwCnNoMmpYMXV1dVVEdlhqTVYzTVpV
            ekxtTitNNEdNYzJzc2VXVFlzL25NVm8KLS0tIE5JZjZjcUdFQXlQTWIxYUFiY1V6
            dXpkSWNCdWxPa3UvNTFHdE1DQUdiSjAKKKgJksq3WzvtOtiDk7BFzSzWOmyAI1MV
            mcPYk6I1MN9eWm+JVykBGeIsnkHSAUhFn09mjJ1IC9odvsH8ynJz6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cUhSalkrT2p3SU02WUxR
            c1VIYzVIWFlZTkdWaEFUc1kxa3IxdTU2K0EwCkh5Zk5PUC9HRWpmdG5ZMHN0bUha
            SmdyVXFyK2dXdmVqMDBaOUZCb1Zaek0KLS0tIDlZT3UxTUdiOWc5cmIzNnRyOGRN
            Um5OVjZmVTFEa05jSDNaci9mQUU4cXMKoezejF5XaGkXbztAQlK2Zd8zpdMiVE+n
            3bmuJvsrOFbdVHQ8SApyF9Ck9SZrvAdZSk/xid9WwCzZqjIeo/hKVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NEU5cHp2ajlWTXdvWXVr
            dFlXL0VGOUVxWGRDVnVFVGo5dVluL05HVHlRCmEyTW9LdlBvTXBUNENLTHplcDFC
            b0Y5VXUrWkoraHpXeGlobCt4NGV2dlUKLS0tIEJ3dmt3Vlc3UzYzSjNDMTBHTGx2
            RVg3WU1ZVEQxb3haNXozTWhOYW50UzAKFy+EARkbXfYR+NhS2cWr48cmX1cf4EfB
            8Vmm5TtwPJV/0XhXF5Y2cQunO3xdhMh/k9ySqZM3o2DpK/bq7x0pgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:55Z"
    mac: ENC[AES256_GCM,data:/D9iWVjKMYX/TiJagXtpyCJM4dbH8TK508c/XQOHfpv0XTufgxAxgX0H3eDvPk8rAfOefikIw+sn6cmb+IGyZOq1hF8W5t/9xCvEuJpSnwDCkKUR2hOnRzgFaWucmX5K6QeD+n1Mu1X845Hl4K095Tgp+CUtM8Cpzm4tJn3GaZ4=,iv:r3IrRUsp59Q8Po/2we3agnHGNlneV2RXi6bQ69QAj44=,tag:/zjbqpsSZGN7YGFQv9xSKw==,type:str]
    version: 3.13.3
