apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1-identities
    namespace: object-store
type: Opaque
stringData:
    PROVISIONER_ACCESS_KEY_ID: ENC[AES256_GCM,data:jb9vIZBE1NksfJpCQdIpgOj3Kmc=,iv:UW5UllzQYybPB3LUqE36HR7iZygf+EgC458BFgsA5Co=,tag:2ZMrJFQxqqMSQVmk8qu1Nw==,type:str]
    PROVISIONER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ueJQ8j0MNpEMVOPv2B4r4l05PvbgDDVrlXOS/YxZy7077s259ZPzO19OH3TRJJfEI5pKT7TyrRjRHp7SGEQJaA==,iv:dc0hwR5T7+varKD81UoQYQfzYR/HkQZIEeebXcN4hw8=,tag:9OVIHfnDaG1DR9Kl+XCqrw==,type:str]
    TOOLCHAINS_UPLOAD_ACCESS_KEY_ID: ENC[AES256_GCM,data:FxAJCucudoAXVgdbLiVouIDrXIo=,iv:rlc54j27Krl/rC1UYQvIWDtyr8dpiTbSI0SoaRVE5Ew=,tag:8ySOxb3ztiQoTkxSn/NpwQ==,type:str]
    TOOLCHAINS_UPLOAD_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0zf/EJqFSUNPI+/tlOr5HcSA5O5FnBywi8uHSaL1On9lb2fyusnSte+ZUr5WZVqEa579PSGx2QHXjsDc7QREfA==,iv:pRg2y4rZukLyrim0wUUqlFji0Ax4UURYxp5OTMBAlBE=,tag:Ut/Rkit4seFG8VjqK5nJ5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b2djTGNSV0ttMmhrUDdK
            NDBIYnd4cFpqWjBxdllKOWM4d3p0N01ZN0hnClp2UzNWTjJSYTMxTnZUck5yNWVH
            WUZSQ0hUUldvQmNObUpwNkRYTU5ONk0KLS0tIFBIR25Cak5QWEc2bVNLWXI2Z0Fx
            V3VXUEZ6T3NqekJhdkxGNXREd0J1YU0K8xq+jILyPt/if42MnDEAv8LRgPdjj/3h
            KEFp+HZv7N1R64ZfwUsWfniGrxVSMGzGHoyRi/zELTRfRLYJ23vVQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVGRUc1I4aWlkRFFhelZT
            RysweFhSeXRvUld2NzhVRHQ5ZGZmb3FqWmdRCjkvZVVIRWNic1VLMUxZZ3hReXVV
            OXVWZG0rN3JmNnpBdm92NHVrcEJsdTgKLS0tIFMwc2JQUWZ6SGxPZUVJbGdwcHpj
            cG1YTXpIWFZaVmhmUlNhMG1aNmVNRzQKV7PiO2b+ICk5Bfj12SNXzeM16AphT00t
            fbUUrzawEO7Tt3NyI2pPKeFLYnVOo3cLSNIj9+rrsnT5KRO1IkukMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNWsyYk5odXBTYmxTMEtv
            TEptQ2tTYWh3NFFycFJKa3FNb0JGWVFXYnhBCnJoN3JENE1DaWdDODlVM3FFY2hx
            ZWw5aU9RWVFpaTlMUU82QlI2U1BubWMKLS0tIGxyRmxmK1dNelo5L2R6OEt0ZUZi
            by9qYkhxamQ3alJXWXp2a3VWQmFlNTQK/iANEVJo5FlH0Kuu9/R8Aiin613WrUMM
            g8q6/IToqeVEVhYbCVcQkmqVWGby1eNTaucH6BuqjaTdx7FlZ8e8oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T19:44:27Z"
    mac: ENC[AES256_GCM,data:v9u5EG8q/ysJv2506lH/+/Bv4nIQnc13opow14mvZweWrhMzjeadX7YU3LV3BGi4eWozdnGuCR9sGuJUG4AhK7PIL4aAgO9IZhN7jAjHbPoPqNhiEKrmvSHu7Bh+ojCJS/aF+ZAPv6/bU2wt1lvF9KSlOCByyoIDi1NIOGEL3VQ=,iv:Ym7Fh5rqDN+t6b4dbYCZxDDRybmZ16x1bmMBG+iORKo=,tag:kOqQ5jwjHHu/8z2q7xJawg==,type:str]
    version: 3.13.3
