apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1
    namespace: object-store
type: Opaque
stringData:
    WEED_JWT_SIGNING_KEY: ENC[AES256_GCM,data:gV+4JmvFKSsZWdCewHYeT/oiDx7KQtcXJn+rRm2j3JVGK5EQlcR3fyG4dKbFOa5/aSlUrewYryT7UWnofwu4yw==,iv:CIwr/L3Zfu56q/YMOZ+8iHkcjuFEJietudwm+PzP5Ho=,tag:9Ect5NUG2Ef+yyfuLdtWyA==,type:str]
    WEED_JWT_SIGNING_READ_KEY: ENC[AES256_GCM,data:qvN3MjBjORxAGXP+Sqg1+sqB8y5rCp0E8/BUOds/lTwiCE1E2G/VqiESUBG1CsAu3H0foxH0gT2XUt9EELQLlA==,iv:8TX1+8/MjlAavFjk/WANDj5h6XLu4109KfTcg0qUgPI=,tag:OXWKRtUcVZdopgP2CNnitQ==,type:str]
    WEED_JWT_FILER_SIGNING_KEY: ENC[AES256_GCM,data:EZ3pQCJLtZ3OPHpcuJu7acZZ2WO0dub0nMOO+zvd8rQyF3UnzxFOWhKlI1LlN6PJ+ZWgeA9zozFX4WHCiLOMFw==,iv:QSNARJnG5bthgiKuV1QcjLNIuqFIJRMzKQOjCKfnxoI=,tag:XX/ty71MB2nb1ieR7qHh3w==,type:str]
    WEED_S3_SSE_KEK: ENC[AES256_GCM,data:IQzhuB1wOPlAFRsmBCgQg8C59h6Tgc2jj+rKYl2CacNF38wymH7F6t+DxMRcO6IDqdaffBKpt5wnl30JC9wpqA==,iv:MU1O5ATNW3VOySI71SoZyhTEQPyAqbTJOrFPDjRrSOo=,tag:eWA2sLBGd67uBGDAmSWEpA==,type:str]
    WEED_S3_SSE_KEK_PASSPHRASE: ENC[AES256_GCM,data:7xY26MuJE4PpbR5V/K0O0uY0T3VloqjBcNViChIp2tDYpBTPMaJhUGmuMvZ671PPfDoRZMU3MaEZiDH6LCR7rQ==,iv:ZF5FdJCyUx3/p/fhR476Y43gGXd2nE+kEmB/kxNAcpQ=,tag:gINyhT+r05iDpdZT4lJ9lw==,type:str]
    WEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:M9ExcCPQNf30E2wpganKEtw4cloBolKDOdj/tpl8YQmvNVQ4TwTXGcwU7VHXXliA4WHmJAYu0pym3yN+oKmakQ==,iv:oG9LksHTeRpZ3xb183/nuka2CLQw4W4Ugy2mHZKRZ9k=,tag:YHhqGPpBQdlxNXe9utOa+w==,type:str]
    s3.key: ENC[AES256_GCM,data:k4VucwPJg2JXndvXiSFlYvX3vdrRUe7NGBuRwMkZ6L2CmVTR1Q1igc6+VOk56Ttn44RA7PTmN3FDgx+boArtBt1Usg9tI2/D2UYNyZo9SeF1cnBTWeZ+MRIO0ON2d+3VcBIDEOvuJ+Gbzg67Nz4VFJliRt7k85N/4g6+6+HqZr5GckoJ5DzhCvA/4Jcfh8H0H5hdr1OZ16SQPT1XNfCTGNtDgB8Q/7B+XXz6EiI8WkUmCthIxAT79L5LWOf+/yA4xtrQq9aofghWVu+s24PK0rd7Htcz90bmpyCAekuqOZsU5P75qe1wYcaVVX20vXARtw==,iv:NGf1QHXcRvEOshH/ZRXVNp+I4ANG9GXA+crrBdpxP3I=,tag:jw943I2WCKg3JaepjKA6Tg==,type:str]
    internal.key: ENC[AES256_GCM,data:faO/UZziQy/hWrd62tnT5sPSx96Gg6m7BwBrFG+MLw5ot7sDrrgKLOQToOcCwd6q4UUkNeqa2fEkaaC/WG8X2Y7tBeBzUYqZHc74RVUKsWrLtdGVcHehoSpEpZGA2W2FuSeq0MX7eoImC72rbyiDKyySOvyAIxfGUroXZxDT3mi2ruBN9kQzAMTunsysdG0mQf4Uy+bA8E/JIZd5I+SBJjolSqfeNuFdqFMFxkHtF6o2sjWlsr2PPGFLSKFkq6RLDzsGgxIxvfGn8YWxevIgTOXDnBdKc9ruwevKwMUB6Vtrlc96PO+qpFt0HFpI0zMTsg==,iv:CXMmxdu+cuMwsC9oEb9ho6ubes7w+Nyj/BGyWjWNkbI=,tag:otYobN0FHqVs5WF+liDkBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdHpNbG1GeWdUSHplVklj
            ZlpMRDNKc09MMTJ6U252dVRXdDZiY3BYaDNNCmVaam12UTNRTkhZY2NjNW9wQjhw
            TVNoelVLWnQraHRCYm1yYXkxUzFqR0EKLS0tIHZxWDRZdUFPT3NHNGVkL29kWFhC
            aDd6dE12WDVhdC9UbGpPdHR4WDN2UWcKYuhtUmdOpfQP5DPzjDsCx5DH2fOZahaa
            mXOvySptgnMmE1xlgn2XJSBNOf0VvgEhyo4u1LMdOWKt1QhWQssc4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNXA5RjFWT3RtV2VQQTc3
            NGRqOG1nOFhnam0wME9uVmtNRUc2KzZ3dHhFCnBLaFZvZiszRDJLK1NtaFhjWjJt
            SWp3VnNDTDdhLzdyeUg0SEd5TkZiNjgKLS0tIEdtZGd4d3cxVnp6TElXMXdac0Mx
            bE5KbFZsc01IQW9GK0QzSitTdEZZMjAKRjx6bGbT+K7MZRzytNvCo3p8BBI1yGUS
            Z3qow36pHXTpX3CD9cNfd9akHoGZrCZFj/Qbh8UmeFHPB7qC2UA8QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamw1YUsrZ2twOEgveXhC
            TXNUbm9sU3cyM3p4QksycnozanF0cjVNMUFFCndFNktFNlFVcis4cDRGVS85THdz
            Z3B5OVhMVEViekNZVVdTeEUxcHJYNTQKLS0tIFl4WkFiZllRMWw0VGhROGQ2U201
            SWZmbjMwZmJ4VC82TnBaanpPMFFNcDAKybRNcGoH92FxbjlvhgBuDLuLtp+VjQNx
            d4maotiDztU2/pxslTryxihVme3b1kT9VO66s+Ge12QyxFXQ5FqMrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T20:49:00Z"
    mac: ENC[AES256_GCM,data:QtTPCOaJopF5AfaVzH3/5O2LYseBjvlOupl74IQaxUnh3PVd1sZcsygXHZeSJc87QiR4MJgq6Fs89ci6psnXr5nVKIzyXCpNkzjPTCtlFW+GGJOvObzI03abEhFtHFHMViwqtP1ADDfSq6VpnmqKIzVmDRU+3Ax6vvxUSCuE7fI=,iv:oPrQZbrcp0toMrKIK6uVF0wTBb7KIKtVUrYL8P9nbO4=,tag:cmRvU3pqIviDzg/Ho40jjw==,type:str]
    version: 3.13.3
