apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-nl-identities
    namespace: object-store
type: Opaque
stringData:
    PROVISIONER_ACCESS_KEY_ID: ENC[AES256_GCM,data:mcWL4rMzZY3nzn/V2hKRJYYUFIo=,iv:+kTgsdy+0uuxYnpCey2njUBZE2NsVLkPTRlGrcahiYo=,tag:/mEehx7BBdj2rHXBuRmhuA==,type:str]
    PROVISIONER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6ijcLQKkxe8iyugWdnv92FZOoTAD0Fe9WPzFIVB4bcqhQG2JsYoJXe6rF2aSJ898EbvKlevzB0PmBLl1SOLw7A==,iv:+2vt8r8NDPsqfD8hPLYDHrVkNkrgCc5E/GrZffpiUNI=,tag:Qs4soC0GXTsDBAP3MBPYNg==,type:str]
    PARSER_DATASET_ACCESS_KEY_ID: ENC[AES256_GCM,data:237AXcRzzsyqG2klnF4iH8VRHHQ=,iv:DBnOplI03Lg2nGPJ1/X34qXYwJDyhTjqXmTFVuaE17k=,tag:8LJDfA71Hegug8IAS3xDPA==,type:str]
    PARSER_DATASET_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mDms0MySnvUsFEs/GHPQPR0GMHCW/F8kRtbFVnzc6KUaMUGSax+AGD7NF9G5Fi6YX3vIyeYfdjdIgZLbC7Y6kg==,iv:fK/PvmBJdSMVV019FN0DlhzDPwc4wcqyS/i9wungnss=,tag:1TDA0kXmDF4ZoT+K/n7kIQ==,type:str]
    PARSER_MIRROR_ACCESS_KEY_ID: ENC[AES256_GCM,data:KFM7tZi3ySgVEILboOWgpl0SBkQ=,iv:To4UBB1W6ZjnmssT5mOXadLtVCLLSGMy2XMdpJVFoYY=,tag:pl2kCNYpLUn8ykVqqYydEg==,type:str]
    PARSER_MIRROR_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nNgKgS/7UmiWAPy0cMp02jLV5/TCRliVFBupauPWNw2ohYHI8nA9fo/mqFCU8OhM8S23nVLn+oIpXOf964DoxA==,iv:zSDl5K6DXPznHYHhD/gMYhtt+7dqxbGUKOi5pg1O/wU=,tag:L0oPP/WctENAkEzgvR8hPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV3o0ZklvUlhjQmJ1WWlO
            YzVsRmNtQmZQL09tQzM1TVl1STFBR0F2N25vCnhOc3F3U0ZIeWlkbE9VOUhTTWlO
            TFBLdUdxMzlLL3lKNkRrOHcwSXcxUzgKLS0tIGgwb2VRUndxeWZuSks1V1BId1VM
            V3BobllKWlNNMDhjL2NKTGxUc294TFUKYkUjtx4QTu1Bwsz4H9dVxhfGah7+2pEQ
            +oVxjF8mG4anHbpKu2ElfNWeZQb87TUggN4ODederqST4i0LpvAZ1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRkZBUENPdjVSeDlzUG5X
            SWxuM3BhS0VDNHJmMlJIUVMya2JJeGxWWDBvCjg2VEJtMUVOZWd1TjN2YjRncTVC
            SmNkQzh3bjZ4d0E4eUVkNStpS20vdEkKLS0tIDk5Wjk0cmpBMVNHNS9adDJYWVBu
            cHc5M0xmeUp5ak9kWFVDODIzOVVaOFkKJ/ddGcK3lSmgmUXpXKLoA9vZm2Eo2LfC
            PnItMUT6mhY4fDoxmeKyNRPERXgdrdwYBqj9pCLXc2Z4XAZgWpVADQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ2YwOW55djR6dWVrV1hO
            NTF3bTNsc3o5RUtBUkxHUWRFb2lyenZxTncwCldZRkNvdEdYZmRDbnIzcXVmaVdD
            c3dzYzlMRVRtNzAxSENXWWNsNDRoNWsKLS0tIDB2V1NaNzhCeUp0NTVpUFZRUXFW
            dWFXNE9IZGFyV21nL3ZJSjlLbDVnclUK2GQtBSk0qse+GiVsMzankd0m3BhTze45
            hVOs7JF7dRODrifbhvUOfZwHVz6XS4GaIkHLWO8iTRtD3XtSpX07BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T20:34:52Z"
    mac: ENC[AES256_GCM,data:RsyBRtH9ef8haHIxbanaY1Rdzu8hAB/HWtg6fWgjIQmOw5eERmpyf5tAd0JlIK3TMAobmnEgTYJ0B0VUuZPyQxoxAXMKPr3DVpYlshHeF11yUCaA5gyVjN40tTYqune2uDWPBvqNTYwQkguR30QRACpzF6kn+RKd5ryjnifcUHw=,iv:SLF3UvuJizbQVhDqVnhhbIUiyi67dA6VSKT0wJmXyZc=,tag:BJ8KLiw0E1SbdSrrgUmeOQ==,type:str]
    version: 3.13.3
