apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-nl-identities
    namespace: object-store
type: Opaque
stringData:
    PROVISIONER_ACCESS_KEY_ID: ENC[AES256_GCM,data:244uoRAn+XI3wm8ZqDcHguJ/fB8=,iv:hOy72+wvVvikfiU6gqvUxlcY4528aXNDjJm96vQqJgU=,tag:qDGha/6uEjX0J6AWUOROEg==,type:str]
    PROVISIONER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uNkkcZQMalWpfrPI78fSs6wN1i/NjS5VD690aFtZPb2jkVmjeCK3nc8nt8UhmobnqglzPg5iUdYxRMYgHedA+g==,iv:IP0ZBrv33nalgi+KQw80C/ITHhr2+y2M7PC3+OsEf3U=,tag:EXTmV+k8oYn1X/yBRCbOsg==,type:str]
    PARSER_DATASET_ACCESS_KEY_ID: ENC[AES256_GCM,data:eZi+iQmbnygUGLmqmXQMWf3NteE=,iv:iKBuNAKU5E2zhbgIwvfjv/xY3TztlQjappq1e2CPww4=,tag:y3+qrYrOblnhZqZqmWLNpQ==,type:str]
    PARSER_DATASET_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CQ90kwffzff7tRvVqSpLZu6Hx8zEtbwCW0PPcwMqPG8JiUXj5rGqSkEXVeYNuKJVGMLvFFBrdlcF65n/D1CC2w==,iv:OHNzBa/3/K+bzQqWWzuYiF0r6xGUUo05hc82YZSeLSQ=,tag:M50IrVCLjGaYL1Lrmnn9Gg==,type:str]
    PARSER_BACKUP_ACCESS_KEY_ID: ENC[AES256_GCM,data:dgQw5Q4Re0fcbTKQaVHAfQUwYZE=,iv:5KkdadmawMt+KvcT1NA++MldQmYToANQcVsuPlW22ew=,tag:oFiN7TulYbjd8acfdZwPzA==,type:str]
    PARSER_BACKUP_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+GP+qJqjowqkI4pnhXeclJypUiGPI918+zBI7VUbpWaETqdNuBMPK0n8zIJ4euIv5hhVDGjFQ+WQa3HXRxr/5w==,iv:y3HhnHie5ycTJ8p8ohsyhyzQz5tHOraIopPmR3hBjCg=,tag:pK+OPdoVE7Xd/M+0TYrzrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOGNoOHFYV3VBeFRMbHhm
            THhCeDVHYS9ZNitETGEzRUo4enppY003bHhRCmgvZHRpUjg2YXJrR25pd0MrYzFa
            bEcralVGMElpdDluYWwxT0Rnby9LZWsKLS0tIDY1Yk9HWGl4VU9EZGh0My9vOUtX
            NE1NSHAvL0gxK2ZxMXI3VDlnOXRQTlUKdgqYz37mW8jZG0L781irg/kd1/hVzIl3
            ZmmbOOepyqLLRulRrlBbWv3EBpelRbRgzBt+FYguQ9hpTGoF93WITA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcm4vbkJkYlh6OURFQVMv
            ai9xcXpwdzUzUkh4SnB6YlE4SzNCV0hCd0JZClhkVXVhcFhOaDFhRnpGbmppQTdG
            YmloTThveGZVUHUvOHVUa0QxaEFhd0EKLS0tIGNRbmNKQjZWQnlpWHJ4Y2kwMlpt
            VVZHbytyR2hKMnBTNG14ZEFVTnV4WUUK47ZSwX6HAD0u3+0HhEsbaXc9y2V/Ubuc
            aWJAQBQQGPkQyZc8jqxj96o3rYwsN01rvy28v4hrn0EBW2LKu4osuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UXp1N1Q0bnJUOTZ5TXdX
            MEhMdmc1UUZLR2t3Z3RCZWxtRklsZmZYRlU0CmNsNnhUMVJ4V3p3YjBnbzE2MXNw
            cTRtcTNYbmJpY2cyUE5FMFRtdnFOc2cKLS0tIGd6aWM5aFptb0Z1ang0ZFJzWGpB
            Y1FSVzNHNmEvY1lNQU9jZkwxZFJPSXMK0v4YYt5EnCH75W5tS1Gt6k9lwoFN+aRc
            KFiAGYhUHb+K0SOws4isnZhVqexql0y8Z2YDaKZZow9YeAA7as4YEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:07:58Z"
    mac: ENC[AES256_GCM,data:uNyLqk3zQ2bXhMfWpTzgrJDaz/yMgqX4ap7ipg0cHpdsldcphMGxC+Pj5DcmB960asWlq/Wiqt2Tp+CEROXGNm0HpyUpHbgRFlIRJ6LjTKleieUWDh3ZQWewEpcDu0Bi5agJRuh+n8bWtFWpR30dujsAlRhKlQfuu5y2LyvjT/w=,iv:nTc1EmgQ3mVsEnvZic9+f3X3h+GqDAKNUe/4exYjvyg=,tag:fobnXDIqTO3BpGQiNjCYJQ==,type:str]
    version: 3.13.3
