apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-nl
    namespace: object-store
type: Opaque
stringData:
    WEED_JWT_SIGNING_KEY: ENC[AES256_GCM,data:zb+8L7QEO8TkPfkRj9cCK1y0FQvO+CASJe+Wp0o0WXLP52sUGubgEdheH/htWyT/NoeKJULlEbjnw70VUSD3nQ==,iv:U8Z1kaTU+bq9uPJ45nb9+ga9gehaxnJj5XCb8cw18iw=,tag:5HpaA4tI/zjtEIQkUCaT5A==,type:str]
    WEED_JWT_SIGNING_READ_KEY: ENC[AES256_GCM,data:eJYkQ5Ps5JnYaDFXKjOTioLJxRDGnIrnb7YU5dYgELuApy+WNuMA/EYJJlMHXP2/cPnNwpvPb7sNpOt4dShDwQ==,iv:IKQo4OFQg0ognG/PWQcNs4aOCjCbSYyA9MZy5fR6Y5s=,tag:f0E22CTabU/fbaC2cd2x1A==,type:str]
    WEED_JWT_FILER_SIGNING_KEY: ENC[AES256_GCM,data:A2cJ7R3yJL0wYm4ARIeq1SBt+vQFE0TYuIPIoH+weMjlcoZnIN1Ai27OWZ5Dygb+ECyj+z6g0grXhXfsVjVyBA==,iv:yiuHJTjvbV4xFi0dFnq1FJQxQc+MxBM4gt4jw2tjxdQ=,tag:iXyKbTFkahZULqF8eGMADw==,type:str]
    WEED_S3_SSE_KEK: ENC[AES256_GCM,data:e568PzLA1/V88xnyPIepJ0v9z1QyjDQeOvyzNKaR2LwA1TlZJw5XRi01c+7oSwx9e/kodWLRIHJuNk1oMc0EPA==,iv:7lNQd/m7Hx9GrB5Jpo1JMy8b09JhGzUV7izMx1HUXi4=,tag:QFY2inMlgyRJf8k/EFxzSg==,type:str]
    WEED_S3_SSE_KEK_PASSPHRASE: ENC[AES256_GCM,data:Y+MXvsUhzoYWJi9nQvujD9jlFU/O+whrvoHdnmGPlzuLseQ7rJQWfySlQX0KPRhOZG/q6JN/T+hhTduJGA2GQw==,iv:s0cUUJ2/bn1H3yuX0bO73ORIyxu6e/vCpEgWPfDtBJw=,tag:N1GyLFzCxMy/DDt13P6Dzg==,type:str]
    s3.key: ENC[AES256_GCM,data:YhX247ODFM+/vXcXrSGo0xb43/Jqmu5MmpMwZCp2WcefzDExkvFowSlZsyNp7WtyuNF4gIzVYOZVDNjJMhipbLUU0DjvsKdUCUfrK9DEhOamDZh7OSqcMYn76JdBFa/rXo86oB5Cez7zrwhX2x4lUCGIZRdjDupVwHvun/V8wbWkU3LdQ70YPPQXpn7zV+Z7T9jBge+BXmB3u672yOphvP5gMETe5qyKKXLk00hrcn5vLs4nD1bTDHHmpM1QPpQJiqiAIB8QV9WN1ZLTd3uM1DlFgwyLz0l1DdIqrQTpbQzMbyi6RwquDBiumvA8CvChqQ==,iv:KdBbmHN4v0wvxUHqTeYZ0ZvWuNNwNYkkMNWT9/5X6YM=,tag:yfv6Pbc4PhxjE49n0OU3FQ==,type:str]
    internal.key: ENC[AES256_GCM,data:isTTjhdXp5Tb88yPao6qZcRrLgvQiIlYFCHmbypr+LMvDovQ4bAw/jMpUBNaFlbSCKQdGO4HTd+FUhf/vkoVl4nhnyEKPSi1cquOo7U+0eH4kN109d9BDd/iOD9MS8TfRRzjfG/bckjXGMbQfz4S2WfFE/s1RS9oDb9dJETirO+OukwJ53YiwhnJV14RVtgyvbTJeq3jbSernQO2KWTvDO+ix6UnQvEDmDFkT1QnuasA77OjwTy1GivsHwNjXmXrZBIV/Wj8OgJsQdmORX4kNQyIYzt+/2zfjnCLMuRNMDf/hbtotrrICL1w+mBSuizG4Q==,iv:xmTGvOlNBGF8XUBQ1mQqbvSOKJmhK1fCB0+bynlPQjE=,tag:bRp9u1DuCMc+wP/gqVDCpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVW5YRFFvTnZza0lOMlEx
            dEhOMElGLzZmdVVhSUYwc1NZclBpQk1tMkZjCndmSUlzU0oyTVNPb2txblRDd2Mv
            N1VaY0dvYUxJMzEwVGluWlg2VnZKaFkKLS0tIGkyaE44Rm5SaHd3MWdZbjJwY1do
            NkVSaDFkeitROWRUSG4vdC9wWUE4MjgKnY3+oMla14BSE9h8NV4CplffZRG+3h5r
            teAazLWYEc18Hd137Um0uSxo0WW0Kpo9+RP0q1HaJBCcSUCjI/EGeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MTRNeWdkSSszMzNhMTRq
            TXlkbDVLZWorS3FlN01NVjdlUHZHOURsOUZnCjhhY0ltYTdIeEtxejJlaWlOWldF
            NVhSWWZzcTNsQUtnVVVIbUVHb0NyaUUKLS0tIGh1ZzF6WlhtTTZxazlENHN2WkJ3
            N09BT0tsbU1TdHM0Sy90bTRuQkNoKzAKT3DyXurNOw1iUroWHj7fEtBlIFsNhS6r
            sFcydvlFaOqBly8jET84D3i33W6Fr0x1c68fRqCikNjO2wfe4LHlqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRk5zbGRsS0Y1OWdCamVW
            UWVtUlEzL21jOENySUFPTUdOU1A4NWNIQzBjClF2Q1IwN0JYbHpRdXo0amVJVkd2
            TDRPbWlkclFvWGR2eGkzczVkVmZDUEkKLS0tIGJsMGlqVzBjTHFycitPR0pkY1Z4
            VGdDZlA0QS93MlNINlJoSTF4UllQMk0KWZ2WNlzn5+msEdr0LS7fxZ4kOGiSuV1d
            eIcvmeTKprs64x4PLQT+s2HkH7YUuobr4EIJdnfE+8Yi2he0j0bLNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T20:49:00Z"
    mac: ENC[AES256_GCM,data:tBYqTsXgJduOfBmaGmlFUYwZowRELIgmPVcz1JliQ7OmJOBiQTmT+394q/IuJAXqdsWOMPAyZeoPF0+fHR5DhJQ4xqvY10NtZYbEF56kFSOvs9iP4wkouhnLq4rFgzSISIDGnin/m5WiJm5hPgWUQG+o2MVQaFmPSnIgYrRkVXI=,iv:PBRureERr96sqL4kQFu9kyiAZVg3T2d2mUfeq4GGPaU=,tag:CC61HWQYd6DnsI+uDJ29UA==,type:str]
    version: 3.13.3
