apiVersion: v1
kind: Secret
metadata:
    name: parser-dataset-aws
    namespace: object-store
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Qg+PTkPFlAppMWtkgdIHxP24Yhk=,iv:+30JcE7oXPG7Kr4aIBPT4eJ8zg3oUThPNx0toQ4wLk4=,tag:B7l5CSAoDW2piZ0n0dDujw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DrUdIME2qJ7kThUfKRVELmmn/tgT9RGxwBZAsjYqBluw/ofyIu8I8g==,iv:ZTNic1f556LXHENlfzVdzi7k0t/YGK+TMe2YomvQh/c=,tag:CWa7RHTBCrbwdJQAR2NXzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUFV0c1hHSVc0SjM5bkRY
            eFlsQlpwU1VOaHJaeEdFU1huWjk5cnRHVkNFCitWOFZxTW01M1FvamtPZVJzNVlP
            a1lpVHpQR25KZElCWWk2MWpPS3BVTXMKLS0tIEphR21QSHloRE9YU2tYUEFheU5Z
            VHNoS0xZcDhFaUhRa2JnRjJMRERpRlUKox7iWY1uHFLJvz7oS4ZCPuMxiyJ1qOhT
            CdBjZTQm1BJBdhS7nlwyI+zHDAS7/I8PvCcNoCJbhK98arQxhKVYrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZVVhTW8za1VWV3Jhems2
            d3RaR2FUdjMzTFRsOFI4aDljVGpWRndWVlNvCmJ3MmJzZklJMXVwdWgzV2FrREVZ
            cDhMNkh4WlpyVmtJQmVsZ2FhVTNXQnMKLS0tIFpRcUNqZ0RacTJUdTY5MjgrUVpo
            NStibEFSOGJISUowYXp1NWZ2dkJwaEEKpxXTLtGPcqhA+oKWREKgt64J7YD8cdd0
            F5qX8ZARbRFKy/58kuBmojaXkLnOLAWmlvBxjXszHBfijUtwSBopqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WXJhZGpmWEQrR1BtUERl
            UHpCYTlpdFpRcVFTRktXaFRhL1Q2a3dFR0hNCkIyeWhjUUw2aXVBb3VjeXJZWDRW
            Z0RLL0wxbHRxRGtCcnhBeWJQY3V4aVkKLS0tIE9HRGx4Vk1YN1p2Y3JhTzFVeHVD
            QWNFaVFyZUhwZkxVOGdGYXZkemNkY1EKKlw4+eKw3+/S5oXfau6quHaUFZ4teX0/
            9glVhLggwnmI+yfjLAoMzhvcpawxRCry86sFePB4x4d8IJ5TO5l7pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T21:39:54Z"
    mac: ENC[AES256_GCM,data:O0ugHLo3ll+73/jPF8XqxuFAAfQVs0AonUQsROcJi8MPp3ew0mm0KJl2tiuWAfnMwrWKkfk/DoAUjqzWnKxkLiTK22gK/oe0TrKbhRsN9JodV36h1burw4pgHUJaU4N5spP9doM/ZBvA/0e5FR2PVdiPkLpwicaz/k2LfB31ieU=,iv:RHvuNwDTOQoWnK8EsDxCZfnOooMLx9J//Ho+7sdQfWU=,tag:rmknwSDku+FW8r3GUNa9kQ==,type:str]
    version: 3.13.3
