apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1-restic
    namespace: object-store
type: Opaque
stringData:
    RESTIC_PARSER_ACCESS_KEY_ID: ENC[AES256_GCM,data:6VAwsmUHwh9HxaVVLsgwB7ZYPlM=,iv:QtZsgm4AA5rM8T8DMp6cO5uP9RcUWxxF4fe92iwUaeI=,tag:tAodTDx3r4X1ZPPtDlPvTA==,type:str]
    RESTIC_PARSER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:89aeCtmT3XjWd71+9cPbmU+oxjmq97eaf0GtICKwn7xIdAxKhCnqQmm4vLEgL9bhO7HAv18sidmkVQNEqVDLFw==,iv:j0IedAVv6+9HzLU2nf+ijQMvZhrF3BrB+E0IsvcKbs8=,tag:eD15M+z8MQhAhmktkE1zXg==,type:str]
    RESTIC_Y_ACCESS_KEY_ID: ENC[AES256_GCM,data:jneFrJAhAOyPuOiNDNpTCeAoQ/g=,iv:NX4Y3V6kKvpBLF8Ch7d9TBvSty3FWvgOji8df7xMapc=,tag:AFnX1hPchVxGKKO9QxxGgw==,type:str]
    RESTIC_Y_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QuJpIpnIsDvEX9BzhfGwWlN+1XKB9NgVjTMEOzFiA2UinqLxtLwa6vJCCYI46K8ugA8EpfWvC0bcnDIwdGkMEg==,iv:xrofF4RyfZ3YlufpLQVcILRwrVbXoVT7D+Q5gykAsU0=,tag:lrfs8zVcRdTMvKIov/NJvA==,type:str]
    RESTIC_PORTFOLIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:OQD0RuyPqn6cxWMZSvrS9P3etno=,iv:HAS7UCpTD/UEh10nfI9g+pshrhSq3CU/a+vx69evrYI=,tag:x6gLB/bMTMn74YM0GQzrvg==,type:str]
    RESTIC_PORTFOLIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:spHEd+I4WaUpxDvcpHMgJuE1NXVa9qDMYwFWOhwq1x30hF+jB31T+1ApP4rp4U3Xgh4KbCJQLQEpn64zOigQNA==,iv:JkZMNmVqBJSW9iLSykO8YoOEDESJFdOg6uCmkFm9YhE=,tag:3D+yYmm/vj+RoNOggUobGA==,type:str]
    RESTIC_ATTIC_ACCESS_KEY_ID: ENC[AES256_GCM,data:H11NcnIdStih4TOFtx+zbHzipqo=,iv:D1YiwaoU+q6538goBul83yw3dwzKF6zSj5T/ezKc80c=,tag:UL6G8RpvS0Ce87L/GEzwXA==,type:str]
    RESTIC_ATTIC_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jEqXIGRS72SiyirlZgy3pCVQvS1dRBvemAHNUXVU1EdDlvRnh/sS0QO5XA==,iv:oKqW69JUu0dZQCEYFn+ma9iFfBKMiox7xDrM5WhkRNg=,tag:B0w2vozT83KvvbW3IYFxcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRHlzbkMrWEhTNzk0a1dZ
            RlVjbHdkL01RN01NVDdSUGZjRjUxUUp1VEZ3CnVZS2JrZmJQdGQxcU13dmVWWVZB
            dG1INUsyZG8vZG9lZDViSlBQbVdhVkEKLS0tIEpvWFpXNURQblVjTno5UDRMTDJG
            TnlFMzN6MUpNT3dYNXU3a2ZVcEZjQTgKaUhFIvI2UUS/0TePg993co4s4UtzE3UE
            WcG4MJImyEjxFEFJXpWTtxGN/ihFcb5rb4sPBUwvtP+2K2Dt7ktUkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK3RDMGc3RkdJZVMzb2h2
            ckdBVDZVanRqK3luRkhhZnNlZUp6TzNKTG1zClpUanpIaEFHMkdMdktSZGYrS2l2
            WEowTU80M2FYQmJNYU85WUQyNmNYRHMKLS0tIFpzVzgxL2l5U1hRaklRN1ZKa3Iy
            RDY4OVh4ODBzRFVYV0E5VzNJbmh0SncKjV256fxR3sbA1p0GexdZ0qqUZ/MJ8mv/
            zKm95Y58BRqtV9iS6hyg6DGFDT6qmBwQG5lCELJd1GQYSgHtzGbl0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZEp5cFQzWUVxK1loaW4r
            LzR4elpNck94aWVXRzlVeGtlaGdnQzdiUVNjClFLWmhWcjZKdkhHdkFvdCtvMkZn
            QS9HbEdwcWZTU3pRY01oU0hRd3FJTW8KLS0tIFQzNjUyYnFydnhOUEI1QUwrb2JK
            VEZReUFDV3VZdkdiVFhsMWtVN1JrZHMKNbmEnmq/K5v79d9aLbnjF7JB9jkbKAxQ
            swtuLE7FrIALS+CjtOF5lrwR844+iXna0VcdqFBC3/GrAt3Ogx0fEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T01:10:20Z"
    mac: ENC[AES256_GCM,data:h+L0nPhQtAXinqVWvcRSiuy86cbA+o6Eib0tWMljBNhIgtRc/CBK836paC/IWfWOvdXx0r2mHTggbzap/P+0pyUpEIPWj9Rk0viunxWJT7Fy05tRNOw06+TjiZRblGOyiYAL8UxQZfRP1ms22EeURfFZJio8smJIVqSXUslyVqk=,iv:XzfTbdm4UYxLHwwSk+eeBS7K/JcI7vie4S8rzrM1ktk=,tag:juTF5HeuM5oSfuXjTZPxrg==,type:str]
    version: 3.13.3
