apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-hel1-restic
    namespace: object-store
type: Opaque
stringData:
    RESTIC_PARSER_ACCESS_KEY_ID: ENC[AES256_GCM,data:bRkJwq0dawNwzCgu06pCj5LUZKI=,iv:BAIMGq9XycHi4rWGagwxrTjDrT4jPZ+jNEOn4gPCf2I=,tag:E751s0qrZHcuGopkaqQ98w==,type:str]
    RESTIC_PARSER_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1S5+NcrWISReThninCoj5JAB61I42GO49xS0xjjaSpEYVM1n5A7vvZ6jHR45R0xQlnlvYKXt9ISnUAz3hXL2fQ==,iv:rWoUM6ayTcdbXbvodK+4YBTshcnZH3ZgpPllyVwEi8Y=,tag:4BO7ufWMeQFirsW+vqG9ug==,type:str]
    RESTIC_Y_ACCESS_KEY_ID: ENC[AES256_GCM,data:Ii8cfNKOWXW0P2MHTcOqV0di1jk=,iv:a2LQMsGbFGccY3SWXvRZ6m2YXNDCyfNEPJKWFNzjCYk=,tag:4mNkHTYPOjvqjx49c40nng==,type:str]
    RESTIC_Y_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7C/YHP3614uSB8ehgMA+60QGlXg1krfsJMymTQmEPp6fX3HoUohGTrZtHCUNs+qou+i2nbbOqT8jkamsE0gW9g==,iv:LkszuzScDqj1QFF8a0l/fdzHmZJXnQCsLjtGB+RYQy4=,tag:2FcVl/cWDJb+cfZtVUQ7fA==,type:str]
    RESTIC_PORTFOLIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:bOyeC89ZvrMQltXc9PQ6ZOjvyjs=,iv:m7xvve1z4oAZFdsVCuwfIQMV/fafm62E32s7FynZoN4=,tag:lglUtiCndJkIMqyIwQzSmg==,type:str]
    RESTIC_PORTFOLIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Su3O0YB8wZUrvAke251lOjur4y8mPTsQ+yr33OM7QrtQed3uFwjrpMKK2iDLePBKWXL32xN3LO5vIZl5iy9QQg==,iv:6o7avnd7CuSX7eb7gLBpKFkUOpHX8aDFhbtF3Mn8UB4=,tag:e0vTwg0XKH06N129PD9J7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaHpkVVZIdjM2NWxCQ29p
            SFh1MENEMmtLdlAwSytiWTh4K21mRVhpMWhRCnBMM3RwOGtmK3cwWUU5VUJOSCtm
            dWgzdEQ5bXIzQlBuMW9aQjRjYUNvYUUKLS0tIGVKYWFZSlNqTm1LbGw1eDg4Y0hP
            U05jRk51RC9sTGVzOVE2OW1zRjV5cmcKJMo1wklpQ4LW5RvXugyQ2hZBxWyrK0Yk
            pQgOo7tfVeamE9aBbbkMZIV9Vg+pY83nppFBVL2LhPv/wRstrz7uyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTmhyL3M5ZGwxTHBJb3Fq
            L2VEVFVzdjhvY0FNQ0tuandySXArZytGZGdFClROMWlvTHZJdlIzYzJvemZtY2Y4
            V3VCc3RlSTIySE5ReGxteXl3QzBoTjgKLS0tIHIvdzYxNFV6UG52N2w0V0RsMlZ1
            Qkw4RWpBeEE3OFlIZWZKMDM4dUR5Z2cKPDlMTY0QFFJxm1arOt/++DjoBgN6+sQB
            1IsOl5y2bxbgPlGI8W4/1ZBQOH3TnpsNtrmF05cu9F+aHPJUyUFVIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArME9IRlRVTDd1d0h5eVhP
            QmZyYWVWK3d2b2lPbGRRQ2tEZXVqaUp2dlZrCnMxRGFRcEFDQ0FNN1VER3BjL0tX
            UE41UksreGlFbk1INHRaV1R4RDlycjgKLS0tIGJ3TktCdGxudURycGVkaFBmWVFF
            ZjA0ZEVSRUVuRE80aGJxL2ZXTVRjM28Ko6wpqm/t/5CvJ5MOe4QcUY1jNq8Ht21Q
            IVk3hXcBY4nUL/ZhomxEwkYssUmfULF15Guqj44q1QXGg0YKdeuajw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T01:48:23Z"
    mac: ENC[AES256_GCM,data:xRWIoj3BdcnaYsq2QY9HnxBfPDY3t7bA5AFfgxVO5l8Rzzywo5hbGC4L4va1vPCYwbySxQ8XXSE57uQydP6hJ3XnpCN7RDEZ5km6nZPLsxwxVn3x0CRs4VjyioCYnobdfgGlI1Frav3XbDZcv4N8iA/MtFpPTI7daSz5tP9VQoI=,iv:tzckDf64fk1fsfYu3sPztEijOq6ze+CDqeztsS//neM=,tag:kIOnO1NuKnWxx5XAjFL0tA==,type:str]
    version: 3.13.3
