apiVersion: batch/v1
kind: CronJob
metadata:
  name: repository-maintenance
spec:
  schedule: 42 1 * * 6
  timeZone: Etc/UTC
  suspend: false
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      template:
        metadata:
          labels:
            app.kubernetes.io/name: repository-maintenance
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          priorityClassName: batch
          nodeSelector:
            kubernetes.io/hostname: fredrir-09
            kubernetes.io/arch: amd64
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: maintenance
            image: ghcr.io/fredrir/platform-backup-tools@sha256:1dd4da1509547564d4094dc03f6351d72600f76416f8e66d8dc5870dc38a36ce
            imagePullPolicy: IfNotPresent
            args:
            - -ec
            - |
              restic --retry-lock 10m check --read-data
              restic --retry-lock 10m forget --group-by host,tags --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --prune
            envFrom:
            - secretRef:
                name: backup-repository
            env:
            - name: RESTIC_CACHE_DIR
              value: /cache
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: '1'
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: cache
              mountPath: /cache
            - name: tmp
              mountPath: /tmp
          volumes:
          - name: cache
            emptyDir:
              sizeLimit: 1Gi
          - name: tmp
            emptyDir:
              sizeLimit: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: repository-maintenance-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: repository-maintenance
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 100.64.0.0/10
        - 169.254.0.0/16
        - 127.0.0.0/8
    ports:
    - protocol: TCP
      port: 443
