apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-parser
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:G/bu3xLScORu4U151F4MlvqNbaNGwnKJr78=,iv:vCVSFBLa2tPb7z2Xe5c6QjeYRpuyT5lcKobpnzgfT+o=,tag:CVssv9hvSvYnqXoSLMumCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gR5Us/9+gYM6TUwaFYiNJijUI9IC0k4gjmhKsQfuoSFybtOZw75WtaoM3eisjd0BNgA9j6au7ZnbvoQMyKgM4A==,iv:44BcLtZ/MsQYKmfO80xAVJPPbuuWEAavRQhlObl+TZA=,tag:HfPPsSxA53JR4U1eJvk9Tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK01lR3JFMFBYaDFqM3R1
            Uk9BTk1LVWJPRGxUaEF3cDJmcmRsRkxRWTNJCmJpS3VSbXhWQkROem9uT0hPWFJz
            MGNxODMreUszRnViRVluZjA2dDdxaG8KLS0tIGU1TFRNeDRwaVk1TFNlS2ZFa0h3
            dmZKRXE1K3VXOWdTbzE4V2hWMXlieTQKZlpVTQUVnONyaGgWLItD7apKipeiAhyK
            pE59rao1ejHe7Co27OFFUae8BSLREmc/8Z6byi0wQsEGEDAzXksFGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbENyeXZDams1R3MreFlU
            YWo2Q2t2cysvbDhkam9GWm5WcFhLaWlFTkhzCkZIOXU3YjROcGZrSUU2ZUtHRDlq
            YlVpYVp4N2RiNzBmcitGMXdBUU9vUzAKLS0tIGVHOFc1Yk1NT3dmRlREY3k0b1dV
            Z1gxUjc0NEFVU1BvYllDTENYY3V1WFEKdUBpnRwLHKVEX7V23WNJLCiVg1Y7TyZl
            TFzp8gqtGvfCeMP1ImSoAyhMwvz1SK2XWgoXMalqNidSG6BGEGLXtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL1ZmZm5sbWwrL0ZVUHVW
            ZDlmbXFkQ3J3VUtKRk55bURpc0FlQ1hIbWpFClg1S2ZJU3BlaXphMnNzV2tEWXdC
            cG55UzFiUEdJZ1E5WWlNZXh6dTE4RzgKLS0tIEgzdCtRNng4YmJ1cHNldjV3bENk
            ak5WcVpuT1ZoUDJSRWRDVFB4MDJZc0kKVvL8TYme+mFxCt+WyPx4gkbb+MVUDDfP
            1+oeWYFelvnTOLe6ETE82YTX0rV89/AEzUcSzzJJagjZrY05XIlq1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T23:14:56Z"
    mac: ENC[AES256_GCM,data:LZPiQf4K/p6VQXajaca+ecBM1RlRVsUrA3OAvIMVbCLuIs1cCgxOzIyFxdE8xZzd2fTtfIbWU4NiFgd90I5dBh1n4nQXq3USqdbrahoB4UoQ/+9y26XHq7jpziapoTCs2Xd42pDoDLuOwsKTB8eSSEX9j7uid2HlL0FySOovODw=,iv:i15yOwoKT+u74T7GhI4A9FRYiEum5yJJ8NaOA+Kjv1c=,tag:8fNMkCVsHsifOABgGj8Ptw==,type:str]
    version: 3.13.3
