apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-parser
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:58F4tdzGY9FnK8cSJVy5LD1QTFKXc0fs5no=,iv:vCVSFBLa2tPb7z2Xe5c6QjeYRpuyT5lcKobpnzgfT+o=,tag:oAfbU9sEgINv9NbHUD37CQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZSthC14/m2lrC9DLy1HQSmofzCHphPxGXpbgIqrzqqUkxXrBz8P3A/0D3BSVWYvC1TuOd4ABctYdZyQkkFuTUQ==,iv:44BcLtZ/MsQYKmfO80xAVJPPbuuWEAavRQhlObl+TZA=,tag:dXp7YKO5d7Vx4fYvD18OpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydFg3WHlsNFZlc1dYN05K
            NzBHUVhEN09SUjhyNytzZ2JTUkZBcFF3UEMwClBkSlZZaHVHSUJ3Q1BsUGRvNXRP
            RG1IK3JSODZ6WEpTNmhISndraE0zcnMKLS0tIEF0SVdRTzduSnJoaGxHaEl2SkMw
            akE0RXU1d29pZkFwdjMyZEJtNFBMR3MK9WXSgbyvJpbOb7/w+LHOVesAtVLtlCKB
            JGONasS98+BuUspcjfMketUEA1V25ofiMxW+pQwpRUtSbv7+SUIyPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTkpHcHRCZWwxa0NKdGZT
            VXY2NjJVbWtGVDkzaGNNY0p1Q0xiY00xN3g0CnZ5QTR0VE5ZVzFsM2hSS1NRaDJm
            ZVM3WVYwSEdyVlFkVmVpUGd6UzFyNzAKLS0tIDF5cjZJM0tUQ25zQ1VMeXVoSnpa
            YTBMa1NZcTFXcUI3MTdXaXRUeU84TFkKKcZUpcIKUflcPx/Iu99mRC6nqOI9RPcj
            5MGKMQaclagZWe7/XhOISiQUU7pmYkUchLpP8UxxNjyaR6bkNtvXTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc1RGK0hxT3N3d3cvTUdM
            aERwdnNQTUU0RmhYeklBWVFOMnVsQy9IU3kwCmJsSjd2cHhBRkk2RHBJWjB6NmJI
            RWVqRS85Nm9XN2pzWXVxSU9uSmRhd1kKLS0tIGl4bXd2L2F5MU5NQTNLNXNtTWtH
            OEdvWkovR3JSRmZWcGwvMHR2TDZuZWsKn2Mq8tnI/vBQFvtcJWRQkpgyd/yZTgzl
            IB4rQ2JY8MWBHM15xv2/zsbe7E70y3pB7pn8JGruSu7VOIVD6VEfvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:33Z"
    mac: ENC[AES256_GCM,data:55YLMBcgPdyacXfvT7ajkZABnGGlXAlRR53At83j/d+/Jy24PRED1YEoBlYNqjQaJnEbGL1RGHea0LLhCRKBzoeeM8rDnbklo6xi7DDP/F2mzEtoqKHVoIsD6AbvS0KFrfc55cnumemqy2xrW1EcH8f0813x0M81OsUmiRSmlw4=,iv:+WZXpZC1zXAIT9H15mUtpGdrmJ4qkNB8rXsGDC0FHK8=,tag:PTrv2rYgScSM25IzFvCx+A==,type:str]
    version: 3.13.3
