apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-parser
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:0v+yV7aTXw==,iv:Z3ZWijBqHEe//Ry+ImHOnCCqGyKzhCNgPXS8ZK4j6X0=,tag:zmnrOWHl+M1FBGrdS6we9A==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:sUrv/FHUPPF0,iv:Udo5srJ2kbOB6WG2tfNmKVHpJUgTUS25oC6qS7861O4=,tag:bDwUvvcIQmAIJj2GGyes4g==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:sYOApypjh7+j8T97/pa8ZddX8MZtniwtf7UBrs3S0T92RfDaYjjWvU7BLcXTjJY0JtFZks7FGsZiCw+CBheXcdWbd+2rA4LL/O9ugYjixnKUU1Fttn8M6sEWY7hi0raGJqjcxf0aBeiCcNtSnSpb7b4UDEaxSdHAPhEZ01F1j9Ipv6/VeVziSYjzQHiMcwrjNmHEhTKg5QNKiHy7DXWWJ8TFe1JBQqb9e0k6Y6GpNRtX+qky6UEQRgl1E4llJUccX4WkuYeVnLEuJycuP/S8OpBT7grzP5DADKk8XtniDJDfEk/PszTmokNQB5bij6N8oEV/U/p4yKuM34v6LeinSXc8tZUgh8WVbnawccgBogmkJ8y0enGfCVrph5TblYmo74bYUHc2VIfyn1Jgaz9gcvZPYBTqy4W7osSG3p2sNC044PkbY0efIOEPvcKrWlbmFChRt9hLjG4W5jXaez7NBaEcEae/HMfv8l65Z7UCjFBh81Sx8LwNOf4fDjaWBVRZHkjhMcRJgyKYEQIYJ66BE/OlWsMKFv0FMaok5uCb5Dvkz9n0dzCRMg/svLWZgnkYjxsHLk+6jzB9O9E3XADtmOD2x+70RmF4BhFiYJA7IKRpI89dr16Bkzq3ypRFnrcTLsH9FHZ3x3ls5cjMMlILwWj5huNmQu7Oao/yEvD4qEiL0V1ZEtiZmm8YVQtB3LT9UlUmBiG9SpuqUkjtZLc7eVcJZIOV9H888deDOsRXmzuGpfB/vaQUMo2DAdj0t4XsIFVmaiBi5QRxcsEFajKW93TCWX/qxy4m0dg5wKXJNDEgt0naxAjpjb4D5yYTSc9rDHjxYiikOEZENLByEMY7/1J03xO9KoB6532J22lqzibs99jFhEjDBdMOkxZqYU/5ByaX61OPzk1Wd3tM13CwzCU88qojtPz52Da5+wWJEWCzT+ABNyV6ApDJTnTLLH3vp+x8vp4Zg0bq5mQPqywXczXKSCvS43SfCp1zJlg2EHWikhgQ2xlt6uGp8sKs7uqrNz3Wce/flAQ+Iw1RIp3zxbegoLC7qGEHoM6Q+Ryl11U0zw49wQfwrMIs5ubQ4rw5LK2MFtWLoCKIp00xBptKBX35DXnHI9wtDxJdvozWCQtKgr+og/8Y1r7cMfssYbVnrl4VSTN5JQdicSXEMzFWIp9rGvQZHhc75vO78GjOprp3DPy1L0rs6nj4jc3BpPUbWeo352/TwthyCQ6mILgw3FVyux7oGiK5rdLStEPQXivhNJdjP/7EKOFQCj1BhCBS6zD7gSDWfo+wGvr7M2EP6fKl9c9EaJP7tevL3YLAb2CaMNCfPtEdcSsYEYOhDLOo39AAwzYUJohh26e1DmcoT9hjWHH5wWSp1OVw3jFJ8Z/73+Mvx8kMHKVMfPoBZrfmITMQDatfpZ0dBqnKrEzOI/QOchwKg62pwJgZQ3LHPS/MgX1jmlicwK9MRG6E9O4NVD41eVAZKs/9dC0C4M3bO0yvHJOUkU9heF7vmI1y2LBbv7pj0GCUOjZ/67dcbcnfC57tklDXaZnE7fRbmqfA0Hd1g/sFMpJJJKWQ+aU9ICt3UKlDV+v2S0GhWQwZ5Z54qxgUaQPxeareAVbvkqOCoOSSIVF7HfwGLYXsECscKPMHvfNMFJDMAOqLx3j+i8eHRhsKME0nOrkws8VPSfDEAQetE0Aw2I51G0IvvauBPdDx8vpokrv7YB3C/H1qYzsT1a4WPgmO/JjwD/sI7+otNwVGU6LR248qOmZEgItMkXG+kier8iULYODls7QlTnnBhTVNNfbe5tqPF/Vtw8kOxR4EM50q4J0ezhkkHknoF94EUpjR7EB9ZkaY4IKNiI+F828t2TcuZYm2KK4CPymvPfK+z3NV6UZsNPb6oj0ynHDTCeCZwtBRSDItBEVdst6tQ4CtKWCa1lPqEqN02jZAnHRXrtsRQDCaDMJv1qrYBNz68Agt2o44WPsxPe7Z2OVekA4ZdEDVtDSyuRmpRgr2Ib4yfnK/HY89Lt5pgoWSisI5ADTnz9Ir/efCIUZYFe/Vwj7Ve5cZ9uOikbMbVtflm+Y4I/01XijSkkIOHlpRy9Ckg/1O/K1v7E7eb0+FGOLfQoEuBUF0/WuStfpZ1LneIInIK7FudltwSceUjebcRQoMkD0sUCgrjt4TBaC3y7Z4iUNwsuNPU3gYg0ocjUMwxN4MZyfzg7xEVrgcaqkC3xnTRq1kKLfu6d6jpH/MQA==,iv:5FrhSWDoEaFRZCqnMHYUd/IL7B2Wn6smYzzuSVqcSeg=,tag:YcW0mzGm8ewdN5Se1VWRJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTUQyZWpEbEFialJwdkhB
            UDg0b2IwNDV0VEV6bEtDYjkxNDYvKy9INGd3CnBaZkYyNFNLckQ3RnUrMFZ5Y0h3
            UlRXWFpqVHNLRGFPVGhjZFF6ek1TQ0UKLS0tIGRGbFFCVDhnaXB2ekdCbGUzM1Mz
            NmVmNDZlaE9xd3VlTmUzRTFRdVRDbkUK7Ka/3PtJfiegtq0FllK+B9ID6yS8AYiD
            m+SzMxKbNTg9kClk0s5rNou95bEIgPwYd3+qlP0FeH6QPcpXmLaIcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U0I4QWErV0dIeFluRU10
            YkI3dC9oc3dqcWg5a3MvK2MyZUEyanBjQUE4CkQrWndSaHZCSkI2TkNmaGRIRkp6
            WEg1Zml5bE5jd21US2ZTZDVEVFhJVnMKLS0tIFRwdTFMT2s1QlVzOGZQVTJ4ZklJ
            ZWRQNS9xS0xoZkpLUXQ4UE8vS3ByUTgKDzcSMA3n14noNrAkXAQt7esSKxoJrDwI
            ahKTmTPL0hhrar5G1S5pfrpRuQDuZFDRt1x9epj8GRF44c+rAcLSYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIci94eWYwQWNvMS9FbVRQ
            RTdWM0RaZXJraGE0aTAvSngzdFBsUDhWeVVNCjAvdkp2RUJFdCtlUXdySVNFSW9h
            N0psSGlrcDhWUWVzSjZlL0dLMkw3b0EKLS0tIHc1NmpHclNVWlp5dm9DLzNPU0xl
            NEJHM0szcTVIUmVEWTZLUmhyWkJDclEKx9pAWQ8bAoiY3mOxFszgo9gGwXNsRWhR
            tzTDbGALUnBmYnajFH5clklPm4cVhllWDTMjXqizmLCT2tT6c8hYrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:idxqmiiO7CXfYrVkJkI5hzTMBlq/FKyMcSUXaG/BiN62iqNQnQXWB8aOxpwQnokFmnMPnlGql+leehyC6B0nTf1HKKGwfQ+lJVckdYioueITU567M2ydv1EcIp/mVmKE3/2QkPRnzxuD5CVyUHnDgLECQ5aZIRsyOSPOS9grGwQ=,iv:EqIF5+62ErCAM0uc9UNQlsQfQhFNzFvoIBQc1sUqyGg=,tag:UpGt78Hi3I8REGcmVv3SLQ==,type:str]
    version: 3.13.3
