apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-parser
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:ww6tc4vrtw==,iv:Z3ZWijBqHEe//Ry+ImHOnCCqGyKzhCNgPXS8ZK4j6X0=,tag:j8NLFS/IWdHZzk+utMjuYQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:eQw9qc4o+eiW,iv:Udo5srJ2kbOB6WG2tfNmKVHpJUgTUS25oC6qS7861O4=,tag:4UsqSwrl1K8HEsovt3ONxQ==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:46b2lNu5fJ4YQHNyDGwTIiMNI1/f6IuRs1rD2BfRfv4YpK+aUBhd33r5erCG47GUN4MUvUVkWtLZpzhmsiVbCNOTzRrqSzF5m1jBl9PklP/Y+NgBC0JRUALpEosE9HI/cPBrbtW8RdsckysYkDTpULEwCkxeXzfEVc3UNSb4J1tLtklZV2gCTSs2o7VfS8LzaR4jIt0AtVaHN3z5akCIQdmoPRgL75zzQ5cmjpJlDS8fLJbJSjIEZkzwWV009A9/KAr4vIzfbtu2+WNdJ7RlYmF3gAjD3c1pIl2gRSKbUqVbVw7QR+STPSxNUmgSpCkRgMI309BldBAW5ZJOqkikaHdDCfQDlMlGDZ3CSz4AsLV4EutHg1pB3GmDu+AF2M4zDQSVLda+iI4pMVvPOZQKEtjBNKewwyp7W7wIih0VMirxEWjavwhUbmk2kAIYWB6V3hw7CqrM/MaIW6XnOOPqA5+0AHGqYC/PWGq0b34O+j3yxzlJrnK/zjb4Y+8IMHtBZVEII3pD35/cy7KSrJYDjCHZ/EgS6BqZQYApFd2mamudKTpFBBgH8v+cNf3R+7QMHy2YLarORyzreYcjXWSjGzYqJQznums+n213bn4Af8mP2cFDHepfwEbjmliEEGvT8Zvg+O6BpSRs8hS5wcBZSgN0WoqZNDeycMXwemRKSFCaPs0gvWSpGRpNwABBtnHeToegVvp55TwirLBdijFlS3JSk6tBVHih3aZfBhibAltWwKDpu1rC31l3ZFDwedRVDsCozw3sptlYQ1UiUnO2XTkUAnN9U7P8rDNqx5Tmp3/hxQ/4CVydICH7VysZRKUlNvHpseSJPN5bSZqPcZPsVC7G77dsTQ78BppXnLJhGFRdfFzHo2KqvNdxIXGN0nm8q6e3XisWmgbwnV+MRrbnDCQALFYROFssWB/eKFnEyMtO5f6Av/CIe13QTY/STdfUnp4GnDm0+wrybGWTqMCMzKdllu/THaYz8nSbFrimwguAyLV0buCgVhPIpSelExvgxip15puY4eEGDr3iR6FnKIa8FbsOquB9MsIzMha1FNzKCvlxZITgMxACSxUDOj+rBKxZHz5lGq+LUxeDXJBEi3rEhBRrG/f/Rtk9Or+8vnMqc9X3fgD5hkKnS2GqSM5u6SRjBXFX0zmqL74L/h/EeR8xF4UAqdU5p6fRzX6nZ+hNf0PJAbZbE2zyVPXI9BP4Tcg/N3FN93r3bEq1FN5pRJHBFs9YcQifKKmoEX5AIWyMZT/QUCbOF52OLLVC5Sni5wD6qbdQUL8umZsMoxYN1xi+ykLyiGKzvgvOzDLzOXO2Rs+IXe3FkJS6dbJKxe30bxhba2jqlkh0tZ7EveTtaNcnHsSwgU11Fv7x/Ccaz/0OHy4Fq1pVGPDmMB9PdsGD7PM3f/97itBDyCbgzEpcgBAT2hpHIOJEsChiD0HzbnV8CTXAHeZCMhTNXDybFRg5z6QzFeoFLuqBF9sGGnIRL983nuG5Sm1H5sC3dEeGMpFi/RFtz//OoCV0ImgMK5n6+54nkv/bp/RQvint7XihA4RPQVcsVJQ5zvkdGPGud4BpZnkdLj4X3CO+1KwkIO626y2fnhfIanOD4dMtqRlu+di2gjCz1NkegcIFotLUL4+lxOn5Ny8pIblX8IzDxZgas6899Q6Ezj4UET8Ljz5eApigdHgsBLsytH4U64VM1nLKESGsemczihUGz92o1/ENpm2UJTwXlsrWDOlZ+UiK7TQeshmOo8TWxfxjWHrvqBqgha2Mapgc6mh8hmJv5/jjmEv49FfCR4ZWc/1Hxc46zAnMiGlbs++fmqfK57miw+2rL4aTKclLsLotdmeUKiyHzXwUjfCvlij/7xXxVo78J1ib6zRF1QzaTDYtPTtH1uB9XMSNhTVh+1GiiCQthlxgwE0PQ78Y8tnmfSeZft6Lo0sde66ECyXTYyvvlmJy8yewNb5KPOcmCQrS8qlkDpFKJPuKse/2vELekng6H6pkdGNJwHmBiiT2ym/mLvXRhH6y2lMG0aHzJXhn+tFIXschM1XnMaFChWbodH2BYXj16jmX1QYAQviQ2H+4TMVXstO3VKFStu7RGYcpfWGFCKCjKa9Bpx/cqnz7sKCHJAqHkeUVkr0VW2lel6d+Vt86Xz4/kz162DUysWCpSdCzk+LMnUsor5gGdKHHPdCqYOnFPVgWAwhKIdgMOltDUNgagnxf6Roow4V046yBDX4fEA==,iv:5FrhSWDoEaFRZCqnMHYUd/IL7B2Wn6smYzzuSVqcSeg=,tag:Drtcv5g/k4umyWjv1KUnLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a09rNHJmNmdRY3FCbEkr
            MHYvaFlUU1gwSnNkRTg3b3NHZkRSMk13UkJBCkhnZHVPMHd6R0hBRm1RN3o4Rjg1
            YTJFNklSMzhscVNzayt0T3FXSzY5UncKLS0tIDM2RjREUmNVL3ZDeThSMlI5WkxF
            VFN0VENyN1JXV1RwSzhkbHRqQ1VSOVEKDeU1V1ShPWE5+krC5xbI/OnRz1yACOlf
            TY5VJJhs//LSI5ucgOy/t0Uhyz89eWQLZqyMx9beaH1KNofiZMUaHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVlnVU5GVnFGVWVLdndw
            R3lRTy9zQStMcEEvdFhCQ3d1K3hBeWZITkhrCkVMWU9tRmpEQnBIUVd1QzVZVzhn
            N3FTL0hDZXpJMTc1SnZZQnNqR0dJQU0KLS0tIHo0ZGh5ZXFVMkt6aldyRE9tWEho
            OFQyTkxmekl2OEtrblhXdUlZS09YbDQKtvaDUNMyhZ8HGTYxV9d+Qq6FIaSrRLQX
            WfrbMxSatLBYuAAMIXFOh8LyS1iY5YdMbtqOfRhrvQCk0Op6xO/9RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K0xRUE5wYStiZzE5QlYr
            MXlLSC93ZkozUG1OK1JrSXV3V0JzUnMrM3kwClZ5a3VyM0pJY0xrZUU5Qkc0V0dx
            cWZERnU3YTdka1F5L0JmalJkUXJETjAKLS0tIEYzVmQ3bmhGMFdOLzVQMXBUSnJ3
            TjVzRVVELzJpM1BBd0ZXeHdvRW5IakEK99+Fg615wqxB1DimG1mT9mLpyrVEgsvq
            15zsgL+jhxEullzfXoqDs0QS+V6z5LGllo8PyDhSIGpH4UTz7EL2Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:33Z"
    mac: ENC[AES256_GCM,data:5/1TbdMEKMWva5v4eecqOodlEVbj6YCcOd1VUrZmRyla3S3sfDgFkzk99/zkr4NnXz69ddKevOTZE0js9G9Pk42Tw9zFixwUcLOpN7/q9kFbktVBzBV3ZBXBO/uT6voN5TEoKsnOLypfb9CQea7XMnUn4JEfObBck6ulR594CA4=,iv:NFqmTpE+W/h5Bz+H/4QW8vakxWUGbLmKfN9ZsqWQGtw=,tag:ANvaTLSsbcB9FicaxWZEqg==,type:str]
    version: 3.13.3
