- name: Register trusted dedicated build runners
  hosts: build_engines
  become: true
  gather_facts: true
  vars:
    build_runner_cli: "{{ lookup('ansible.builtin.file', playbook_dir + '/../build/cli-release.json') | from_json }}"
    build_runner_toolchain: "{{ lookup('ansible.builtin.file', playbook_dir + '/../build/toolchain.json') | from_json }}"
  roles:
  - infra_binary
  - build_runner
  - build_engine
