- name: Configure K3s servers in bootstrap order
  hosts: server
  order: inventory
  serial: "{{ '100%' if ansible_check_mode else 1 }}"
  any_errors_fatal: true
  become: true
  gather_facts: true
  vars:
    k3s_role: server
  roles:
    - k3s

- name: Configure K3s workers
  hosts: agent
  serial: "{{ '100%' if ansible_check_mode else 1 }}"
  any_errors_fatal: true
  become: true
  gather_facts: true
  vars:
    k3s_role: agent
  roles:
    - k3s
