apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:6dT8HGJGu9QWoY8AGy+EwZa+V6sWyDWXvOJBSEFnmDSRgO/gNFgSzKUy8wJx+CV1grvDVcg=,iv:z3Ta37Tjmpa87ZjfPE/VY9aOJFTKh+TjzkxjKVrwltM=,tag:4E4u/VuYyPhrDl49hk96mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SmFKWHBiV0dsUHgvd1hK
            Z25TVmtPWlBDT1lITFpWdHp5R3VNakdZZVZzClBwbEZURzhGTUZqZUxLMGFVaDB1
            NWt2UXZFaHBLa3FvY1B2WHhWbU1iQWcKLS0tIFlBVnQ1eHUzVG54TTR6MU0xUU8v
            T2RuMDRmZ0loU3VrcVhMYnBCdmx3M3MKhyycQaJUTcNYBr99phMGxx2vkxtzy6n9
            I+Y/sLEpXVXxNkLst57KSp/IRnTF8b/Mnlp6GFGj+kQSV175Q1XH0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVWJldzZpZDlCektlQVpM
            WkhqQ0ltWGVXS3dUbnBuZytEL3lCMFRBK2s4CmtJb1IxL1B2NnpJbnd2QTIwTi9K
            Qy9BVENLRlgxUkZwaUsrUGFWUUh2VkkKLS0tIEl0WHVGVFFOekN5K0R2TDRnK2xh
            REpKWnFGMUhGb3pFblp0MUNHdUYyVEEK1D50NIBDCgQtJeTRjv6gwywZrVTKoe8m
            0O5Q8Js9c/0I/vCdmKwNuxU4Kt8ASASt9HrhFB5JP4JbmkWfx/tLiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYME9VOXRueEJxYVV6c1kr
            VWVmNm5TWUhqRE4wSGVMQkFKNnByRkF1UGlvCnRwb3E5bXl4TXBuV2E0T3ZJcWZW
            R2NDSFhrajZBY3BrYTlCVWZFTHhlT2MKLS0tIHRObUVJN2RpNU5PS0VneWh4Ry9Q
            bXJBS1lselFyVTFTc1RheUJLbks2b1kKbViQpLGzSAiznSzKTYm1WaqApWLk/jbi
            l7bQ6x6ybnlAcVzAnTv3RK7SQy3vukW7XsU3zXpy8BE9/TSv2YR3BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T14:52:18Z"
    mac: ENC[AES256_GCM,data:8YKK5NYeGH8nz7TmWKDlzkFysvu5wq2u/t4UM+Rj7NJiaF5WSfo70Jj5oYZBGEvg8DjIdvRCqKeO5+YfjlSwtmFsbUzlOs9Ze0n0IpzVo6rPELG4C3BKrywutBuAZENqkX6jVQjXoQaS6zTXb/H/cwYFpMT6pZkC0Y+77PPXfu0=,iv:T+/an62mDtOA4Ohqv113HkmX6DOwylbuhDGW4I45/oQ=,tag:oOMiDveFSU0NIyteVkrr6A==,type:str]
    version: 3.13.3
