daemon off;
worker_processes 1;
pid /tmp/nginx.pid;
error_log stderr notice;

events {
	worker_connections 1024;
}

http {
	server_tokens off;
	keepalive_requests 100000;
	client_body_temp_path /tmp/client_body;
	proxy_temp_path /tmp/proxy;
	fastcgi_temp_path /tmp/fastcgi;
	uwsgi_temp_path /tmp/uwsgi;
	scgi_temp_path /tmp/scgi;

	log_format filter escape=json '{"time":"$time_iso8601","remote":"$remote_addr","port":$server_port,"method":"$request_method","uri":"$request_uri","protocol":"$server_protocol","content_type":"$http_content_type","status":$status,"grpc_status":"$sent_trailer_grpc_status","bytes":$body_bytes_sent,"seconds":$request_time}';

	map "$request_method $server_protocol $http_content_type" $grpc_call {
		"POST HTTP/2.0 application/grpc" 1;
		"POST HTTP/2.0 application/grpc+proto" 1;
		default 0;
	}

	map $status $refused {
		403 1;
		default 0;
	}

	upstream bazel_remote {
		server unix:/run/bazel-remote/grpc.sock;
	}

	server {
		listen 100.87.168.66:9092;
		http2 on;
		client_max_body_size 16m;
		access_log /dev/stderr filter if=$refused;
		deny 100.87.168.66;
		allow 100.64.0.0/10;
		deny all;
		if ($request_uri != $uri) {
			return 403;
		}
		if ($grpc_call = 0) {
			return 403;
		}
		location = /build.bazel.remote.execution.v2.Capabilities/GetCapabilities {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ActionCache/GetActionResult {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/FindMissingBlobs {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/BatchReadBlobs {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/GetTree {
			grpc_pass grpc://bazel_remote;
		}
		location = /google.bytestream.ByteStream/Read {
			grpc_pass grpc://bazel_remote;
		}
		location / {
			return 403;
		}
	}

	server {
		listen 100.87.168.66:9093;
		http2 on;
		client_max_body_size 272m;
		http2_body_preread_size 256k;
		client_body_buffer_size 256k;
		access_log /dev/stderr filter;
		deny 100.87.168.66;
		allow 100.64.0.0/10;
		deny all;
		if ($request_uri != $uri) {
			return 403;
		}
		if ($grpc_call = 0) {
			return 403;
		}
		location = /build.bazel.remote.execution.v2.Capabilities/GetCapabilities {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ActionCache/GetActionResult {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ActionCache/UpdateActionResult {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/FindMissingBlobs {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/BatchReadBlobs {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/BatchUpdateBlobs {
			grpc_pass grpc://bazel_remote;
		}
		location = /build.bazel.remote.execution.v2.ContentAddressableStorage/GetTree {
			grpc_pass grpc://bazel_remote;
		}
		location = /google.bytestream.ByteStream/Read {
			grpc_pass grpc://bazel_remote;
		}
		location = /google.bytestream.ByteStream/Write {
			grpc_pass grpc://bazel_remote;
		}
		location = /google.bytestream.ByteStream/QueryWriteStatus {
			grpc_pass grpc://bazel_remote;
		}
		location / {
			return 403;
		}
	}

	server {
		listen 100.87.168.66:9095;
		http2 on;
		access_log off;
		if ($request_uri != $uri) {
			return 403;
		}
		if ($grpc_call = 0) {
			return 403;
		}
		location = /grpc.health.v1.Health/Check {
			grpc_pass grpc://bazel_remote;
		}
		location / {
			return 403;
		}
	}
}
