apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-y
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JQt0Mw9tCpFvmqtI7dK2mIyuy4FryZWlj+w=,iv:DAvj1RLjTYrLDPHul6JlBEmrDDrGDnTJhSpvtYd1sNU=,tag:bxIW94aNJOuY0qTL6wR9Vg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9mX6//Js/M4L3UoNPoA/3OGUmAfZh1Vmx4t8bUvmqMzdyyucYwEm9ur2q/QGtKluEHJrrqIcG/mwsZO1N5o17w==,iv:vvROoziMhU3C9i7RW7YlgPfEA6xB+j5g+fIp0bN1Pyw=,tag:JPrzVVuWRTkdOCjGHLqk+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbnJhZzRNTTJGL0xUT3pW
            aTBxQldYQktDWXBuRlhoNjNxaEZXQjBXWFY0ClpxdzRhbWJXMTVYZXlnMU00ejhB
            WFdaWGQ0NnJnTHBSVWJ1VWcyQnAxUXMKLS0tIGIwQXlpckc1Y05JZWZDMCtEcjhh
            YU5jVjZjbkJnMGlGaUVPTSs0Rm1lcmsK7vyrNCQOLCJmuiM4zuLXwvSrtGMWYuO1
            pzpwIC15SRm6u40v0eKnFyPhKDNt/PAJwR/ctgRbhgiiGH4o1IpQmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2ZDbFhaWkJrbTEvbHJL
            dEorNmxKQnMrN0diZVlES2NUbXVNV20zZG5jCjVLcnBXVFpwMmNoM1Fvd3JMK2FZ
            VS9wSXN3d2tFREpKTzJ3QXJ4eWs0VnMKLS0tIHZnSC9kd0l1VkRNZ3FXS2tPdmdB
            SW42blQ1UUU4ZzM4TGhGR21CcE1tY28K5jWRLgteIp9LhMkv2RDDLFOlo1zfM6pq
            pqsvPluyBMWTO2JtEXewhcJ9h8Ak1Xa5xRdywwidZ+q66LFDADqvDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQk5PY0oxYisyYVBoSDVN
            SktOZjVIaUFPb3hhdWdHSnNLUjg3OGpHbmdRClRCTG4vWTlsZ0VteTdjS1M1WUZu
            ZkJCS3A0VVY0emhqSVdUSjcxZlNXdEEKLS0tIFFSRFUyMm8vRFpXUmwxdDVmTkp6
            YnRxNWxKaFpLWFhCUTMvL25ML242QUkKL69ON3pYvJdiGprHAZkaUzjJkEYoP16r
            tbvksRI2h0RS8kXJyI9W+8XjVN68msBCq2/BiFqawum4RS9cR4J5WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:zIu7NXxVlyHu0OWIIL0PEev1x40+NJl9c0ZZT9eBkeg4w3v2D1j2xAysIR87HE24ptqDoDZYWlVVO5MM7VzEVXYpgmGXGwh/pHmP53Lan1ZM/x+o26eavQKE5m2+lsFo+w+r0RUXiMgKvpKDZwo8CewIzucyd3ZmEa4w/I/tDL4=,iv:PAGurcTH1FWlzKK9Z8A+oS4A2FVcJAkzHRB0NWvdtgA=,tag:l8Gq6/kKpo2KASB/yS+jOw==,type:str]
    version: 3.13.3
