apiVersion: v1
kind: Secret
metadata:
    name: buildkit-cache
    namespace: ci-y
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wkymAkY8h3WYmdlubQiHvr4bWQxwKkHD+Wo=,iv:DAvj1RLjTYrLDPHul6JlBEmrDDrGDnTJhSpvtYd1sNU=,tag:Ov5IDEKriXhNo++G9JH7pQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vntu2uekvMaiLxPITKyRyfdVr5Wh4X7FD/tF2g7gki+w3UsX2bFGULJTnQbPmIBvP+8uUQBFk3MS45MOVpF5Uw==,iv:vvROoziMhU3C9i7RW7YlgPfEA6xB+j5g+fIp0bN1Pyw=,tag:eBiuSHqG863aIC7y+sC4HQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd2xwZEhPYVhTMUFvS1R0
            Qmx1SDcrRGkyeko2N2tpK2ZrVXBZM2d2bEFVClRnVGJ4Zk5qRCtjSktRTDJMSm5x
            RVM4eUxjTWFDNEI2a2Y2bkExYUpQKzAKLS0tIDRCUjJtOUFraDNkbm9tZFZHRjBB
            REJqYzY3N2JkbnJUeGFHN0xTR2gxdG8KVtXbGCelEx1BQlShpKnzAhZ5toVJm79K
            PFvWCc0wd/lve8CbEUkJElel1tIsqyI3VVUbjmFeLlnymJBkz0M6zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkhqd3lUMGdtelhFZzds
            VGwvcitmUVI1UVRjQUdJN3lwajNXQzRLMUQwCnc0M3lHTi9mcDZubEhmeWJ0OVFN
            V3JSbUsvanZSSnNGN2dUZ1ZnK3lSYVkKLS0tIGlBRERsZ1dXaWNudGhHY0ZSaVN0
            MjJBK2k0dE1TZExFd0dWcWZlTlhqQjQKzSb7KTJuGWEcYQYjVKKsn/aRZYe53WMs
            5vRnBcE0VlwnKluxW11fMnytz3IhpoMUGHyH6CJn1iQ3VBbVdyRzIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTDY5UWVYMmo4WG4xTXli
            aHM1TlBGMHc4bkJXbTdwZjJTV2ViS0FOSkNnCmhUMnBrU2NTdXdHc0lrWXFHNG1T
            MGlqZ3R5QWM1VEt3b2wxSkwxNEhhUFkKLS0tIFZHSUpxY1BlSVBuZTBQRWwydndw
            VkN1WEVsa2JuRVlZZ2hINWtINUtzbnMKWOJkrDo0Y6L0KypxcrzKVsv6qSzaa4Dj
            qDs9KhQNj6Uwrxab1AVhi69FhOlFQTqULTF8AW4kOPJ+aJMJcMYNfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:53:22Z"
    mac: ENC[AES256_GCM,data:9q5N8uhbk6IctwKa1GTA5lMmRcfFQvODmPCSQBI7ltFz/EsC0hZ1fRIhWyrEYuxKczXL0Ew4KSKtMApo+wFz75LUvlHft16pXVzh2Mq4u/XgHqZYCTXHlsICyBgUtUuuAtKYEJKYVd0o5aNXF8MbSW/8e79/fDcT0ADw6JNaAL8=,iv:+Vp8sI5397AgqqUi+uHiSs+BvESC3Yak23OQdLYKJDc=,tag:0kE0ycYWr/lOsNDCDiQ14A==,type:str]
    version: 3.13.3
