apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-y
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:SINiekeaHQ==,iv:nlYxu+Ta0M7WBI2NEFGYojs86/xYv92jsrjNKL/yef4=,tag:TbCo0U3IgJVSyOVpniIaBg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:Ec6+k16Szhfh,iv:k9YjWt7chjq6xerpuAzQ6yLfezsi2oU7/f0zOn5FYcU=,tag:Q7ijFvQG9BO2ys1TW1C4Hw==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:aVoNYI9kuIINw9rkOtrSgqkBXQMOr7xhqCJVGVqll4QB3IqSvmP+xCzGwKdm1NmefxmxBgm26fBUUCsBb1kZzJnt321+XuYkup7gngZytCiKcHWspxL6ky1cfNkk/HaILn6ubUX5PmEsNirnYwg/qe0urwMuyi7DnvB1/GMQy8P2Og8praDpjF/XWtRPg0WdLkrMTc1pcxfFt3qGvcXeTI49Isfh7HRGk1KcwrfJA9OFc3Njs4wem4CQm5r4w3Rhyv7GWVcSZqzAszMNqQRQvNwEbyZZfOx7lR1R3cyPddf3M5wmrwC2CCep9epWyIR/Z8A4Kxkrh0W0a70aTmpoe7OGvngCtJTQxxPIEyAbNHqqukmN/hgsWXF0WL+hH6MIaU8SMG/tyCr9NkWG3R9LS6lbaz7/H7ruPD0uIQpGQyILe57oyfNsWdJHw/bn52LXIozSL4M4EuLUtnK4emsZIkb2FGn7RPn56XVBpfg7fJACD/MvdErScXavIUsyGwFR9vSu0w0R+B1n9hoB2sVxxBKcKxxFP5rqXdOu+mqB0ZXMPs5ffB936/+yZfj43jyKp4DMvSHYg8b3rKwAZ3KpOJTjDQUjsICf7NJgB5Dg+Edcvl/Bn8WOZGQE7gZCIis18XPH0cn0fnzMnWYVUQasqPnDeG3Cd866EF4H3IqmeiFIdgbOouGQu/riX2r8zZt7e8rfteR/xnAPcpxsK0yuswKB45VMN0bQGKMF+gugVFecSq8DGdSbaZCTaLrEgUIGukqdOGnd0PWjS3q9MOkFO3dAxQEa6/R76qOxIIAvXahOUtP8klPKxQm9uj04j07bWXcSLurH9gl55BRRC4+UVY31NaMxpqWO2lnPMafePGDhQ0xjeqPcAQ0c/oto2AVw/j7PjvC/+MmSY9IllXkcNTnwo5FzlOBogLZB4IhP3/nwSRZqFz20OGGf/SOZ9ieeCgvQ85NJ2qqlEN+5YHvaev2TPWRqC75qyzkNrdCXnZMCSRxSGIupUan6SYIhW5cVA099a/Fi3escfJ4z8ZmfXQ+KxmkK9pUsyY2K2Sp7uoOz97qi8IaCIcOlBdBw+OO7Q4kyToOctv39xLecCVQ39vBg4TydHn8Z+zaF0ADzhJasTCUkL/rvPo1mNnXbPnILXR2bGhLxNpAJoe/zj/6JP63x7E+0/iwczAIaSEXbMcJrgUfNh7Rf4jZr3D+UBhcVIeZ8gqwNW9j6EVkJWenGqfLQ2hWft8F8WmNpsyXc20XYoNVfejyI2VARli3MlwZSY7MhG3WJZZ2NzpRLHuRT/Id/2KBJdP0jd7sE1K4w6EXEzcIyHQB8bxcVQ8vpQFJxv3tDwIXftVVfalyUF9ewR7D2rUv12c+sf4MI9IiBIFYzFAn30oo+aBTIbSKB6ffLdT5wHZZvysnxLapd1vtsaHiETNiO1GDCxQ1jjFrwjFSqbR8nnTveqZyMBTUdf8XJggoKwFfawJAaJjlVAoqA37Lqibj2V2bwax0179HPOWDL8pWJd130iAdQOEWHvm599lRXJ9utVAllkOLvKihA7RIR4ZRvKPV64vEFjm7Jb2IcSKgfHXzwDo2U4UEWdLtvV27GLI6Svxrs1dIwKPpQqDhfWIxkdTaD+ggvntzCOajH74EfLxNWxB3GRYTU7kDeMgEgPAExiTEpGCu43rEnFIGH4j+KQgOmYNePqfkj/od9SgS/PyGIzXmNBPTcjgae+MztDcUN88XrSvDwxapAkyWrDZDDR0Qhmzg0JbOGpMGukkd47rdMd/AXF6odZQT1bT5rzO767CmzMG9tN7aQQslQ8sLOpRZ3plbjhZPtHvcDGHNH9aISmkJimh+7ocGNaBi4SBoLxqJ8JcEXuyq4IQbaFEoRobVSM0Lla7VtTL5zxplUoxDLh731XIoCVVXPM0cxwOmSfyt5rc9eOqYUXZkl0pIAYX+Brp6XtbG4LTPuCzY2ng6PH0SBeCWU1hLfJoN66ZGP+ldg4CwHKv5YRC8TC4hqaGUNIBQjLZ7QNweap+inugz1x1+a8kzoaqqIK1+zV2BpYWmD75QkQSPmBdcWSjhN6Qtv7rRp2NHOP7YU7e8LFbrP+0KkN9nR5F8s0bUqi1hM+fXkOSm4pXrq0pMkSvva/xpZwPZzhuoemwcNMR+9TJl5jnaCZtupYuFbNwcEghwLEdB+xwaZIoXg9O1lzYTFy9ucoCi8F64t9yn4vX/nqjokUJ/GXm+WfA==,iv:V9afSc9r2AZNJeZOkILtkPnoLbrKlkuh12y3jcZ7UwQ=,tag:FGIa/dMVtJIO1QNO4y8xTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUU5rZGE5eXB4NFI0Vk1M
            VWMvM2dQRWhZRXhtYzBFeXRqdmlKd0x3ZlZFCjFUbDFKWW5ic2NJTThnbmRYeTVS
            Wnc4RUVPNEw3U0Q0amIwNzhNWEx6am8KLS0tIE9sY2haeUVpZ2wwOFdsN1hZK1dt
            dUdsamZVZDM4VlJoU0k3Q2FNcHJZa0EKwZ8OUdfFklu5O/0B5hkMM+dyLxmcTbe5
            M0QDrzVcUT4cYf4p/Elt5swM1gIkYeD2U4knsKr6CnunCmuxU6uvDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdnM0bFdPOEM0YkU5ZENp
            dWgrZ2s4UzMzcG92T3RhM3QzZmZLTDRKVHhZCmgyTnp3UXNQQ1prUzNnZm9SbnEy
            c2YvR3JjV3lpcCthUlNTSUhMOGZIalUKLS0tIDdMU0NKSlV6WXY3cXM1MFVFYlQz
            Y1BBMEFhRW5ZWFl2c29EeHZnMWIrNjAKleKU+vl7OWdL2wMSUEX0NMvuKMVCin04
            n8FJRWSWpKhDsgei3xvu79J9j6xFlIgIfXXyvuZZuOe+swkasy0/ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N3UwbnJBblBoaldqY1J5
            OTR4MnZ3dnBHYTdDWnlub2pOeGJFRkV2Qm5ZCnN1bUFJQmVpV1F3aXlXZGp1Q0ZK
            MXNOQVpYenBpd2pxUEhhaXB4STRVQUEKLS0tIFpvMEd6OEd2KzJMdUhTTzVKbEpp
            RTl1ODlhTUZvbUFHSE53RXJDd1o2cEkKqm0lciiLbHQoWK379zJDhc54iJ5nVz1p
            Fq+2oOwiU/r688hrWqXwbeAotVpNjsAFFbckBOyojfReuGgWziu5BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15wjewk6yjs5vsezah0sa9vz3gyl569eexwj74l8dvrc2vlsxuq3q7hq52d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:07:33Z"
    mac: ENC[AES256_GCM,data:frD5hSAYR/3/kioVKCLuW5sD7USXPifwgboxbgNLM+d/2Ds0gXQR3uEA/Rppl1atjjI/Y/D1ozq1c8QTecItSk6thbyyAYBCoJG8b0Acz8J2gyKzuDV5Idumi/KjqykUIiGjcx3S42bJYr1m7mib8WyzeSzIoju5KfjtWPPpXwU=,iv:XG3VH4iCaCIrh5w42FvUWmY+1G1tLHEATWi/2m4rPdg=,tag:uhpEc9e+GPJ0ld9aWXt1Kg==,type:str]
    version: 3.13.3
