apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: ci-y
type: Opaque
stringData:
    github_app_id: ENC[AES256_GCM,data:TWoi7/126A==,iv:nlYxu+Ta0M7WBI2NEFGYojs86/xYv92jsrjNKL/yef4=,tag:jvl4jxJTUgzzmrE479g09Q==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:u7SlEzrxu5Zj,iv:k9YjWt7chjq6xerpuAzQ6yLfezsi2oU7/f0zOn5FYcU=,tag:P4QTxufYRXHt1Psgsu/r8g==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:isO0zBfUdUgZBjs2j+7rhQ/EFkKA23t8N8usoL6MhcTHDYbZXjsM/4SoODo4ZHY8lNfwMXuKcK4GaFHey1f3kKdBAB6AOCCQl6ieqZJquopMhlLIH09x/ig/cLpAIFCN5ILX7C5WU+C90wmGYlWctgE6WJFILViWJlGB9X5FfsnvftZax4dNeF2qThlmmlpYHrVscLMtR2NoA7AVv9QA6D6k9PuxarQnsMRUXY7Kb7qROZf6HAjk27qpbB8yn56t7RV0YeMF6XIYyH3yNhGec6zlZsX9GhVfV8LxfxrKUcupKrxcgVHa9Iq6X7LFho4K7p2o+vvmG+vIbUz5uHqRepC1OicynirtLE1xi/cv6PsTHFZD0Wx+Byd8Poa4a8imLY01yDmZtPG7ajH+KQ/Wf/kxBJNTHMOkKkgu3MnTM80Po0pF3w1rsbGrtito0RIITXmp072quJVGzwaLPVTNSE57PH1LoHOLYWTC6pdHvpT4aed+Zxam/VXx5q3ovJSKNoIH5yb1D0Gr/mrcL0Sc5athyo69Hb2c8rCteKivXiZCpfB3l+akvnkNilx121AQgDXwg/RuYc1X7UGSWNQt/oX5YaOTiTLRbU1EA0nJIqmGUo6UCY4NBGP+HtaRDqsBr5bX8LnGUXLLkEsAUa04scFX1VotgOUJ+txnAyOP4fqV6NRQooa2RS5dTvgdqDhpzQv/25KV/lVTn+mXJP5dfwck9UGbHDKrv+0pdgqJZ02gcxp1ol0ussWCC/Y2K8xG/kU2QNcpLqkFz9NeZID/rHhTAsbFqrBRgYQQjqApapLdNEWyMjK4Dt9aGpbbZud1e2tupKUATzEbpT59SRVJDL/Ihvi+Xc7gNrN89lonnvBEx0Xdx9fAJOJO/0JoZFPjlCwqvIwUcj9yGtnJ58b4SzHh+2M76u/2MSeRJeUsWBak1trw18eLMhVkqt6Xq4BNbgiPQyCG98got1jv116OB9LwThYki07BmCSAnKU13OR217LLKUuOFOQZaA/Zq0o4mnP62Q8OlZewVm1M0qWgvl6ld5PE4D6QbT0DHkrVxqAQWzGcXlPZEs4ElqU7Km78RuLXWEZZ1z1XdOi7oKU/3uaiTJuXVelDkOhHplzinabRW4u8eOswGl2PXrBro68QqzVprzv4g0DJpDj0NdQdSZTuiJWNlMg5h01aOv/oMIqHV9iWPMN3dlqkQKVyc67Y7dTkkmfS51tw3DP5eWKBWTlOj6ODZzumZLcA6zI2t0ckkooMV2IhmuRryusTRU1j21crrg1wjwXn2g6RPlvBMNwCyOI47G8KdY2X6XiCHrJAm0NZ3Qa1wcy0ZMDdOc5vXM2+TjiYdpjrNoqtQ6volsVBRujif2kt3LK6zLTUtYnSN2KJHBRqO+1RylRilie8VWER/JOyKmpjDEFFFIePOS1UmD6mOm4o9ncRdxtjhRbuaPoNJqXFkoiLPSiisDkqo1MS3MOYaJFX39O+CU51oSCgqNwfWxPmhrz1CwSOgDd5SNbbuuksVz/PxKbUjaG9WHpHPRng3WFVNLfFY7mhLRf4fOwbmfKOyu3s8LLeM3IX7D9Dc1f2fok976mYpJWTJ050wSZRVMwn3wmnmK5ReLyho3gHBhJmcRsQkurdZVrxGYRFvXr1pTzr5EjBeZV1Gxxt4DXQENao6rNTjbOJYQCoC0d7U+fut9vjiwiBI7PMJg/RgILEeRu4mDP2nMa+/kKING194QEDHVSQI2Z+eREq2Tx1/an/mcIluxLD/6v+hthdM1k/PoygOAsh7pxbOsp/aXGXWCjVfLkO58quHOI+g8DXu2SHos1c2iG+A/auy3oYvN4ZHeaL7q428yPIuMrya4mKQmaRxS3xaReuPZJRtgt+ptJmDPaBqvZkOWT0niLmd2yCgT3cQIHfc8dwZCEy/OIJojTOqQjGvubfPBldVb+MHCXU9vEKg49NWGmc6Ni2NPb2w5rE48JYEqrThzvkYHx5o2bFdnWS28TXayA/z1D/Z+rpxBKoMsUCV0xRckf2jmxsB0WZF88gSMcpqDlQj/G6Poh3GdX/kQOz6wqzhMH3DeAtHAF1/kv5H3DwAzjPyvzgP+OOJXakrZsQCVBLW5O+RvhkNnDEUlTMoCbbPssYPnKP8iCdvHNiIQnu5UAPjGabR8TLhdZuatn3ewSgJWO636204lelXXniVEaqq8XfNgKxKNrb9oq1jwEVbCNZyGk44X2i6bEvVA==,iv:V9afSc9r2AZNJeZOkILtkPnoLbrKlkuh12y3jcZ7UwQ=,tag:m0HmbYtx+CN24m66oMKKsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y0xEK0JGWUJVZklXRzYr
            SHJwVFVrRlY0V2lyT3Y2dHI0a3pNdXNBSlZVCmpzVVIwczRQV3RRRjUvTXpBYWsy
            NW5iUERUd1VHeHlUK09yWG90KzRLaTgKLS0tIGNobHpJcGZEYXN6SllxWnVhV3c2
            bXd3OVZtQnJVNzF4K0srN3FIWWt6UTgKFBZ7KuSB1UvDVGZWmVZuHNBeFT38sTTD
            /MagztLe2sRee4ZaqJHQRXiiodkNS3eDUyqMspp/wLzeJYCac5Yi8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eva47ddzjgmvrzjd8mxm7h0n6vvamw5xp94aqvlm2d3yf3uvracqypxu7x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMXBWRlBRWFlMUXBmUlZk
            UjdKYzhEblNQWlhnSXc2dXBvNmVsLzMzcW13CjhzVXhQZnVrbjllYVhmT0hSSjI4
            UjFYYk5VRExNbDI0K0w3WXBDNWM5WE0KLS0tIFMrQjE2a0lXdHZUQXpzZXFzVThy
            VEc0SDJzTnNXbWNjRWozMmlpWllnbUEKfhpgBccvnrmkLPh6fk6lJDzgmKi0lJkY
            83D1Hks7NiusxFokz83lOwAGCcsDDAxbOZiU8rCkpdEn80npL21Etg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wflp6cynwm97wndq5zxmpaxwz59h62a7dku8qdyue5zm9g4djfnqwj9n0m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRWtxRWNBWDVRbXIyanFZ
            Vlc2RVhmRlNYekdXTDdBdXlzYUJvWVlETzE0Cjd4VmN5YnI1UzMwNjlUYTY2QWZw
            aGg2UVZoMXZZLzR1NmtMQjQrWlV1T0kKLS0tIGhBNjUwT3ZqbTBiME1TcjRtN3Iw
            MVBCS1hyY2Y4YUx5Yms2RXlMSDZDSTAKoLoRtS0k1B5CodQh/NzpdwKB436XH1hi
            ZGvalSfBDW99VVkHg8tuCNe4bmbgStZ+4ikbzbYZTErRcWCTX3m3dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mxszcn7gs8gnvhpq8ku748szqe8u6raferefg986slu83r3zkcmswe29zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T16:14:34Z"
    mac: ENC[AES256_GCM,data:QWZXYDR2RSUkvbYgI51LskrNURQoWFYVMkgJvRMJ1vG2rSohWc1zwoiyULL+Ex2f2ue+rs2LVoYioAO+I0U0TwkHPuazV/Bl4dbmexKcDs/QCKEdw5A7FPNKzhSV1146/n+6FQ0es5uFanqkJt5D2Z0DJJGcBDzPWEPHSL+tiQ4=,iv:QAVTXIMJLQzo4rkr9mNv7HU0jeXyrCI7yfYs03R+jD8=,tag:q1+tHb+zBPCuxlLvsoPpPw==,type:str]
    version: 3.13.3
