apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-y
resources:
- ../ci-namespace
- github-app.secret.sops.yaml
- buildkit-cache.secret.sops.yaml
components:
- ../buildkit-cache
patches:
- path: quota.yaml
