issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/llunde\-frontend(@1328144104)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1328144104$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^(self-hosted|github-hosted)$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@(d9016b2889c88f1ec99bfe9d7262343a759e4b69|f467a384e922ddb64955bc19469892077e5bd507)$
  job_workflow_sha: ^(d9016b2889c88f1ec99bfe9d7262343a759e4b69|f467a384e922ddb64955bc19469892077e5bd507)$
permissions:
  actions: write
