issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/llunde\-backend(@1327945675)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1327945675$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@eb764b837d1fd10cb71fde1963500854aaef5d6c$
  job_workflow_sha: ^eb764b837d1fd10cb71fde1963500854aaef5d6c$
permissions:
  actions: write
