issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/llunde\-backend(@1327945675)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1327945675$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@f20fbb8d9c0f2d1c09f94f05939e92b21cc9d91b$
  job_workflow_sha: ^f20fbb8d9c0f2d1c09f94f05939e92b21cc9d91b$
permissions:
  contents: write
  pull_requests: write
