issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/llunde\-pyparser(@1328252868)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1328252868$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@8e0af06efaa451db44c46e3ec22243aa7231bd98$
  job_workflow_sha: ^8e0af06efaa451db44c46e3ec22243aa7231bd98$
permissions:
  contents: write
  pull_requests: write
