issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/Y(@900286164)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^900286164$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@931cd1e9b6aee88250c9681397e7ee0b733bd0ab$
  job_workflow_sha: ^931cd1e9b6aee88250c9681397e7ee0b733bd0ab$
permissions:
  actions: write
