issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/portfolio(@773018612)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^773018612$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@1f2eecbc81ba184252f9ed85f893fa5eb3b5150a$
  job_workflow_sha: ^1f2eecbc81ba184252f9ed85f893fa5eb3b5150a$
permissions:
  actions: write
