issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/llunde\-frontend(@1328144104)?:ref:refs/heads/main$
claim_pattern:
  repository_id: ^1328144104$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  runner_environment: ^self-hosted$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/build-image\.yml@7a5988fc798ad6799e9f5ed8f79249812f97ca80$
  job_workflow_sha: ^7a5988fc798ad6799e9f5ed8f79249812f97ca80$
permissions:
  contents: write
  pull_requests: write
