issuer: https://token.actions.githubusercontent.com
claim_pattern:
  repository_id: ^900286164$
  repository_owner_id: ^114402558$
  event_name: ^push$
  ref: ^refs/heads/main$
  job_workflow_ref: ^disabled$
  job_workflow_sha: ^disabled$
permissions:
  contents: write
  pull_requests: write
