apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - application.yaml
components:
    - ../../../components/object-store-trust
images:
    - digest: sha256:35e2ad2ff61c654923a3735ae22e12785e25f3ba6d9079adbeda70e3b8db06ec
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
