apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - application.yaml
components:
    - ../../../components/object-store-trust
images:
    - digest: sha256:1e834bad8fc70d1b75631eaebd57a0517307b7e4e8a7ff7903d47d58511851d7
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
