apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llunde-pyparser
resources:
    - application.yaml
images:
    - digest: sha256:a591588d3612b9f1c78b78db003060d3866503214de8c32b66e5a6fea95bf3d3
      name: ghcr.io/fredrir/pyparser-review
      newName: ghcr.io/fredrir/pyparser-review
