platform_preflight_approved: false
platform_drain_approved: false
platform_initialize: false
platform_sandbox_enabled: false
platform_gvisor_version: "20260907.0"
platform_k3s_version: v1.36.3+k3s1
platform_tailscale_version: 1.102.4
platform_role: agent
platform_node_name: ""
platform_admin_keys: []
platform_node_ip: ""
platform_private_ip: ""
platform_private_interface: ""
platform_api_name: k3s-api.internal
platform_api_backends: []
platform_pod_cidr: 10.42.0.0/16
platform_service_cidr: 10.43.0.0/16
platform_tailscale_auth_key_file: ""
platform_advertise_routes: []
platform_server_token_file: /run/secrets/k3s-server-token
platform_agent_token_file: /run/secrets/k3s-agent-token
platform_backup_environment_file: ""
platform_k3s_artifacts:
  amd64:
    file: k3s
    sha256: 2f98a9f8fe5782479ee2d54e70a1b10a7f6fd4cae8d38ed3098452dc6eed76b5
  arm64:
    file: k3s-arm64
    sha256: c9a209103f480f163b7c6a56f00862b4481927b284dc29a3716bb70d886691a8
platform_tailscale_sha256:
  amd64: 50748df1045e60b5b695f19f4c56b0da36c019948b440fb456b6584a50f0d8b9
  arm64: 9dd1e6a592a014bbaea0103167ffe299adeda4ba14e078ce9c2895364f6c4c3f
platform_gvisor_artifacts:
  amd64:
    architecture: x86_64
    sha256: 81416511897ab8abd4e723d66823c5b0461a2ee3311cfa70d152404ef9b860cf
  arm64:
    architecture: aarch64
    sha256: 2b162adb35860f598ab2f89b9d752bff2c7ee6175c05d9cc532174a336cfb38c
