apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
spec:
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3000
      template:
        spec:
          containers:
            - name: backup
              envFrom:
                - prefix: PRIMARY_
                  secretRef:
                    name: backup-primary-repository
                - prefix: OFFSITE_
                  secretRef:
                    name: backup-repository
              env:
                - name: BACKUP_REPOSITORIES
                  value: primary offsite
                - name: PRIMARY_BACKUP_INITIALIZE
                  value: 'true'
                - name: PRIMARY_BACKUP_KEEP_LAST
                  value: '3'
                - name: OFFSITE_BACKUP_KEEP_LAST
                  value: '1'
                - name: OFFSITE_BACKUP_INITIALIZE
                  value: 'true'
                - name: OFFSITE_BACKUP_INTERVAL_DAYS
                  value: '14'
                - name: PRIMARY_RESTIC_CACERT
                  value: /usr/local/share/object-store/ca.crt
                - name: PRIMARY_AWS_DEFAULT_REGION
                  value: hel1
