- name: Create repository runner directory
  ansible.builtin.file:
    path: '{{ item.root }}'
    state: directory
    owner: '{{ item.account }}'
    group: '{{ item.account }}'
    mode: '0700'
  loop: '{{ build_runner_state_repositories }}'
  loop_control:
    label: '{{ item.root }}'
