FROM docker.io/moby/buildkit:v0.33.0@sha256:6c2fa84a6b61ccd72899dde4239f8d5717f05f9a8ca6f3cad185fb1a95a94de3 AS buildkit

FROM ghcr.io/actions/actions-runner:2.334.0@sha256:b6614fce332517f74d0a76e7c762fb08e4f2ff13dcf333183397c8a5725b6e8e
USER root
RUN apt-get update && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*
COPY --from=buildkit /usr/bin/buildctl /usr/bin/buildkitd /usr/bin/buildkit-runc /usr/bin/buildctl-daemonless.sh /usr/local/bin/
ENV RUNNER_ALLOW_RUNAS_ROOT=1
ENV BUILDKITD_FLAGS="--oci-worker=true --containerd-worker=false --oci-worker-snapshotter=native --oci-worker-binary=/usr/local/bin/buildkit-runc"
WORKDIR /home/runner
