apiVersion: v1
kind: ResourceQuota
metadata:
  name: builds
spec:
  hard:
    pods: '5'
    requests.cpu: 10500m
    requests.memory: 31Gi
    limits.cpu: 30500m
    limits.memory: 51Gi
    requests.infra.fredrir.com/ci-slot: '5'
