name: Build image
'on':
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      test-command:
        required: true
        type: string
      platforms:
        type: string
        default: '["linux/amd64"]'
      context:
        type: string
        default: .
      dockerfile:
        type: string
        default: Dockerfile
      nix-target:
        type: string
        default: ''
      request-release:
        type: boolean
        default: true
      component:
        type: string
        default: app
      build-arguments:
        type: string
        default: '{}'
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}
    secrets:
      NIX_CACHE_READ_TOKEN:
        required: false
      NIX_CACHE_UPLOAD_TOKEN:
        required: false
permissions:
  contents: read
jobs:
  build:
    if: github.repository_owner_id == '114402558' && contains(fromJSON('["773018612","900286164","1327945675","1328085692","1328144104","1328252868"]'),
      github.repository_id) && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.ref_protected
      == true && startsWith(vars.INFRA_CI_IMAGE, 'ghcr.io/fredrir/infra-ci@sha256:') && contains(fromJSON(vars.INFRA_CI_ARCHITECTURES
      || '[]'), 'amd64')
    uses: ./.github/workflows/project-ci.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      project: ${{ inputs.project }}
      test-command: ${{ inputs.test-command }}
      platforms: ${{ inputs.platforms }}
      context: ${{ inputs.context }}
      dockerfile: ${{ inputs.dockerfile }}
      nix-target: ${{ inputs.nix-target }}
      request-release: ${{ inputs.request-release }}
      component: ${{ inputs.component }}
      build-arguments: ${{ inputs.build-arguments }}
    secrets:
      NIX_CACHE_READ_TOKEN: ${{ secrets.NIX_CACHE_READ_TOKEN }}
      NIX_CACHE_UPLOAD_TOKEN: ${{ secrets.NIX_CACHE_UPLOAD_TOKEN }}
